### ISSUE TITLE
Support for multiple shells

### ISSUE THREAD

**Issue by atrauzzi** [vercel/hyper#1147]
What would be better than the shell option?

Multiple shells!  I'd love to be able to have both Linux on Windows as well as PowerShell tabs open :)

**Comment by ekinnee** [comment]
I'd be interested in this also. It is one of my favorite features of ConEmu as I find myself in cmd and PowerShell quite often throughout the day.

**Comment by lllama** [comment]
I would also be very much interested in this on Windows - similar to ConEmu would be ideal.

(apologies if this is not how the Community Feedback label works)

**Comment by matheuss** [comment]
Hmm, how would this work? 

For now I'd suggest just opening a new tab and typing, for example, `powershell` (given that you're default one is `bash`) 😄

**Comment by lllama** [comment]
In ConEmu, I have ctrl-<a number> mapped to different shells. I have powershell, powershell as admin, and cmd as my main three, but also have the various Visual Studio cmd shells mapped as well. Being able to replicate this would be great.

**Comment by lediur** [comment]
I'd also like this feature, especially to easily start admin shells.

**Comment by ehdevries** [comment]
Yes, agreed, an easy way to open an admin shell would be great on Windows.

**Comment by MartyGentillon** [comment]
related pull request: https://github.com/zeit/hyper/pull/1347

**Comment by szul** [comment]
This is definitely a feature I'd like to see too.

**Comment by fallspectrum** [comment]
Agreed.

**Comment by doppleware** [comment]
This feature would be extremely useful, especially on Windows where there are several shell types I constantly switch between (bash, powershell, regular command line, vs command line)

**Comment by resir014** [comment]
Please add this! I share many of the same use cases as the people above me and it's pretty much the only thing preventing me to switch from ConEmu.

**Comment by tobico** [comment]
This is hugely important on Windows, and a feature provided by most other Windows terminals. While WSL does a lot, there are still some programs that only work in PowerShell *cough*docker*cough*.

It usually works by having the "New Tab" option expand into a menu allowing the user to select a shell to use from a selection of defined presets. In addition, it's possible to add a custom keyboard mapping for each shell preset, which will open a new tab with that shell.

**Comment by ppot** [comment]
I'm hitting session restoration before doing multiple shell. ;)

**Comment by atrauzzi** [comment]
While we're documenting use cases, I just came across another one today...

I'm defaulting to WSL with hyper right now, but I need PowerShell to do electron application development on Windows.

**Comment by hsiktas** [comment]
> Yes, agreed, an easy way to open an admin shell would be great on Windows.
> 
>  👍 8

Could this work while keeping the powershell.exe elevated but leaving Hyper.exe as a normal user process?  
If I look at ConEmu, I see that a "PowerShell Admin" tab is also starting a ConEmuC64.exe child-process with the same high integrity level as powershell.exe.  
  
I don't think that anyone would like to run the entire Electron-stack with admin rights. 😱

Somewhat tangential, but a similar topic about running GUI applications as root and their security implications: https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/

**Comment by JustSid** [comment]
I would like this as well. My use case is that I have to switch between wsl/bash, Visual Studio Command Prompt, PowerShell and Admin command prompt regularly.

All I want is a single terminal that I can use to drop into any of these without making my life harder.

**Comment by blackwire** [comment]
So, I found a work around that seems to be okay. It's not automatic, but once you have it up it works just fine. You can start out with the Powershell terminal and open a new tab and then type in **bash** or **bash.exe** and it will start the WSL (Windows Subsystem for Linux). This way you can have both terminals running. Hope this helps a few people. It took me a second of thinking and then I realized this and have been using it this way sense.

**Comment by atrauzzi** [comment]
Not really because I start with bash :)

**Comment by blackwire** [comment]
If you just need to run a few things using powershell in the WSL environment you can alias powershell.exe to **ps** or something like that in your .bashrc file and use **ps yourpowershellscript.ps1** this also works with any powershell command. You can also just kick over to the powershell terminal by using **powershell.exe** without any parameters. This doesn't work quite as well though as if you don't have a terminal emulator for WSL it will throw up on your ssh connections.

**Comment by atrauzzi** [comment]
I think ideally we should just keep this issue focused on multi-terminal support.

Workarounds run the risk of derailing this ticket.

**Comment by szmarczak** [comment]
Any news?

**Comment by chabou** [comment]
There is an awesome workaround here: https://gist.github.com/legowerewolf/a3e0eb7830752488fec329c7bdcb2d2a

I hope that it will be a plugin soon 🤞

**Comment by marcinfigiel** [comment]
This single feature makes me still use ConEmu instead of hyper.

**Comment by ctolkien** [comment]
Chiming in on this one too, would be hugely invaluable for those that need to jump around on different shells (us Windows users!). Also is one of the better features of ConEmu.

**Comment by 5paceToast** [comment]
One way to achieve this is what most terminal emulators do on linux - your configuration file determines the *default* shell, but you can specify one on the command line, like `hyper -e /bin/mksh` (or `hyper -e C:\Windows\System32\cmd.exe`)

**Comment by ThisIsSet-L** [comment]
Here's a little workaround, extending @5paceToast  's suggestion.

Create a bunch of shortcuts to Hyper, right click to properties for each, edit the command line for each to point to your intended shells. Then, with the Shortcut Key field below, assign each to a shortcut. When you reach for that hotkey, Hyper will launch with that assigned shell.

Lengthy, should be included as a feature, kinda messy: yes
Works: also yes.

**Comment by albinekb** [comment]
After using windows with WSL for some weeks now, I really feel why this is necessary!

**Comment by racoonx2p** [comment]
@ThisIsSet-L Can you please specify setting for this? I tried to create new shortcut for Hyper in win10.

Hyper is starting with WSL bash by default and I want to have shortcut for CMD. I tried this:
Target: `C:\Users\petik\AppData\Local\hyper\Hyper.exe -e C:\Windows\System32\cmd.exe`

But it doesn't work.

**Comment by otonielguajardo** [comment]
Hey any news on this? I'm trying @chabou 's solution meanwhile

**Comment by nickjj** [comment]
I'd really like to see this too. I'm toying with the idea of using hyper.js but the lack of this feature is keeping me with ConEmu currently.

My use case is:

94% of the time I'm in WSL / Bash
5% of the time I need to run PowerShell as an admin (to work with Vagrant on Windows)
1% of the time I need to run PowerShell to manipulate various Windows properties

An ideal workflow (IMO) would be:

1. You can default to a shell of your choosing (Bash), which hyper.js already does.
2. When launching a new window / tab, it will use your default shell, which hyper-.js also does.
3. Offer a "Shell" context menu to pick an alternate shell to override the default (bash, powershell, admin powershell, etc.).

The last one could be implemented in a number of ways:

1. It could convert the current window / tab to the selected shell and while this is nice, it might be an issue if you tried to launch an admin / elevated shell since by default you're not using this. So you might be forced to open a new window? I'm not 100% sure how Windows permissions work.

2. You could choose to launch either a new tab or new window with the selected shell. This might be the way to go since the behavior is the same in every case? And in the case of trying to launch a new tab with an elevated shell, that option could be hidden / disabled (unless it's possible to do this).

**Comment by legowerewolf** [comment]
Oh wow, hey, my workaround script is actually being used!

**Comment by henning-erlandsen** [comment]
What about supporting this though multiple profiles/configurations? For some shells I want some environment variables to be set for instance. This could be achieved through overriding the default config with something like:
```
profiles: {
    bash: "bash.js"
    ubuntu: "wsl.js"
} 
```

Then this could be selected from the menu File > New window/tab > [ Default, bash, ubuntu ]

**Comment by ronaldscott** [comment]
I really want this feature too. In the meantime, here's my own hacky workaround to dealing with the lack of this necessary feature: https://gist.github.com/ronaldscott/5f8f7566277586a2b0a1d639000c4553

**Comment by AaronBeaudoin** [comment]
Why is this still not implemented nearly 3 years later?

**Comment by matheuss** [comment]
@AaronBeaudoin because this is an open source project whose maintainer work on it on the side :+1:

**Comment by szul** [comment]
@AaronBeaudoin #1347 Addressed but it was never merged. There was some back-and-forth mostly over coding style consistency. Eventually, the OP of the PR moved on from Hyper as a tool, the PR got stale, and it was closed. This workaround https://github.com/zeit/hyper/issues/1147#issuecomment-381339196 has worked great for me.

**Comment by szul** [comment]
@matheuss I get the annoyance with @AaronBeaudoin's comment, but Hyper is one of the open source projects that Zeit frequently promotes, and there has been at least one PR that addressed this, but nobody from the team merged it or got back to the programmer's later comments after he resolved the change requests on the PR. This is probably the most frequent request from all Hyper users. Maybe a Hyper roadmap would help mitigate requests like this. Is one available publicly?

**Comment by AaronBeaudoin** [comment]
@matheuss I think I might have come across the wrong way. My sentiment is simply that being a very popular and loved projects in its category, Hyper's community would benefit from, at the very least, some transparency on where the project is going.

My next thought was going to be whether it is worth contributing to the project myself, but considering @szul's insight I am hesitant to put time into a request that might not ever be merged. I believe that community contributions for highly requested features should be honored by addressing them in a matter of months... not years.

**Comment by szul** [comment]
@AaronBeaudoin I'm sure there are many reasons mergers don't go through: code quality, efficiency, priority, etc. I'm not faulting them for that. Zeit has a lot of great products, and they need to prioritize revenue generating work. This is a situation where not only is there a long-standing request for the feature, but also OS attempts to contribute the feature to the project, so it would be nice to know what the long-term roadmap for the project is, and where this feature stands in the priority, if at all. That would mitigate some of the "where is this at?" questions, which clearly solicited a knee-jerk reaction.

**Comment by Hariama** [comment]
Just a heads up, there is actually an extension that fixes this issue quite eloquently called "Hyper-Shellect". It's functionality is a lot like the workaround script from legowerewolf. Even though the original developer and their code have gone AWOL on Github, the extension is still available on npm (https://www.npmjs.com/package/hyper-shellect). The only problem I have encountered is that when you try to close a tab or pane with 'ctrl+alt+w', the extensions can make hyper crash, which is really something to be looked into.

**Comment by www-wagner** [comment]
Another available extension is [hyper-launch-menu](https://hyper.is/store/hyper-launch-menu). It works like a charm for me!

**Comment by zhorton34** [comment]
@www-wagner Already Referenced it, but Hyper Launch Menu. Here's the official readme docs. 

https://hyper.is/store/hyper-launch-menu/source?README.md

**Comment by beardedeagle** [comment]
@www-wagner & @zhorton34 I tried installing hyper-launch-menu via:

```shell
hyper i hyper-launch-menu
```

and added the following inside my `module.exports`:

```shell
  shells: [
    {
      name: "Linux",
      group: [
        {
          name: "Ubuntu 20.04",
          shell: 'wsl.exe',
          args: ['--login'],
          default: true,
        },
        {
          name: "CentOS 7",
          shell: 'wsl.exe -d CentOS7',
          args: ['--login'],
        },
        {
          name: "NewishUbu",
          shell: 'wsl.exe -d NewishUbu',
          args: ['--login'],
        },
        {
          name: "OldUbu",
          shell: 'wsl.exe -d OldUbu',
          args: ['--login'],
        },
      ],
    },
    {
      name: "Windows",
      group: [
        {
          name: "Powershell 7",
          shell: "pwsh.exe",
        },
        {
          name: "Powershell",
          shell: "powershell.exe",
        },
        {
          name: "CMD",
          shell: 'cmd.exe',
          args: ['--login'],
        },
      ],
    },
  ],
```

However, I only see default in my shell select list. What am I doing wrong here?

**Comment by mariorocha2308** [comment]
> @www-wagner Already Referenced it, but Hyper Launch Menu. Here's the official readme docs. 
> 
> https://hyper.is/store/hyper-launch-menu/source?README.md

How i can use launch menu?? say import and export :c

**Comment by snwflake** [comment]
2022 and still not a single usable terminal emulator for windows

way to go!
