### ISSUE TITLE
Make transparent window configurable

### ISSUE THREAD

**Issue by sliepie** [vercel/hyper#1345]
Electron and frame less/transparent windows seems the have several issues on Windows and Linux.
Some issues that are currently related to this:

* Windows Snap not working #1128 
* Hyper shows blank screen on Windows (7) when Aero is disabled #1223 
* Background turns transparent on Windows on full reload #1026 (Seems to be an [Electron issue](https://github.com/zeit/hyper/issues/1026#issuecomment-270523845))
* Several [limitations](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations) as documented by Electron
* @paulcbetts (Electron Master) has transparency explicitly disabled for Windows and Linux in this PR #1307 

Since Hyper turns transparency always on regardless of the platform. I agree with Paul that transparency should be disabled for platforms where it causes issues like mentioned here above. However as an advanced user I would like to have control over this, as I like to have a transparent terminal and can live with the sacrifices (Windows Snap) that I have to make on Windows 10.

When enabling transparency is a configurable option in `hyper.js`, there should be a description with the trade offs that users have to make. Many users (including myself) have a habit of forgetting about trade offs like these and what causes the issues they experience, for example Windows Snap that isn't working. The instant reaction of most users is to log an issue on the project, which leads to unnecessary work for the maintainers.
I would propose that transparency is an option that could be enabled via a (core) plugin. This raises the bar for users, but this is reasonable regarding the trade offs that they have to face. The readme of the plugin can provide users with the necessary info.

**Comment by paulcbetts** [comment]
> I would propose that transparency is an option that could be enabled via a (core) plugin.

afaik plugins are loaded in the renderer process so you're already too late by the time it gets loaded. Just turn it off tbh, it's not with the significant headaches.

**Comment by GerjanOnline** [comment]
My 2 cents: just make it a core setting `enableWindowTransparancy` defaulted to `false` (in `hyper.js`) with a good comment above it (warning etc)

Personally, I would regret that I will loose the nice transparent effect of Hyper. It just works on my Windows machine ™ (although with some issues, but those are fixable bugs imo)

**Comment by stefanivic** [comment]
I talked to @matheuss about this before and we discussed that making it configurable is the best option. So yes, i can see it in the future. PRs are always welcome.

**Comment by paulcbetts** [comment]
> I talked to @matheuss about this before and we discussed that making it configurable is the best option. So yes, i can see it in the future. PRs are always welcome.

That makes no sense, why would you allow people to opt-into incorrect and broken behavior

**Comment by StrictlySkyler** [comment]
AFAIK this will need to change in Electron in order to truly enable transparency on platforms not supporting it currently.

Is there any discussion about getting such a change landed in Electron upstream?
