### ISSUE TITLE
Support expanding aliases

### ISSUE THREAD

**Issue by citrusui** [vercel/hyper#1572]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04, Xenial
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/anonymous/1e07e052548d8c853f174e3809c2e20d
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

In bash, you can expand aliases by typing the alias name, and then pressing <kbd>CTRL</kbd> + <kbd>ALT</kbd> + <kbd>E</kbd>.

For example, typing `ls` returns `--color` for me.

Here's an asciicast demo to further explain my confusing explanation: https://asciinema.org/a/104127

**Comment by LabhanshAgrawal** [comment]
I tried it on the latest [canary build](https://github.com/vercel/hyper/actions/runs/153185087) in Ubuntu
It was working properly.
Closing this, feel free to open a new issue if you face any problems.
