### ISSUE TITLE
Crashes on open with invalid config

### ISSUE THREAD

**Issue by sambass1** [vercel/hyper#1589]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: <macOS Sierra 10.12.3>
- **Hyper.app version**: <Hyper 1.2.1>

When I open Hyper the terminal open and closed quickly. The app is still open however. When I click on preferences in the menu bar the below pop up box shows. I've tried uninstalling and reinstalling but same problem occurs.

**A JavaScript error occurred in the main process**
Uncaught Exception:
TypeError: Cannot read property 'write' of undefined
    at Server.rpc.on (/Applications/Hyper.app/Contents/Resources/app/index.js:269:24)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.ipcListener (/Applications/Hyper.app/Contents/Resources/app/rpc.js:34:11)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by Anzumana** [comment]
How did you uninstall the app? You could try https://freemacsoft.net/appcleaner/
And then reinstall.

**Comment by sambass1** [comment]
I used appcleaner to remove it and still the same issue. Also installed the older version of Hyper and the same problem.

I think it's an issue in the preferences but I can't edit those without using the terminal.

**Comment by rohan-buchner** [comment]
I had the same issue. Open the `~/.hyper.js` file in a regular editor / other terminal. then make sure the file has no typos in in. In my case the plugins array had an extra comma in it.

**Comment by sambass1** [comment]
Great, advice. Opened the  ~/.hyper.js file in a regular editor and changed what I needed. Working fine now. Thanks @rohan-buchner

**Comment by albinekb** [comment]
I think we should handle that error and show a nice alert so next time the user knows that there's something wrong in the Preferences👍🙌

**Comment by CaRDiaK** [comment]
I'm having this exact problem with Windows. I also see other issues listed. I made a backup of my config before I changed it to use powershell. I'm now assuming one of my args is wrong because it just throws an uncaught exception on startup. 

I could roll back my config, or try again but it isn't clear where this config file is in Windows. A reinstall cleaning the app folder makes no difference either, if you reinstall, something is lingering because it just throws again.

**Comment by VeritasX** [comment]
I am having the same issue, mine did not trigger until i misspelled the address for bash and i tried editing the config again, no such luck so i uninstalled went back version etc, still the same error

**Comment by Anzumana** [comment]
will give it a try. and see if i can find a good solution for this issue

**Comment by fmontes** [comment]
Same issue on Windows.

**Comment by pablopunk** [comment]
They also have this error in the VS Code terminal and [here's how they handle it](https://github.com/Tyriar/node-pty/issues/74#issuecomment-295520624). I guess listening to that error and noticing the user should be fine until something better comes up.

**Comment by jstangroome** [comment]
I have encountered this same error call stack as OP with Hyper 2.0.0 on Windows 10, but not on start up, instead whilst attempting to Ctrl+C to exit `top` inside an SSH session started from the Bash on Windows shell.

```
Uncaught Exception:
TypeError: Cannot read property 'write' of undefined
    at Server.Window.rpc.on (C:\Users\jason\AppData\Local\hyper\app-2.0.0\resources\app.asar\ui\window.js:158:16)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.ipcListener (C:\Users\jason\AppData\Local\hyper\app-2.0.0\resources\app.asar\rpc.js:33:11)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (C:\Users\jason\AppData\Local\hyper\app-2.0.0\resources\electron.asar\browser\api\web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

**Comment by najam489** [comment]
Hi, you have to search for hyper.js file in your system and edit it by your need delete all the code if you don't know what is causing the error
I hope that will help

**Comment by edlahaba** [comment]
Howdy! Can I take this issue?

Greetings!
