### ISSUE TITLE
Start in specific location

### ISSUE THREAD

**Issue by math2001** [vercel/hyper#1663]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1

Is there a way to start Hyper in a specific location? And, if you could make a `.exe` file to run hyper a bit more user-friendly than having to run `Update.exe` with an argument that isn't even specified in the `--help` message, it'd be very helpful 😄

**Comment by lednhatkhanh** [comment]
+1 for this, I'm also looking for this feature!

**Comment by LabhanshAgrawal** [comment]
Fixed in #3769
