### ISSUE TITLE
Border radius not working. 

### ISSUE THREAD

**Issue by ASAPHAANING** [vercel/hyper#1674]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.04**: 
- **1.3.1**: 
- **Default config**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I can't get border radius to work at all. Tried applying it over basically every single div element with a !important tag.

**Comment by henrikdahl** [comment]
What are you trying to apply border radius on?

**Comment by ASAPHAANING** [comment]
Well I want the border-radius to be applied to the actual borders of the terminal. But in practice I've applied the style to every element on the way down without luck.

**Comment by kodekrendel** [comment]
Also whould like to know how to set border-radius in Ubuntu. Tried `borderRadius: '10px'`

**Comment by CodeXtinction** [comment]
+1 for this, I'm on elementary, will love those rounded corners

**Comment by Bernardi23** [comment]
I want it aswell. Amy updates?

**Comment by dragaoazuljr** [comment]
I want it aswell +1

**Comment by LabhanshAgrawal** [comment]
ref https://github.com/vercel/hyper/issues/3074#issuecomment-396027642
