### ISSUE TITLE
Invasive "ln" character in (neo)vim when using WSL/Hyper

### ISSUE THREAD

**Issue by rmreq** [vercel/hyper#1886]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: Latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Hi, I've encountered a strange issue when trying to use vim on Windows WSL using Hyper. For some reason it prints "ln" in the margins, and sometimes in the white space following the last character of a line.
Here's a sample:
![hyper_vim](https://cloud.githubusercontent.com/assets/28678557/26564553/e9a353c2-44a7-11e7-911b-8c518a513c7d.PNG)
I resized the window before capturing it, which made the "ln"s invade my buffer more aggressively, but that's generally what it looks like. 

This behavior does not occur in the standard WSL terminal.

Also, vim in Hyper on WSL doesn't respect my theme settings, but that's unrelated.
I've been trying to document issues I encounter on windows because I'd really like to use Hyper more regularly. Please don't register any issues I post as a complaint; I know how much work is is to maintain cross platform software, and I wish I were able to contribute more. Just wanted to bring it to your attention. Thanks.

**Comment by rmreq** [comment]
Update:
The issue starts when I scroll past the last visible line, at which point my powerline-bar starts traveling up the page, followed by ln-characters. It's confined to the right side of the screen until I scroll back up, at which point it spreads to the end of lines as shown in the original post.
Here's a sample from just after the problem appears:
![vim 2](https://cloud.githubusercontent.com/assets/28678557/26564769/e899e60a-44aa-11e7-85ef-e229502e4a7c.PNG)

**Comment by neolectron** [comment]
+1

**Comment by notrab** [comment]
This happens for me for me also but only when I have exited regular Vim inside TMUX.

Entering/exiting Vim without TMUX doesn't produce this error.

**Comment by notrab** [comment]
Ok I narrowed this down to be an issue with [vim-airline](https://github.com/vim-airline/vim-airline/issues) for my use case.

**Comment by ruiehq** [comment]
Did somebody fix this issue? I'm also getting this weird bug

**Comment by JesseObrien** [comment]
Damn this is obscure, didn't know if anyone else would have hit it haha. Looks like I'm getting the same thing every so often. It does seem to be airline leaving things behind. If I do a `ctrl+p` lookup, airline pops up to about the middle of the screen and then when it drops down after I open the file it leaves these hanging where it was.

**Comment by jeffcato** [comment]
Also seeing this with `vim-airline` on my linux machine.  In my case seems to happen when the status line gets an update from `ALE` lint results. ¯\_(°_o)_/¯
![screenshot from 2018-01-03 12-33-03](https://user-images.githubusercontent.com/3280456/34532118-f727fc5a-f082-11e7-8037-5a29af20f79b.png)

**Comment by rgalbo** [comment]
I have a very similar issue also using neovim and tmux. The weird background noise of the "ln"
<img width="1440" alt="screen shot 2018-04-13 at 11 24 21 am" src="https://user-images.githubusercontent.com/6351996/38746550-76849386-3f0d-11e8-9731-65001d29d11b.png">

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2 and earlier, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build.
