### ISSUE TITLE
Split window should maintain working directory

### ISSUE THREAD

**Issue by nomad3k** [vercel/hyper#1973]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 & Mac OS 10.12.5
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: n/a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When Splitting a Pane (either horizontally or vertically) the new Pane should have the same working directory as the old one.

I make heavy use of the panes, as I like to get multiple watching processes going at once and see them all in one place.  It would be a bit more productive for me if I didn't have to constantly cd into the project directory every time I split a pane.  Thanks.

**Comment by joggienl** [comment]
Did you check the list with plugin's for that: https://github.com/bnb/awesome-hyper

This plugin will do: https://www.npmjs.com/package/hypercwd

**Comment by nomad3k** [comment]
No, I didn't check plugins.  Thanks.

https://www.npmjs.com/package/hypercwd preserves the CWD for Tabs, but not Split Panes.

**Comment by joggienl** [comment]
> https://www.npmjs.com/package/hypercwd preserves the CWD for Tabs, but not Split Panes.

It does

**Comment by nomad3k** [comment]
If your answer was "It does (on Mac)" then you'd be right, but on Windows it doesn't.  :)

Looks like they have an open issues https://github.com/hharnisc/hypercwd/issues/18 but the project hasn't moved forward in 6 months.  Isn't this something that should be core, rather than a plugin?

**Comment by joggienl** [comment]
I did a quick look on the plugin code, indeed my guess is that this will only work on Linux and macOS (maybe Bash on Windows or Cygwin like stuff as well) and not in cmd on windows..

I think this feature could most definitely be awesome to have in the core and configurable (just panes and not tabs or visa versa or both).

**Comment by CodeTheory** [comment]
We're currently considering having this in the core.

**Comment by Ademord** [comment]
Speaking of tabs and working directory, I am adding Hyper to Nautilus context menu and I'm trying to figure out what parameter do you feed hyper so it opens on the indicated directory. Can anyone help me here :(?

**Comment by joggienl** [comment]
maybe this link will give you some help with that: https://askubuntu.com/questions/845178/how-to-open-nautilus-directory-in-current-terminal

disclamer: did just a quick google search and found this one..

**Comment by colbin8r** [comment]
I'd also like to see this in core! (I'm the guy who opened https://github.com/hharnisc/hypercwd/issues/18. 😃) Just wanted to mention that as a user on Windows running Hyper on the WSL, I'd love to see support for both Windows/`cmd.exe` and bash in the WSL.

**Comment by hharnisc** [comment]
I had some time this weekend to update `hypercwd` for windows https://github.com/hharnisc/hypercwd/pull/25 

If you update `hypercwd` to version 1.0.0 you should get the new functionality

**Comment by eromoe** [comment]
`hypercwd`  would get error when opening a new tab  https://github.com/hharnisc/hypercwd/issues/51  .
It looks like some hyper update after 2.0.0 break hypercwd . 
This feature should be build-in .

**Comment by scott-joe** [comment]
@hharnisc can we get another fix? It just freezes Hyper when used :\

**Comment by chevtek** [comment]
Also fighting with this issue. Split panes always reset to home directory and the hypercwd plugin just causes an error when you try to make new tabs/panes with it installed and loaded.

**Comment by cerino-ligutom** [comment]
> Also fighting with this issue. Split panes always reset to home directory and the hypercwd plugin just causes an error when you try to make new tabs/panes with it installed and loaded.

Still the same issue as of writing this.

![image](https://user-images.githubusercontent.com/6721822/178904651-5e13e993-e5b6-4d0b-93a8-3eb78150f253.png)

If `hypercwd` is enabled/loaded and I try to do a split pane, it causes an error.

![image](https://user-images.githubusercontent.com/6721822/178904841-946d8106-c087-4394-8a47-2aab30c6a9f6.png)

**Comment by LabhanshAgrawal** [comment]
You can use the canary build with `preserveCWD: true`
