### ISSUE TITLE
Hyper does not remove context menu extension on uninstall [Windows]

### ISSUE THREAD

**Issue by mqudsi** [vercel/hyper#2068]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 15063.540
- **Hyper.app version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Uninstalling hyper does not remove the shell extension:

<img width="175" alt="hyper context menu" src="https://user-images.githubusercontent.com/606923/29134587-bca7d072-7cfc-11e7-83f5-07d5a2113a79.png">

**Comment by mikaalanwar** [comment]
+1 

I came across the same issue.

![image](https://user-images.githubusercontent.com/22380077/66276482-04dba300-e8ad-11e9-892e-dc7410ad8cbb.png)

**Comment by LabhanshAgrawal** [comment]
Doesn't seem to be the case on latest [canary build](https://github.com/vercel/hyper/actions/runs/162241917)
Feel free to open a new issue if you face any other problems
