### ISSUE TITLE
Problematic ANSI escape

### ISSUE THREAD

**Issue by jaydenseric** [vercel/hyper#2285]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra v10.12.6
- **Hyper.app version**:  2.0.3 (canary)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

In a file called `bug.js`:

```js
process.stdout.write('One\n')

// ANSI escape to clear the screen
// See https://github.com/sindresorhus/ansi-escapes/blob/v3.0.0/index.js#L77
process.stdout.write('\u001Bc')

process.stdout.write('Two\n')
```

Running `node bug` in Hyper outputs:

```
wo
```

When it should be:

```
Two
```

The Terminal app has the correct output (although it does not correctly clear the scroll history, but that's another story).

**Comment by Stanzilla** [comment]
@jaydenseric Hey there, could you test this in the Visual Studio Code terminal, please? If it happens there as well, it's https://github.com/xtermjs/xterm.js/issues/1395 otherwise Hyper's fault.

**Comment by LabhanshAgrawal** [comment]
Tested using the latest [canary build](https://github.com/vercel/hyper/actions/runs/153185087)
It seems to be working properly
Feel free to open a new issue if you face any other problems
