### ISSUE TITLE
Links broken in Terminal on resized window

### ISSUE THREAD

**Issue by jonathanlinat** [vercel/hyper#2424]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Professional
- **Hyper.app version**: 2.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jonathanlinat/437bfc84af7b30836243949f3f40284a
- **The issue is reproducible in vanilla Hyper.app**: hyper-snazzy plugin + Git bash

## Issue

![hyper_cutted_link](https://user-images.githubusercontent.com/14064112/32402346-8854fa14-c100-11e7-9425-cb24f4d296bb.gif)

**Comment by kenorb** [comment]
Same in Hyper 2.0.0 (stable)

**Comment by CWSpear** [comment]
It looks like if the link wraps at all (no need for resizing), then the URL won't work properly.

**Comment by albinekb** [comment]
This is fixed upstream in xterm @chabou we need to use the latest xterm to get this..

**Comment by LabhanshAgrawal** [comment]
We're on the latest xterm and this issue is not reproducing on latest canary [build](https://github.com/vercel/hyper/actions/runs/157826845)
