### ISSUE TITLE
All Panels Zoom Out not working

### ISSUE THREAD

**Issue by EdgarACarneiro** [vercel/hyper#2447]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsof Windows Home 1703
- **Hyper.app version**: 2.1.1 (canary), commit: c62e042
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue
Zoom Out in all Panels not working. When pressed CTRL + SHIFT + MINUS, nothing happens, even though the opositte keymap  - CTRL + SHIFT + PLUS, to zoom in all panels, is working.

**Comment by LabhanshAgrawal** [comment]
tested to be working on latest build
