### ISSUE TITLE
Ability to move around the the command prompt by clicking?

### ISSUE THREAD

**Issue by HaraldNordgren** [vercel/hyper#2537]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Is it possible -- through an extension or without it -- to move around the command you are typing by clicking. Like in a modern text editor?

This would be particularly helpful when you have a very looong terminal line where you need to navigate to change something in the middle. One solution is to paste it in to your text editor to to change it. But it would be neat if Hyper could also do it.

**Comment by thedonquixotic** [comment]
Plus 1 on this.
