### ISSUE TITLE
Terminal Screen is Rendered in Only 1 Column

### ISSUE THREAD

**Issue by cybertk** [vercel/hyper#2609]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 1607 Windows 10 Pro
- **Hyper.app version**: 2.0.0-canary.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Empty
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

See following screenshot

![capture](https://user-images.githubusercontent.com/455809/34925361-ce1f52da-f9e3-11e7-9a91-6e4c1091fab3.JPG)

**Comment by MAPESO** [comment]
@cybertk  Hi, We are aware of this error, we are working to solve it 😄 
Thanks for the report.

**Comment by Stanzilla** [comment]
This is how it behaves on Windows after https://github.com/zeit/hyper/pull/2612 and https://github.com/zeit/hyper/pull/2594

https://dl.dropboxusercontent.com/s/91g9nys1sxgen3h/2018-01-16_01-41-46.webm

**Comment by chabou** [comment]
The good news is that it act in the same way bewteen focused and unfocused tab.
But there is some glitches with line returns in your video. I suspect a race condition when a resize event occurs during a previous resize event. I have better result if I resize windows very slowly. We maybe need to debounce some calls. Or act like `ConEmu` and resize terms only when mouse button is up.

**Comment by LabhanshAgrawal** [comment]
Closing as this was for v2
Feel free to open a new issue if you face any problems with latest [builds](https://github.com/vercel/hyper/actions/runs/157826845)
