### ISSUE TITLE
Nano: Enter Key Not Working

### ISSUE THREAD

**Issue by harblz** [vercel/hyper#2647]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I frequently make small file edits via ssh to a Linode (running Ubuntu 16.10). When I edit a file using nano, the enter key stops behaving as expected upon entering nano - outside of nano, it behaves as expected. Hitting enter does not create a new line - it toggles "Can Now UnJustify." When I attempt to save a file the terminal does not respond when I hit the enter key to write the file to disk. It appears as if the terminal / nano is not capturing the enter key correctly - or perhaps I'm just doing something incredibly dumb. I've reproduced this on two different machines, with fresh vanilla hyper installs.

**Comment by markopolo123** [comment]
Looks like this problem here, an issue with OpenSSH on Windows 10:

https://github.com/PowerShell/Win32-OpenSSH/issues/1004

**Comment by DANIELG1952** [comment]
The issue with the enter key in nano can be bypassed. In the /etc folder there is the “nanorc” file in which we can remap some keys. At the end of the file I added 2 lines:
bind ^S savefile main
bind ^E enter all
When I edit a file with nano I can use ^S to save the file or ^O and ^E. And to use the enter function (break to new line) in the text I use ^E.

**Comment by DANIELG1952** [comment]
Another solution is to install the latest OPENSSH from 
http://www.mls-software.com/opensshd.html
OPENSSL by Microsoft is 7.5 and here we become 7.6.
This version has no problem with the keyboard at all.
