### ISSUE TITLE
[Feature Request] - .hyperfile file acting as a launch script

### ISSUE THREAD

**Issue by alshdavid** [vercel/hyper#2685]
I have an environment that has the same setup.

1) Open hyper as admin
2) Split vertically
3) Split vertically 
4) Split previous horizontally
5) Split next vertically.
6) Run series of commands on each
7) New tab
8) ...etc

This has been the optimal environment for my current workflow and I repeat this process sometimes multiple times a day.

Would be really cool to have `.hyperfile` file type that can be opened by hyper, allowing scripting these start up events.

For example:
`startup.hyperfile`
```
// Starts with no tabs so you initialize the first
const tabOne = hyper.createTab() 
const tabTwo = hyper.createTab()

const splitOne = tabOne 
const splitTwo = tabOne.splitVertically()
const splitThree = tabOne.splitVertically()
const splitFour = splitTwo.splitHorizontally()

splitOne.runCommand('dir')
splitTwo.runCommand('dir')
splitThree.runCommand('dir')
splitFour.runCommand('dir')

tabTwo.runCommand('npm install')
```

Then from Windows, I'd just double click the `.hyper` file and it would go ahead and run the sequence.
Thoughts?

**Comment by albinekb** [comment]
I like the idea! I think this is already possible by creating a plugin that registers with .hyperfile extension, and picks that up, runs it with it's own lib converting it to hyper's redux actions, dispatching them to the hyper store and thus opening tabs etc.
