### ISSUE TITLE
Support for vertical selection

### ISSUE THREAD

**Issue by kenorb** [vercel/hyper#2697]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.13.2 (17C2120)
- **Hyper.app version**: Hyper 1.4.8 (stable)

## Issue

In _Terminal_ app I could press _Alt_ key and make a vertical selection, similar in iTerm. E.g.

<img width="194" alt="screen shot 2018-02-22 at 16 01 22" src="https://user-images.githubusercontent.com/266306/36549109-dbd38b02-17e9-11e8-8129-a22e3c69241d.png">

However vertical selection is not supported in Hyper.

**Comment by chabou** [comment]
In our v2, selection is handled by xterm.js.
Thus, we need to implement this in xterm.js repository.

**Comment by Stanzilla** [comment]
Hey there, to verify if this is indeed a Hyper issue or upstream at https://github.com/xtermjs/xterm.js/ could you please test if another xterm.js powered terminal shows the same problem you are experiencing? I suggest using https://github.com/Microsoft/vscode for testing. Thanks!

**Comment by kenorb** [comment]
Seems it's fixed now in [upstream](xtermjs/xterm.js/issues/1300).

**Comment by Tyriar** [comment]
You'll get this just by upgrading to 3.5 which was just released 👍, though you will need to expose `macOptionClickForcesSelection` if you want to enable alt+click to force selection on macOS (more info at https://github.com/xtermjs/xterm.js/releases/tag/3.5.0).

**Comment by LabhanshAgrawal** [comment]
fixed in #3255
