### ISSUE TITLE
the start dir of win10 shortcut lnk is unavailable

### ISSUE THREAD

**Issue by shynome** [vercel/hyper#2732]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/tag/2.0.0-canary.14) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  windows10 1709
- **Hyper.app version**: 2.0.0-canary.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: <https://gist.github.com/shynome/cfa2d08b4588c4c9a2bc6e3b88c69806>
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

the start dir options are the same, but hyper open `c:/user/<user>` dir.

| wsl  | hyper |
| -----------| -------- |
| ![image](https://user-images.githubusercontent.com/17316043/36947854-a559843e-200c-11e8-9858-c411ec57659e.png) | ![image](https://user-images.githubusercontent.com/17316043/36947861-b54cb154-200c-11e8-835b-ad6272611eda.png) |
| ![image](https://user-images.githubusercontent.com/17316043/36948018-33bf8280-200f-11e8-9110-fa2a50cb398c.png) | ![image](https://user-images.githubusercontent.com/17316043/36948014-1fa94592-200f-11e8-9bc2-98c44a4b894a.png) |

when I open hyper in right mouse button menu , it work ok
![image](https://user-images.githubusercontent.com/17316043/36947969-7bff8974-200e-11e8-8669-d8988c5b4102.png)
![image](https://user-images.githubusercontent.com/17316043/36947975-95f09724-200e-11e8-8164-b3f1dd5e0170.png)

**Comment by LabhanshAgrawal** [comment]
use `workingDirectory` config key #3769
