### ISSUE TITLE
Retain commented out plugins when installing/uninstalling plugins from the cli

### ISSUE THREAD

**Issue by timothyis** [vercel/hyper#2756]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version (canary)
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.3 (High Sierra)
- **Hyper.app version**: Hyper 2.0.0-canary.14 (canary)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I tried to comment out three plugins in my .hyper.js config so that I could take screenshots of other plugins and themes that I'd install via the Hyper CLI. Upon either installing or uninstalling the plugin/theme that I was taking a screenshot of, the commented out plugins in my config disappeared and the node_modules pertaining to them also got removed.

## Expected Behaviour
Unless specified, plugins commented out should retain

**Comment by chabou** [comment]
`node_modules`should be cleaned, no problem whith that.
But we should keep commented plugins.

It should happen somewhere here:
https://github.com/zeit/hyper/blob/e4cef0a17234f1c99a6a9ef171cea41f7b382163/cli/api.js#L104-L105

**Comment by itaisteinherz** [comment]
@timothyis could you try to reproduce this again using the latest version of Hyper?
I just tried adding a commented-out plugin to `~/.hyper.js`, and even after installing and uninstalling modules using the `hyper` binary the comment remains.

**Comment by BrunoBernardino** [comment]
I can confirm this doesn't happen with the latest stable version of Hyper. Can probably be closed.
