### ISSUE TITLE
nodeschool.io render issue

### ISSUE THREAD

**Issue by yoyoys** [vercel/hyper#2821]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.4
- **Hyper.app version**:  2.0.0-canary.16
## Issue
The italic font render failed, and blue background not appear too.
  
### hyper
![image](https://user-images.githubusercontent.com/22124891/38731434-c21278a6-3f4c-11e8-89df-e6fa9b8447a2.png)
  
### iTerm2
<img width="907" alt="image" src="https://user-images.githubusercontent.com/22124891/38731441-c9c4d102-3f4c-11e8-9530-ad92fa4f0c79.png">

**Comment by chabou** [comment]
Reproduced.

Thank you for your feedback 🙏

**Comment by LabhanshAgrawal** [comment]
Tested with latest [build](https://github.com/vercel/hyper/actions/runs/157826845)
seems to be working properly
ref https://github.com/vercel/hyper/issues/4404 https://github.com/vercel/hyper/issues/2038
Feel free to open a new issue if you face any problems
