### ISSUE TITLE
Hyper CLI command not installed if /usr/local/bin doesn't exist

### ISSUE THREAD

**Issue by colinhemphill** [vercel/hyper#2829]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/colinhemphill/04a4c1e91a89ac2958e679581e38fb26
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I updated to 2.0.0, and the `hyper` commands aren't working for me. From poking around in documentation, it doesn't look like I'm supposed to do anything to have access to the CLI, but maybe I'm wrong.

`bash: hyper: command not found`

<img width="1440" alt="screen shot 2018-04-16 at 11 33 39 am" src="https://user-images.githubusercontent.com/1854690/38822929-9618750a-416a-11e8-81ee-e8f732fbcda7.png">

**Comment by chabou** [comment]
Can you try to find this symbolic link?
```
❯ ls -lah /usr/local/bin/hyper
lrwxr-xr-x 1 chabou admin 52 avr 15 14:14 /usr/local/bin/hyper -> /Applications/Hyper.app/Contents/Resources/bin/hyper
```

**Comment by colinhemphill** [comment]
@chabou It appears `/usr/local/bin/hyper` doesn't exist on my machine.

**Comment by colinhemphill** [comment]
@xoche I think there's a closed issue for that one: https://github.com/zeit/hyper/issues/2826

**Comment by colinhemphill** [comment]
@chabou I created the directory after you posted your first question and tried to install Hyper from scratch. This is a brand new Mac and it definitely wasn't there initially. Maybe I need to update the permissions on `/usr/local/bin` and try again?

**Comment by donatoaguirre24** [comment]
I'm having the same problem in windows 10, I update hyper to v2.0.0 but the CLI doesn't work

**Comment by colinhemphill** [comment]
@donatoaguirre24, you're problem on Windows might be related to this: https://github.com/zeit/hyper/issues/2823

**Comment by chabou** [comment]
After some discussion with @colinhemphill on Slack https://zeit-community.slack.com/archives/C1TMVKPFH/p1523905461000364

It appears that `/usr/local/bin` could not exists (and not be added to path).
Install `homebrew` fixed this.

We should take care of that.

**Comment by rbukovansky** [comment]
Mine `/usr/local/bin` exists and hyper was not installed there? Permissions? Shouldn't Hyper try to install itself there by using elevated permissions?

**Comment by albinekb** [comment]
No, `/usr/local/bin` is used for the reason that it does not need elevated permissions 👍

**Comment by dawid-s** [comment]
> No, /usr/local/bin is used for the reason that it does not need elevated permissions +1
Unless you are trying the get it working on a machine where you don't have write permissions in /usr/local/

Wouldn't it make sense to try to symlink to $HOME/.local/bin if it fails to acess /usr/local/bin?

**Comment by jacksonhvisuals** [comment]
For some reason, on my macOS 10.13.4 installation, installing Hyper from the website didn't install `hyper` cli command. Checked /usr/local/bin, and it's not there.

**Comment by samstr** [comment]
Same issue for me. Brand new Macbook Pro. High Sierra 10.13.4 (17E202). 

`hyper: command not found`

Hyper.app installed fine. Well, I dragged it into Applications and executed it without any errors.

Turns out `/usr/local/bin` didn't exist on my machine.

**Comment by dsantosp12** [comment]
In my case, /usr/local/bin exists, and I still have the same issue.

**Comment by jacksonhvisuals** [comment]
Got it to work. Had to install it via NPM and reboot. Dunno why it didn't install by default.

**Comment by jakobereksen** [comment]
@jacksonhvisuals how did you install via npm?

**Comment by jacksonhvisuals** [comment]
Actually, I think all I ended up doing was installing `hyperpower` and rebooting... which *shouldn't* have fixed the issue, but it did. @jakobereksen

**Comment by jakobereksen** [comment]
ok thank you. that did not work for me though. Even though I did install hyper through brew cask on my admin user, the install failed silently, because my default user did not have write permissions for usr/local/bin. I temporarily enabled my default user to write in that directory and the install worked. Still a weird behaviour, since all other programs I had installed before the same way did not have problems of that sort.

**Comment by bkjoel** [comment]
Sorry if bumping the thread or anything along the lines.

In my case I didn't get the symbolic link on `/usr/local/bin` and had to create it manually using - `sudo ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper` which fixed the problem 👍

**Comment by bkjoel** [comment]
@chabou I was thinking of helping with this issue.
I’m not familiar with MacOS installations (the whole drag to applications shazam). 

After fiddling with the source I was able to find ‘app/utils/cli-install.js’ which had a part where it tried to create a symlink in ‘/usr/local/bin’ and figured it ran on installation. 

I believe this is the root of the problem in cases where the symlink isn’t created (not in cases where the folder doesn’t exist, although a check could be performed there prompting the folder’s creation) -  ‘/usr/local/bin’ comes with writing permissions only for Root (specifically Wheel group?) on brand new MacOS installations. 

The question is whether the installation process runs on higher privileges and if not whether it should. Either way I think the default permissions on
’/usr/local/bin’ are the main problem.

Can we run the installation on higher privileges? Should we modify ‘/usr/local/bin’ write permissions?

**Comment by scottyzen** [comment]
> Sorry if bumping the thread or anything along the lines.
> 
> I installed Hyper on a brand new OSX installation -
> In my case I didn't get the symbolic link on `/usr/local/bin` and had to create it manually using - `sudo ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper` which fixed the problem 👍

This worked for me. Thanks

**Comment by andersab** [comment]
I can recreate this in my OSX environment...

1. Download and unzip Hyper
2. Open Hyper after you download (it appears the /usr/local/bin link will link to where ever that is you first started it from - my case was the download temp directory in the browser)
3. The link will be broken once you close that hyper instance
4. Once you drag the app to "Applications" it will be broken also

I fixed it by the following

```bash
rm /usr/local/bin/hyper
ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper
ls -lah /usr/local/bin/hyper
``` 

The last command checks it.

**Comment by moebg** [comment]
@andersab Thank you ! Fixed it on my computer! 😄

**Comment by FelipeVegners** [comment]
> I can recreate this in my OSX environment...
> 
> 1. Download and unzip Hyper
> 2. Open Hyper after you download (it appears the /usr/local/bin link will link to where ever that is you first started it from - my case was the download temp directory in the browser)
> 3. The link will be broken once you close that hyper instance
> 4. Once you drag the app to "Applications" it will be broken also
> 
> I fixed it by the following
> 
> ```shell
> rm /usr/local/bin/hyper
> ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper
> ls -lah /usr/local/bin/hyper
> ```
> 
> The last command checks it.

Great, It's work for me!

**Comment by andresayej** [comment]
> @chabou I was thinking of helping with this issue.
> I’m not familiar with MacOS installations (the whole drag to applications shazam).
> 
> After fiddling with the source I was able to find ‘app/utils/cli-install.js’ which had a part where it tried to create a symlink in ‘/usr/local/bin’ and figured it ran on installation.
> 
> I believe this is the root of the problem in cases where the symlink isn’t created (not in cases where the folder doesn’t exist, although a check could be performed there prompting the folder’s creation) - ‘/usr/local/bin’ comes with writing permissions only for Root (specifically Wheel group?) on brand new MacOS installations.
> 
> The question is whether the installation process runs on higher privileges and if not whether it should. Either way I think the default permissions on
> ’/usr/local/bin’ are the main problem.
> 
> Can we run the installation on higher privileges? Should we modify ‘/usr/local/bin’ write permissions?

This worked for me as well. Thanks!

**Comment by andresayej** [comment]
> Sorry if bumping the thread or anything along the lines.
> 
> I installed Hyper on a brand new OSX installation -
> In my case I didn't get the symbolic link on `/usr/local/bin` and had to create it manually using - `sudo ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper` which fixed the problem 👍

This worked for me as well. Thanks!

**Comment by fakhriperdana** [comment]
> I can recreate this in my OSX environment...
> 
> 1. Download and unzip Hyper
> 2. Open Hyper after you download (it appears the /usr/local/bin link will link to where ever that is you first started it from - my case was the download temp directory in the browser)
> 3. The link will be broken once you close that hyper instance
> 4. Once you drag the app to "Applications" it will be broken also
> 
> I fixed it by the following
> 
> ```shell
> rm /usr/local/bin/hyper
> ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper
> ls -lah /usr/local/bin/hyper
> ```
> 
> The last command checks it.

Wow this works! Thanks!

**Comment by ArgentSun** [comment]
> I can recreate this in my OSX environment...
> 
> 1. Download and unzip Hyper
> 2. Open Hyper after you download (it appears the /usr/local/bin link will link to where ever that is you first started it from - my case was the download temp directory in the browser)
> 3. The link will be broken once you close that hyper instance
> 4. Once you drag the app to "Applications" it will be broken also
> 
> I fixed it by the following
> 
> ```shell
> rm /usr/local/bin/hyper
> ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper
> ls -lah /usr/local/bin/hyper
> ```
> 
> The last command checks it.

This is more or less exactly what I did today after installing Hyper for the first time, and it's what I came to report. Applying this fix allowed me to use Hyper but led me to this error when installing a theme: https://github.com/zeit/hyper/issues/3648#issuecomment-532355802

**Comment by peterjhart** [comment]
Installing hyper.app in macOS Mojave would fail when creating the symlink.
Uninstalling then installing via `brew cask install hyper` successfully created the symlink.

**Comment by Andersclark** [comment]
> 

This worked for me, after I created the bin-folder first.
