### ISSUE TITLE
Bold text doesn't respect colors in config

### ISSUE THREAD

**Issue by LinusU** [vercel/hyper#2836]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/LinusU/a8d67a9459c989028682803a1a4307e7
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When outputting bold text, the colors specified in my `.hyper.js` file is no longer used, and instead, the default colors are used. This makes e.g. "bold cyan" look bad on a white background:

<img width="384" alt="screen shot 2018-04-16 at 18 44 01" src="https://user-images.githubusercontent.com/189580/38825929-279345e2-41a6-11e8-9c37-2ebac052aeee.png">

## Expected output:

This is how Terminal.app renders the same thing, with the same color settings:

<img width="411" alt="screen shot 2018-04-16 at 18 44 48" src="https://user-images.githubusercontent.com/189580/38825962-435d70fe-41a6-11e8-83d0-fae81bd76f5e.png">

(note how the prompt doesn't look the same in Hyper since that's using bold colors as well)

**Comment by LinusU** [comment]
This is possibly related: https://github.com/xtermjs/xterm.js/issues/1239

**Comment by chabou** [comment]
Totally related to xterm.

One workaround could be to disable brightColors. You can copy regular color as bright colors in your config:

```
  colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#000000',
      lightRed: '#C51E14',
      lightGreen: '#1DC121',
      lightYellow: '#C7C329',
      lightBlue: '#0A2FC4',
      lightMagenta: '#C839C5',
      lightCyan: '#20C5C6',
      lightWhite: '#C7C7C7',
    },
```

Or use 1.x color scheme:
```
   colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#000000',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },
```

**Comment by LinusU** [comment]
Thanks for the workaround, fill try and fix this in Xterm instead though 😄 

see xtermjs/xterm.js#1391 😎

**Comment by chabou** [comment]
@LinusU Amazing! Please continue your good work on this PR!

**Comment by LabhanshAgrawal** [comment]
https://github.com/xtermjs/xterm.js/pull/1391 is merged

**Comment by sircinnamon** [comment]
I think this bug is still present. Bold text is failing to respect the colors set in my config (both the `color` and the `brightColor`)

![image](https://user-images.githubusercontent.com/16858312/151062051-fbcb00aa-2724-4338-92e5-4c7d3918a555.png)
