### ISSUE TITLE
hyper cli not installed when updating to 2.0 on linux

### ISSUE THREAD

**Issue by jeffshaver** [vercel/hyper#2854]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: CentOS 7
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jeffshaver/9a2b67ec274e30de37e78425ed0ca8a6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: I don't think this has anything to do with addons, but I didn't test it without my `hyper.js` file and `.hyper_plugins` directory not existing.

## Issue
I upgraded from 1.4.8 to 2.0.0 and then proceeded to try to run `hyper i hypercwd` but I got an error saying `zsh: hyper: command not found`. I looked around the github repo and found a few issues that kind of seemed similar but were specific to MacOS or Windows. I checked to see if those issues seemed to solve my problem regardless, though and it doesn't seem as though they do.

In the MacOS issue (https://github.com/zeit/hyper/issues/2829), it's problem was that `/usr/local/bin` didn't exist. Not only does my `/usr/local/bin` directory exist, but it also has other things in there that I am able to use.

The Windows issue (https://github.com/zeit/hyper/issues/2849) didn't seem relevant because it had to do with something not being added to the `PATH`

**Comment by albinekb** [comment]
Maybe we didn't have permission to write to /usr/local/bin?

**Comment by jeffshaver** [comment]
@albinekb why would other installs be able to write to that directory? I could try changing the permissions and re-installing

**Comment by LabhanshAgrawal** [comment]
The issue mentioned here seem to be fixed in canary branch
please try a build from https://github.com/vercel/hyper/actions/runs/568537952#artifacts
closing this, please open a new issue if you face any problems with the ci build
