### ISSUE TITLE
can't open new tab

### ISSUE THREAD

**Issue by Thebigbignooby** [vercel/hyper#2889]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0 (but problem existed in previous versions too)
- **Link of a [Gist](https://gist.github.com/Thebigbignooby/6aac31e7b5e8344162b79c234e97edd9)
- **Relevant information from devtools** 
```
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyperfull (2.0.1) loaded.
bundle.js:1 Plugin hypercwd (1.2.1) loaded.
bundle.js:1 Plugin hyperlinks (0.5.0) loaded.
bundle.js:1 Plugin hyper-tabs-enhanced (0.4.2) loaded.
bundle.js:1 Plugin hyper-statusline (1.7.6) loaded.
bundle.js:1 Plugin hypertheme (0.1.0) loaded.
bundle.js:1 Plugin hyper-material-theme (2.0.6) loaded.
bundle.js:1 Warning: "hyper-material-theme" plugin uses some deprecated CSS classes (x-screen, ::selection).
O.Object.keys.forEach @ bundle.js:1
C:\Users\rory\.hyper_plugins\node_modules\hypercwd\configParse.js:5 hypercwd: no 'config.hypercwd' object found in ~/.hyper.js - see https://github.com/hharnisc/hypercwd#configuration for configuration details
index.html:35 total init time 601.905
```
- **The issue is reproducible in vanilla Hyper.app**: dont know

## Issue

I am on windows, and get the following error when I try to open a new tab

![hyper--bug-new-tab](https://user-images.githubusercontent.com/4172090/39039612-1dd6d162-4486-11e8-9758-321d4d1bf464.PNG)

**Comment by timothyis** [comment]
Could you try and comment out your plugins and see if it works then? If it does, try and comment back each plugin one at a time until you find the culprit.

**Comment by Thebigbignooby** [comment]
lol, so I commented them out and new tab worked. thanks

now, i uncomment "hyperfull" plugin and "new tab" opens 2 tabs at ounce haha

.... ok weird, I have now uncommented all plugins, and new tab still works, and opens up only 1 tab every time.

**Comment by gazedash** [comment]
I can reproduce this without any plugins

**Comment by ivanreese** [comment]
I had this issue due to the hypercwd plugin. Switching to https://github.com/LeanderFS/hypersamewd fixed the issue for me.

**Comment by gazedash** [comment]
> I had this issue due to the hypercwd plugin. Switching to https://github.com/LeanderFS/hypersamewd fixed the issue for me.

I tested it without any plugins at all and it was reproducible

**Comment by kivi** [comment]
I have the same problem on windows 10. I have a similar error "A JavaScript error occured n the main process" with hyper\app-3.0.2  
I can reproduce the issue with hypercwd and without hypercwd.

**Comment by LabhanshAgrawal** [comment]
doesn't seem to happen now that we use newer node-pty versions
closing for now, can reopen if it's there with v3.1.3
