### ISSUE TITLE
Javascript error lauching 'WinPTY agent Security'

### ISSUE THREAD

**Issue by mathvbarone** [vercel/hyper#2908]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64 bit
- **Hyper.app version**: 2.0

## Issue
I just installed the last version of Hyper.js, and when I try to launch the terminal, I'm having this error:

![error-hyper](https://user-images.githubusercontent.com/17620824/39122928-b25bd7fe-46cc-11e8-9886-ccdb8477123e.JPG)

**Comment by nonamelab** [comment]
Do u still get an error when u remove .hyper.js config file in your user folder ?

**Comment by mathvbarone** [comment]
Yeah man, I removed the whole pack of files and downloaded again. I did it twice.

**Comment by 7ictor** [comment]
@nonamelab I had the same issue and it worked for me just to remove the `.hyper.js` config file.

**Comment by mathvbarone** [comment]
I got it, and deleted the file right now....same error.

**Comment by mathvbarone** [comment]
I just noticed that if I delete the config file, and full reload my Hyper window, it works.
However, if I close the window and open it again I have the same error.

**Comment by nonamelab** [comment]
Are u starting it as administrator or normal user ?

**Comment by gmarinella9** [comment]
please check your firewall, I had to put a new rule to solve it

**Comment by hullarb** [comment]
yes, it seems to be the firewall in my case too.  it's just started to happen after the last update (2.1.0).
after temporary disabling windows firewall hyper could start and after re-enabling firewall it seems the issue is gone.

**Comment by abetrs** [comment]
I have the same problem I tried the firewall solution it didn't work the run as admin solution didn't work either

**Comment by ademspr** [comment]
Hi, Are you using McAfee antivirus?

**Comment by lilisgeorge** [comment]
Hi, I had the same issue executing hyper on a brand new laptop today, having pre installed mcAfee antivirus. I tried to solve it after reading this thread by disabling firewall without luck.

The problem solved as soon as I removed McAfee antivirus from the system.

I didnt investigate further why McAfee was causing the reason even with the firewall turned off since I didnt care keeping it anyway.

**Comment by frankenperez** [comment]
Hi,

I get the same error when I try to run Hyper with McAfee antivirus installed on my laptop. Deactivating firewall doesn't solve the problem.

**Comment by paxet** [comment]
Same problem here.
Tested it and confirmed Hyper can open correctly when disabling McAfee real time scan.
Once open, I've enabled again real time scan Hyper and continues to work fine.

**Comment by abetrs** [comment]
Yeah I deleted McAfee and it worked. Don't know why or how
