### ISSUE TITLE
Color is not escaped when a process is exited.

### ISSUE THREAD

**Issue by NicksWorld** [vercel/hyper#2918]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OSX high seria, 10.13.3
- **Hyper.app version**: 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/NicksWorld/21ddb662a88fe3fdbde54aa1550d8043
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, color is still not escaped

## Issue

When exiting a process using color, the color still exists.

An example of this is parrot.live and pressing ^C:
![parrot.live and ^C](https://image.prntscr.com/image/OILCMEH6S7ys8qVIaLe3Qw.png)

(Use ```curl parrot.live``` to get the example I used)

This is producible both with and without plugins installed. It appears it is just that colors are not reset when the process is exited (^C). From then on, the default color of text is the color it exited in, until another process uses color and resets it back to normal by escaping the color.

NOTE: This is using bash - does not work on all shells

**Works for any color**

Other screenshots:
![continuing color](https://image.prntscr.com/image/SpTl-OPwTtyflmz45tyuJw.png)

![resets after more color](https://image.prntscr.com/image/1rUzBMYcSJC6DuD1IS8syQ.png)

![more](https://image.prntscr.com/image/_P9MQOG_T3elNBDhgH5itA.png)

**Comment by timothyis** [comment]
I can't reproduce this, weirdly.

![image](https://user-images.githubusercontent.com/1695613/39161478-ced842ae-4768-11e8-8d8e-abf74604c3be.png)

I wonder if it has something to do with your shell? Which shell are you using?

**Comment by NicksWorld** [comment]
this? ```GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
These shell commands are defined internally.  Type `help' to see this list.
Type `help name' to find out more about the function `name'.
Use `info bash' to find out more about the shell in general.
Use `man -k' or `info' to find out more about commands not in this list.```

**Comment by timothyis** [comment]
Okay, I can reproduce this with bash

**Comment by NicksWorld** [comment]
Would you like me to write that it is bash in the issue body?

**Comment by ShaggyDev** [comment]
This issue is reproducible in the standard Terminal.app on mac. Is this really something that should be solved within hyper?

**Comment by Dakor91** [comment]
This also seem to affect text-background color, for example when exiting raspi-config on raspian:
![grafik](https://user-images.githubusercontent.com/4193623/47780915-b5840e80-dcfc-11e8-92e5-0409f13880a8.png)

If I start raspi-config and choose "finish" right away, everything is fine.
But if I start raspi-config, then choose one of the options (e.G. "Interface Options") and then"Back" followed by "Finish", the background color stays as shown.

**Comment by tpanning** [comment]
Is there a current way to reproduce this? It's not reproducible in hyper or the standard Terminal.app on Mac, even in bash. It seems more likely that curl has changed to reset the colors on interrupt than both hyper and Terminal.app fixed something.
