### ISSUE TITLE
Sometimes pressing ESC key takes a while to get response

### ISSUE THREAD

**Issue by LexSong** [vercel/hyper#2922]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 
- **Hyper.app version**: 2.0.0(Stable)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Sometimes pressing Esc key will take a long time to get response.

The reliable way to reproduce it is:

1. Run windows version vim with `vim`
2. Press `i` into insert mode
3. Type `test`
4. Press `<Esc>` key to leave insert mode. It will take roughly a second.
5. type `:q!` to leave vim
6. Even after leaving vim, `<Esc>` key still take a while to register. Random typing anything and `<Esc>` key will take a while to clean the cmd command line.

Reload won't fix it, only full reload with Ctrl-Shift-F5 can reset this behavior.

**Comment by LexSong** [comment]
I can reproduce this issue in the demo app of xterm.js.

**Comment by ecielam** [comment]
Am also getting this issue

**Comment by ecielam** [comment]
Testing the terminal timeout tweak in this post seems to fix this. I am only getting this issue when ssh'd to outside servers. This only popped up recently, it's been working fine for a while.

https://stackoverflow.com/questions/12312178/tmux-and-vim-escape-key-being-seen-as-and-having-long-delay

**Comment by jamessewell** [comment]
I get this too - but not when I first open a terminal and SSH out. It happens over time.

I'm using WSL as my base shell

**Comment by srchulo** [comment]
This also happens to me over time.

**Comment by jamessewell** [comment]
I love Hyper - it's the best terminal experience I've found for Windows.
This is pretty much a deal breaker for me though.

I end up eventually finding myself pounding ESC over and over again in VIM
trying to get out of insert mode :(

**Comment by uadev** [comment]
I have the same issue.

**Comment by kaddkaka** [comment]
I have never used hyper, but just for information I can share that I'm having similar problem with ESC taking about 1 second to register.

My setup is: WSL (Windows Subsystem for Linux) with Ubuntu -> ssh -> tmux -> nvim

**Comment by LabhanshAgrawal** [comment]
> I have never used hyper, but just for information I can share that I'm having similar problem with ESC taking about 1 second to register.
> 
> My setup is: WSL (Windows Subsystem for Linux) with Ubuntu -> ssh -> tmux -> nvim

Not clear if this is on hyper or ubuntu.exe?

**Comment by LabhanshAgrawal** [comment]
@LexSong @ecielam @jamessewell @uadev 
Is it still happening?
Can you try out the [ci build](https://github.com/zeit/hyper/actions/runs/83039360) once also (lots of improvements since last release)

**Comment by agscala** [comment]
I had this issue and narrowed it down to a tmux config problem:

Fix it by adding `set -sg escape-time 0` to `~/.tmux.conf`

You can apply it without restarting tmux by:

`<C-b>:source-file ~/.tmux.conf` (or substituing `<C-b>` for your tmux control key.

**Comment by LexSong** [comment]
> @LexSong @ecielam @jamessewell @uadev
> Is it still happening?
> Can you try out the [ci build](https://github.com/zeit/hyper/actions/runs/83039360) once also (lots of improvements since last release)

Hi, sorry for the late reply

I can confirm that this issue no longer exists.
I'll close this issue.
