### ISSUE TITLE
Sluggish running over SSH

### ISSUE THREAD

**Issue by LeeDownshift** [vercel/hyper#2926]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/StlthyLee/51de883cf928adefa0579bb48fd7d134
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue
When working over SSH, Hyper becomes very sluggish. For instance making changes to files in either Emacs or Nano, it can take between 5-10 seconds just for a key press to be registered.  Doing exactly the same tasks in Terminal.app works without issue and no lag.

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and reopen this or open a new issue if you face this problem with the new build.
