### ISSUE TITLE
macOS: Set default directory?

### ISSUE THREAD

**Issue by kevinSuttle** [vercel/hyper#2929]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS 10.13.4 (17E199)
- **Hyper.app version**:  Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/kevinSuttle/0e830041913088561cd1997d5c08da00#file-hyper-js-L36
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  **N/A**
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

Is it possible to set the default directory? Adding another index to `shellArgs` only results in a runtime error.

<img width="532" alt="screen shot 2018-04-24 at 11 16 02 am" src="https://user-images.githubusercontent.com/95672/39197078-a4b0fe82-47b1-11e8-9963-bc53872ab009.png">

```js
Uncaught Exception:
TypeError: Cannot read property 'resize' of undefined
    at Server.Window.rpc.on (/Applications/Hyper.app/Contents/Resources/app.asar/ui/window.js:146:14)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.ipcListener (/Applications/Hyper.app/Contents/Resources/app.asar/rpc.js:33:11)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

**Comment by saikrishnav** [comment]
I have a same question for Windows. How do I set the default startup directory for Windows? I am not using any custom shell.

**Comment by chabou** [comment]
Changing default directory depends on which shell do you use.

For `bash`: execute only one time : `echo "cd ~/code" >> ~/.bashrc`
For `zsh`: execute only one time: `echo "cd ~/code" >> ~/.zshrc`
(And edit this line in rc files if you want to change this directory later)

For Windows (CMD or PowerShell): see this issue: https://github.com/zeit/hyper/issues/2794


BTW, we definitely need to add a new config entry for this. Issue created: #3000

**Comment by LabhanshAgrawal** [comment]
you can set the `workingDirectory` config key for this.

**Comment by TheKasjel** [comment]
> Changing default directory depends on which shell do you use.
> 
> For `bash`: execute only one time : `echo "cd ~/code" >> ~/.bashrc`
> For `zsh`: execute only one time: `echo "cd ~/code" >> ~/.zshrc`
> (And edit this line in rc files if you want to change this directory later)
> 
> For Windows (CMD or PowerShell): see this issue: #2794
> 
> BTW, we definitely need to add a new config entry for this. Issue created: #3000

This worked fine for me, Im on Mac Catalina. THX. !
