### ISSUE TITLE
ANSI characters not showing up correctly

### ISSUE THREAD

**Issue by Azzhoe** [vercel/hyper#2946]
<img width="533" alt="screen shot 2018-04-27 at 8 07 20 am" src="https://user-images.githubusercontent.com/38174330/39364150-92d8786e-49f2-11e8-88d7-36e97801e74f.png">

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra
- **Hyper.app version**: 2.1.0 Canary
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When loading up BitchX irc client, some of the characters aren't displaying properly. I know this has to do with the text encoding because I also had the same issue when using Terminal.app. I was able to fix it by changing the text encoding to Latin-US (DOS), but I'm not sure if its even possible in Hyper. Please let there be a fix for this.

**Comment by LabhanshAgrawal** [comment]
Please try the [latest canary](https://github.com/vercel/hyper/actions/runs/151770461) once
closing this as it's for v2
Feel free to open a new issue if you face any problems with the canary build
