### ISSUE TITLE
Cannot select part of the link without opening it

### ISSUE THREAD

**Issue by kenorb** [vercel/hyper#2949]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.13.2
- **Hyper.app version**: 2.0.0 stable
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue

1. Type `git clone https://www.example.com/`.
2. Now try to select either `example.com` or other part.

Whenever you release click on the URL, it gets open. That's fine if the URLs are clickable, but not when you're trying to just select them.

**Comment by LabhanshAgrawal** [comment]
Fixed in #4543
Use a new build from CI and set `webLinksActivationKey` to one of `ctrl`,`alt`,`meta`,`shift`
