### ISSUE TITLE
Pasting large bodies of text warps the text

### ISSUE THREAD

**Issue by krainboltgreene** [vercel/hyper#2963]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macos 10.12.6
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/krainboltgreene/9e95de78ceb455ab44488e26de844558
- **The issue is reproducible in vanilla Hyper.app**: Can be reproduced in Vanilla

## Issue

<img width="1422" alt="screen shot 2018-05-01 at 4 04 36 pm" src="https://user-images.githubusercontent.com/334809/39497748-8ac7b7ce-4d59-11e8-8151-21c9ac59e393.png">

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this issue with the new build
