### ISSUE TITLE
Change Title Bar To Hostname

### ISSUE THREAD

**Issue by dlynchcodes** [vercel/hyper#2990]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64
- **Hyper.app version**: 2.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.githubusercontent.com/dlynch29/ddb57552acac57222e1b68b2c92ac6c6/raw/7e61f171b1263f7422b90eedad4b2c6406352a31/hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Hi there, I'm using zsh on 2.1.0 on Hyper on Windows 10.

I am just wondering how I can set the text in the title bar to be the Hostname, whereas it is currently the current working directory. 

Thanks :)

**Comment by thammuio** [comment]
I am looking for this too...

**Comment by LabhanshAgrawal** [comment]
you need to configure the behaviour from zsh
if you're using ohmyzsh checkout [this](https://github.com/ohmyzsh/ohmyzsh/issues/5700#issuecomment-316111109)
