### ISSUE TITLE
"exit" is not clickable on most top right position

### ISSUE THREAD

**Issue by fyears** [vercel/hyper#2996]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10
- **Hyper.app version**: 2.0 stable
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue

After maximizing the hyper window, the "exit" button on the top right is not the most top right of the full screen, which is annoying: I cannot just move my mouse to top right of the screen and click "exit" without much thinking, but I have to move the mouse back a little bit.

Let the screenshot explain my issue:

![screenshot](https://user-images.githubusercontent.com/1142836/39821098-fe6274f4-53d9-11e8-8d00-7d19a40b569c.png)

It's not about the core functions but is very important for usability. Most of other apps (at least in Windows) allow users click exit ANYWHERE near top right screen after maximizing their windows.

**Comment by LabhanshAgrawal** [comment]
Fixed on canary, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts)
