### ISSUE TITLE
Add startup/working directory config

### ISSUE THREAD

**Issue by chabou** [vercel/hyper#3000]
It should be more easy to configure a startup directory.
Currently, it has to be done at shell level for macOS/Linux shells (.bashrc/.zshrc...) and at `hyper` config level for CMD/PowerShell (See https://github.com/zeit/hyper/issues/2794).

I suggest to add an optional `workingDirectory` config parameter. If it is empty/undefined/malformated, default (config location) directory will be used.
Only an absolute path is valid. If a path is passed as parameter to `hyper`, it must be used instead of config/default, as is currently the case.

Magic should occur here: https://github.com/zeit/hyper/blob/f72093c9d75da963544a48a0eee8107ecb170cf8/app/ui/window.js#L93

**Comment by mtslzr** [comment]
Created PR #3021 for this.

**Comment by DamianRivas** [comment]
@chabou perhaps this issue should be closed since it was resolved by commit 164a600805cc8ba24ed01d58ba5cae6455107b2b

I was looking for a good issue to work on. I need to make 10 PRs to OSS projects before I can graduate from my apprenticeship. I use Hyper daily so I would love to help with anything if y'all need it :)

**Comment by corbanb** [comment]
Does this no longer work in 3.0? 

`workingDirectory: "~/Sites/someplace",`

**Comment by corbanb** [comment]
Does this no longer work in 3.0? 

`workingDirectory: "~/Sites/someplace",`

For now I just added `cd ~/Sites/someplace` to one of my custom plugin files for`oh-my-zsh`. ha

**Comment by kaushikchaubal** [comment]
I just added the workingDirectory field in my .hyper.js file as well and it didn't work as expected.

I aim to create a PR with a fix soon.

**Comment by kaushikchaubal** [comment]
PR created for this: https://github.com/zeit/hyper/pull/3769

Ready for review

**Comment by chabou** [comment]
There is a plugin for this: https://www.npmjs.com/package/hyper-working-directory

But maybe it should be a core feature?

**Comment by kaushikchaubal** [comment]
My two cents... this was a core feature which then broke. I think if we want to keep like-fo-like, it should be a core feature. (happy to be overruled)

**Comment by chabou** [comment]
I think it was never implemented 🤔

**Comment by ppot** [comment]
Was never a core feature. But had a flag in the config to define a default for the user.

**Comment by johnletey** [comment]
Has this been implemented? I see that #3769 was merged, but see https://github.com/zeit/hyper/pull/3769#issuecomment-552374299

**Comment by LabhanshAgrawal** [comment]
#3769 was merged
