### ISSUE TITLE
Brew download indicator appears on new line

### ISSUE THREAD

**Issue by Abeldvlpr** [vercel/hyper#3020]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/AbelIngrand/9c57eb1d4da68ea608e73cc2987040c7

- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When using homebrew in hyper in bash, the download of a package (ie: using install or upgrade) prints # on new lines instead of a single line.
```
==> Downloading xxx
#
##
###
####
#####
######
...
```

The normal beahaviour should be:
`==> Downloading xxx
########....`

**Comment by danteissaias** [comment]
I am also experiencing this issue.

**Comment by LabhanshAgrawal** [comment]
doesn't seem to be the case now
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and reopen the issue if you face this problem with the new build
