### ISSUE TITLE
How to highlight text with different colors 

### ISSUE THREAD

**Issue by ssashanks** [vercel/hyper#3022]
I searched all around the internet  and installed different themes, does Hyper not support highlighting different text with different colors? (Like I want to highlight all "error" with red or All text before $ handle in terminal with blue)

hyper-electron-highlighter theme shows something like that in the screenshot, but does not work. Same goes for all themes

**Comment by albinekb** [comment]
This is something that needs to be supported in xterm for hyper to be able to support it.

**Comment by LabhanshAgrawal** [comment]
that theme just sets the colors and some css, colored output in the terminal depends on whether it contains color escape codes
color escape sequences are supported in hyper
for any custom highlighting, you need to setup your shell/program to output accordingly or use some plugin
