### ISSUE TITLE
Wrong powerline 

### ISSUE THREAD

**Issue by solshark** [vercel/hyper#3030]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.4
- **Hyper.app version**: Hyper 2.1.0-canary.1 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/solshark/134c69e5c587d5f91ce1f44f9c1d4338
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Self-explaining screen dump:
<img width="1284" alt="hyper 2018-05-18 09-37-41" src="https://user-images.githubusercontent.com/107233/40233055-11bf5860-5aaa-11e8-9f99-caabd71922ea.png">

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build.
