### ISSUE TITLE
Cursor stops blinking when switching tabs

### ISSUE THREAD

**Issue by slammayjammay** [vercel/hyper#3041]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac High Sierra 10.13.1
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist](https://gist.github.com/slammayjammay/58e595840c1c2eacef67f1379cd2ba83) (same as the [default config](https://github.com/zeit/hyper/blob/master/app/config/config-default.js) except `cursorBlink` is set to true)

## Issue
The cursor will blink on startup and for any newly created tabs, but once a tab loses focus the cursor for that tab stops blinking.

However unfocusing and refocusing the Hyper app fixes it.

Currently seeing after a fresh install.

**Comment by GLaDOS-root** [comment]
Even I noticed this exact same issue.

**Comment by LabhanshAgrawal** [comment]
this is working with the canvas renderer
closing it for #3626 which is for webgl renderer
