### ISSUE TITLE
Windows Open Hyper here + initialWorkingDirectory

### ISSUE THREAD

**Issue by rodmansw** [vercel/hyper#3042]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**:  2.0.0 (stable)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

When the initialWorkingDirectory property is set the option Open Hyper here doesn't work, is being override by initialWorkingDirectory

**Comment by LabhanshAgrawal** [comment]
doesn't seem to happen in canary
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build
