### ISSUE TITLE
"yarn run dist" produces an invalid binary on mac with latest canary

### ISSUE THREAD

**Issue by MisterTea** [vercel/hyper#3060]
Upon running the canary binary produced by yarn run dist, I get this:

![image](https://user-images.githubusercontent.com/306879/40569837-d301fcfa-6039-11e8-9224-abebbaec7994.png)

**Comment by tjwelde** [comment]
This relates to this PR: https://github.com/zeit/hyper/pull/2866. I commented there with two solutions, but I need feedback.

**Comment by jcrben** [comment]
We should also update the test to actually test that a valid binary is produced - right now it's just hanging with no success or failure https://github.com/zeit/hyper/blob/canary/test/index.js#L11

**Comment by LabhanshAgrawal** [comment]
seems to be fixed
