### ISSUE TITLE
Drag Drop files and folders to get the path does not work on Windows 10

### ISSUE THREAD

**Issue by phifa** [vercel/hyper#3061]
I want to drag files or folders from the explorer into hyper to get the path, but that does not work. My cursor turns into a forbidden cursor and nothing happens. 

I expect it to work like on the Mac, when you drag sth into the terminal, the path is copied into the terminal.

**Comment by albinekb** [comment]
I think this is a regression or it has never worked on windows, see #110 and the fix in #559

**Comment by abeldantas** [comment]
@albinekb this would be a great feature. Any idea how one could add it?

**Comment by misolori** [comment]
This also does not work on macOS Mojave 😢

**Comment by shinriyo** [comment]
@misolori 
Me too. is it difficult to fix?

**Comment by bet4it** [comment]
This is fixed in [v3.1.0-canary.4](https://github.com/zeit/hyper/releases/tag/v3.1.0-canary.4).
