### ISSUE TITLE
Call Hyper from context menu not open current directory when called on disk root

### ISSUE THREAD

**Issue by accetone** [vercel/hyper#3062]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 2.0.0
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When you call hyper with "Open Hyper here" from context menu from disk root ("C:\", "D:\") it open in default user path ("C:\Users\XYZ") instead disk root

**Comment by Elderry** [comment]
In addition, if the directory name contains `[`, `Open Hyper here` will open hyper in root path(C:\ for me).
