### ISSUE TITLE
Ability for dev environment to have hot reloading (Reload on file save)

### ISSUE THREAD

**Issue by El-Dringo-Brannde** [vercel/hyper#3064]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.4 (17E202)
- **Hyper.app version**: 2.1.0-canary.1 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist here](https://gist.github.com/El-Dringo-Brannde/ce76b3079d6a5f8cfffd02882b52cb06)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

I was curious if anyone would be interested in me changing the `yarn dev` (or something similar) script such that it allows for the dev environment to be reloaded on file changes. 

I know currently we have the webpack doing a re-compile, I mean refreshing the actual window.

**Comment by Stanzilla** [comment]
@El-Dringo-Brannde go for it :)
