### ISSUE TITLE
Hyper notifies about older version update every time

### ISSUE THREAD

**Issue by jshrt** [vercel/hyper#3068]
- [x] Your Hyper.app version is **2.1.0-canary.1**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

Hyper still notifies me everytime I open it about the 2.0.0 version, and I am already one version ahead of that

![screenshot from 2018-06-04 14-42-14](https://user-images.githubusercontent.com/13497307/40932713-a3e5b118-6805-11e8-94dc-c95a17cfee7b.png)

 - **Hyper version**: undefined "2.1.0-canary.1"

 - **OS ARCH VERSION:** linux x64 4.13.0-43-generic
 - **Electron:** 1.8.4  **LANG:** en_US.UTF-8
 - **SHELL:** /usr/bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "\"Fira Code\", \"Fira Code\", \"Fira Code\", \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": true,
  "MaterialTheme": {
    "theme": "",
    "backgroundOpacity": "1",
    "accentColor": "#64FFDA",
    "vibrancy": "bright"
  },
  "paneNavigation": {
    "debug": false,
    "hotkeys": {
      "navigation": {
        "up": "alt+up",
        "down": "alt+down",
        "left": "alt+left",
        "right": "alt+right"
      },
      "jump_prefix": "alt",
      "permutation_modifier": "shift",
      "maximize": "ctrl+shift+x"
    },
    "showIndicators": true,
    "indicatorPrefix": "^⌥",
    "indicatorStyle": {
      "position": "absolute",
      "top": 0,
      "left": 0,
      "fontSize": "10px"
    },
    "focusOnMouseHover": false
  }
}

          {
  "plugins": [
    "hyper-blink",
    "hyperterm-paste",
    "hyper-polarbear",
    "hypercwd",
    "hyper-pane",
    "hypersixteen",
    "hyper-dracula"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by chabou** [comment]
You've downloaded a canary version.

Please change your `updateChannel: 'canary'` In your config file or download stable version from our website https://www.hyper.is

**Comment by jshrt** [comment]
Shouldn't this configuration entry ship with the canary installation by default?

**Comment by chabou** [comment]
Yes, it would be great. At the start, canary releases were not intended to be installed directly. But they are... a lot.

So PR welcome.

(Duplicates https://github.com/zeit/hyper/issues/2704)

**Comment by jshrt** [comment]
It would be great if I can allocate the time to this, looking forward to a PR.

Thanks for the time.
