### ISSUE TITLE
How to make the corners rounded in Windows?

### ISSUE THREAD

**Issue by Bernardi23** [vercel/hyper#3074]
![hyper](https://user-images.githubusercontent.com/36115642/41192816-6d76177a-6bda-11e8-8fcd-d0737aad1976.png)

- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10 Home
- **Hyper.app version**: 2.0.0

## Issue
Is there any way I can make the corners rounded like in MacOs?

**Comment by MAPESO** [comment]
@Bernardi23 Hi 😸, **this feature is unique to macOS**. The api de electron shows the dialogs according to the operating system.

**Comment by MAPESO** [comment]
Do you think we should close this issue? cc @albinekb @Stanzilla
