### ISSUE TITLE
`hyper install` crashes if .hyper.js has other lines above the `module.exports`

### ISSUE THREAD

**Issue by legodude17** [vercel/hyper#3076]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS 10.1.4
- **Hyper.app version**:  2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/legodude17/de5c254a5087f1e8f6e3cfb27c04faa2
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
`hyper install` crashes if if you include other JS than just the `module.exports = ` at the top.

**Comment by LabhanshAgrawal** [comment]
fixed in #4086
