### ISSUE TITLE
On hyper uninstall, context menu integration is not deleted. 

### ISSUE THREAD

**Issue by teunvw14** [vercel/hyper#3090]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 latest
- **Hyper.app version**: Pretty sure it was the last version ( I uninstalled so yeah, can't see that now)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Not applicable
- **Relevant information from devtools** None
- **The issue is reproducible in vanilla Hyper.app**: Not sure

## Issue

The title speaks for itself I think. On hyper uninstall, the context menu integration is not removed. I haven't been able to do it manually either, so if anyone can tell me how to do that (I have tried finding it in the registry, but there's no entry for it there), that would be much appreciated.

**Comment by teunvw14** [comment]
I was able to remove the entry manually in the registry at [HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper]. Maybe someone finds that useful.

**Comment by teunvw14** [comment]
Another note, I uninstalled through the "Apps & Features" settings interface.

**Comment by teunvw14** [comment]
Whoops, didn't mean to close the issue.
I wanted to add that I uninstalled Hyper through the "Apps & Features" settings.

**Comment by SiddharthPant** [comment]
For me the option was remaining in HKEY_USERS too. Make a search for "Open Hyper Here" by doing Ctrl + F in the registry editor. I think that's because I by default use a non-admin Standard user.
It was present at location Computer\HKEY_USERS\<Windows generated Very long ID>\Software\Classes\Directory\Background\shellex

**Comment by LabhanshAgrawal** [comment]
Tested on latest canary, seems to be fixed, no results on searching 'Open Hyper here' in registry after uninstall.
