### ISSUE TITLE
Hyper crashes on launch (window closes after a short flash)

### ISSUE THREAD

**Issue by morajabi** [vercel/hyper#3092]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.3
- **Hyper.app version**:Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/morajabi/f19a766bd70cef35434223f40e241d53
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Cannot open it, it closes so fast.
- **The issue is reproducible in vanilla Hyper.app**: Yes, I only had `hyper-snazzy#1.2.2` but removing it from plugins had no effect

## Issue

Opening the Hyper app, flashes the app, and closes the window. But menus are still there, Hyper is still open in the dock, but windows close automatically after around 200 ms. 

I once got this error and took the screenshot, but now it just closes without the dialog:
<img width="431" alt="screen shot 2018-06-18 at 5 54 38 pm" src="https://user-images.githubusercontent.com/12202757/41538958-c4af8b68-7321-11e8-947b-7ab0ae5bdf65.png">

**Comment by chabou** [comment]
It should have been fixed in our last canary.
Thanks to https://github.com/zeit/hyper/pull/2940

**Comment by morajabi** [comment]
Thanks! I'll close it for now then, if I got more info, I'll update the issue! 

Since I just got this error from my normal terminal too: 
```
dyld: Library not loaded: /usr/local/opt/gdbm/lib/libgdbm.4.dylib
  Referenced from: /usr/local/bin/zsh
  Reason: image not found
``` 

Probably this is the cause. Maybe you can add checking another terminal in the issue terminal to see if it's a bash / zsh issue :)
