### ISSUE TITLE
Error when adding native node module to an extension

### ISSUE THREAD

**Issue by TylerLeonhardt** [vercel/hyper#3096]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.0-canary.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/tylerl0706/a467cfc3894c5bae6642fc3d938a2189
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

```
Error: The module '\\?\C:\Users\tyler\.hyper_plugins\local\hyper-opacity\node_modules\electron-acrylic\build\Release\ElectronAcrylic.node'
was compiled against the ABI-stable Node.js API (N-API).
This feature is experimental and must be enabled on the 
command-line by adding --napi-modules.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.f._load (file:///C:/Users/tyler/AppData/Local/hyper/app-2.1.0-canary2/resources/app.asar/renderer/bundle.js:1:5100)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\tyler\.hyper_plugins\local\hyper-opacity\node_modules\bindings\bindings.js:81:44)
```

- **The issue is reproducible in vanilla Hyper.app**: No. You need to install a module that has a native dependency.

## Issue

Hi 👋 big fan of Hyper here. I have a mac and a PC and I LOVE themes that take advantage of electron's vibrancy on macOS like in [Verminal](https://github.com/defringe/verminal).

I wanted to try to enable the same thing for Windows. 

I know vibrancy is only supported on macOS, but I stumbled upon this:
https://github.com/23phy/electron-acrylic

and attempted to add the node module to the [hyper-opacity](https://github.com/lucleray/hyper-opacity) extension.

Unfortunately, since electron-acrylic is a native module, I got the error you see above. Any ideas on how I can get around this?

Ideally electron-acrylic could be built into electron... but if not, it'd be cool to have it built into hyper so that Windows gets the same love as macOS... but if not, if there's some way to add it to an extension to give hyper that fluent design, I'd be really happy!

**Comment by tylerl0706** [comment]
Good to know! When I have a sec, I'll give that a try. Otherwise, I'll just wait for the next canary :)

**Comment by iamakulov** [comment]
(BTW, there’s the `electron-vibrancy` module which apparently also can enable Acrylic blur on Windows: https://github.com/arkenthera/electron-vibrancy)

**Comment by LabhanshAgrawal** [comment]
we're on electron 11 now
shouldn't be an issue now, please try the latest build from ci and reopen this if you face this problem with new build
