### ISSUE TITLE
Enhance line length/wrap

### ISSUE THREAD

**Issue by ldexterldesign** [vercel/hyper#3098]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X 10.13.5 (17F77)
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ldexterldesign/e9771254dfa40265b892cc8effecafc7
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: vanilla

## Issue

Hi all,

Hope you're well

Thanks for software

As a user I want to control line wrapping so I can see content on a single line (e.g. useful for logs) - is this possible?:

If yes, please provide config instruction

If no, can we make this enhancement

![hyper mov](https://user-images.githubusercontent.com/1715809/41750751-dbd0276e-75bd-11e8-8a92-ec356aa01290.gif)
![terminal mov](https://user-images.githubusercontent.com/1715809/41750753-dfbb46d8-75bd-11e8-8e56-9d41ba96229f.gif)

NB My OS X Terminal comparison

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Keep up great work

Yours faithfully

**Comment by albinekb** [comment]
I think this is an issue with xterm.js, see https://github.com/xtermjs/xterm.js/issues/622 for more info about it 👍

**Comment by LabhanshAgrawal** [comment]
Closing as upstream issue https://github.com/xtermjs/xterm.js/issues/622 is closed
Feel free to open a new issue if you face any problems
