### ISSUE TITLE
Hyper CLI doesn't print a newline after unknown options

### ISSUE THREAD

**Issue by AlexGustafsson** [vercel/hyper#3105]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro (1803) / WSL (Ubuntu 4.4.0-17134-Microsoft)
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: clean install, uses bash
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When running a command such as `hyper -i hyperline` an error occurs (the correct command is obviously `hyper i hyperline`). The error is printed without a trailing newline.

```diff
~/Documents/GitHub$ hyper -i hyperline
-The option "i" is unknown.~/Documents/GitHub$
+The option "i" is unknown.
+~/Documents/GitHub$
```

**Comment by thefifthisa** [comment]
Hi, I'm new here and would like to take this!

**Comment by MAPESO** [comment]
@thefifthisa Hi 👋 😸 feel free to help ❤️

**Comment by MAPESO** [comment]
If you need help or have any questions, let me know :)

**Comment by thefifthisa** [comment]
Thanks, @MAPESO! I'm actually having trouble recreating this error. Here's what I get on bash and git bash:

![bash](https://user-images.githubusercontent.com/30595954/42134673-30c2d296-7d73-11e8-9b47-a838c27ec3df.PNG)
![gitbash](https://user-images.githubusercontent.com/30595954/42134700-982e3e16-7d73-11e8-938d-20a0b3fcb9e0.PNG)

Am I missing something?

**Comment by AlexGustafsson** [comment]
@thefifthisa You’re not missing anything, your output seems to be correct. Are your versions (hyper, windows etc) similar to those I mentioned in the description?

**Comment by thefifthisa** [comment]
@AlexGustafsson Yup! Also on Windows 10 (Home) and Hyper 2.0.

**Comment by AlexGustafsson** [comment]
After concluding that the Hyper source has no instance of any log close to the error I'm seeing, I've been looking through all the dependencies and I think I found the culprit.

In the source of the dependency [args](https://github.com/leo/args) I found the following code [here](
https://github.com/leo/args/blob/490e18c5a35fc099f01fe7b64b584b18b4aedede/lib/utils.js#L147):

```JavaScript
process.stdout.write(`The option "${option}" is unknown.`)
```

I've opened an issue in that repository (https://github.com/leo/args/issues/129). Perhaps this issue should remain open until the upstream error is fixed.

The difficulty of the fix is the same as it would be here, perhaps @thefifthisa would be interested in fixing the issue?

**Comment by thefifthisa** [comment]
@AlexGustafsson Oh okay, thanks! Working on it now.

**Comment by SidneyNemzer** [comment]
Upstream was closed as not an issue, but this one is still open 😅

**Comment by LabhanshAgrawal** [comment]
Closing as upstream issue https://github.com/leo/args/issues/129 is closed
Feel free to open a new issue if you face any problems
