### ISSUE TITLE
Hyper takes much time to open directory path

### ISSUE THREAD

**Issue by HugoRenzi** [vercel/hyper#3115]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home Single Language
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: No, I'm using hyper with Cmder shell.

## Issue

When I try to open any path on hyper, it takes more than 10 seconds to open it. There is any config I should set to fix it?

Thanks!

**Comment by LabhanshAgrawal** [comment]
doesn't seem to be the case now
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and reopen the issue if you face this problem with the new build
