### ISSUE TITLE
Last login message and MOTD are not displayed

### ISSUE THREAD

**Issue by insanityfarm** [vercel/hyper#313]
When I open a new window or tab I expect similar behavior to Terminal.app, which performs a login for every new session. I assume under the hood it's running `login -fpl $USER` to achieve this. Should this behavior be baked into HyperTerm as well, or relegated to a plugin? Either way, I miss my MOTD!

**Comment by MatrixV01** [comment]
Missing my MOTD from Terminal in HyperTerm as well.

**Comment by chabou** [comment]
Can you try with our v2 and open a new issue if this persists?

**Comment by Rabattkarte** [comment]
This is still present in Hyper 3.0.2 (stable) on macOS 10.15.7

**Comment by LabhanshAgrawal** [comment]
Tested to be working on latest canary using
```js
shell: 'login',
shellArgs: [
  '-fpl',
  'your_username_here'
]
```
