### ISSUE TITLE
Create a new tab with an extension

### ISSUE THREAD

**Issue by bigbadwofl** [vercel/hyper#3130]
Is it possible to create a new tab from an extension or is my best bet to simulate keystrokes (Ctrl+Shift+T) through some bash script?

**Comment by RahulReddy75** [comment]
@bigbadwofl If the question is about a opening new tab , you could do it by (Ctrl + T) .

**Comment by bigbadwofl** [comment]
@RahulReddy75 Thanks, but I'd like to do it programmatically.

**Comment by LabhanshAgrawal** [comment]
You can dispatch a `termGroupActions.requestTermGroup()` action
