### ISSUE TITLE
Nano - Text Buffer issue? on Windows 8.1 shell: git-bash

### ISSUE THREAD

**Issue by teebu** [vercel/hyper#3142]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 2.0.0 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Using shell config: 
```
shell: 'C:\\Program Files\\Git\\git-cmd.exe',
shellArgs: ['--command=usr/bin/bash.exe', '-i', '-l'],
```

When trying to `nano` any text file, seeing what I assume is buffer text issues. Scrolling around text, the text is not what it should be.

![image](https://user-images.githubusercontent.com/5531844/43377798-a8ea7a02-9377-11e8-9996-dc8f3a982e70.png)

Same another attempt:

![image](https://user-images.githubusercontent.com/5531844/43377929-85d8dd28-9378-11e8-977e-e94cb5cf1bea.png)

What it looks like in git-bash:
![image](https://user-images.githubusercontent.com/5531844/43378030-07a18bc0-9379-11e8-99eb-8d3354683ec3.png)

Maybe an xterm issue? I don't know how to test that.

**Comment by ron-casey** [comment]
Having this exact issue in macOS.

**OS version and name**: macOS 10.14.2
**Hyper.app version:** 2.1.0 stable
**Link of a Gist with the contents of your .hyper.js:**
**Relevant information from devtools (CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere):** N/A
**The issue is reproducible in vanilla Hyper.app:** Is Vanilla

![Example of issue](https://media.giphy.com/media/AFghBUx3fcr3nzzObl/giphy.gif)

**Comment by ollitapa** [comment]
Same issue here:

**OS version and name**: macOS 10.14.2
**Hyper.app version**:  3.0.0-canary.7 (canary)
**The issue is reproducible in vanilla Hyper.app**: Yes
**Renderers**: WebGL
**Plugins**: 
  hyper-search (0.1.0),
  hyperlinks (0.5.0),
  hyper-aurora (1.0.1)

**Comment by Ominitay** [comment]
Same issue here on Arch.

**Comment by LabhanshAgrawal** [comment]
please open a new issue if it's still there in 3.1.1
