### ISSUE TITLE
Window Title not changing to "user@hostname:~" after SSH (git Bash as shell)

### ISSUE THREAD

**Issue by thammuio** [vercel/hyper#3156]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Build: SCCM OSD - Windows 7 Enterprise SP1 x64
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/thammuio/01f9b7187f706890197d8dc383229e73
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue
I am using git Bash for my shell and when I ssh to a user@host - hyper window title is not changing to reflect the format that git bash is displaying. If I open git bash alone, and ssh to a host then the git bash window title will change to user@hostname:~. But if I ssh from Hyper(using git Bash as shell), the window title is not changing as it supposed to be and its staying still as initial startup title. Any help is appreciated to resolve this.

Hyper:
![image](https://user-images.githubusercontent.com/6325610/43727902-eadad2ee-9968-11e8-9d31-7c8ef2cc651a.png)

Git Bash:
![image](https://user-images.githubusercontent.com/6325610/43728095-9d41f804-9969-11e8-96cb-7c6b78961686.png)

**Comment by LabhanshAgrawal** [comment]
it seems to be fixed in canary (tested on win 10)

closing as this is for v2, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and reopen this issue if you face this problem with the new build.
