### ISSUE TITLE
How does _onTerminal work?

### ISSUE THREAD

**Issue by shiftsayan** [vercel/hyper#3162]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.6
- **Hyper.app version**: Hyper 2.1.0-canary.2 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/shiftsayan/64bc51f812112993797f253e891a544f
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: No, I am creating a custom package.

## Issue
I was trying to fork [hyperterm-1password](https://github.com/sibartlett/hyperterm-1password) to meet some of my workflow situations (basically, just the ability to send strings to the Terminal without any 1Password auth).

I edited the `index.js` to this:
```
exports.decorateTerm = (Term, { React, notify }) => {

  return class extends React.Component {

    constructor (props, context) {
      super(props, context);
      this._onTerminal = this._onTerminal.bind(this);
      console.log("Initialized");
    }

    _onTerminal (term) {
      console.log("On Terminal")
      if (this.props && this.props.onTerminal) this.props.onTerminal(term);

      const handler = [
        "keydown",
        function(e) {
          if (e.metaKey && e.keyCode === 220) {
            e.preventDefault();
            this.terminal.io.sendString("Testing...")
          }
        }.bind(term.keyboard)
      ];

      term.uninstallKeyboard();
      term.keyboard.handlers_ = [handler].concat(term.keyboard.handlers_);
      term.installKeyboard();
    }

    render () {
      return React.createElement(Term, Object.assign({}, this.props, {
        onTerminal: this._onTerminal
      }));
    }

  };
};
```

On reloading Hyper, the console outputs "Initialized", but not "On Terminal" as I expected and nor does it type "Testing..." to the Terminal on pressing `cmd + \` (code 220).

What would a workaround to send a string to the Terminal on pressing a keyboard shortcut?

**Comment by shiftsayan** [comment]
#

**Comment by SwarShah** [comment]
@shiftsayan You'll have to refactor the code to accommodate changes made in v2 of Hyper i.e upgrade to xterm.js.

The code you have posted above is most likely based on hterm which is longer used in Hyper so _onTerminal and anything related to term may not work directly.

Have a look at the plugins which upgraded to be compatible with v2 like following ones https://github.com/zeit/hyperpower/commit/c9ed3e412414d7286ae8c09908e73053001b8aff
https://github.com/krzema12/hypergravity/issues/20
https://github.com/linonetwo/hyper-visual
