### ISSUE TITLE
Cryptic output for flowtype error messages

### ISSUE THREAD

**Issue by smtrd3** [vercel/hyper#3172]
I am using the following config
[.hyper.js](https://gist.github.com/smtrd3/2e4da9628b98f7b336f97f05dc11fe01)

version is ``Hyper 2.1.0 Canary.1-stable``

flowtype output lookslike bellow
```
Launching Flow server for C:\Users\dell\Documents\projects\tb-agds
Spawned flow server (pid=8212)
Logs will go to C:\Users\dell\AppData\Local\Temp\flow\CzCzBUserszBdellzBDocumentszBprojectszBtb-agds.log
Monitor logs will go to C:\Users\dell\AppData\Local\Temp\flow\CzCzBUserszBdellzBDocumentszBprojectszBtb-agds.monitor_log
←[0K←[31mError -------------------------------------------------------------------------------------- src/providers/imgds.js:5:13←[0m←[0m
←[0m←[0m
←[0m←[0mMissing←[0m←[0m ←[0m←[0mtype←[0m←[0m ←[0m←[0mannotation←[0m←[0m ←[0m←[0mfor←[0m←[0m ←[0m←[0m←[0m←[0m←[0m←[0;1mp←[0m←[0m←[0m←[0m.←[0m←[0m
←[0m←[0m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m2←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m3←[0m←[0;2m|←[0m←[0m ←[0m←[0;2mexport default class ProviderIMGDS {
←[0m←[0m     ←[0m←[0m←[0m←[0;2m4←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m  constructor() {}
←[0m←[0m     ←[0m←[0m←[0m←[0;2m5←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m  async auth(←[0m←[31mp←[0m←[0;2m) {}
←[0m←[0m     ←[0m←[0m←[0m←[0;2m6←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m}
←[0m←[0m     ←[0m←[0m←[0m←[0;2m7←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m
←[0m←[0m     ←[0m←[0m←[0m←[0;2m8←[0m←[0;2m|←[0m←[0m ←[0m←[0;2m// export default class ProviderIMGDS {
←[0m←[0m
←[0m←[0m
←[0m
Found 1 error
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by leonardwkerr** [comment]
I am getting this same type of output using `sbt` on Hyper Version 2.1.1

I am using git bash as my shell. (`C:\\Program Files\\Git\\usr\\bin\\bash.exe`)

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2
please try the latest build from https://github.com/vercel/hyper/actions/runs/836867788#artifacts
and open a new issue if it's there with the new build also
