### ISSUE TITLE
Feature Request: Close tab with scrollwheel

### ISSUE THREAD

**Issue by luco** [vercel/hyper#3176]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: mac OS High Sierra
- **Hyper.app version**: 2.1.0-canary.2

## Description

Is it possible to close tabs with the scrollwheel? This would be great if possible.

**Comment by audunolsen** [comment]
Wouldn't `cmd + w` suffice?

**Comment by luco** [comment]
@audunolsen ...

**Comment by LabhanshAgrawal** [comment]
works on canary, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts)
