### ISSUE TITLE
No way to get hyper version from command line

### ISSUE THREAD

**Issue by chadasapp** [vercel/hyper#3205]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.14 Beta (18A377a)
- **Hyper.app version**: 2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
`hyper --version` or `hyper version` should produce the version number alone and exit cleanly. Should be pretty easy.

**Comment by albinekb** [comment]
PR welcome if it's pretty easy!

**Comment by hayer** [comment]
@albinekb PR submitted. Propose to use #3207 as it prints only the version which makes it a bit easier to use in scripts checking version - so you don't need to remove the prefix string.

**Comment by hayer** [comment]
PR got merged at least, so yes? But I am unsure.

**Comment by LabhanshAgrawal** [comment]
tested on canary and it's working
