### ISSUE TITLE
Hyper change non-ASCII PATH variable on Windows

### ISSUE THREAD

**Issue by zhaobenx** [vercel/hyper#3219]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 [10.0.17134.285] 
- **Hyper.app version**:  2.00
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Every time I open hyper, it changes my path variables that it modifies non-ascii character to some unknown characters. 
![image](https://user-images.githubusercontent.com/23143530/45752093-f9d4b700-bc46-11e8-9cfc-bc6d0c659005.png)
The screen shoot shows it changes my user name(in Chinese) to some marks. Not just path for hyper, it 
 changes every words in path.

**Comment by zhaobenx** [comment]
I think it is the issue of winreg's encoding.
And its author gave one solution: [https://www.npmjs.com/package/winreg#processing-utf-8-data](https://www.npmjs.com/package/winreg#processing-utf-8-data)

**Comment by LeoDupont** [comment]
Had this issue too after installing hyper: my `Path` user variable got corrupted.

Not only the hyper paths are incorrect, it also corrupts other paths in the user variable if they have non-ASCII chars... I figured it out after global npm modules stopped being recognized by Powershell.

**Comment by LabhanshAgrawal** [comment]
Fixed in #4261 
ref #4190
