### ISSUE TITLE
Prompt disappears after typing on Windows 1809

### ISSUE THREAD

**Issue by mikecousins** [vercel/hyper#3239]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro x64 1809
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mikecousins/c6d35ddfb9c15e32ce1612e01546190c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After updating to Windows 1809 the intial prompt now disappears after typing in it.

After reload or launch:
![image](https://user-images.githubusercontent.com/725614/46498732-82249180-c7db-11e8-824a-a46a5968bb39.png)

After typing the letter `c`:
![image](https://user-images.githubusercontent.com/725614/46498744-8a7ccc80-c7db-11e8-8f51-f293e689e60a.png)

After typing `d c:\github` and pressing enter:
![image](https://user-images.githubusercontent.com/725614/46498769-98325200-c7db-11e8-86be-0ae52ca0574c.png)

Notice the command ends up also displaying as ccd instead of cd even though it works fine strangely.

**Comment by jthomp** [comment]
:+1: Having this issue, as well. Also on Hyper v2.0.0 on Windows 10 v1809.

**Comment by mikecousins** [comment]
Also, after this first interaction, everything seems to work normally.

**Comment by albinekb** [comment]
Isn't this a bug with windows and not hyper? We haven't changed anything?

**Comment by baskezada** [comment]
Having the same issue in the same conditions.

**Comment by mikecousins** [comment]
> Isn't this a bug with windows and not hyper? We haven't changed anything?

Depends who you ask I guess ;)

**Comment by Nirajn2311** [comment]
What's the status of this as it is very irritating.

**Comment by mikecousins** [comment]
Looks like Microsoft is fixing this. It also happens in VS Code and Android Studio.

https://github.com/Microsoft/console/issues/270

**Comment by Noxillio** [comment]
Relieved I'm not the only one with this issue. This is still going on, it's driving me f***ing crazy.

A Microsoft developer said that the fix will be in a spring update.

**Comment by dgdav99** [comment]
Just updated to 1809 and same issue both on Hyper and VS Code. Still waiting for fix

**Comment by Noxillio** [comment]
> Just updated to 1809 and same issue both on Hyper and VS Code. Still waiting for fix

I actually don't have the issue anymore on the Insider Build 1903. Fix is coming 👍

**Comment by LabhanshAgrawal** [comment]
Seems to fixed since Windows 10 1903
