### ISSUE TITLE
"hyper" not in PATH after installing canary version

### ISSUE THREAD

**Issue by darkvertex** [vercel/hyper#3251]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `CentOS Linux 7.4`
- **Hyper.app version**: `hyper-2.1.0_canary.2-3069.x86_64` (installed via *.rpm)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

I had installed the latest "stable" rpm and `hyper` became available as it was under `/usr/local/bin/hyper` and `/usr/local/bin` is the PATH env var by default.

However, when I installed the latest "canary" rpm version, it went under `/opt/Hyper/hyper` and `/opt/Hyper` is not in the PATH, or at least not for me by default.

I don't know if this is by choice or accident, but I would have expected "hyper" to become an available command regardless of _stable_ or _canary_ being installed. Is this a bug?

**Comment by LabhanshAgrawal** [comment]
Closing as this was for v2
Feel free to open a new issue if you face any problems with latest [builds](https://github.com/vercel/hyper/actions/runs/157826845)
