### ISSUE TITLE
Issue when setting both foreground and background text color

### ISSUE THREAD

**Issue by vivekvjn** [vercel/hyper#3257]
I'm having an issue with text display while setting both foreground and background text color in a shell session.

To test, try `echo -e '\e[31m   767M \e[41m____________________\e[m \e[31mdir1/\e[m'`

It works for me in putty, VS Code etc. 
![image](https://user-images.githubusercontent.com/6826760/46421953-331f2380-c72b-11e8-8363-290ac2da85ac.png)
but this does not work on Hyper:
![image](https://user-images.githubusercontent.com/6826760/46422013-52b64c00-c72b-11e8-9a85-fc052f8245cd.png)
although, if I don't set foreground color, it works:
![image](https://user-images.githubusercontent.com/6826760/46422342-0ae3f480-c72c-11e8-8680-c452354f293b.png)

Using Hyper 2.0.0 on WSL
![image](https://user-images.githubusercontent.com/6826760/46422105-85f8db00-c72b-11e8-8f94-714220b164d5.png)

_Originally posted by @vivekvjn in https://github.com/zeit/hyper/issues/2038#issuecomment-426686804_

**Comment by LabhanshAgrawal** [comment]
See https://github.com/vercel/hyper/issues/2038#issuecomment-652630719
