### ISSUE TITLE
Hyper CLI command "not found"

### ISSUE THREAD

**Issue by ghost** [vercel/hyper#3262]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Version 1803 (OS Build 17134.345)
- **Hyper.app version**: 2.0.0 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Polygon-6789/d229d4d824b7d9b91e1a4be626cbabc7
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Changed shell to PowerShell

## Issue
I want to install a plugin in hyper, and on the website it said to use the "hyper i <package name>" command, but when I put this into Hyper, I got "command not found" by PowerShell. Here's a screenshot:
https://i.imgur.com/n0EzV1Y.png

I tried searching for issues related to this but didn't find anything about PowerShell.

**Comment by V1NAY8** [comment]
@Polygon-6789 I know this Issue It just worked by Running **Hyper as Administrator**.

**Comment by Socratides** [comment]
It worked for my by restarting my PC, then tried again.

**Comment by cnscorpions** [comment]
> @Polygon-6789 I know this Issue It just worked by Running **Hyper as Administrator**.

it works, thank u

**Comment by geoffbacon** [comment]
For anyone else running into the issue of the hyper CLI not being found (on Mac OS): I had this problem when I installed 3.0.2 from the website, but I uninstalled it and installed using brew 

```
brew update
brew cask install hyper
```

and now the `hyper` command works.

**Comment by aamorimsimoes** [comment]
> For anyone else running into the issue of the hyper CLI not being found (on Mac OS): I had this problem when I installed 3.0.2 from the website, but I uninstalled it and installed using brew
> 
> ```
> brew update
> brew cask install hyper
> ```
> 
> and now the `hyper` command works.

thanks, works perfectly here!

**Comment by LabhanshAgrawal** [comment]
On windows you might need to restart for changed path to take effect.
On mac you can use Tools/Plugins menu > Add Hyper CLI to PATH option.

**Comment by rgbrizzlehizzle** [comment]
minor nit, `brew cask` is deprecated in new versions of brew, correct command going forward will be `brew install --cask hyper`

**Comment by saharsadoghi** [comment]
Hello. What about linux `hyper.AppImage`?
