### ISSUE TITLE
Scrollback config option not working

### ISSUE THREAD

**Issue by joesepi** [vercel/hyper#3283]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.14.1
- **Hyper.app version**: 2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joesepi/352046cf12e0f03028eb58ba54b35c6a
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: YES

## Issue

I am looking to console.log a large data object and my buffer/scrollback is cut off; meaning I cannot see the beginning/top of the console.log object. I've tried increasing my scrollback config option, but no matter what change I make to the scrollback value, I get the same result. :/

**Comment by adrichey** [comment]
I am also experiencing this issue on MacOS 10.13.6 with everything else being the same. It appears that the `scrollback` option doesn't actually increase the buffer size. I have also tried setting it to `3000` and `10000` with no success.

**Comment by sydneyitguy** [comment]
same here on MacOS 10.14.1 (18B75)

**Comment by Shafik23** [comment]
Same here on MacOS 10.13.6

**Comment by Azfletch** [comment]
Also unable to apply scrollback MacOS 10.14

**Comment by garethlowrie** [comment]
Also unhappy! macOS 10.14.1

**Comment by ItzMuffin** [comment]
Same in macOS 10.14.2

**Comment by alejandropprado** [comment]
same in macOS 10.14.1

**Comment by aecorredor** [comment]
Any update on this? Same thing is happening for me on macOS 10.14, I'm guessing this has to do with https://github.com/zeit/hyper/pull/3038#issuecomment-470605698

**Comment by adrichey** [comment]
This is still an issue as of today for me on macOS 10.14.4.

**Comment by Circuit8** [comment]
Same here using Ubuntu 18.04.1

**Comment by arpitchauhan** [comment]
I'm facing the same issue with macOS 10.14.5 and Hyper 3.0.2 (stable).

**Comment by jamieweavis** [comment]
I'm seeing the same issue on macOS 10.14.5 and Hyper 3.0.2 (stable).

The `scrollback` config has no effect whatsoever - tested in zsh by running:
```sh
$ for i in {1..10000}; echo $i
```
Output shows that exactly 1000 lines exist from the top of the screen to the top of the buffer.

**Comment by bignimbus** [comment]
I have this issue on both macOS 10.14.5 and Ubuntu 18.10

**Comment by tardis626** [comment]
+1 here

**Comment by leotm** [comment]
Same on macOS Mojave 10.14.6 (18G87) and Hyper 3.0.2 (stable)

**Comment by 27Bslash6** [comment]
How is this not a priority? A single console.log response object fills my scrollback....

**Comment by jonathanmarvens** [comment]
This is indeed pretty frustrating!

**Comment by stradled** [comment]
Still a problem in 3.0.2
macOS 10.14.6 (18G3020)

**Comment by clutch-justin** [comment]
This looks like it is working now?

Hyper 3.0.2 (stable)
macOS Catalina

**Comment by rendhalver** [comment]
I am also seeing this on Linux with 3.1.0-canary-4 and 3.0.2.

**Comment by jschneekloth** [comment]
Still issue, MacOS 10.15.7, Hyper 3.0.2.  This is a blocker to user adoption and maintaining users in real world scenarios. 
 Working around limitation this is tedious and cumbersome.

**Comment by LabhanshAgrawal** [comment]
I don't see this issue in new ci builds https://github.com/vercel/hyper/actions/runs/504157911#artifacts
tested on macOs 10.15.7

**Comment by mvgeny** [comment]
Works fine on macOS BigSur 11.1

**Comment by graham73may** [comment]
This is still a problem in 3.0.2. Issue shouldn't be closed.

**Comment by canda** [comment]
In my case the error was that I was setting `scrollback` as a property of `module.exports` instead of `module.exports.config` 

I was doing
```
module.exports = {
  config: {
  ...
  }
  ...
  scrollback: 9999
}
```

Instead of
```
module.exports = {
  config: {
  ...
    scrollback: 9999
  }
  ...
}
```

I think I suffered this for across 3 years and 4 different laptops 😂

**Comment by seanmatheny** [comment]
Has this finally been fixed/enabled now? I just tried again on a whim on 3.2.2 and it preserves scrollback at least up to 999999 lines for me (I quit testing there). 😮 

`module.exports = {
    config: {
        scrollback: 999999,`

**Comment by gersonmontenegro** [comment]
macOS: Ventura 13.0.1
Hyper: 3.3.0

what worked for me was:
```
module.exports = {
  config: {
  ...
    scrollback: 10000
  }
  ...
}
```
