### ISSUE TITLE
Weird character

### ISSUE THREAD

**Issue by ZynosL** [vercel/hyper#3301]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ZynosL/5f4392a9d8de115fcbf9bd6188559872
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
The console add weird characters. For example, when I run the composer command:
![image](https://user-images.githubusercontent.com/44950253/49306085-7e5a7600-f4d1-11e8-9886-563f7d509310.png)
Thanks

**Comment by chrsengel** [comment]
These are escape characters that specify the color of some output. I think [this issue](https://github.com/zeit/hyper/issues/2038) and [this one](https://github.com/zeit/hyper/issues/3257) might be related to yours. Apparently Windows 10 has some problems with colored output.

**Comment by ZynosL** [comment]
And there is no solution ?

**Comment by garethpbk** [comment]
I've got the same issue; it's easily fixable in git bash by changing the terminal option to `xterm-256color` but this doesn't work with Hyper.  Will keep trying to find a fix.

**Comment by bwiercinski** [comment]
@ZynosL @garethpbk still no solution? all apps are working fine on hyper, but https://github.com/lihaoyi/mill dont. in addition on mintty everything works fine

**Comment by LabhanshAgrawal** [comment]
see https://github.com/vercel/hyper/issues/2038#issuecomment-652630719
