### ISSUE TITLE
Hyper.js not running on double-click

### ISSUE THREAD

**Issue by premedios** [vercel/hyper#3305]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/premedios/30fc4a5ccbc015dd4ad43fe5f0beb4f0
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When I double-click on hyper.exe in c:/user/user (which is bad putting there!) nothing happens and there are no errors. Windows defender blocking it maybe? I tried uninstalling and deleting the .hyper.js file, restarting, installing again but it still doesn't start up.

**Comment by carfis** [comment]
Hi Premedios, I had the same problem.
I ran this code on the Windows PowerShell Console (As Administrator):  `rm ~/.hyper.js`
Then you can open hyper again.

I found the code here: https://github.com/zeit/hyper/issues/2211

**Comment by premedios** [comment]
Still doesn't run

**Comment by LabhanshAgrawal** [comment]
doesn't seem to happen in canary
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build
