### ISSUE TITLE
Error: EPERM: operation not permitted, rename: config.json.3431043348 -> config.json

### ISSUE THREAD

**Issue by kenorb** [vercel/hyper#3306]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: v2.1.0-canary.2 (stable)
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue

When laptop wake up from the hibernation, it shows the following error:

![Javascript error](https://user-images.githubusercontent.com/266306/49371177-83e0d780-f6ee-11e8-95c4-9b6f07f14dc8.png)

> Error: EPERM: operation not permitted, rename: config.json.3431043348 -> config.json
> at Object.fs.rename.Sync (fs.js:772:18)
> at Function.writeFileSync [as sync]
> at ElectronConfig.set

Note: I had two instances of Hyper terminal running. Could it be the reason?

**Comment by mosesoak** [comment]
Happened to me on Stable 3.0.2 on WSL Ubuntu. I am running oh-my-zsh, not sure if that makes a diff. I wasn't using the app including opening or closing any windows, it was just sitting open and threw this error.

![image](https://user-images.githubusercontent.com/24345/86163402-09905900-bac5-11ea-8bc7-23fbf3ae01d6.png)

**Comment by LabhanshAgrawal** [comment]
@mosesoak can you try the latest [canary build](https://github.com/vercel/hyper/actions/runs/151770461) once and check if the error is still there
Do post a screenshot if it occurs (will help in debugging)

**Comment by mosesoak** [comment]
If I get time I will try Canary, but it only happened once randomly so
there's no real repro I can try on it.

**Comment by docmarionum1** [comment]
I was having this issue constantly, at least once a day if not more. (Same exact stack trace as mosesoak posted a screenshot of. 

I updated to the latest canary build a couple of days ago and so far so good. I'll update if I see it again.

**Comment by LabhanshAgrawal** [comment]
Fixed in 820c094923b492501762084c3f134918b22a4f2e
