### ISSUE TITLE
Error: `node-pty` failed to load

### ISSUE THREAD

**Issue by BadPaiva** [vercel/hyper#3321]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:12:3)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:20:9)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:113:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by BadPaiva** [comment]
I fixed this error temporarily by deleting this part of the session.js file inside /opt/Hyper/resources/app.asar
"try {
  spawn = require('node-pty').spawn;
} catch (err) {
  throw createNodePtyError();
}"

**Comment by BadPaiva** [comment]
I used the npm asar to extract the app.asar files to the /app and it worked, but I still do not know the reason for the error, and whenever I go to install a plugin it displays several errors but it is installed normally

**Comment by thehaxxa** [comment]
I solved this by reinstalling Hyper 2.1 over 2.0, not sure what the root cause of the issue is, but reinstalling Hyper worked in my case.

**Comment by daaang** [comment]
I'm having the same problem, on ubuntu (19.10). I'm on Hyper 3.0.2, and I'm not having any luck with uninstalling and reinstalling (with `dpkg -r hyper` and `dpkg -i hyper_3.0.2_amd64.deb`). I'll attempt building from source instead, but I'm not able to run Hyper when building from the 3.0.2 release.

**Comment by daaang** [comment]
I have Hyper 3.0.2 running from source via `yarn run app`. I tried installing from the deb generated by `yarn run dist`, but it resulted in the same node-pty error as before. So until the next release, running from source is a decent workaround. Feel free to @ me if you're trying to replicate the problem; I'd be happy to help.

**Comment by LabhanshAgrawal** [comment]
Might be a problem with packaging, the code base has updated a lot since 3.0.2. You can download the latest build from [here](https://github.com/zeit/hyper/actions/runs/58425235) and give it a try.
Currently one known issue with latest build is that esc button getting captured for search bar #3929 (should be fixed soon)
You can use `ctrl+[` as a workaround for esc.
Let me know if you run into any issues.

**Comment by LabhanshAgrawal** [comment]
@daaang did you try the ci build?

**Comment by daaang** [comment]
Ah I have not, since running from source has been working just fine. But I can confirm that the ci build also does work!

**Comment by LabhanshAgrawal** [comment]
> Ah I have not, since running from source has been working just fine. But I can confirm that the ci build also does work!

Glad to hear that it's working, can you please close this issue then?

**Comment by LabhanshAgrawal** [comment]
Do remember to download the stable release of 3.1.0 when it's out, as I don't think that the ci build will check for updates (at least on mac it doesn't)

**Comment by LabhanshAgrawal** [comment]
@daaang sorry I didn't realize that you have not created this issue.
@BadPaiva Can you please try the ci build, confirm if it's working for you and close this.

**Comment by pradyuman** [comment]
We're running into this issue when trying to run the debian package: https://github.com/NixOS/nixpkgs/pull/91153. Any idea how we can debug this?

**Comment by LabhanshAgrawal** [comment]
@pradyuman can you try the deb file from [ci](https://github.com/vercel/hyper/actions/runs/149163272)  directly on NixOS? I'm not familiar with nix, so couldn't get all that's there in the Nix package in the pr.
Before packaging node-pty is re-built based on the os. So that might be causing the issue.
Is it possible to build from source in Nix package? like AUR.

**Comment by LabhanshAgrawal** [comment]
closing as the original issue is fixed

**Comment by mohitejaikumar** [comment]
https://spin.atomicobject.com/node-gyp-windows/ try this one , this helped me
