### ISSUE TITLE
Build for Linux ARM devices

### ISSUE THREAD

**Issue by sschepis** [vercel/hyper#3337]
any plans for a Linux ARM build? if nobody else is on it or has attempted it, i can give it a try.

**Comment by chabou** [comment]
I can't remember any previous try.
Please do it 🙌

**Comment by Ashwin-A-K** [comment]
Hi, I am interested to work on it if i get some mentoring

**Comment by jyangchisyan** [comment]
Dear All, I have interested in it. I am attempting to build on jetson tx1 which is Nvidia Tegra system based on arch64. However, I encounter some obstruction. Could any help me?  🙏

**Comment by FeddiGhani** [comment]
I Build First ARM Based Mac OS BigSur app with rosetta 2, Congrats me - Feddi Ghani

**Comment by jyangchisyan** [comment]
#4135 #4375 
Group related issues into original issue

**Comment by danacr** [comment]
and this is the one for 3.0.2: https://github.com/danacr/hyper/releases/tag/v3.0.2-arm64-fpm-1.10.2

**Comment by danacr** [comment]
I'll have a go and add the fixes in a PR

**Comment by NoviceEric** [comment]
> 亲爱的所有人，我对此感兴趣。我正在尝试在jetson tx1（基于arch64的Nvidia Tegra系统）上构建。但是，我遇到了一些障碍。我陷入了日志消息的结尾。有没有人可以帮助我？ 🙏
> 
> > 子hyper-cli：
> > 哈希：23db9a59841fd1181c4d
> > 时间：34313ms生成
> > 于：2019/05/20 9:09:45 AM
> > 资产大小块名称为
> > cli.js 394 KiB 0 [已发出]主
> > cli.js.map 8.7 KiB 0 [已发出] main
> > 入口点main = cli.js cli.js.map 
> > [2]外部“路径” 42字节{0} [内置] 
> > [6]（webpack）/buildin/module.js 497字节{0} [内置] 
> > [8 ]外部“ fs” 42字节{0} [内置] 
> > [11]外部“ os” 42字节{0} [内置] 
> > [27]外部“ stream” 42字节{0} [内置] 
> > [29]外部“ child_process” 42字节{0} [内置] 
> > [65]外部“事件” 42字节{0} [内置] 
> > [66]外部“ URL”42字节{0} [内置]
> > [78] ./cli/index.js 5.63 KiB {0} [内置] 
> > [79] ./app/package.json 941字节{0} [内置] 
> > [209]外部“ http” 42字节{0} [内置] 
> > [210]外部“ https” 42字节{0} [内置] 
> > [211]外部“ querystring” 42字节{0} [内置] 
> > [222]外部“ zlib” 42字节{0} [内置] 
> > [253]。 /cli/api.js 3.96 KiB {0} [内置] 
> > + 268个隐藏模块
> > 警告配置中
> > 尚未设置'mode'选项，对于该值，webpack将回退到'production'。将“模式”选项设置为“开发”或“生产”以启用每个环境的默认设置。
> > 您也可以将其设置为“ none”以禁用任何默认行为。了解更多：[https：//webpack.js。](https://webpack.js.org/configuration/mode/)
> 
> ----更新附带日志文件------
> [hyper-run-dev.log](https://github.com/zeit/hyper/files/3196261/hyper-run-dev.log)

1

**Comment by LabhanshAgrawal** [comment]
Can you try the build from [here](https://github.com/LabhanshAgrawal/hyper/actions/runs/558368017#artifacts) and tell if it's working for you?
