### ISSUE TITLE
URLs within quotes incorrectly include end quote

### ISSUE THREAD

**Issue by linrock** [vercel/hyper#3345]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: 2.1.0

## Issue

When a URL is in quotes (both single + double quotes), the hyperlink includes the end quote when clicking the link, which opens an invalid link:

![image](https://user-images.githubusercontent.com/208617/50151388-1c3ca600-0304-11e9-8c4c-d540eda53ea9.png)

Expected behavior is to ignore the end quote when a URL is wrapped in quotes. This is the same behavior as in iTerm 2 and the native macOS Terminal. The use case is for URLs as strings within a CLI (Python, Ruby, etc.)

**Comment by linrock** [comment]
Thanks @nersoh, confirmed this issue is upstream in xterm `3.9.0`.
I submitted a partial fix here https://github.com/xtermjs/xterm.js/pull/1846

**Comment by erikrtn** [comment]
I am getting the same issue but for parentheses:
<img width="835" alt="screen shot 2019-01-14 at 11 00 28 am" src="https://user-images.githubusercontent.com/1253422/51124188-af75d800-17eb-11e9-916d-287c2411cf56.png">

**Comment by LabhanshAgrawal** [comment]
doesn't seem to happen in canary
please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build
