### ISSUE TITLE
Resizing window doesn't repaint correctly.

### ISSUE THREAD

**Issue by parktheredcar** [vercel/hyper#3357]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 latest
- **Hyper.app version**: latest canary release
- config gist:  [here](https://gist.github.com/parktheredcar/5b004d681074574323c6c34f3ad7699b)

## Issue
Using hyper on windows with git bash inside and TERM set to cygwin. This is related to #476 but I don't think it is the same issue. The steps to reproduce are only one case, there are many others in curses/ncurses based programs, eg irssi

Setup: `vi file-that-doesnt-exist`.

Reproduction steps: Resize the window larger and smaller than it originally was when vi was launched a few times. The display breaks.

Workaround: In `vi`, text input will correctly refresh the display. this doesn't work for `irssi` and some others.

Notes: Doesn't reproduce on mintty

**Comment by LabhanshAgrawal** [comment]
can you please try out the latest [ci build](https://github.com/vercel/hyper/actions/runs/157826845) and see if the issue is still there.

**Comment by LabhanshAgrawal** [comment]
duplicate #3634
