### ISSUE TITLE
Symlink for .hyper.js on win10

### ISSUE THREAD

**Issue by mu-yu** [vercel/hyper#3365]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **win10 18305**: 
- **2.1.0(canary)**: 

## Issue
I use a symlink for .hyper.js from OneDrive to my user home. whatever the .hyper.js content is , after shutdown and boot win10, the .hyper.js's content will be overwriten by default content.

 This issue starts after i upgrade my os version to 18305. It works pretty good in the previous os version.

**Comment by LabhanshAgrawal** [comment]
Tested working on the latest version
closing as it's for v2
