### ISSUE TITLE
Cursor offset by special characters

### ISSUE THREAD

**Issue by ovalb** [vercel/hyper#3417]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS 10.14.2 Mojave**
- **Hyper.app 2.1.1**: 

## Issue
I'm using hyper with zsh and an oh-my-zsh theme that makes use of some special powerline characters. As soon as one (or more) of them is shown, the cursor offsets backwards and starts one (or more, according to the number of _powerline characters_) character behind. Using the specific _powerline fonts_ doesn't seem to change anything.

#### Here is what happens (Hyper):
![bugs](https://user-images.githubusercontent.com/10159528/51286503-95a6e180-19f3-11e9-805e-c55594c76209.gif)

#### Here is the expected behaviour (iTerm):
![good](https://user-images.githubusercontent.com/10159528/51286846-07335f80-19f5-11e9-8af6-3d9e5b647dc9.gif)

Not only the cursor is offset, but the special characters themselves are offset to the left (they are supposed to be on the far right, touching the edge of the window)

This issue seems to be independant from powerline as it happened with emojis and other non-standard unicode characters.

**Comment by LabhanshAgrawal** [comment]
unicode support has improved a lot in canary
closing as this is for v2, please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build
