### ISSUE TITLE
Hyper install not working

### ISSUE THREAD

**Issue by premedios** [vercel/hyper#3423]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: deleted as per other issue
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I installed the new version of Hyper (2.1.1) but it's not showing in the start menu! Why is this not in Program Files!?!?!

**Comment by Witchen** [comment]
Same issue, it is installed in "C:\Users\[username]\AppData\Local\hyper\app-2.1.1", Hyper Terminal is running (Hyper is showing in the Task Manager), but it does not show any window or UI.

**Comment by senjoux** [comment]
Having same issue hyper install command doesn't wok, tried the following :

- hyper i hyper-material-theme
- hyper install hyper-material-theme

Error log is :

> Warning! Due to WSL limitations, you can't use CLI commands here. Please use Hyper CLI on cmd, PowerShell or GitBash/CygWin.
> Please see: https://github.com/Microsoft/WSL/issues/1494
> 
> Disabling Chromium GPU blacklist
> running in prod mode
> electron will open file://C:\Users\Hamza\AppData\Local\hyper\app-3.0.2\resources\app.asar\index.html
> Hyper CLI already in PATH
> Hyper CLI installed You may need to restart your computer to complete this installation process.
> Checking for notification messages
> Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at consumeBody.call.then.buffer (C:\Users\Hamza\AppData\Local\hyper\app-3.0.2\resources\app.asar\node_modules\electron-fetch\lib\index.js:240:55)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> 

My preferences changes are :

>     shell: 'C:\\Windows\\System32\\bash.exe',
> 
>     // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
>     // by default `['--login']` will be used
>     shellArgs: ['-i'],
> 
>     // for environment variables
>     env: {TERM: 'cygwin'},
> 




- [ ] Windows 10 Pro
- [ ] Hyper app version 3.0.2 
- [ ] Hyper data location "C:\Users\XXXX\AppData\Roaming\Hyper"

**Comment by LabhanshAgrawal** [comment]
@senjoux It's as the error log says, hyper is installed in windows and there are some limitations on using the cli directly from wsl.
You can try `cmd.exe /C hyper i <plugin>`
If that doesn't work just do `cmd.exe` once and run the hyper command there and then exit from cmd.
Let me know if it worked for you.

**Comment by LabhanshAgrawal** [comment]
The [first](https://github.com/vercel/hyper/issues/3423#issue-400824796) comment about start menu issue is for v2.1.1 please try with latest version and create new issue if it's still there.
[Second](https://github.com/vercel/hyper/issues/3423#issuecomment-455988321) comment is about #4035 
[third](https://github.com/vercel/hyper/issues/3423#issuecomment-647011001) seems to be resolved.
