### ISSUE TITLE
Feature request: Multiple Profiles > Quick login

### ISSUE THREAD

**Issue by ghost** [vercel/hyper#3436]
It would be really useful for devs that have to access multiple servers on a daily basis to create profiles with command/username/password stored. Something like the image below:

<img width="902" alt="screenshot 2019-01-23 at 22 03 16" src="https://user-images.githubusercontent.com/36828277/51640258-e9b54700-1f5a-11e9-8ce8-f3ae971f0e69.png">

By making it accessible on the toolbar we could connect to a server with 2 clicks:

<img width="261" alt="screenshot 2019-01-23 at 22 08 15" src="https://user-images.githubusercontent.com/36828277/51640473-77913200-1f5b-11e9-86a4-c22c93d00187.png">

**Comment by robertgrzonka** [comment]
This sounds great. I'll try to figure it out :)

**Comment by rohitkrishna094** [comment]
Any update on this feature? or is there a better way to do this?

Right now I have setup aliases for multiple ssh commands. But it would be great if we could that within the app in menu bar or side bar, kinda like mobaxterm.

**Comment by mangkoran** [comment]
This feature would be a great addition. As a Windows and WSL user, I oftenly switch between multiple WSL instances and Powershell with Windows Terminal's profile feature.
