### ISSUE TITLE
Add keymap to open hamburger menu without using the mouse

### ISSUE THREAD

**Issue by gwojan** [vercel/hyper#3443]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, 1803
- **Hyper.app version**: hyper 3.0.0-canary.6 (canary)
## Issue

I would really like to be able to open the hamburger menu from the keyboard. I have checked the default mappings for hyper and don't see anything related to the hamburger menu.

**Comment by doniyor2109** [comment]
Hi. Can I work on this issue?

**Comment by Stanzilla** [comment]
Sure, go ahead :)

**Comment by doniyor2109** [comment]
@Stanzilla Should we add hotkey for linux?

**Comment by Stanzilla** [comment]
I'm not familiar with the conventions on Linux so probably not the best person to ask :(

**Comment by doniyor2109** [comment]
@chabou How about <code>ctrl+\`</code> ?

**Comment by juancampa** [comment]
I think is fine to have the same convention on Linux, as long as it's customizable. I personally use i3wm withhout any decorations so I normally don't see/use menus. And I have removed from Hyper as well with custom CSS in my `~/hyper.js`

**Comment by jsrj** [comment]
If it hasn't already been done, mind if I add the same functionality for Mac?

**Comment by JoffreyGe** [comment]
@jsrj just a question, why do you want to add a shortcut on something ignored on Mac?
`// default: true on Linux, true on Windows, ignored on macOS`
If the burgerMenu can be displayed on macOS could you show me?

**Comment by AkashDhiman** [comment]
Is the issue still active? Can I work on it?

**Comment by Stanzilla** [comment]
Sure, go ahead :)

**Comment by Amagon96** [comment]
I didn't see a merge requesto for this issue, is still opened? 😮

**Comment by Lunchb0ne** [comment]
Maybe add support for remapping it?

**Comment by LabhanshAgrawal** [comment]
> Maybe add support for remapping it?

You can just map the shortcut for `window:hamburgerMenu` in your config
