### ISSUE TITLE
start -a index.js doesn't work

### ISSUE THREAD

**Issue by CityOnTheEdgeOfForever** [vercel/hyper#3450]
I'm taking a FullStack Development Course online. The instructor shows how she issues "open -a index.js" which launches index.js within Atom. Windows equivalent command is start. When i issue the same command with 'start' it gives error mesg:
![image](https://user-images.githubusercontent.com/45753751/51998000-b7c94680-246c-11e9-83c3-2d74b46f639f.png)

Any ideas why? Thanks.

**Comment by Miklet** [comment]
This is not a an issue with hyper. but with wrong `start` usage. What actually -a option means for `open` command? You can open file in Windows using `start path/to/file`. It will start a program associated with given extension.
