### ISSUE TITLE
The right-click menu does not function correctly

### ISSUE THREAD

**Issue by dclong** [vercel/hyper#3453]
- **OS version and name**: Mac Majove 10.14.3
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dclong/72b51ecdad5d3af7a88af7c2ee56fbe9

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A

- **The issue is reproducible in vanilla Hyper.app**: No. It works in in vanilla Hyper.app.

## Issue
The right-click menu doesn't work well in Mac. When right click on Hyper, the menu pop up. However, when I click on an option, another menu pop up instead of performing the right action association with that option.

**Comment by LabhanshAgrawal** [comment]
doesn't seem to happen in canary
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this problem with the new build
