### ISSUE TITLE
Lines from the end of the output are invisible below the scroll view

### ISSUE THREAD

**Issue by jaraco** [vercel/hyper#3461]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.3
- **Hyper.app version**: 3.0.0.canary-7
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/03056530823a8ca51c11a63e80515d88)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla (I think)

## Issue

Starting with 3.0.0.canary-7, I've started observing this behavior where I'm unable to reach the last 1-3 lines of the output. I know the output is there, and I can scroll up and back down, but the last couple of lines remain hidden below the scroll. Interestingly, even when this happens, I've observed that the issue goes away spontaneously--in the same view where the lines were unreachable, they became visible (even as I was writing this ticket).

More investigation is necessary, but I'm logging this much for now until I have more detail.

**Comment by jaraco** [comment]
This happened a few times earlier today, but hasn't happened since. I suspect it may have been a transient issue. I'm going to close this unless I encounter it again or have more information.

**Comment by jaraco** [comment]
This issue has happened once or twice since I first reported the issue. I've found when it happens, resizing the window from the right border rectifies the issue. I still can't tell what's triggering the behavior; it seems to happen randomly. I'll report back when I have more info.

**Comment by anakaiti** [comment]
I'm having the same issue in Vanilla 2.1.2. It seems to only happen if more than 1 tab is open. Resizing the window also fixes the issue for me.  

When a new tab is opened, it's a bit too large at 158x40, after resizing the window. It correctly scales to 158x38.

**Comment by jaraco** [comment]
I've managed to do a screen capture during one of the times this happened. Leading up to the production of this capture, I'd just recently started Hyper and had only run a few of commands in the terminal, the last of which emitted more than a full page of output. When it did, the bottom of the output was truncated, so I started the capture.

I tried to narrate it, but I failed to capture the audio during the capture, so here's what happens in the video:

- starts out showing the screen with the truncated output
- scroll to the top to show that the top of the start of the output is visible and working normally
- scroll back down slowly making note that the scroll bar continues past the bottom of the view.
- point out that the scrolling stops and some output is unreachable
- resize the pane slightly to illustrate how the truncated output then appears.


[Hyper output truncated.mov.zip](https://github.com/zeit/hyper/files/2894895/Hyper.output.truncated.mov.zip)

**Comment by ketozhang** [comment]
This has been happening to me ever since Hyper 2.0 I believe. I'm on Windows 10 using Hyper mainly for WSL.

 A temporary fixed mentioned before is to resize the window. No luck on anything permanent.

**Comment by irfanfadilah** [comment]
I don't know if this is related or not, I'm on Hyper 2.1.2 (Windows 10) and sometimes the output didn't auto-scroll to the last line (didn't show the writing/input area) so I need to press return/enter to make the writing/input area visible on the screen.

**Comment by jaraco** [comment]
This issue is still causing me grief... and there haven't been updates for months. I'm going to start looking for a new terminal.

**Comment by LabhanshAgrawal** [comment]
@jaraco try with the latest build once 
https://github.com/vercel/hyper/actions/runs/675890687#artifacts

**Comment by jaraco** [comment]
Testing, will report back if an incident occurs. If you haven't heard from me in 1-2 weeks, you can assume that addressed the issue.
