### ISSUE TITLE
"Hyper" wants access to control "Google Chrome"

### ISSUE THREAD

**Issue by jsphkm** [vercel/hyper#3472]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS 10.14.2**: 
- **Hyper 2.1.2**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

This message came up when I did `npm start`
```
"start": "concurrently \"react-scripts start\" \"node server.js\"",
```
I am aware that this may not be an unusual activity.  I just want a bit of clarification about the permission access.

![screen shot 2019-02-11 at 10 52 33 pm](https://user-images.githubusercontent.com/28643797/52617265-18368b80-2e50-11e9-9725-164591a1e80b.png)

**Comment by jsejcksn** [comment]
@jsphkm Why did you close this? What did you discover?

**Comment by jsphkm** [comment]
I had some similar pop ups like these for other programs when macOS Mojave was released.  I eventually dismissed it since the security was built into the os and was triggering these alerts for other apps that wanted access to stuff like files, e.g. vscode.  However, I can reopen and continue this thread.  Did you come across this problem too?

**Comment by jsejcksn** [comment]
Yes, I suspect it has something to do with React wanting access to dev tools—but I’d like to find out because even if it’s simply that, this permission is not a granular one and therefore it exposes a large attack vector for misbehaving/compromised/malicious code.

**Comment by admosity** [comment]
Had this popup when one of my instances was firing up a browser (strapi in this case).

**Comment by LabhanshAgrawal** [comment]
The popup is not for `hyper` to get access to control chrome. It's for the react-scripts.
This shows hyper's name as it's the parent process, the permission is not granted to hyper or processes running in it except the one that requested it. If you run some different command which needs this permission, it'll again ask for it.
