### ISSUE TITLE
Cannot use custom fonts using WSL

### ISSUE THREAD

**Issue by ajfick** [vercel/hyper#3478]
- [x] Your Hyper.app version is **2.1.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
No

  - **Is the issue reproducible in vanilla Hyper.app?**
Yes

## Issue
I am unable to use custom fonts in Hyper while running WSL bash. It appears that custom fonts are ignored entirely. I have tried multiple fonts, and removed all hyper plugins (though verminal is currently installed). 

I have also tried changing the font in the "Ubunut" app on Windows 10, which changed the font in other terminals including VSCode but not in hyper. I have seen this issue discussed in some other forms before, but none of the solutions for those issues worked in my case. 

 - **Hyper version**: undefined "2.1.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** WSL **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 14,
  "fontFamily": "\"Fira Code\", Menlo, Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "C:\\Windows\\System32\\bash.exe",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [
    "verminal"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by Miklet** [comment]
It may sounds stupid but how did you install your font? Did you install it through fonts on Windows? When I wanted to use some font in WSL all I had to do was just to install it in Windows fonts.

**Comment by ajfick** [comment]
@Miklet I did install it through windows. In all fairness, I am new to windows, so maybe I did something incorrectly? Though it seemed pretty self explanatory...

**Comment by Miklet** [comment]
I see you are trying to use Fira Code font. I've set it up like this and it works:
```
'"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
```

**Comment by rynjwssl** [comment]
I also ran into issues with this, but I was able to figure it out after stumbling upon a few separate StackOverflow posts/GitHub issues.

Are you using a custom theme? If so, then you might need to provide a `fontFamily` definition for your theme as well. Actually, I see that you mentioned verminal, so following this might help: https://github.com/zeit/hyper/issues/2470#issuecomment-422094161

I think it would be helpful to clarify that themes might override properties set in your `hyper.js` configuration file somewhere in the documentation.

**Comment by eromoe** [comment]
There is select in msys2 option on Windows
![image](https://user-images.githubusercontent.com/3938751/54263718-77510280-45ac-11e9-8939-689491ef292c.png)

It looked good in msys2
![image](https://user-images.githubusercontent.com/3938751/54264045-2d1c5100-45ad-11e9-9f23-2557e332d9c4.png)

but in hyper looks ugly

![image](https://user-images.githubusercontent.com/3938751/54263998-1413a000-45ad-11e9-84a1-c657ce334b26.png)

**Comment by zamgill** [comment]
Fix:
https://github.com/zeit/hyper/issues/3343#issuecomment-451235240

**Comment by eromoe** [comment]
@zamgill Sadly, it doesn't work.

**Comment by zamgill** [comment]
> @zamgill Sadly, it doesn't work. version 3.0.0-canary.8
> The most problem is #1733

@eromoe please see my attached settings. Note that although i am using hyper material design theme, i have to put the font size and type under verminal (right after fontFamily).
[hyper.txt](https://github.com/zeit/hyper/files/2986187/hyper.txt)

![image](https://user-images.githubusercontent.com/22265437/54653749-1cc71300-4a92-11e9-87b0-5d32ad94a2ff.png)

**Comment by eromoe** [comment]
@zamgill Do you use  Windows 10 1803 ? 
I use `Fira Code` instead of  `Ubuntu Mono derivative Powerline`  and I didn't install any plugins.
It looks like verminal is a plugin settings .  I install that plugin  but still in ugly vim.

**Comment by zamgill** [comment]
> @zamgill Do you use Windows 10 1803 ?
> I use `Fira Code` instead of `Ubuntu Mono derivative Powerline` and didn't install any plugins.
> It looks like verminal is a plugin settings . I install that plugin , however, still in ugly vim.

@eromoe i'm using Windows 10 1809. 

Verminal comes preinstalled when you install Hyper. That's the default theme. 

Can you please send me your settings? I'd like to take a look at it.

**Comment by eromoe** [comment]
Here is [hyper.txt](https://github.com/zeit/hyper/files/2990691/hyper.txt) . Almost same, I have checked them by  beyond compare .

**Comment by zamgill** [comment]
> @zamgill Here is my [hyper.txt](https://github.com/zeit/hyper/files/2990691/hyper.txt) . Almost same, I have checked them by beyond compare .
> 
> Could you run this https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh to check if truecolour work well on your system ?
> Mine is ![image](https://user-images.githubusercontent.com/3938751/54339142-eabb4880-466e-11e9-81c7-c4dd2f55fbc6.png)
> 
> It also may by some difference wsl config . All powerline font looks bad:
> ![image](https://user-images.githubusercontent.com/3938751/54736187-f1087200-4be4-11e9-80bd-64b8fbb92c01.png)

i would suggest creating a new account on your pc and installing hyper on it and then applying the changes i mentioned. I could be the case that the installation is messed up on your account. 

Following is my test result for hyper:
![image](https://user-images.githubusercontent.com/22265437/54811332-d5da4880-4c5e-11e9-987f-a969467fd16b.png)

This is for cmd:
![image](https://user-images.githubusercontent.com/22265437/54811376-f0acbd00-4c5e-11e9-98df-7b3dc4731790.png)

and this is powershell:
![image](https://user-images.githubusercontent.com/22265437/54811459-1934b700-4c5f-11e9-9f77-f9c8d405c7ce.png)

**Comment by eromoe** [comment]
Updated to 1809 ，color become correct
![image](https://user-images.githubusercontent.com/3938751/55053406-0541e880-5097-11e9-89c0-83b20f105467.png)

Though powerline font is still wrong .

**Comment by eromoe** [comment]
@zamgill I found the problem, your example `hyper.txt` had : 
```
    plugins: ["verminal", "hyper-opacity", "hyper-material-theme"],
```

After remove  `"hyper-material-theme"`  , it looks much better 

![image](https://user-images.githubusercontent.com/3938751/55054278-366fe800-509a-11e9-8ef3-14bee31d807f.png)

-----

The key steps is ： 

1. must have and only have `verminal`  in pluins
    ```plugins: ["verminal"]
    ```
2.  must have 
    ```verminal: {
      fontSize: 12,
      fontFamily: '"Fira Code"'
    },```

PS1: I think `verminal` is the theme name can be changed. 
PS2:  `Source Code Pro for Powerline` look better than `Fira Code`

**Comment by Resisty** [comment]
I have this issue as well on 
* Windows 10 build 19041.685
* Hyper 3.0.2
* No plugins
* Fonts are installed in Windows and in WSL via `fc-cache`, `fc-list | grep -i ${font}` shows them installed.
