### ISSUE TITLE
OS X Drag Folder to add path to command line stopped working

### ISSUE THREAD

**Issue by JulianBerger** [vercel/hyper#3487]
- **OS version and name**: macOS 10.14.3
- **Hyper.app version** Hyper 3.0.0-canary.1 (canary)

## Issue
The ability to drag folders into the terminal to add the path to the command line stopped working with hyper 3.0.

It was introduced with: #559

**Comment by nobleworkshop** [comment]
The same for me. OS X Drag Folder to add path to command line stopped working.

**Comment by guigo2k** [comment]
same here :(

OSX 10.14.6
Hyper 3.0.2

**Comment by actual-size** [comment]
Fixed in #3690, it'll be included in next release
