### ISSUE TITLE
Main Menu > Help > Report Issue does nothing.

### ISSUE THREAD

**Issue by sampathsris** [vercel/hyper#3501]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I'm using no such file. Default installation.
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Main Menu > Help > Report Issue does nothing.

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2, please try with v3 or canary
