### ISSUE TITLE
Hyper Javascript error occurred in the main process

### ISSUE THREAD

**Issue by jonesgreg** [vercel/hyper#3522]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by arsari** [comment]
Same issue with unsuccessful solutions in the repo.

![image](https://user-images.githubusercontent.com/22566231/55297799-9a2a4600-53f7-11e9-8586-ee3e29f5422a.png)

**Comment by lin-credible** [comment]
![image](https://user-images.githubusercontent.com/3191641/58156732-5d692580-7ca9-11e9-8387-199c526ae6eb.png)


![image](https://user-images.githubusercontent.com/3191641/58156696-4296b100-7ca9-11e9-911f-3433e38e72fb.png)

**Comment by LabhanshAgrawal** [comment]
stale
