### ISSUE TITLE
Showing shell color code after `hyper install`

### ISSUE THREAD

**Issue by PhysRex** [vercel/hyper#3524]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: v2.1.2(Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist of my .hyper.js](https://gist.github.com/PhysRex/8e15546c47a3f08017c6970ef5f735e4)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

whenever I install an extension using the `hyper i <extension_name>` command, I get additional characters around the response. Looks to me like the color/styling used in bash formatting.

*example:*
```bash
$ hyper i hypercwd
?[32mhypercwd installed successfully!?[39m
```

**Comment by LabhanshAgrawal** [comment]
see https://github.com/vercel/hyper/issues/2038#issuecomment-652630719
