### ISSUE TITLE
Cursor blink

### ISSUE THREAD

**Issue by dg1234uk** [vercel/hyper#3533]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate - Previous _closed_ issues #3318 and #3351

- **OS version and name**: MacOS 10.14.3
- **Hyper.app version**: 2.1.2
- **Link of a Gist with the contents of your .hyper.js**: [.hyper.js Gist](https://gist.github.com/dg1234uk/560f7fd12c8dfa2f031b712f4704365c)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Nil 
- **The issue is reproducible in vanilla Hyper.app**: YES 

## Issue

I have `cursorBlink: true,` set in `.hyper.js`. When you start the app, the cursor blinks as expected. However, if you switch focus between different tabs or panes, more noticeable the more times you switch. The cursor will start blinking erratically.

**Comment by ppot** [comment]
This will require a .gif of some sort. Thanks 🙏

**Comment by dg1234uk** [comment]
@ppot 
![Apr-04-2019 22-07-18](https://user-images.githubusercontent.com/2423155/55588680-4c2e7e80-5726-11e9-92d7-b97811900a04.gif)

As you can see as I switch focus between panes the cursor blink frequency in the left hand pane changes. The time between losing focus and regaining focus anecdotally appears to effect the frequency of the cursor blink.

**Comment by MichielLeyman** [comment]
I get this exact same issue - both on MacOS 10.14.3 and Fedora 29.

**Comment by ppot** [comment]
Interesting. Have you tried without plugins?

**Comment by dg1234uk** [comment]
@ppot yes and same issue.

**Comment by mtrussell** [comment]
Mine doesn't blink at all... ever. I have tried setting it to false, then back to true, I also tried altering the cursorShape, and I've tried commenting out all of the plugins. Nothing has worked for me.

Using Hyper 3.0.2 on Windows 10 v.1903

**Comment by Bonlou** [comment]
Same as @mtrussell on Ubuntu 19.10, I will try tomorrow on 18.04 and report here if it's working.

**Comment by rohitkrishna094** [comment]
`webGLRenderer ` is set to true and `cursorBlink` is set to true and yet cursor is not blinking. any fix yet? thanks

**Comment by risonakamo** [comment]
on windows sometimes it blinks again when changing font size...but does not work all the time

**Comment by Gpx45** [comment]
@risonakamo is right, I was able to get the cursor to blink again after changing the font size and saving.

However closing Hyper and reopening will cause the cursor to go back to not blinking again.
It seems to only go back to blinking once you edit and save your .hyper.js config but it will only last until that instance is closed.

I'm on Windows 10 Pro v1909

**Comment by slamoureux** [comment]
on mac os my cursor will not blink unless I set webgl to false

**Comment by klakiervx** [comment]
For me it is blinking only when `webGLRenderer` is set to `false`. It is still working ok after restart. Setting it to `true` breaks cursor blink again for new windows and sometimes even for already open window just after it reloads config.

**Comment by VictorHMartins** [comment]
@klakiervx  Thank YOU!! I should've tried setting webGLRenderer to false!

Thank you!!! 

I was wondering what would be the reason for that. I'd assume webGL is essential?

**Comment by Pikdo** [comment]
I have the same error cursorBlink setting doesn´t work on hyper last version, it is true, hyper version:+3.0.2 with "zsh" and "oh my myszh " installed on win10 WSL Ubuntu 20.04, the cursor is static.

**Comment by slamoureux** [comment]
When I switched to the Canary version this issue was fixed.

**Comment by LabhanshAgrawal** [comment]
this is working with the canvas renderer
closing it for #3626 which is for webgl renderer
