### ISSUE TITLE
Screen frozen in bottom

### ISSUE THREAD

**Issue by eddieimada** [vercel/hyper#3555]
## Issue

Bottom part of app is frozen when scrolling in apps such as nano. To reproduce open a long file in nano, scroll down one page and then up one page (one line at time) you will see the bottom part of the screen is not refreshing.

 - **Hyper version**: undefined "2.1.2"

 - **OS ARCH VERSION:** darwin x64 18.5.0
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** /bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "\"Roboto Mono\", Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [
    "verminal",
    "hyper-quit"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment]
Has been fixed in canary #3391
