### ISSUE TITLE
Support for wsl.exe --distribution flag

### ISSUE THREAD

**Issue by erhassettbg** [vercel/hyper#3569]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Build 18875
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [hyper.js](https://gist.github.com/erhassettbg/2a4516006cbbeb427bc9d89fcf963cc8)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is reproducible.

## Issue
In Windows 10 Build 17763 (1809), a "--distribution, -d" option was added to wsl.exe to allow specifying a specific distribution to launch with WSL. When trying to add `--distribution <DISTRO>` (or `-d <DISTRO>`) to shellArgs, Hyper starts, opens the window and then immediately closes it. A current workaround is to use `<DISTRO>.exe` for the shell executable in hyper.js, but I would like to see Hyper support using the distribution flag in shellArgs.

**Comment by LabhanshAgrawal** [comment]
I tried it on the latest [canary build](https://github.com/vercel/hyper/actions/runs/153185087) using
```
shell: 'C:\\Windows\\System32\\wsl.exe',
shellArgs: ['-d','Ubuntu'],
```
And it was working.
Closing this, feel free to open a new issue if you face any problems.
