### ISSUE TITLE
unable to apply colors properly

### ISSUE THREAD

**Issue by AM-77** [vercel/hyper#3579]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  18.04.1 Ubuntu
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/AM-77/147a9c634a8c568b26cbbfdd020aa30e
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: nothing
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`
## Issue

Sometimes it just shows text without colors
![Screenshot from 2019-05-05 14-40-56](https://user-images.githubusercontent.com/18232579/57194367-7dc58000-6f46-11e9-83ff-394b73ec2344.png)

**Comment by LabhanshAgrawal** [comment]
closing as this is for v2, please try v3 or the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and open a new issue if you face this issue with the new build
