### ISSUE TITLE
3.0 Upon closing, spawns high-cpu-usage "Windows Command Processor" 

### ISSUE THREAD

**Issue by Blindmikey** [vercel/hyper#3621]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: Windows 10 v1809
- **Hyper.app version**: 3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Blindmikey/f41544a7a0ee2f35e05ad1f6da7ec51c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After closing hyper.js 3.0 terminal, a process titled "Windows Command Processor" surges to 20-30% cpu usage and does not go away. Opening hyper.js again, and subsequently closing it will show another "Windows Command Processor" process surge to 20-30% cpu. 

![Annotation 2019-05-07 074952](https://user-images.githubusercontent.com/115122/57310286-5d103e00-709e-11e9-8917-5f5d8e91bb48.jpg)

This can be repeatedly done until the system quickly slows to a crawl, effecting system performance.

**Comment by pcnate** [comment]
I'll try to remember to check for this when I finish work today.

**Comment by Blindmikey** [comment]
Persists in 3.0.2 - though I've noticed if I type "exit" to close the terminal, no "Windows Command Processor" spawns at the top of my CPU consumption. It only occurs when I click the "X" windows close icon in the top-right.

**Comment by DJCarlosValdez** [comment]
Same problem, began when integrating cmder shell to hyper

**Comment by PritamSangani** [comment]
For me, when I close an unresponsive Hyper application, without using the Task Manager to kill the task, the Hyper application continues running at around 60% CPU usage, even though it is not open. (I am on Windows 10 Build 18362 and Hyper 3.0.2)

**Comment by stacy-rendall** [comment]
I also have this problem with cmder shell inside hyper. Typing "exit" to close terminal closes the terminal as expected, only clicking the "X" close icon results in the issue.

**Comment by kariudo** [comment]
More of the same on my end, not integrating cmder on this machine though. I do have clink installed though.

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/pull/3781
