### ISSUE TITLE
Hyper stays in background not opening

### ISSUE THREAD

**Issue by jonassanthosh** [vercel/hyper#3644]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1803
- **Hyper.app version**:  3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jonasbuggs/1f0fc114aaf2b86f333b22f263687fc3
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When i was using Hyper 2.1.2 it was working fine. When i updated to 3.0.0 after update whenever i try to open hyper it stays in the background. No windows are opening to work with even i try to open the application again it also stays in the background 

Hope you guys help me with this 

Thank you

**Comment by akibarika** [comment]
I am running it on Windows 10 as well. Same issue happens on Hyper v3.0.0 and v3.02.

Thanks

**Comment by PhilipEnglund** [comment]
Same problem here, both on 3.0 and 3.0.2

**Comment by yosoymatiasn** [comment]
I had the same issue and just realized the mistake.

In the config file, change: 
"shell: 'C:\\Users\\jonas\\AppData\\Local\\Programs\\Git\\git-bash.exe', " 
to:
"shell: 'C:\\Users\\jonas\\AppData\\Local\\Programs\\Git\\bin\\bash.exe',"

**Comment by akibarika** [comment]
Thanks @yosoymatiasn , fixed the issue in the config file
$Env:AppData/Hyper/.hyper.js

**Comment by veeenu** [comment]
I have the same issue on Windows 7 x64, both 3.0.0 and 3.0.2, both with PowerShell and regular cmd.exe. Removing all of Hyper's installation and configuration data (the folders both in `AppData/Local` and `AppData/Roaming` and `.hyper.js` in the home directory) and reinstalling may or may not make it work once, and not anymore after closing and reopening Hyper, but it is inconsistent and I can't seem to understand which behavior leads to either outcome.

The processes stay open until I kill them, if I edit the configuration files the notifications keep popping up so they're definitely active.

**Comment by michaelspedersen** [comment]
I am seeing the same on Win10 x64 with WSL (Ubuntu) and PowerShell. The best solution/workaround I've found is going to $USER/AppData/Local/hyper and deleting the app-3.x.x directory, which forces a revert back to my previous (working) version, v2.1.1.

I have tried with my current (modified) configuration and the default one - No difference in result.

**Comment by jonasbuggs** [comment]
> I had the same issue and just realized the mistake.
> 
> In the config file, change:
> "shell: 'C:\Users\jonas\AppData\Local\Programs\Git\git-bash.exe', "
> to:
> "shell: 'C:\Users\jonas\AppData\Local\Programs\Git\bin\bash.exe',"

Tried this still hyper stays in the background :(

Anyway Thanks

**Comment by jonasbuggs** [comment]
> I am seeing the same on Win10 x64 with WSL (Ubuntu) and PowerShell. The best solution/workaround I've found is going to $USER/AppData/Local/hyper and deleting the app-3.x.x directory, which forces a revert back to my previous (working) version, v2.1.1.
> 
> I have tried with my current (modified) configuration and the default one - No difference in result.

This solution works temporarily but after sometime hyper is automatically updated

**Comment by michaelspedersen** [comment]
> > I am seeing the same on Win10 x64 with WSL (Ubuntu) and PowerShell. The best solution/workaround I've found is going to $USER/AppData/Local/hyper and deleting the app-3.x.x directory, which forces a revert back to my previous (working) version, v2.1.1.
> > I have tried with my current (modified) configuration and the default one - No difference in result.
> 
> This solution works temporarily but after sometime hyper is automatically updated

That is true, but from my experience in the past week it is only when the channel you are following is updated, so using "stable" it shouldn't happen too often. It is however still a workaround for me as well, but as the window doesn't open it is difficult to debug :)

**Comment by DIGnmg** [comment]
Same problem here, both on 3.0 and 3.0.2

I tried solving this issue with the proposed fixes here but no luck for me!

**Comment by jchitel** [comment]
I decided to try hyper on Windows (I've been using is successfully on Mac for a while) and I'm running into this issue. When I start Hyper, I get no window or any visual indication that anything is happening, and task manager even lists the Hyper processes as "background".

It would be really nice if there were some log files or a debug flag or something that would allow us to investigate further. As of now, there is nothing in the AppData/Local/hyper directory for me to go off of (aside from the squirrel log, which is just for installation).

I would be happy to provide any information about my setup/files if requested.

**Comment by jchitel** [comment]
I was able to get it working by cloning and building from source (`yarn run dist` and then running the resulting installer). I can't seem to find an older 3.0 version that works from the downloaded installer (from [here](https://github.com/zeit/hyper/releases)).

**Comment by neel229** [comment]
I was facing similar problem and fixed it by manually typing the bash.exe location. Also set the login argument to --login and not to -i .

**Comment by jigar-p** [comment]
According to the example provided in `.hyper.js`, the path should be in following format: 
```
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
```
In my case, changing from `C:\Users\jpatel\AppData\Local\Programs\Git\bin\bash.exe` to `C:\\Users\\jpatel\\AppData\\Local\\Programs\\Git\\bin\\bash.exe`  (adding extra `\`)   fixed the issue.

**Comment by flyinggfigh** [comment]
I can't even find the .hyper.js file.

**Comment by LabhanshAgrawal** [comment]
> I can't even find the .hyper.js file.

it should be in either %APPDATA%\Hyper or %HOMEPATH%

**Comment by yosoymatiasn** [comment]
> I can't even find the .hyper.js file.

With hyper open, you can click on the dropdown menu -> edit -> preferences, and that'll take you to the file.

**Comment by srk1195** [comment]
You can open the hyper.js file by clicking **ctrl + ,** .
It is annoying that the terminal disappears into the background and every time need to open it from the tray. Any of you guys have any solution on how to stop hyper going into bg?
