### ISSUE TITLE
Last Login not showing

### ISSUE THREAD

**Issue by AndreasSchantl** [vercel/hyper#3656]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.4
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/AndreasSchantl/dd03e315e8684e6e6f699c3710a1e393

## Issue
I am using oh-my-zsh and it seems that the last login is not showing when the terminal has been started. Instead, I am just seeing a '%' sign. See screenshot below.

![image](https://user-images.githubusercontent.com/9936988/57566961-c069db00-73d2-11e9-88e4-de87fb52e84d.png)

**Comment by joemulray** [comment]
also am experiencing this same issue

**Comment by ahorvat** [comment]
I have the same issue

**Comment by joemulray** [comment]
what shell are you using out of curiosity @AndreasSchantl

**Comment by AndreasSchantl** [comment]
@joemulray It is .zsh

**Comment by CodeBrotha** [comment]
Was this ever fixed?

**Comment by LabhanshAgrawal** [comment]
last login isn't there in vscode, terminus etc. also. It might be a terminal.app thing.
the % issue's solution is as per the last comment
