### ISSUE TITLE
Multiple Horizontally window resize & display problems

### ISSUE THREAD

**Issue by oguzzkilic** [vercel/hyper#3667]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **macOS High Sierra - 10.13.6**
- **Hyper.app version - 3.0.2**
- **[https://gist.github.com/oguzzkilic/14d8999a7aab7ad2b45e22184a3ec3ad](https://gist.github.com/oguzzkilic/14d8999a7aab7ad2b45e22184a3ec3ad)**
- **N/A**
- **The issue is reproducible in vanilla Hyper.app: yes**

## Issue
![hyper-multiple-window-problem](https://user-images.githubusercontent.com/3652404/57676092-695f4280-762c-11e9-85d7-eca763d31c57.gif)

## Problems
- window freezes
- keypress not working

**Comment by LabhanshAgrawal** [comment]
duplicate #3593
