### ISSUE TITLE
Hyper not initializing to defined Working Directory after Update

### ISSUE THREAD

**Issue by yevgetman** [vercel/hyper#3678]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/yevgetman/75d17207c5eb25d53d4e43f6741da6f0
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Having recently updated Hyper to the latest version (3.0.2 as of this writing) I am finding that Hyper Terminal no longer initialized to my set working directory (workingDirectory: ~/sites). Despite having reset the configuration & restarted Hyper, the terminal always initializes to the root directory (~). I have the hyperterm-working-directory plugin installed (v0.1.1)

**Comment by LabhanshAgrawal** [comment]
Fixed in #3769
