### ISSUE TITLE
Blurry text on windows

### ISSUE THREAD

**Issue by GiacomoLaw** [vercel/hyper#3684]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: Lastest GM Windows version
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/GiacomoLaw/23b93dc36592e636906bf8465895b16d
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I tried on Vanilla, however it did not work.

## Issue

![image](https://user-images.githubusercontent.com/9038673/57979288-a738de00-7a13-11e9-8c9c-5823065e3d9f.png)

Text is blurred in interface.

**Comment by JiCkY-007** [comment]
same is happening with me did you find any solutions to it
![Capture](https://user-images.githubusercontent.com/63316956/84994449-550f4280-b168-11ea-9528-ef88fc6d0c28.PNG)

**Comment by LabhanshAgrawal** [comment]
Give the latest build a try https://github.com/vercel/hyper/actions/runs/137478211

**Comment by LabhanshAgrawal** [comment]
@JiCkY-007 did it work for you?

**Comment by Revandzy** [comment]
Sorry for necroing. I have the same issue, I've checked the latest build https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.4 but I don't see *.exe file there...

**Comment by HassaanNaushahi** [comment]
Did anyone find a solution?
Please let me know

**Comment by joaopaulo23** [comment]
Set webGLRenderer equals false.
