### ISSUE TITLE
Add support for underline ANSI escape code in WebGL Renderer

### ISSUE THREAD

**Issue by dmohns** [vercel/hyper#3691]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate *Comment:* I believe it is not duplicate of an open issue, see below. 

- **OS version and name**: MacOS Mojave 10.14.5 
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A 
- **Relevant information from devtools** : N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
This is a continuation of the closed issue: https://github.com/zeit/hyper/issues/3194. Albeit the old issue being closed the problem still exists and is reproducible.

Currently Hyper does not display text decorated with ANSI escape code `4m` for underline correctly. I am not sure if this is a bug or feature request. However, a commenter from the old issue suggests this has been supported before and hence, should be classified as a bug. See https://github.com/zeit/hyper/issues/3194#issuecomment-456966115

### Reproduce

Run 
```bash
echo -e "\033[4mhyper\033[m"
```

### Expected result 
The output gets underlined. See screenshot from iterm2.

![image](https://user-images.githubusercontent.com/14202480/58337663-98549000-7e46-11e9-9d5c-2d3e1dde4b88.png)

### Actual result
The output does not get underlined. See screenshot from Hyper.

![image](https://user-images.githubusercontent.com/14202480/58337678-a0accb00-7e46-11e9-9722-866bc4b01aa4.png)

**Comment by dmohns** [comment]
By going back to an older version of Hyper I was able to confirm: Underline used to work. See screenshot from Hyper Version `2.1.2`

![image](https://user-images.githubusercontent.com/14202480/58339219-655fcb80-7e49-11e9-80e5-65875be51146.png)

**Comment by Tyriar** [comment]
You might be seeing https://github.com/microsoft/vscode/issues/35901

**Comment by dmohns** [comment]
> You might be seeing [microsoft/vscode#35901](https://github.com/microsoft/vscode/issues/35901)

I think the VS Code issue is related to similiar issues in Hyper about displaying under-*scores*, see https://github.com/zeit/hyper/issues/2812
However, (and as far as I understand) this issue is distinct from the above mentioned.

Note, how in the screenshots for iterm2 and Hyper `2.1.2` `y` and `p` reach pretty far down and intersect the underline. If the problem originated from misaligned bounding boxes (similar to the VS Code one), I would expect `y` and `p` to be cut off in Hyper `3.0.2`. But `y` and `p` look properly rendered in `3.0.2`.

**Comment by dmohns** [comment]
I accidentally found a big hint. It looks like the `webGLRenderer` is causing problems. In fact, if I disable `webGLRenderer` in `.hyper.js` the underlines appear.  See

![image](https://user-images.githubusercontent.com/14202480/58366585-bec10c80-7ed4-11e9-8bda-d42f3aca2671.png)

![image](https://user-images.githubusercontent.com/14202480/58366589-cbddfb80-7ed4-11e9-9daf-e54819e708f6.png)

**Comment by sobolevn** [comment]
Any progress? Still happens to me.

**Comment by Tyriar** [comment]
The webgl renderer doesn't support underline yet https://github.com/xtermjs/xterm.js/issues/2251

**Comment by levymitchell0** [comment]
Still seeing this on 3.0.2

**Comment by LabhanshAgrawal** [comment]
Working in v3.1.3
