### ISSUE TITLE
Fonts become blurred on canvas-based rendering

### ISSUE THREAD

**Issue by shanoaice** [vercel/hyper#3693]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro Linux Illyria 18.0.4
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

It's a strange problem. The fonts in the top area are sharp, but rest of them are really blurred. This problem always exist no matter how many tabs I open, and my machine does not support WebGL2 rendering.

![image](https://user-images.githubusercontent.com/25174488/58426679-c698d080-80cf-11e9-8fb5-7e6bc2ff4dfa.png)

**Comment by KsRyY** [comment]
Super strange thing happened today. I accidentally maximized my Hyper.app window and when I set it back to the normal size, it lagged for several seconds and suddenly everything become very sharp. It never happened. Plus, there appeared two rolling bar on the bottom and the right side of my Hyper.app window.

**Comment by KsRyY** [comment]
Here's the snapshot:
![image](https://user-images.githubusercontent.com/25174488/59104730-dc768300-8964-11e9-8d38-dccd041dfe5d.png)

**Comment by shaddu38** [comment]
Who have similar problem, you can try old versions (e.g. version 1.4.8), there i don't have this issue.
