### ISSUE TITLE
'/bin/bash' not found on Windows 10

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vercel/hyper#3712]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I haven't touched it
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
While in the Hyper terminal immediately after installing on Windows, both before and after a restart, any attempt to use the global `hyper` command after previously running `npm i -g hyper` results in:

```
'/bin/bash' is not recognized as an internal or external command, operable program or batch file.
```

<img width="373" alt="Bin Bash Not Found" src="https://user-images.githubusercontent.com/3335181/58725923-5b404e80-83ae-11e9-8ed1-c1347d6b36b5.PNG">

Note: this is not a cry for help (#3709); the intention here is not to find a way to use WSL or some other `bash` provider on Windows. This is a bug report that the `hyper` command does not work on Windows 10 without extra configuration.

**Comment by Ayanrocks** [comment]
try using bash only. Make sure you have ubuntu installed

**Comment by alightgoesout** [comment]
I had the same issue, which was caused by the `shellArgs` parameter. Make sure it is either empty (`[]`) or contains an actual directory (maybe `['~']`).

**Comment by LabhanshAgrawal** [comment]
the `hyper` cli command is installed by hyper. You shouldn't install it from npm. That's some different package.
