### ISSUE TITLE
Portable Version of Hyper?

### ISSUE THREAD

**Issue by hl2guide** [vercel/hyper#3725]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Please consider starting to release a proper portable version for Windows.

**Comment by AlonsoK28** [comment]
Is now possible use the Portable version for Windows?

**Comment by WooRepo** [comment]
well?
