### ISSUE TITLE
Italics get clipped

### ISSUE THREAD

**Issue by ekmett** [vercel/hyper#3729]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 10.14.4
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ekmett/44f3ef7e30e1ae11d714070018e555a2

## Issue

When using italic characters, they render, but they get clipped at the boundary of a box that is the wrong size.

<img width="712" alt="Screen Shot 2019-06-12 at 2 09 36 PM" src="https://user-images.githubusercontent.com/304657/59375260-c0376500-8d1b-11e9-9f26-f76b4db9c65d.png">

You can most readily see it in the clipped italic 'd's, 'y's and 0's in the attached image above.

I'm guessing something is wrong with the handling of font metrics to compute the bounding box for glyphs, either here or whatever you are using to handle text upstream. `Terminal` handles the same font just fine.

**Comment by patreeceeo** [comment]
FWIW I'm also experiencing this exact behavior, right side of italic glyph getting clipped, in Hyper 3.0.1-canary.4.

**Comment by Stanzilla** [comment]
The canary builds are suuuuper outdated, you would have to try with a CI build or compile your own.

**Comment by LabhanshAgrawal** [comment]
works properly on latest canary, see #4404
