### ISSUE TITLE
Unresponsive Process when closing with multiple children on Windows

### ISSUE THREAD

**Issue by nopjmp** [vercel/hyper#3733]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1903 (10.0.18362.0)
- **Hyper.app version**: Hyper 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/nopjmp/037ceadf403af8b47c74a5ec21e95db9
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
If another process is running under pwsh or cmd, Hyper will freeze and doesn't seem to know that it killed the entire process tree. I'm not sure if this is an upstream issue with node-pty.

Fastest way to test is using pwsh/powershell and `Start-Sleep -Seconds 30` or connect to a server over ssh, then try to close Hyper.

I wasn't able to replicate this on the latest Alacritty with the ConPTY backend enabled.

I've attached screenshots from Process Explorer to show before and after.
![before](https://user-images.githubusercontent.com/5185561/59564468-e9524100-900c-11e9-8407-f357345e2da5.png)
![after](https://user-images.githubusercontent.com/5185561/59564470-eb1c0480-900c-11e9-96c8-07706cd2fcc7.png)

I can file a bug upstream if this is an upstream issue.

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/pull/3781
