### ISSUE TITLE
Request: Ability to drag file to hyper and show path similar to other terminal applications.

### ISSUE THREAD

**Issue by chadmandoo** [vercel/hyper#3742]
Would be nice to be able to drag a file into Hyper and display its path.

**Comment by VdustR** [comment]
Same request

It doesn't work since v3.0.0+ and works fine until v2.1.2.

**Comment by ethanentW** [comment]
I'd appreciate the ability to do this as well.

**Comment by doomlaser** [comment]
This would be a critical feature for me

**Comment by mihaiserban** [comment]
frustrating that this used to work before, but it was removed from v3+

**Comment by bet4it** [comment]
Duplicate of #3582

It has been fixed in #3690
Wait for the next release
