### ISSUE TITLE
I can't write any accents

### ISSUE THREAD

**Issue by AdsonCicilioti** [vercel/hyper#3745]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora release 30 (Thirty) x86_64
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/AdsonCicilioti/16638ba6610e41a0459616a647b3e09d) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Nothing abnormal
- **The issue is reproducible in vanilla Hyper.app**: YES! i've tested in this way.

## Issue

I can't write any accents in vowels in my language (pt_BR).

I have already researched similar problems here but none of the above mentioned solutions solved the problem.

I tried disabling all plugins and nothing changes.

A small image of attempts to write with accents:

![image](https://user-images.githubusercontent.com/6278398/60051373-3c7d6100-96a9-11e9-9023-067a64753634.png)

I can type avents in any other applications including terminal emulators. Less in Hyper.
I've tested on ZSH and on Bash, but nothing change.

My locale
```bash
[adson@fedora ~]$ locale
LANG=pt_BR.UTF-8
LC_CTYPE=pt_BR.UTF-8
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=
```

System info:
![image](https://user-images.githubusercontent.com/6278398/60052716-5e2c1780-96ac-11e9-8c7b-23c63e950782.png)

**Comment by jorgimello** [comment]
Same here. Previous versions didn't have this problem

**Comment by vinimmelo** [comment]
Same here m'a man, suffering with this problem. How can we fix this?

**Comment by jorgimello** [comment]
My solution was to use Terminator from now on.

**Comment by Stanzilla** [comment]
Set `webGLRenderer: false,` in your config and try again please

**Comment by jorgimello** [comment]
> Set `webGLRenderer: false,` in your config and try again please

It didn't work.

**Comment by LabhanshAgrawal** [comment]
I tried to type some accented characters on the [latest canary](https://github.com/vercel/hyper/actions/runs/151770461).
I tried this on a mac.
I hadn't typed accented characters earlier so used the below table from https://slcr.wsu.edu/help-pages/keyboards-osx/
IIRC similar method was also there for linux using right alt or compose key

Accent | Key Strokes | Available Characters
|---|---|---|
Grave  \` | option+\` then the character | À È Ì Ò Ù à è ì ò ù
Acute  ´ | option+e then the character | Á É Í Ó Ú á é í ó ú
Circumflex ^ | option+i then the character | Â Ê Î Ô Û â ê î ô û
Tilde ~ | option+n then the character | Ã Ñ Õ ã ñ õ
Umlaut ¨ | option+u then the character | Ä Ë Ï Ö Ü Ÿ ä ë ï ö ü ÿ

Do try the canary build once
closing this, feel free to open a new issue if you face any problems with it
