### ISSUE TITLE
`sudo logname` returning `root` instead of my user

### ISSUE THREAD

**Issue by FezVrasta** [vercel/hyper#3762]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Catalina
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default one, not relevant
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

If I run `sudo logname` on Hyper, I get `root`, but if I run it on any other terminal app (included the macOS default one), I get my username (which is what I'd expect).

Above, Hyper, below, Terminal:

![image](https://user-images.githubusercontent.com/5382443/61252587-dcf7fb80-a712-11e9-8a93-8d20c0f18653.png)

**Comment by FezVrasta** [comment]
I just noticed this seems to happen only on the macOS Catalina beta

**Comment by FezVrasta** [comment]
I updated my iMac to Catalina and I'm having the same problem on this computer...

Is there any chance to see this issue prioritized or at least acknowledged?

**Comment by Stanzilla** [comment]
I don't have a mac, so that's a nope from me, sorry.

**Comment by bramus** [comment]
VSCode has a similar issue: https://github.com/microsoft/vscode/issues/96463

I've noticed that depending on how you start VSCode the result for `logname` differs. If this is also the case for Hyper, then perhaps it's an Electron issue?

**Comment by dronenb** [comment]
I just ran into this bug. Obviously this is an issue, but the alternative that I decided on is using $SUDO_USER environmental variable instead of the logname command.

**Comment by bramus** [comment]
I've filed [an issue over at Electron](https://github.com/electron/electron/issues/26721), and the reply there was as follows:

> This is not an electron issues, this is fundamentally how Cocoa apps works, you can check by making a simple swift app that just exec's `logname` and comparing. Whether it's a bug in Cocoa / macOS is up to your interpretation, but it's definitely not an Electron specific issue 😄

Oh, Apple … 😭
