### ISSUE TITLE
How do I actually use hyper on Linux?

### ISSUE THREAD

**Issue by rja907** [vercel/hyper#3779]
OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-52-generic x86_64)

I installed hyper by following these commands on a remote Digital Ocean Ubuntu droplet server:
```
sudo apt-get install gdebi

wget https://hyper-updates.now.sh/download/linux_deb

sudo gdebi linux_deb
```
It installed a bunch of stuff but I don't know how to use it. All I see is that there is a `linux_deb` file in the directory where I ran those commands.

**Comment by mrsauravsahu** [comment]
You can use `dpkg` to install hyper.

```bash
# Download the deb file
wget -O hyper.deb https://releases.hyper.is/download/deb

# install the package
sudo dpkg -i hyper.deb

# if the above fails due to some dependency requirement, install them with
sudo apt -f install

# then try to install hyper again
sudo dpkg -i hyper.deb
```

Now you should be able to able to launch hyper either through the application list or by running the `hyper` command in a terminal.
