### ISSUE TITLE
Cannot remap editor:paste in Hyper 3.0.2

### ISSUE THREAD

**Issue by m4rkw** [vercel/hyper#3825]
Hyper 3.0.2 on windows 10

config: https://gist.github.com/m4rkw/caf261398f09b5acbffe5b0763c5f489

alt+c works for copy, alt+v for paste does nothing. it was working on 2.0.0.

**Comment by zeatful** [comment]
I'm suffering from this same issue and it's very annoying.

**Comment by mihyaeru21** [comment]
I have same issue on Hyper 3.3.0 on Windows 10.
