### ISSUE TITLE
Cursor blink only works when settings is refreshed

### ISSUE THREAD

**Issue by jerameel** [vercel/hyper#3835]
- [/] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [/] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 30
- **Hyper.app version**: 3.0.2

## Issue

Cursor blink does not work when hyper is started, but works fine after the settings is refreshed.

**Comment by nzlysenko** [comment]
I have the same problem.
- **OS version and name:** Microsoft Windows 10, Build 18362.356
- **Hyper version:** 3.0.2

**Comment by ngeor** [comment]
Same here (Windows 10, Hyper 3.0.2)

I noticed that if I zoom out (View -> Zoom out) it starts working (and then it continues to work after I zoom in again).

I don't know if it's relevant, my cursor shape is set to BEAM.

**Comment by didymus** [comment]
I have a similar issue, but it is different in that when I immediately change it to `true` it starts blinking, but any reload causes it to no longer blink. Same with other changes such as colors.

**Comment by LabhanshAgrawal** [comment]
#3626
