### ISSUE TITLE
Feature Request: Customize Installation / Plugin Path

### ISSUE THREAD

**Issue by boxsnake** [vercel/hyper#3856]
Env:

- Win 1703 ver 15063.966
- MSYS2-64
- zsh
- Hyper 2.0.0 stable

Feature Request: Copied From #2920
when I install Hyper.app, may I customize where to install, and where global/local plugins installed? I do not want the programs and plugins to take my space from driver C:\

----

A solution is: (for `electron-builder`, `nsis`)
```json
{
    ...,
    "build": {
        "nsis": {
            "oneClick": false,
            "allowToChangeInstallationDirectory": true
        }
    }
}
```
For plugins installation paths, I think there should be configuration items in hyper.js. When the packages are installed, check hyper.js config first.

Hope it can be merged to master, thanks.

**Comment by LabhanshAgrawal** [comment]
fixed in #5553
