### ISSUE TITLE
[bug] There will be a % character after startup

### ISSUE THREAD

**Issue by d1y** [vercel/hyper#3939]
I have a % character after startup, it’s really uncomfortable.

![image](https://user-images.githubusercontent.com/45585937/68002211-b26e8600-fca2-11e9-9b98-a66d74bd5a50.png)

**Comment by d1y** [comment]
![image](https://user-images.githubusercontent.com/45585937/68002236-cf0abe00-fca2-11e9-8099-a7d6da7e70b9.png)

**Comment by bet4it** [comment]
Duplicate of #3586

**Comment by d1y** [comment]
solved. editor `.zshrc` append

```bash
unsetopt PROMPT_SP
```
