### ISSUE TITLE
Resize breaks Hyper and view gets distorted on macOS

### ISSUE THREAD

**Issue by ppamorim** [vercel/hyper#3951]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.14.6 (18G95)
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ppamorim/947049a5176a2380cbf43a6bf560a8be
- **Relevant information from devtools**: Check the last screenshot.
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When resizing the view on macOS, the screenshot starts warping (distorted) and gets broken, there is no way to solve this manually, seems that the screenshot is stuck so I need to close Hyper.
The application is still running but the screenshot gets distorted and stuck.

![Screenshot 2019-11-04 at 13 36 42](https://user-images.githubusercontent.com/5521682/68125190-de8b4080-ff08-11e9-9410-3c397abce185.png)
![Screenshot 2019-11-04 at 13 36 55](https://user-images.githubusercontent.com/5521682/68125191-de8b4080-ff08-11e9-9fec-5ec63e97d4b2.png)

Log from console:
![Screenshot 2019-11-04 at 13 44 50](https://user-images.githubusercontent.com/5521682/68125357-578a9800-ff09-11e9-9f1d-c36f6f556c3c.png)

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself? Or setting `webGLRenderer: false,` in the config.

**Comment by dgethings** [comment]
Hi,

I have the same problem. I've tried with `webGLRenderer: false,` and the problem persists.Here's a copy of the console log.

All I did was add the config line. Quit Hyper, started it again, opened the Developer Tools window and then resized the text (from 12pt to 16pt) using cmd + +.
 
<img width="811" alt="Screenshot 2019-11-12 at 08 22 58" src="https://user-images.githubusercontent.com/2744746/68654470-ead55600-0525-11ea-92a5-9ea1d503b368.png">

I'll give a CI build a try next.

**Comment by dgethings** [comment]
Hi,

I tried the latest CI build but I cannot get it to run. I get the following crash error:

```
Process:               Hyper [5230]
Path:                  /Applications/Hyper.app/Contents/MacOS/Hyper
Identifier:            co.zeit.hyper
Version:               3.1.0-canary.1 (3.1.0-canary.1.3039)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Hyper [5230]
User ID:               501

Date/Time:             2019-11-12 08:42:10.855 +0000
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Bridge OS Version:     3.6 (16P6571)
Anonymous UUID:        F8E49739-4981-463B-CBF3-690EAC80E8AF

Sleep/Wake UUID:       7C673BBB-8624-4CF2-BD91-617610E704B8

Time Awake Since Boot: 89000 seconds
Time Since Wake:       4700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x00003c12a35c2040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

**Comment by wesbos** [comment]
I'm getting this a few times a day too - the whole terminal is still running, but I can't see any new output or interact with it.  Always happens when I resize the terminal 

<img width="1037" alt="Screen Shot 2019-12-18 at 9 37 53 AM" src="https://user-images.githubusercontent.com/176013/71095256-4674ae00-217a-11ea-8828-5b4e280e8fbc.png">

**Comment by araujoantonio** [comment]
I'm with the same problem. Any solution so far?

**Comment by arumals** [comment]
same problem in linux mint

**Comment by LabhanshAgrawal** [comment]
@araujoantonio @arumals can you try the latest [ci build](https://github.com/vercel/hyper/actions/runs/145055527) once and see if it works for you.

**Comment by arumals** [comment]
@LabhanshAgrawal With that build I can't split into multiple panes.

**Comment by LabhanshAgrawal** [comment]
are you getting any error?

**Comment by arumals** [comment]
@LabhanshAgrawal I had a remap to split panes, after removing them it works fine, there is just a minimim delay between a viewport resize and getting the content properly aligned without distortions.

Thanks for helping out with this issue.

**Comment by LabhanshAgrawal** [comment]
that delay is because calls to resize function are debounced.
