### ISSUE TITLE
Hyper sending hundreds of notifications / hour

### ISSUE THREAD

**Issue by tml** [vercel/hyper#3956]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Mojave
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/tml/696c2cdb463824f31ef90fcb9f9ec539
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
I get hundreds of MacOS notifications every hour from Hyper, with accompanying sound effect and pop-up dialog, telling me that my "Hyper configuration [has been] reloaded". Here's a view of my notifications panel in the past 5 minutes:
https://imgur.com/ansindR

Examples of simple operations that appear to cause Hyper to reload its configuration:
changing directories
displaying a directory listing
Opening a new SSH connection
running a "curl" command
starting the Python REPL
mis-spelling a command line tool
de/activating a Python venv
running `brew update`
installing software with pip or brew
performing a `git pull`
`/bin/echo -n ''`

The only thing I can think of that could possibly be unusual in my hyper config is that I use a custom-compiled variant of the Iosevka typeface, turning on specific ligatures and some other font options that I prefer over the default font.

**Comment by juicyfish** [comment]
I am experiencing this too. I have tried disabling all plugins but whenever Hyper is used like in @tml  comments, notifications are relentless.

**Comment by lorensr** [comment]
I tried reinstalling, didn't change. I get one notification per command  I enter.

**Comment by LabhanshAgrawal** [comment]
Do you see any error in dev console?

**Comment by lorensr** [comment]
No errors

**Comment by LabhanshAgrawal** [comment]
Closing this for #4318 as there's been some developments there
See https://github.com/vercel/hyper/issues/4318#issuecomment-650966733 , try that out and reply there if it works
