### ISSUE TITLE
Cancel Command (CTRL+C) Closing Hyper

### ISSUE THREAD

**Issue by Dillie-O** [vercel/hyper#3978]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 version 1903
- **Hyper.app version**: 3.0.2 (stable)
- **Hyper Plugins**: hyper-star wars (3.2.1), hyper-pane (2.1.5)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Dillie-O/d5282c4371c049af5f14a8e51af515c9
- **Shell Used**: PowerShell Core 6.2.3

Steps to reproduce:

1. Launch Hyper
2. Issue some kind of operation that a "break" can be issued for. For me I ran `ping google.com`
3. Let the operation run for a moment.
4. Press `CTRL+C` to cancel the operation

Expected Result: Operation terminates and I see my command prompt again
Actual Result: Operation terminates and Hyper quits.

Relevant DevTool Information - No console errors, but since the app fully closes it is hard to tell if something is happening immediately.

Additional Notes: I've been on PowerShell Core for a few weeks now, but this issue seems to have popped up only in the past week. I'm not sure what else might be different.

**Comment by Fresh-SeanPatterson** [comment]
I haven't seen any followups here, but it appears that this might be a problem with Powershell Core itself, since I found a similar issue in a similar tool

https://github.com/felixse/FluentTerminal/issues/221

**Comment by LabhanshAgrawal** [comment]
The explanation from https://github.com/felixse/FluentTerminal/issues/221#issuecomment-471365938 is also valid for us.
Closing as it's an upstream issue.
