### ISSUE TITLE
Hyper terminal distorted and frozen

### ISSUE THREAD

**Issue by gregegan** [vercel/hyper#3998]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
![image](https://user-images.githubusercontent.com/6665100/69083067-3be9bc00-09f6-11ea-9085-702610254c0e.png)

- **Hyper.app version**: 
![image](https://user-images.githubusercontent.com/6665100/69083031-2ecccd00-09f6-11ea-9721-468a0c7de847.png)

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

A single window in Hyper terminal intermittently becomes "distorted" and freezes from use. Closing the window and starting a new one is the only solution. I have not been able to identify any trends of when this happens - but happens quite often over a week of constant use.

In the screenshot below - the left window is frozen and distorted, while the right window is fully useable.
![image](https://user-images.githubusercontent.com/6665100/69083083-41df9d00-09f6-11ea-9e7e-5239e1332510.png)

**Comment by bet4it** [comment]
Try to set `webGLRenderer: false`

**Comment by gregegan** [comment]
Thanks I'll try that and see if it reoccurs

**Comment by LabhanshAgrawal** [comment]
Fixed in #3951
