### ISSUE TITLE
Missing expression after unary operator '--'. At line:1 char:3 + --login (??)

### ISSUE THREAD

**Issue by anderskitson** [vercel/hyper#4023]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/anderskitson/b95c4009b101546005cab4f5a049783b) with the contents of your .hyper.js**: https://gist.github.com/anderskitson/b95c4009b101546005cab4f5a049783b
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I get the following error in the hyper terminal window. It goes away when I remove the shell to powershell.exe and comment it out, but then I am using command prompt shell I assume. I would like to use powershell. Ok thanks.

```
At line:1 char:3 
+ --i
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --i
+   ~
Unexpected token 'i' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordExce
ption 
    + FullyQualifiedErrorId : MissingExpressionAfterOperator
```

**Comment by abecaleb** [comment]
Hi, I faced a similar issue, you need to remove the --login argument is using powershell.

Just change the shellargs at line 110 

from
`shellArgs: ['--login'],` to `shellArgs: [],`

Save the preferences and reload the hyper terminal. this should solve it.

**Comment by LabhanshAgrawal** [comment]
> Hi, I faced a similar issue, you need to remove the --login argument is using powershell.
> 
> Just change the shellargs at line 110
> 
> from
> `shellArgs: ['--login'],` to `shellArgs: [],`
> 
> Save the preferences and reload the hyper terminal. this should solve it.

This fixes the issue.

**Comment by GYMKHANA23** [comment]
> Hi, I faced a similar issue, you need to remove the --login argument is using powershell.
> 
> Just change the shellargs at line 110
> 
> from
> `shellArgs: ['--login'],` to `shellArgs: [],`
> 
> Save the preferences and reload the hyper terminal. this should solve it.

Thanks!! i have encountered the same problem.

**Comment by tushar-glitch** [comment]
where to open this PowerShell argument?
