### ISSUE TITLE
throw this.createError(index, line, col, description);

### ISSUE THREAD

**Issue by TimDiKaz** [vercel/hyper#4063]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows [Version 10.0.17763.914]
- **Hyper.app version**: app-3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/TimDiKaz/13b79c86f8447cdea97bd2f41981c18c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: -
- **The issue is reproducible in vanilla Hyper.app**: No, i tried installing addons, it worked, but when I tried to learn how to use Hyper.js everything reset

## Issue

!IMPORTANT!
I FOLLOWED THIS TUTORIAL: https://dev.to/amaltapalov/hyper-js-for-windows-4m85

**Comment by TimDiKaz** [comment]
I just uninstalled the following: Hyper, Cygwin, Git-Bash!
I'll wait and I'll try to install everything in the future.

Other problems that occurred: -hyper/bash wasn't able to recognize my commands.
                                                  -hyper wasn't able to install any Plugins or themes

**Comment by LabhanshAgrawal** [comment]
In your config in the `shell` option you are using single `\` (which is also there on the tutorial you've linked). You need to write `\\` instead of single `\` as you need to escape it.
