### ISSUE TITLE
macOS Hyper zip doesn't work so I need to use the dmg file

### ISSUE THREAD

**Issue by CyberFlameGO** [vercel/hyper#4064]
I'm on macOS 10.15.2 (19C57) Catalina and the new Hyper-3.0.2-mac.zip doesn't work, even when downloaded from the hyper site instead of the releases page. I have to use the .dmg file instead. Hopefully a fix could be implemented to not have to use an alternate download you have to find on GitHub instead of the Hyper website.

**Comment by LabhanshAgrawal** [comment]
Duplicate #3959 
The link in the website also points to the dmg now.
