### ISSUE TITLE
Still pointed corners visible with rounded hyperborder

### ISSUE THREAD

**Issue by marmelin** [vercel/hyper#4067]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 Enterprise, 1809, 17763.864
- Hyper 3.0.2 - Canary 

## Issue
My Hyper config :
[hyper-config.txt](https://github.com/zeit/hyper/files/3966748/hyper-config.txt)

I installed hyperborder and all settings are working well (color,etc. ), but there are still pointed corners of the main window visible. I guess that should not be the case. 

![2019-12-16_09h43_36](https://user-images.githubusercontent.com/16539010/70892028-ab000380-1fe8-11ea-809e-99a8e19228bb.png)

Can I get a smooth rounded corner?

**Comment by LabhanshAgrawal** [comment]
can you give this a try? https://github.com/webmatze/hyperborder/issues/54#issuecomment-487603781

**Comment by LabhanshAgrawal** [comment]
ref https://github.com/vercel/hyper/issues/3074#issuecomment-396027642
