### ISSUE TITLE
SSH key based authentication against remote server, how does it work?

### ISSUE THREAD

**Issue by PackElend** [vercel/hyper#4172]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 LTE
- **Hyper.app version**: none yet
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: not existing yet 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

Hi there,
I cannot find any documentation so I try it that way. The only information close is
- https://github.com/zeit/hyper/issues/3100
- https://github.com/zeit/hyper/issues/3950
- https://github.com/zeit/hyper/issues/1375
- https://github.com/zeit/hyper/issues/3279
- https://github.com/zeit/hyper/issues/2373 

and in https://hyper.is/#cfg:

> defaultSSHApp | true | If true, Hyper will be set as the default protocol client for SSH
> -- | -- | --

How is SSH key based authenticitation against a remote server realized?. Reading through limited information available leads to the impression that is possible but how?   
I want to realize [SSH Agent Forwarding](http://www.unixwiz.net/techtips/ssh-agent-forwarding.html). 
In the case of Ubuntu, my guess is to tell hyper to use [Ubuntu Manpage: ssh — OpenSSH SSH client (remote login program)](https://manpages.ubuntu.com/manpages/cosmic/en/man1/ssh.1.html) ([How To Use SSH to Connect to a Remote Server in Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-use-ssh-to-connect-to-a-remote-server-in-ubuntu))
with a reference to the config file for a dedicated session, isn't it

**Comment by LabhanshAgrawal** [comment]
By `default protocol client for SSH` it means that ssh protocol links will open with hyper.
eg. <a href="ssh://new@sdf.org">ssh://new@sdf.org</a>
