### ISSUE TITLE
Hyper Canary + neovim true color = lag

### ISSUE THREAD

**Issue by mpcsh** [vercel/hyper#4175]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro Version 10.0.18362 Build 18362
- **Hyper.app version**: 3.1.0-canary.1 (stable)
- **Link of a [Gist](https://gist.github.com/mpcsh/369248d0dde3c452f7b58e8a4115488d) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

I decided to check out the canary build to see if true color was working, which it looks like it is! Unfortunately, if I use vim with `termguicolors` enabled, I get big time lag. If I run `:set notermguicolors`, it's back to normal, just like that.

**Comment by alexanderjeurissen** [comment]
I can confirm that enabling termguicolors in neovim causes significant lag when scrolling through files.
Input lag seems not te be an issue, it's merely the redrawing that is causing lag.

**Comment by mpcsh** [comment]
Is there any update on this? I just tried it out with `3.1.0-canary.4` and the bug is still there.
