### ISSUE TITLE
fresh install of hyper produces nice glitch art

### ISSUE THREAD

**Issue by Lokua** [vercel/hyper#4177]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan v10.11.6
- **Hyper.app version**: 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools**:
<img width="670" alt="Screen Shot 2020-01-16 at 11 26 07 AM" src="https://user-images.githubusercontent.com/5567407/72547844-10971800-3853-11ea-8ee6-6d7669d9a78e.png">

- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I've had hyper on my system for some years but haven't used it in over a year. I decided to give it another try and when I opened saw the notification at the bottom to automatically update to 3.0.2. I clicked restart, and now Hyper shows some nice colorful glitches. It's quite pretty.

<img width="748" alt="Screen Shot 2020-01-16 at 11 02 13 AM" src="https://user-images.githubusercontent.com/5567407/72548018-708dbe80-3853-11ea-962e-4bd585c85e3c.png">

I thought it may have been an issue with my plugins, so I decided to just delete all the hyper stuff I had in user home folder including anything starting with `.hyper` (looks like user home is no longer the place it should be anyway). Also deleted hyper.app from applications just in case and decided to download fresh.

Same issue:
<img width="587" alt="Screen Shot 2020-01-16 at 11 32 08 AM" src="https://user-images.githubusercontent.com/5567407/72548214-e003ae00-3853-11ea-84b3-c6c9cecab5ff.png">

I'm really hoping this isn't a case of not being compatible with my OS. Thanks!

**Comment by bet4it** [comment]
Try `webGLRenderer: false`

**Comment by Lokua** [comment]
Thanks for the tip. Not seeing a difference.

Oddly though, editing .hyper.js in ~/Library/Application Support/Hyper/.hyper.js did not seem to be noticed, however a new default ~/.hyper.js config was present and that did load changes. Separate issue I guess. Perhaps the docs are ahead of releases.

**Comment by dptasznik** [comment]
I'm having the same issue, same OS (El Capitan 10.11.6).

**Comment by LabhanshAgrawal** [comment]
@Lokua @dptasznik try out the [ci build](https://github.com/zeit/hyper/actions/runs/83039360) (lots of improvements since last release)

**Comment by dptasznik** [comment]
Thanks, tried yesterday and works great!

**Comment by LabhanshAgrawal** [comment]
@Lokua can you also try it out and close this issue if everything's good.
