### ISSUE TITLE
Using win-bash as a shell

### ISSUE THREAD

**Issue by lrnv** [vercel/hyper#4198]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 latest build
- **Hyper.app version**: 3.0.2 stable
- **Link of my [.hyper.js](https://gist.github.com/lrnv/d91af3b65399b23b9df2a432d89e7519)

- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue
Hi, 

I'm trying to run bash on windows, using the win-bash port from [here](http://win-bash.sourceforge.net/). This is an old port, but this is a **native** bash. Running the bash.exe by myself works fine and gives me a terminal. BUT setting the bash.exe into my .hyper.js file does not. 

How can i make this work ? The relevant part of my hyper.js is here : 

`  shell: 'C:\\Program Files\\win-bash\\bash.exe'`

**Comment by Stanzilla** [comment]
Hey there, any reason you are not using WSL instead?

**Comment by lrnv** [comment]
Well I am not Shure I understand completely what WSL is, so correct me if I'm wrong, but this is a complete emulated Linux kernel. It is really not the same thing than a simple program as `bash`, takes more ram, and is less compatible and Integrated into the environnement. `win-bash` comes usulay with a native port of many GNU utilitaries : grep, ls, cd, cat, less, awk, sed, ..  that also run with less overhead than a complete linux system.

**Comment by GimpMaster** [comment]
Irnv

I would recommend git-bash. It comes installed with git for windows. There are a couple settings you will want to have in your preferences file. These are the ones I ended up with.

```
    // PowerShell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: 'C:\\Program Files\\Git\\bin\\bash.exe',
    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    shellArgs: ['--login', '-i'],
    // for environment variables
    env: {
		TERM: 'cygwin'
	},
```

I've really enjoyed using hyper over git-bash's window system. The plugins are great with Hyper and it looks amazing. My one request is that they release a new installable build soon. That last one was May 2019, even though there are canary releases from a few weeks ago.

**Comment by lrnv** [comment]
Yeah i use git bash like you, but git bash is quite slow itself wompare to the native port, and do not cointain as much features (e.g changing the pompt to something actualy usefull like liquidprompt is really slowing everything up, while it is not using win-bash).

**Comment by GimpMaster** [comment]
Interesting. I had never heard of win-bash. I just checked it out. Last updated 2011?

Let me know if you ever get it working. I would give it a quick try.

**Comment by LabhanshAgrawal** [comment]
I downloaded the zip from https://sourceforge.net/projects/win-bash/
and set `shell` to path of `bash.exe` in the extracted zip
and everything seems to be working properly

I tested it on the latest [ci build](https://github.com/vercel/hyper/actions/runs/174098472)
Feel free to open a new issue if you face any problems
