### ISSUE TITLE
Automake and patch unmet dependances

### ISSUE THREAD

**Issue by bphd** [vercel/hyper#4201]
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When you install Hyper, PKGBUILD can make nearly all the work except that it doesn't install automake and patch so it fails. Dependances to add

**Comment by bet4it** [comment]
> Ensure the base-devel package group is installed in full (pacman -S --needed base-devel).

https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

**Comment by bphd** [comment]
> > Ensure the base-devel package group is installed in full (pacman -S --needed base-devel).
> 
> https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

So add base-devel to dependancies, make it verify by the PKGBUILD

**Comment by bet4it** [comment]
> Note: The group base-devel is assumed to be already installed when building with makepkg. Members of this group should not be included in makedepends array.

https://wiki.archlinux.org/index.php/PKGBUILD#makedepends

**Comment by bphd** [comment]
Well, okay

Just to say that it didn't come with vanilla Arch so it's pretty illogical
