### ISSUE TITLE
Watch screen rewrite

### ISSUE THREAD

**Issue by cdenneen** [vercel/hyper#4213]
- **OS version and name**: Catalina 10.15.2
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cdenneen/6616becee15916e04a5d9b688a7e91e1

## Issue
Running command via watch. Switch tab. Go back to watch tab. You must CTRL-C and re-run to see output. 

I've tried to disable webgl rendering but didn't help.
I've removed all plugins but didn't help.

**Comment by jadnhm** [comment]
I am also having this problem. 

Hyper 3.0.2 (stable)
macOS 10.14.6
fish shell

**Comment by cdenneen** [comment]
Example: 

![hyper_watch](https://user-images.githubusercontent.com/720097/86381269-2199e100-bc5b-11ea-87c2-9dfb04cc4e67.gif)

**Comment by LabhanshAgrawal** [comment]
I tried with the latest [ci build](https://github.com/vercel/hyper/actions/runs/153185087)
and it was working properly
can you try that out

**Comment by LabhanshAgrawal** [comment]
@cdenneen were you able to try out the ci build?

**Comment by cdenneen** [comment]
@LabhanshAgrawal it does fix it... thanks
