### ISSUE TITLE
Cert Expired

### ISSUE THREAD

**Issue by Stanzilla** [vercel/hyper#4229]
@rauchg @timneutkens @juancampa the code signing cert in Appveyor CI expired.

**Comment by leo** [comment]
We're taking a look!

**Comment by leo** [comment]
A new certificate has been requested. It's pending.

**Comment by onordbo** [comment]
Any news on this? @leo @skllcrn 🚀

**Comment by skllcrn** [comment]
Can you attempt reinstalling @onordbo? https://releases.hyper.is/download/mac

**Comment by LabhanshAgrawal** [comment]
@leo @skllcrn any update on the cert, blocking issues for [3.1.0](https://github.com/zeit/hyper/milestone/6) are fixed so we'd need it for release.

**Comment by LabhanshAgrawal** [comment]
> A new certificate has been requested. It's pending.

@leo @chabou can you please look into it. It's been 2 months. It's blocking the release.

**Comment by leo** [comment]
Thank you, we're taking a look!

**Comment by bet4it** [comment]
One year has passed... @leo @matheuss

**Comment by rapha8l** [comment]
Would it be possible to use another CI provider ?

**Comment by LabhanshAgrawal** [comment]
Certificates have been issued finally

**Comment by rapha8l** [comment]
great news !
