### ISSUE TITLE
Unable to install CLI 

### ISSUE THREAD

**Issue by taggy** [vercel/hyper#4319]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OSX Mojave 10.14.5**: 
- **Hyper 3.0.2 (stable)*: 

## Issue
Plugin -> Install CLI throws an error Symlink creation failed. ENOENT

**Comment by Th3G4mbl3r** [comment]
Same issue occurs for me as well.

**Comment by LabhanshAgrawal** [comment]
@taggy @Th3G4mbl3r 
Can you confirm if `/usr/local/bin` directory exists and it's permissions are `drwxrwxr-x`

**Comment by Th3G4mbl3r** [comment]
> @taggy @Th3G4mbl3r
> Can you confirm if `/usr/local/bin` directory exists and it's permissions are `drwxrwxr-x`

Hi @LabhanshAgrawal 

It did exist and the permissions were correctly set. However, it is not a issue for me anymore as i had to reimage my laptop and so there is no way for me to reproduce the issue. After reimaging for some reason the first time round itself it worked perfectly.

thanks,
rohit

**Comment by azazel-cat** [comment]
I get a similar error: "Symlink creation failed: EACCES". I installed Hyper using the 3.0.2 dmg onto macOS Mojave 10.14.6

My `/usr/local/bin` has permissions `drwxr-xr-x`.

I granted Hyper Full Disk Access, but that didn't fix it.

**Comment by LabhanshAgrawal** [comment]
@azazel-cat can you try and create a symlink in `/usr/local/bin` pointing to `/Applications/Hyper.app/Contents/Resources/bin/hyper`
that should be usable

**Comment by LabhanshAgrawal** [comment]
```bash
ln -s /Applications/Hyper.app/Contents/Resources/bin/hyper /usr/local/bin/hyper
```

**Comment by azazel-cat** [comment]
Worked (using `sudo`) — thanks!
