### ISSUE TITLE
yarn run app (3.0.2)

### ISSUE THREAD

**Issue by cdenneen** [vercel/hyper#4331]
MacOS

```
~/src/github/hyper 3.0.2
❯ yarn run app
yarn run v1.22.0
$ electron target
Error: Cannot find module 'native-reg'
Require stack:
- /Users/cdenneen/src/github/hyper/target/utils/cli-install.js
- /Users/cdenneen/src/github/hyper/target/index.js
- /Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7646:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function._load (/Users/cdenneen/src/github/hyper/target/plugins.js:82:37)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/cdenneen/src/github/hyper/target/utils/cli-install.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:880:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cdenneen/src/github/hyper/target/utils/cli-install.js',
    '/Users/cdenneen/src/github/hyper/target/index.js',
    '/Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js',
    undefined
  ]
}
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Disabling Chromium GPU blacklist
running in dev mode
electron will open file:///Users/cdenneen/src/github/hyper/target/index.html
Checking for notification messages
ignoring auto updates during dev
No matching notification messages
```

I can get Hyper to launch a window but there is no shell.
Same thing if I build the "dist"
I originally thought it was a problem with the canary tags but I am checking out `3.0.2` to confirm stable and still same issue.

**Comment by cdenneen** [comment]
When running latest canary:

```
Uncaught TypeError: Cannot read property 'features' of undefined
    at new v (bundle.js:1)
    at Object.g [as loadFile] (bundle.js:1)
    at async Object.t.default (bundle.js:1)
```

**Comment by duncannah** [comment]
I also run into the same issue on the latest canary.

**Comment by LabhanshAgrawal** [comment]
> MacOS
> 
> ```
> ~/src/github/hyper 3.0.2
> ❯ yarn run app
> yarn run v1.22.0
> $ electron target
> Error: Cannot find module 'native-reg'
> Require stack:
> - /Users/cdenneen/src/github/hyper/target/utils/cli-install.js
> - /Users/cdenneen/src/github/hyper/target/index.js
> - /Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
> -
>     at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
>     at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7646:16)
>     at Module._load (internal/modules/cjs/loader.js:622:27)
>     at Module._load (electron/js2c/asar.js:717:26)
>     at Function.Module._load (electron/js2c/asar.js:717:26)
>     at Function._load (/Users/cdenneen/src/github/hyper/target/plugins.js:82:37)
>     at Module.require (internal/modules/cjs/loader.js:775:19)
>     at require (internal/modules/cjs/helpers.js:68:18)
>     at Object.<anonymous> (/Users/cdenneen/src/github/hyper/target/utils/cli-install.js:13:20)
>     at Module._compile (internal/modules/cjs/loader.js:880:30) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/cdenneen/src/github/hyper/target/utils/cli-install.js',
>     '/Users/cdenneen/src/github/hyper/target/index.js',
>     '/Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js',
>     undefined
>   ]
> }
> (electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
> Disabling Chromium GPU blacklist
> running in dev mode
> electron will open file:///Users/cdenneen/src/github/hyper/target/index.html
> Checking for notification messages
> ignoring auto updates during dev
> No matching notification messages
> ```
> 
> I can get Hyper to launch a window but there is no shell.
> Same thing if I build the "dist"
> I originally thought it was a problem with the canary tags but I am checking out `3.0.2` to confirm stable and still same issue.

What is the issue here? Are you talking about the `Error: Cannot find module 'native-reg'`, then it's fixed. It's an optional dependency. And it's not there in 3.0.2

**Comment by LabhanshAgrawal** [comment]
> > MacOS
> > ```
> > ~/src/github/hyper 3.0.2
> > ❯ yarn run app
> > yarn run v1.22.0
> > $ electron target
> > Error: Cannot find module 'native-reg'
> > Require stack:
> > - /Users/cdenneen/src/github/hyper/target/utils/cli-install.js
> > - /Users/cdenneen/src/github/hyper/target/index.js
> > - /Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
> > -
> >     at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
> >     at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7646:16)
> >     at Module._load (internal/modules/cjs/loader.js:622:27)
> >     at Module._load (electron/js2c/asar.js:717:26)
> >     at Function.Module._load (electron/js2c/asar.js:717:26)
> >     at Function._load (/Users/cdenneen/src/github/hyper/target/plugins.js:82:37)
> >     at Module.require (internal/modules/cjs/loader.js:775:19)
> >     at require (internal/modules/cjs/helpers.js:68:18)
> >     at Object.<anonymous> (/Users/cdenneen/src/github/hyper/target/utils/cli-install.js:13:20)
> >     at Module._compile (internal/modules/cjs/loader.js:880:30) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [
> >     '/Users/cdenneen/src/github/hyper/target/utils/cli-install.js',
> >     '/Users/cdenneen/src/github/hyper/target/index.js',
> >     '/Users/cdenneen/src/github/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js',
> >     undefined
> >   ]
> > }
> > (electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
> > Disabling Chromium GPU blacklist
> > running in dev mode
> > electron will open file:///Users/cdenneen/src/github/hyper/target/index.html
> > Checking for notification messages
> > ignoring auto updates during dev
> > No matching notification messages
> > ```
> > 
> > 
> > I can get Hyper to launch a window but there is no shell.
> > Same thing if I build the "dist"
> > I originally thought it was a problem with the canary tags but I am checking out `3.0.2` to confirm stable and still same issue.
> 
> What is the issue here? Are you talking about the `Error: Cannot find module 'native-reg'`, then it's fixed now. It's an optional dependency. And it's not there in 3.0.2

**Comment by LabhanshAgrawal** [comment]
Oops, sorry I missed the `no shell` part. The `yarn run app` output doesn't have anything pointing towards that.
Can you post the output from devtools?

**Comment by LabhanshAgrawal** [comment]
@cdenneen can you please post your config?

**Comment by cdenneen** [comment]
@LabhanshAgrawal 

```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // choose either `'stable'` for receiving highly polished,
    // or `'canary'` for less polished but more frequent updates
    updateChannel: 'stable',

    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: '"MesloLGS NF", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // default font weight: 'normal' or 'bold'
    fontWeight: 'normal',

    // font weight for bold characters: 'normal' or 'bold'
    fontWeightBold: 'bold',

    // line height as a relative unit
    lineHeight: 1,

    // letter spacing as a relative unit
    letterSpacing: 0,

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // terminal text color under BLOCK cursor
    cursorAccentColor: '#000',

    // `'BEAM'` for |, `'UNDERLINE'` for _, `'BLOCK'` for █
    cursorShape: 'BLOCK',

    // set to `true` (without backticks and without quotes) for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    // opacity is only supported on macOS
    backgroundColor: '#000',

    // terminal selection color
    selectionColor: 'rgba(248,28,229,0.3)',

    // border color (window, tabs)
    borderColor: '#333',

    // custom CSS to embed in the main window
    css: '',

    // custom CSS to embed in the terminal window
    termCSS: '',

    // if you're using a Linux setup which show native menus, set to false
    // default: `true` on Linux, `true` on Windows, ignored on macOS
    showHamburgerMenu: '',

    // set to `false` (without backticks and without quotes) if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` (without backticks and without quotes) on Windows and Linux, ignored on macOS
    showWindowControls: '',

    // custom padding (CSS format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // PowerShell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to `false` for no bell
    bell: 'SOUND',

    // if `true` (without backticks and without quotes), selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // if `true` (without backticks and without quotes), hyper will be set as the default protocol client for SSH
    defaultSSHApp: true,

    // if `true` (without backticks and without quotes), on right click selected text will be copied or pasted if no
    // selection is present (`true` by default on Windows and disables the context menu feature)
    quickEdit: false,

    // choose either `'vertical'`, if you want the column mode when Option key is hold during selection (Default)
    // or `'force'`, if you want to force selection regardless of whether the terminal is in mouse events mode
    // (inside tmux or vim with mouse mode enabled for example).
    macOptionSelectionMode: 'vertical',

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // Whether to use the WebGL renderer. Set it to false to use canvas-based
    // rendering (slower, but supports transparent backgrounds)
    webGLRenderer: false,

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  //plugins: ["hyper-relaxed"],
  plugins: [],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],

  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  },
};

```

**Comment by LabhanshAgrawal** [comment]
It's a problem with the ligatures addon, it's being worked on.
For the time being you can set `disableLigatures: true` or use a different font in the fontFamily other than the NF font (some NF fonts work with the ligatures enabled also)

**Comment by LabhanshAgrawal** [comment]
@cdenneen did you try it with ligatures disabled or a different font?

**Comment by cdenneen** [comment]
I’ve tried default font but the shell never opens. Do running these never
works for me. Have only had success with pkg installs.

**Comment by LabhanshAgrawal** [comment]
can you add some screenshots and post your changed config

**Comment by LabhanshAgrawal** [comment]
@cdenneen ping

**Comment by cdenneen** [comment]
@LabhanshAgrawal I've updated the repo to latest and it seems to give me a shell now (which is the first time).
The window I launch it from does provide some errors that I figured I'd share:

```
❯ yarn run app
yarn run v1.22.4
$ electron target
Disabling Chromium GPU blacklist
running in dev mode
electron will open file:///Users/cdenneen/src/github/hyper/target/index.html
(node:28191) ExtensionLoadWarning: Warnings loading extension at /Users/cdenneen/Library/Application Support/Hyper/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
(node:28191) ExtensionLoadWarning: Warnings loading extension at /Users/cdenneen/Library/Application Support/Hyper/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd: Unrecognized manifest key 'commands'. Unrecognized manifest key 'homepage_url'. Unrecognized manifest key 'page_action'. Unrecognized manifest key 'short_name'. Unrecognized manifest key 'update_url'. Permission 'notifications' is unknown or URL pattern is malformed. Permission 'contextMenus' is unknown or URL pattern is malformed. Permission 'tabs' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
Checking for notification messages
ignoring auto updates during dev
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/cdenneen/src/github/hyper/target/node_modules/electron-fetch/lib/index.js:240:55
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
✨  Done in 26.81s.
```

**Comment by LabhanshAgrawal** [comment]
The extension error is an issue with devtools extensions and electron 9
https://github.com/electron/electron/issues/23662
https://github.com/MarshallOfSound/electron-devtools-installer/issues/130

the json parse error is because https://hyper-news.now.sh/ is down.

**Comment by cdenneen** [comment]
@LabhanshAgrawal  thanks I will close this issue since things are basically working
