### ISSUE TITLE
Rasbian

### ISSUE THREAD

**Issue by starraiderx** [vercel/hyper#4375]
-->

- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I am unable to install Hyper on the latest rasbian when i install hyper it says that some programms are missing but i have them all installed

❯ sudo apt install ./hyper_3.0.2_amd64.deb

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'hyper:amd64' instead of './hyper_3.0.2_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hyper:amd64 : Depends: libnotify4:amd64 but it is not installable
               Depends: libappindicator1:amd64 but it is not installable
               Depends: libxtst6:amd64 but it is not installable
               Depends: libnss3:amd64 but it is not installable
               Depends: libxss1:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by LabhanshAgrawal** [comment]
Won't you need an arm build? You can try to build it, see https://github.com/zeit/hyper#contribute
take a look at https://github.com/zeit/hyper/issues/4135 for electron install

**Comment by LabhanshAgrawal** [comment]
@starraiderx ping

**Comment by danacr** [comment]
If you're running the arm64 version of raspbian you can try this: https://github.com/danacr/hyper/releases/tag/v3.0.2-arm64-fpm-1.10.2

**Comment by LabhanshAgrawal** [comment]
Can you try the build from [here](https://github.com/LabhanshAgrawal/hyper/actions/runs/558368017#artifacts) and tell if it's working for you?
