### ISSUE TITLE
Problem with mapping  ctrl+plus  ,  ctrl++  key combinations

### ISSUE THREAD

**Issue by tolgahanakgun** [vercel/hyper#4377]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:Microsoft Windows 8.1 Pro x64 Build 9600 
- **Hyper.app version**: 3.0.2
- **The issue is reproducible in vanilla Hyper.app**: I am using Hyper with straight out of the box settings, no installed plugin

## Issue

I cannot map ```ctrl, +``` or ```ctrl, plus``` shortcut for zoom in. I tried with these key mapping settings. However, it is not working.

1:
```
  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
	'zoom:in':'ctrl++',
	'zoom:out': 'ctrl+-',
  }
```
2:
```
  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
        'zoom:in':'ctrl+plus',
	'zoom:out': 'ctrl+-',
  }
```
While zoom out is working, zoom in is not working with any of these settings.
If I map ```ctrl, /``` or some other key combinations to zoom in, it works.

**Comment by LabhanshAgrawal** [comment]
Working for me on win10 and Hyper 3.1.0 canary 4, you can try it out from [here](https://github.com/zeit/hyper/suites/511329619/artifacts/2739589)

**Comment by tolgahanakgun** [comment]
I switched to Hyper 3.1.0 canary 4. It is the same.


![ezgif-2-7f621f926b19](https://user-images.githubusercontent.com/8354277/76600224-28b3ac80-650f-11ea-9afe-9dd913120a94.gif)

**Comment by LabhanshAgrawal** [comment]
I see, you were talking about the `+` button on numpad, I was using the `=/+` button on the top row and that was working.
The numpad `+` is not working for me too, the default keybinding for zoom:in is `ctrl+=` you can try that.
Your keyboard layout seems different, I've a `=` key you might need to press `ctrl+shift+0`(top row).
For the + can you once try the + key from `shift+4`(top row) also.
We use Mousetrap for keyboard shortcuts, will have to check it out to see why the numpad + is not working.

**Comment by tolgahanakgun** [comment]
For consistency and due to the years of experience I am used to use ```ctrl+plus``` and ```ctlr+-```. <br>```ctrl+0``` or ```ctrl+-``` or ```ctrl+/``` key combinations works with the keys from numpad. The problem is with ```ctrl+plus``` combination.

**Comment by LabhanshAgrawal** [comment]
I agree that it's a bug, the `+` key from numpad didn't work for me also. Wasn't implying that you should switch to some other shortcut (though you'd have to until this is fixed), rather just wanted to check if `+` or `=` from top row was working for you or not.

**Comment by tolgahanakgun** [comment]
The `+` key on the keypad can be mapped with `numadd` as [electron key mapping](https://github.com/electron/electron/blob/master/docs/api/accelerator.md) shows, so the following key mapping solved my problem:
```
  keymaps: {
	'zoom:in':'ctrl+numadd',
	'zoom:out': 'ctrl+numsub',
  }
```

**Comment by LabhanshAgrawal** [comment]
oh i see, good to know.
