### ISSUE TITLE
建议去除点击链接自动打开浏览器的功能

### ISSUE THREAD

**Issue by vicliucn** [vercel/hyper#4395]
目前点击链接，会自动打开浏览器，这个功能经常引起误操作，建议去除或者添加开关选项配置。

**Comment by Stanzilla** [comment]
Hey there, could you translate this for us, please?

**Comment by j10ccc** [comment]
Currently clicking the link will automatically open the browser. This function often causes misoperation. It is recommended to remove or add the switch option configuration.

I think it would be better to automatically open the browser by clicking the link **while holding CTRL**

**Comment by LabhanshAgrawal** [comment]
You can use the `webLinksActivationKey` config now
Download latest build from https://github.com/vercel/hyper/actions/runs/828112466#artifacts
