### ISSUE TITLE
italic font does not render correctly

### ISSUE THREAD

**Issue by dominikzogg** [vercel/hyper#4404]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 19.10
- **Hyper.app version**: hyper_3.1.0-canary.4_amd64.deb
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dominikzogg/5dff1d451da360e576acfbf5e9970f8f
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Haven't build it myself, can't tell

## Issue

italic font (at least the on i am using) seems to have rendering issues (same config worked on 3.0.2).

![italic-issue](https://user-images.githubusercontent.com/1011217/77170258-101d3680-6abb-11ea-8436-5f9cc787b93f.png)

**Comment by LabhanshAgrawal** [comment]
Which font is it, the config you've uploaded seems like the default one.

**Comment by dominikzogg** [comment]
Should be Menlo, Fontsize 11

**Comment by LabhanshAgrawal** [comment]
I also saw it when tested at that time.
Tested again with the latest [build](https://github.com/vercel/hyper/actions/runs/153185087) (there's been xterm updates and new unicode plugin added since then)
I seems to be fixed, can you try it once and check if it's working for you

**Comment by dominikzogg** [comment]
@LabhanshAgrawal works like a charm

PS: would like to get the old icon back

**Comment by LabhanshAgrawal** [comment]
The icon is different as it's a canary build.
If you can change the icon locally then you can use the icon from https://github.com/vercel/hyper/tree/canary/build
Or you can also build hyper locally and it will have the normal icon

**Comment by dominikzogg** [comment]
Ah thanks, replaced it with the svg on https://hyper.is/
