### ISSUE TITLE
Hyper is not opening!!!!!

### ISSUE THREAD

**Issue by FlamingPhoenix777** [vercel/hyper#4490]
I changed the shell to `shell: {'path\to\bash.exe'}` in the config file and then it has stopped opening at all. Every time I double click the icon it loads but no screen is seen. No terminal opens.  Please *HELP*

**Comment by nosyminotaur** [comment]
Try going here
`C:\Users\{YOUR USERNAME}\AppData\Roaming\Hyper`
Here you can find the .hyper.js file.
Try editing the config back to powershell to get powershell back. I'm not sure about the correct path to WSL bash so while someone else can help you out with that, you can use this path instead for opening powershell.
`C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`.
Remember to add the shellArgs `--login` too.
If that doesn't work some reason, just delete the .hyper.js file and restart hyper. The settings should be reset.

**Comment by LabhanshAgrawal** [comment]
Remove the curly braces around the shell path. Or as mentioned earlier, you can also just delete the config file.
If it still doesn't open then it might be about #4035
