### ISSUE TITLE
[Canary] Emoji picker on macOS is broken

### ISSUE THREAD

**Issue by marcofugaro** [vercel/hyper#4556]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Catalina 10.15.3
- **Hyper.app version**: v3.1.0-canary.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/marcofugaro/a566da9288bd619c53f07615a9d33d4a (happens also with no plugins)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issueª

When bringing up the default macOS emoji picker (**cmd + ctrl + space**) on the canary version (**v3.1.0-canary.4**), it is detached and it doesn't work. Choosing any emoji doesn't do anything.

<img width="1440" alt="Screenshot 2020-05-12 at 11 47 10" src="https://user-images.githubusercontent.com/7217420/81670126-72edd700-9447-11ea-8622-c0c8fad16574.png">

### Expected behaviour

Instead, using the the stable channel (**v3.0.2**), it works correctly. You are able to use emojis.

<img width="1440" alt="Screenshot 2020-05-12 at 11 45 39" src="https://user-images.githubusercontent.com/7217420/81670341-c102da80-9447-11ea-9283-d57770539722.png">

**Comment by marcofugaro** [comment]
This still happens with the latest canarys

**Comment by LabhanshAgrawal** [comment]
Fixed in #5931
