### ISSUE TITLE
weird characters showing after launch

### ISSUE THREAD

**Issue by s3bastianeljas** [vercel/hyper#4561]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Catalina 10.15.4
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/s3bastianeljas/298e01ebf6e194cf20bf456c1047627c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Only warning I get is `Color: rgba(255, 255, 255, 0.2) is using transparency, but allowTransparency is false. Using fallback #555753`
- **The issue is reproducible in vanilla Hyper.app**: I only installed the `hyperocean` theme. My shell is `zsh 5.7.1 (x86_64-apple-darwin19.0)` with oh-my-zsh  along with powerlevel10k installed.
[My .zshrc file](https://gist.github.com/s3bastianeljas/11f125a06e785b094a1818cbf4aa2926)

## Issue
when I launch hyper, I always get a percent sign, some empty lines and a number, like this:
<img width="652" alt="sc_hyper" src="https://user-images.githubusercontent.com/42433902/82189390-96a19900-98ef-11ea-91c1-d0b43e842313.png">

Sometimes the number also changes, I've seen 1 and 2 so far. I don't know how to get rid of that and I also don't know the meaning of any of those numbers. I have seen other issues from a while ago having the same problem with just the `%` sign, but nothing about the numbers and empty lines. (I always have this with problem when creating a new window (CMD+N or when clicking the icon in my task bar after CMD+W, only if I do CMD+T it doesn't appear)

**Comment by bet4it** [comment]
Use [v3.1.0-canary.4](https://github.com/zeit/hyper/releases/tag/v3.1.0-canary.4)

**Comment by s3bastianeljas** [comment]
Thanks, I downloaded it. Now the numbers and empty lines are gone, but the percent sign is still there.

**Comment by s3bastianeljas** [comment]
EDIT: It still appears so at first launch after reinstall only the percent sign appeared, but now its the same as before

https://imgur.com/a/Al3chGL

**Comment by paulocastellano** [comment]
I have same problem with debian version

![Screenshot from 2020-05-20 23-14-43](https://user-images.githubusercontent.com/265964/82515906-d7680080-9aef-11ea-92c9-8a89720d6892.png)

**Comment by jrbytes** [comment]
Hi,

Use unsetopt PROMPT_SP in .zshrc

Solved in Ubuntu 20.04

[reference](https://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows)

**Comment by s3bastianeljas** [comment]
> Hi,
> 
> Use unsetopt PROMPT_SP in .zshrc
> 
> Solved in Ubuntu 20.04
> 
> [reference](https://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows)

What does that do exactly with my zsh?

**Comment by xZliman** [comment]
@s3bastianeljas 

Go to inside the `.zshrc` file at the top

`# If you come from bash you might have to change your $PATH.`
`# export PATH=$HOME/bin:/usr/local/bin:$PATH` **<- uncomment this line**

That's what worked for me
