### ISSUE TITLE
WSL2 compatibility issues

### ISSUE THREAD

**Issue by ajmssc** [vercel/hyper#4597]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 2004
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After updating to WSL2, the shell doesn't start anymore. The hyper window pops up but is completely blank.

After doing some troubleshooting, it turns out the bash.exe command does not do anything after updating to WSL2 (and re-installing ubuntu from scratch).
The fix I found for this is to change the shell from bash.exe to ubuntu2004.exe, and remove any shell arguments `shellArgs: [],`

I'm not sure if this is my machine or just the new state of things with WSL2.

**Comment by GTMxCode** [comment]
This is what works for me

**Comment by LabhanshAgrawal** [comment]
This is not a compatibility issue. The executable has just changed from `bash.exe` to `wsl.exe` (or distro specific exe).
Closing this, as it's not an issue with hyper.
