### ISSUE TITLE
Hyper adds itself to PATH on every run

### ISSUE THREAD

**Issue by fornnever** [vercel/hyper#4609]
✅ Your Hyper.app version is **3.0.2**
✅ I have searched the [issues]

As title explains itself whenever i run hyper it adds itself to PATH again. I don't know if its because exe location contains unicode characters. I attached a ss file. I tried uninstall and fresh install already.

![ss](https://user-images.githubusercontent.com/19656379/83891739-5008c700-a756-11ea-91e3-8cd9fa492c35.png)

**Comment by LabhanshAgrawal** [comment]
This has been fixed in canary, you can get the latest ci build from https://github.com/vercel/hyper/actions/runs/133549960 and test.
