### ISSUE TITLE
Error when changing terminal

### ISSUE THREAD

**Issue by RBalconi** [vercel/hyper#4610]
Hello, I'm trying to use GitBash or Windows PowerShell with Hyper, however when I change the .hyper.js to the following configuration:
```
    // shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"',
    shell: '‪C:\\Program Files\\Git\\git-cmd.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    //shellArgs: ['--login'],
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],


    // for environment variables
    env: {TERM: 'cygwin'},

```
Give the following error. Regardless of the terminal you place. How can I solve?

![image](https://user-images.githubusercontent.com/18688446/83903446-25a21400-a72c-11ea-9fcd-97844cbb8b4e.png)

Thank you

**Comment by LabhanshAgrawal** [comment]
which windows version are you on?

**Comment by RBalconi** [comment]
> which windows version are you on?

Win 10 Pro - 64 bits

**Comment by LabhanshAgrawal** [comment]
which build number? you can check using `winver`

**Comment by LabhanshAgrawal** [comment]
You have a `"` at the end in the powershell path

**Comment by RBalconi** [comment]
> You have a `"` at the end in the powershell path

I left it that way and it worked, apparently it was the double quotes I hadn't seen. Excuse me.

```
shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
shellArgs: [],
env: {TERM: 'cygwin'},

```
