### ISSUE TITLE
Cannot switch between tabs with command+shift+[ after opening a URL

### ISSUE THREAD

**Issue by 7373Lacym** [vercel/hyper#463]
Steps to Reproduce.
On OSX yosemite
1.) open any url
2.) click somewhere in the browser window
3.) open another tab
4.) try to navigate between the tabs using command+shift+[ or + ]

**Comment by ppot** [comment]
Closed in https://github.com/ppot/hyper/issues/10

**Comment by 7373Lacym** [comment]
nice

**Comment by ppot** [comment]
@7373Lacym Not there yet haha

**Comment by LabhanshAgrawal** [comment]
Seems to be fixed on canary
