### ISSUE TITLE
support for powerline fonts?

### ISSUE THREAD

**Issue by 4khi1** [vercel/hyper#4636]
I am using spaceship theme in zsh shell...
it's showing a box instead of a symbol  

![image](https://user-images.githubusercontent.com/21128035/84650018-1fc6e280-af25-11ea-90a7-0d857378c76b.png)

**Expected:**

![image](https://user-images.githubusercontent.com/21128035/84855598-14d59480-b082-11ea-9d2e-069ab5cc2c64.png)

**Comment by LabhanshAgrawal** [comment]
can you post your config please?

**Comment by 4khi1** [comment]
I am not touched the config file. It's the default config.
Unfortunately I don't have it now.
FYI, OS: Win 10

**Comment by LabhanshAgrawal** [comment]
you will have to use a powerline font for the symbols to work

**Comment by LeapofAzzam** [comment]
Use Nerd Fonts. Search for your fonts in [https://www.nerdfonts.com](https://www.nerdfonts.com) and download it. Then extract it and install the font. Now change the font with the Nerd Fonts version (which is has NF at end of font name)
