### ISSUE TITLE
 canary is smaller than stable

### ISSUE THREAD

**Issue by shinriyo** [vercel/hyper#4658]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

My latest is Hyper 3.1.0-canary.4 (stable)

<img width="532" alt="スクリーンショット 2020-06-17 10 22 34" src="https://user-images.githubusercontent.com/396927/84844279-f91fbd80-b084-11ea-9960-1a0fdaf21f1b.png">
canary is stable?

## Issue

I installed `Hyper 3.1.0-canary.4 (stable)`.
But, it appeared update button on  right-down, if I push it install older (3.0.2) version.

![スクリーンショット 2020-06-17 10 22 13](https://user-images.githubusercontent.com/396927/84844404-384e0e80-b085-11ea-981a-3fab4ed4746f.png)

**Comment by LabhanshAgrawal** [comment]
`Hyper 3.1.0-canary.4 (stable)` Here stable denotes your `updateChannel`
That's why you're getting an update notification, you can change `updateChannel` to canary in the config.

**Comment by shinriyo** [comment]
@LabhanshAgrawal 

Ah, I see.

How to fix
command + ,
```
module.exports = {
  config: {
    // choose either `'stable'` for receiving highly polished,
    // or `'canary'` for less polished but more frequent updates
    updateChannel: 'stable',
```

`updateChannel: 'stable',`
 =>
`updateChannel: 'canary',`

Right?

**Comment by LabhanshAgrawal** [comment]
yep

**Comment by shinriyo** [comment]
@LabhanshAgrawal Thank you. It worked!
