### ISSUE TITLE
the speed of moving cursor is too slow

### ISSUE THREAD

**Issue by PKUFlyingPig** [vercel/hyper#4665]
I feel that the speed of moving cursor is too slow, if I want to move the cursor from the end of a very long command to the middle of the command, I have to watch the cursor moving slowly, are there some solving methods?

**Comment by LabhanshAgrawal** [comment]
It doesn't depend on the terminal.
I usually do `option+arrow_key` to move one word at a time. I'm on mac so the shortcut might differ for you based on your os.
Also possible to do `option+click` to directly move the cursor to desired location.

**Comment by GTMxCode** [comment]
^
On windows its ctrl+arrow. In Linux I'm pretty sure it depends on your shell and settings, for me in zsh in Emacs mode it's the same

If you're using zsh and you literally want the middle of the line you could create a widget that moves the cursor to the middle of the line and then bind it to a key. I might just do this for myself, it's not a bad idea and would be even faster than jumping one word at a time, maybe throw in a numeric argument so you could pick 1/4 or 2/3 for instance. Sky's the limit.

**Comment by PKUFlyingPig** [comment]
Thanks a lot for your share : )

**Comment by LabhanshAgrawal** [comment]
@PKUFlyingPig can you please close this issue as it's been answered.
