### ISSUE TITLE
I am on version 3.0.2 and i am not able to open a file when in .git.

### ISSUE THREAD

**Issue by WirelessHubMaster** [vercel/hyper#4666]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by LabhanshAgrawal** [comment]
Can you elaborate a bit?

**Comment by WirelessHubMaster** [comment]
I am running windows 10 software, hyper version 3.0.2 . I am using the hyper terminal as a web developer. I was not able to "open file.txt" or something like this in my system as bash is not recognizing it. Please solve this

**Comment by LabhanshAgrawal** [comment]
see https://stackoverflow.com/questions/35811533/git-bash-bash-open-command-not-found
you can close this issue as it's not related to hyper

**Comment by Vi8670** [comment]
Web Development by Angela Yu (udemy)
