### ISSUE TITLE
Hyper creates many environment variables

### ISSUE THREAD

**Issue by jacobzart** [vercel/hyper#4676]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise 1809
- **Hyper.app version**: Hyper 3.0.2 (Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Happens with all configs, even with the default:(
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: is vanilla

## Issue

So, recently i faced some problems with env variables, i couldn't add them, because all the limit was spent with hyper env variable, which is for cli, here it is: %USERPROFILE%\AppData\Local\hyper\app-3.0.2\resources\bin

Every time i open hyper, it creates this variable( I tried reinstalling Hyper 2 times, deleted all its folders, thought the problem is with my config, but it happens even with the default one🙁 

Am i the only one, who faces this problem? What should i do?

![image](https://user-images.githubusercontent.com/61295047/85279415-0d9df480-b48f-11ea-8ae6-12e8679d047c.png)

**Comment by LabhanshAgrawal** [comment]
this was a problem with the registry library we were using, it has been fixed now.
Download the latest [ci build](https://github.com/vercel/hyper/actions/runs/143471057) it should set env vars properly. You can delete the earlier entries.

**Comment by jacobzart** [comment]
> this was a problem with the registry library we were using, it has been fixed now.
> Download the latest [ci build](https://github.com/vercel/hyper/actions/runs/143471057) it should set env vars properly. You can delete the earlier entries.

thanks, works as needed😃
