### ISSUE TITLE
Hyper 3.1.0 Canary for Windows

### ISSUE THREAD

**Issue by LeapofAzzam** [vercel/hyper#4681]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 Pro x64

## Issue

For no reason, there no Windows build for Hyper 3.1.0 canary 4. In my configuration file, my update type is canary, but there no any update notification from Hyper. Does there any way to build the canary build in Windows?

**Comment by LabhanshAgrawal** [comment]
There was no build for windows because of a cert issue. You can download the latest build from the [ci](https://github.com/vercel/hyper/actions/runs/145055527)
