### ISSUE TITLE
I am using Version 3.0.2, and there is a slight problem. If we get the window to close, the system starts to slow down, It remains unresponsive until a forced reboot. Please fix this issue.

### ISSUE THREAD

**Issue by WirelessHubMaster** [vercel/hyper#4683]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by LabhanshAgrawal** [comment]
Try the [ci build](https://github.com/vercel/hyper/actions/runs/145055527) once
