### ISSUE TITLE
Spaceship prompt icons not properly rendered

### ISSUE THREAD

**Issue by Olgoetz** [vercel/hyper#4687]
Hi together,

I have been struggling for while to setup spaceship-prompt running in a Hyper Terminal. However, I do not manage to have the icons displayed correctly (e.g. the package icon does not have a space and the node js icon is far too small) in the prompt.

![Screenshot 2020-06-29 at 00 25 27](https://user-images.githubusercontent.com/19877252/85959900-90e3ac80-b99f-11ea-98dd-52ce71fd8bf2.png)

This is .hyper.js:

module.exports = {
	config: {
		// choose either `'stable'` for receiving highly polished,
		// or `'canary'` for less polished but more frequent updates
		updateChannel: 'stable',

		// default font size in pixels for all tabs
		fontSize: 16,

		// font family with optional fallbacks

		fontFamily: '"MesloLGMDZ Nerd Font", monospace',
		//fontFamily:
		//	'"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

		// default font weight: 'normal' or 'bold'
		fontWeight: 'normal',

		// font weight for bold characters: 'normal' or 'bold'
		fontWeightBold: 'bold',

		// line height as a relative unit
		lineHeight: 1,

		// letter spacing as a relative unit
		letterSpacing: 0,

		// terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
		cursorColor: 'rgba(248,28,229,0.8)',

		// terminal text color under BLOCK cursor
		cursorAccentColor: '#000',

		// `'BEAM'` for |, `'UNDERLINE'` for _, `'BLOCK'` for █
		cursorShape: 'BLOCK',

		// set to `true` (without backticks and without quotes) for blinking cursor
		cursorBlink: false,

		// color of the text
		foregroundColor: '#fff',

		// terminal background color
		// opacity is only supported on macOS
		backgroundColor: '#000',

		// terminal selection color
		selectionColor: 'rgba(248,28,229,0.3)',

		// border color (window, tabs)
		borderColor: '#333',

		// custom CSS to embed in the main window
		css: '',

		// custom CSS to embed in the terminal window
		termCSS: '',

		// if you're using a Linux setup which show native menus, set to false
		// default: `true` on Linux, `true` on Windows, ignored on macOS
		showHamburgerMenu: '',

		// set to `false` (without backticks and without quotes) if you want to hide the minimize, maximize and close buttons
		// additionally, set to `'left'` if you want them on the left, like in Ubuntu
		// default: `true` (without backticks and without quotes) on Windows and Linux, ignored on macOS
		showWindowControls: '',

		// custom padding (CSS format, i.e.: `top right bottom left`)
		padding: '12px 14px',

		// the full list. if you're going to provide the full color palette,
		// including the 6 x 6 color cubes and the grayscale map, just provide
		// an array here instead of a color map object
		colors: {
			black: '#000000',
			red: '#C51E14',
			green: '#1DC121',
			yellow: '#C7C329',
			blue: '#0A2FC4',
			magenta: '#C839C5',
			cyan: '#20C5C6',
			white: '#C7C7C7',
			lightBlack: '#686868',
			lightRed: '#FD6F6B',
			lightGreen: '#67F86F',
			lightYellow: '#FFFA72',
			lightBlue: '#6A76FB',
			lightMagenta: '#FD7CFC',
			lightCyan: '#68FDFE',
			lightWhite: '#FFFFFF',
		},

		// the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
		// if left empty, your system's login shell will be used by default
		//
		// Windows
		// - Make sure to use a full path if the binary name doesn't work
		// - Remove `--login` in shellArgs
		//
		// Bash on Windows
		// - Example: `C:\\Windows\\System32\\bash.exe`
		//
		// PowerShell on Windows
		// - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
		shell: '/bin/zsh',

		// for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
		// by default `['--login']` will be used
		shellArgs: ['--login'],

		// for environment variables
		env: {},

		// set to `false` for no bell
		bell: 'SOUND',

		// if `true` (without backticks and without quotes), selected text will automatically be copied to the clipboard
		copyOnSelect: false,

		// if `true` (without backticks and without quotes), hyper will be set as the default protocol client for SSH
		defaultSSHApp: true,

		// if `true` (without backticks and without quotes), on right click selected text will be copied or pasted if no
		// selection is present (`true` by default on Windows and disables the context menu feature)
		quickEdit: false,

		// choose either `'vertical'`, if you want the column mode when Option key is hold during selection (Default)
		// or `'force'`, if you want to force selection regardless of whether the terminal is in mouse events mode
		// (inside tmux or vim with mouse mode enabled for example).
		macOptionSelectionMode: 'vertical',

		// URL to custom bell
		// bellSoundURL: 'http://example.com/bell.mp3',

		// Whether to use the WebGL renderer. Set it to false to use canvas-based
		// rendering (slower, but supports transparent backgrounds)
		webGLRenderer: true,

		// for advanced config flags please refer to https://hyper.is/#cfg
	},

	// a list of plugins to fetch and install from npm
	// format: [@org/]project[#version]
	// examples:
	//   `hyperpower`
	//   `@company/project`
	//   `project#1.0.1`
	plugins: ['hyperterm-atom-dark'],

	// in development, you can create a directory under
	// `~/.hyper_plugins/local/` and include it here
	// to load it and avoid it being `npm install`ed
	localPlugins: [],

	keymaps: {
		// Example
		// 'window:devtools': 'cmd+alt+o',
	},
};

**Comment by LabhanshAgrawal** [comment]
try the latest [ci build](https://github.com/vercel/hyper/actions/runs/149163272)
If you face issues with font set `disableLigatures: true` and `webGLRenderer: false` in the config file

**Comment by Olgoetz** [comment]
Hi @LabhanshAgrawal,

yout suggestion almost fully worked. Additionally I had to set `fontWeightBold: 'normal'` instead of `fontWeightBold: 'bold` (but I do not why actually).

![screenshot](https://user-images.githubusercontent.com/19877252/85999778-f752e400-ba0c-11ea-8e23-2affb914f79c.png)

**Comment by LabhanshAgrawal** [comment]
The fontWeightBold thing is a separate issue. I will close this as it's resolved (the issue was lack of newer unicode versions support, which has been fixed recently). Fill free to open new issue if you face something else.

**Comment by LabhanshAgrawal** [comment]
@Olgoetz one question though, what made you to try changing the fontWeightBold value?

**Comment by Olgoetz** [comment]
@LabhanshAgrawal since it must be something related to the font setting, I just did trial and error. Putting it `normal` made the node js icon appear properly, but the rest does not look that nice any more.
As you suggested sooner or later will open another issue.

**Comment by LabhanshAgrawal** [comment]
Can you paste the text here, or give some details about the setup?
I would like to try to replicate it

**Comment by Olgoetz** [comment]
The .hyper.js config I used to have is the exact same one I pasted in the issue description.

**Comment by LabhanshAgrawal** [comment]
I was talking about pasting the text from the screenshot (with the node icon), so I can paste it in the terminal try out the font weight stuff.
Or a link to the zsh plugins used, so I can install them and test.

**Comment by Olgoetz** [comment]
Ah, sorry.

List of zsh plugins:
plugins=(git ruby dotenv lighthouse bundler zsh-completions zsh-autosuggestions zsh-syntax-highlighting)

List hyper plugins:
plugins: ['hyperterm-atom-dark']

```
contact-keeper on  master [!?] is 📦 v1.0.0 via ⬢ v14.4.0
```
