### ISSUE TITLE
open command does not work and also vm exit is getting hanged after typing qa .

### ISSUE THREAD

**Issue by Vi8670** [vercel/hyper#4698]
- [ ] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** win32 x64 10.0.18363
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "C:\\Program Files\\Git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "cygwin"
  },
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment]
can you elaborate a bit?

**Comment by Vi8670** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/60037680/86029017-41a98480-ba50-11ea-8047-d64a9e96dbf0.png)
I am unable to open text file inside my folder my using the command 
open <file_name.txt> (as per my instructor direction)

**Comment by LabhanshAgrawal** [comment]
see https://stackoverflow.com/questions/35811533/git-bash-bash-open-command-not-found
closing this issue as it's not related to hyper

**Comment by Vi8670** [comment]
Thank you very much 
Its actually 
start <file_name.txt>
not open 
Now it is working 
It is my instructor fault

**Comment by LabhanshAgrawal** [comment]
Which course is this? Can you please tell them to add instructions for windows?
Someone opened a similar issue recently #4666
