### ISSUE TITLE
Strange path change in PATH

### ISSUE THREAD

**Issue by alyasevich** [vercel/hyper#4700]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version

- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10(version 1803)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: No
- **The issue is reproducible in vanilla Hyper.app**: yeah

## Issue
Hi.
After several minutes of use, I noticed that the paths in the PATH have changed. For example, if PATH had such a path C: \ Users \ Admin \ AppData \ Local \ Programs \ Python \ python.exe, then it was replaced by C: \ Users \ ????? \ AppData \ Local \ Programs \ Python \ python.exe. Then I changed the PATH manually, and for a while everything was fine. But then, the paths in PATH changed again. Also, the problem is exactly in hyper, because after I uninstalled the application and changed the path, 
everything was fine 
Thank you in advance 😄

**Comment by LabhanshAgrawal** [comment]
Hey @alyasevich were you able to figure it out?
It was a problem in the registry module we used earlier to set the PATH. It's solved in the latest [canary build](https://github.com/vercel/hyper/actions/runs/153185087)

**Comment by alyasevich** [comment]
> Hey @alyasevich were you able to figure it out?
> It was a problem in the registry module we used earlier to set the PATH. It's solved in the latest [canary build](https://github.com/vercel/hyper/actions/runs/153185087)

Oh, I'm sorry. Looks that I have been using an old version. Anyway my issue is a duplicate. That is why I closed this issue
