### ISSUE TITLE
Unable to run Hyper due to error in Preferences on Windows 10

### ISSUE THREAD

**Issue by scottgemmell** [vercel/hyper#4701]
I was trying to get my ZSH theme to work and in Hyper Preferences I changed line `shell : 'C:\\System32\\bash.exe'` to `shell: '\bin\zsh'`. 

Immediately the app stopped working. I cannot reopen. I have tried uninstalling and reinstalling multiple times.

From reading other Issues it appears I just change the `~/.hyper.js` file but I cannot find this where its expected or anywhere else. Where can I find this file? or what folders can I delete in order to facilitate a fresh install.

- **OS version and name**: Windows 10
- **Hyper.app version**: Latest

**Comment by LabhanshAgrawal** [comment]
The config file is in `%appdata%\Hyper`
You have to set zsh inside wsl, not in Hyper config
Check out this [blog post](https://medium.com/@vinhp/set-and-use-zsh-as-default-shell-in-wsl-on-windows-10-the-right-way-4f30ed9592dc)

**Comment by scottgemmell** [comment]
I see a `/hyper/` folder in `Users/MyUserName/AppData/Local` but nothing that looks like an editable config file

**Comment by scottgemmell** [comment]
Uninstalled app then deleted the above `../Local/hyper/` directory and still not starting up.

**Comment by LabhanshAgrawal** [comment]
It should be in `C:\Users\<UserName>\AppData\Roaming\Hyper`

**Comment by scottgemmell** [comment]
Ah. Many thanks @LabhanshAgrawal
