### ISSUE TITLE
error update plugin

### ISSUE THREAD

**Issue by SeregaT79** [vercel/hyper#4702]
- [ ] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** linux x64 5.4.0-40-generic
 - **Electron:** 3.1.3  **LANG:** ru_RU.UTF-8
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 14,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "bold",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BEAM",
  "cursorBlink": false,
  "foregroundColor": "#0ff",
  "backgroundColor": "#011",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#033",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "true",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [
    "hyperpower",
    "@company/project",
    "project#1.0.1"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment]
can you explain the problem?

**Comment by LabhanshAgrawal** [comment]
```
"plugins": [
  "hyperpower",
  "@company/project",
  "project#1.0.1"
]
```
Remove the 2nd and 3rd entries from the plugins array in your config
