### ISSUE TITLE
Hyper doesn't respond when trying to close inside WSL

### ISSUE THREAD

**Issue by iinfin** [vercel/hyper#4704]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 20161.1000
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [de7adca130745f541fb3ed084509aaf5](https://gist.github.com/iinfin/de7adca130745f541fb3ed084509aaf5)
- ~~Relevant information from devtools~~:
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Hyper app doesn't respond when trying to close while inside WSL (Ubuntu, Kali, or any other). Apparently I have to `exit` first.
It's a minor detail and could be something expected/unavoidable though.

![not_responding](https://user-images.githubusercontent.com/48106228/86510306-41660c00-bdf7-11ea-9fab-6858cbf01b22.png)

**Comment by LabhanshAgrawal** [comment]
your config doesn't mention `shell` as set to wsl

**Comment by iinfin** [comment]
@LabhanshAgrawal I just use default cmd and switch to WSL with `bash` and `kali` commands. I don't use them for daily work so didn't set default.

But yes, I just tried setting it default and I can close Hyper without this problem.
The error seems to occur only when launching WSL afterwards with those commands as in the screenshot.

**Comment by LabhanshAgrawal** [comment]
This is an issue with the `node-pty` version used in that build.
It was fixed in #3781 
Since there hasn't been any release since then, you may instead use the canary build
You can download it from the artifacts in the [ci](https://github.com/vercel/hyper/actions/runs/153185087)
if you still run into this issue, try setting `useConpty: true` and report how it behaves (also try setting it to `false` once).

**Comment by iinfin** [comment]
My update channel was already set to canary but I'll keep an eye on [builds from GitHub actions](https://github.com/vercel/hyper/actions), it seems more frequent.
This fixed my problem, thank you!
