### ISSUE TITLE
hyper cli not working

### ISSUE THREAD

**Issue by Milo123459** [vercel/hyper#4705]
Heyo, Just installed hyper and I ran hyper i  and it said hyper is not recognised as a program.

I on the latest version and 64 bit windows

Would appreciate any help

**Comment by LabhanshAgrawal** [comment]
you tried to run it from command line?

**Comment by LabhanshAgrawal** [comment]
@Milo123459 ^

**Comment by Milo123459** [comment]
i have indeed tried,didn't change anything

**Comment by Milo123459** [comment]
oh and i tried that

**Comment by Milo123459** [comment]
I fixed it :) but then this happens: https://salvage.is-inside.me/OFglNdsy.png

**Comment by LabhanshAgrawal** [comment]
can you post your config?

**Comment by Milo123459** [comment]
i managed to fic it by wiping all data, ty for the help 👍
