### ISSUE TITLE
Change window controls position

### ISSUE THREAD

**Issue by kshitij86** [vercel/hyper#4720]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/kshitij86/1a988c213aa7534eb3f7463b4958dd79) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue

I just installed hype.js on Ubuntu, but the window controls are on the right by default but I want them on the left. How can I change this?
![Screenshot from 2020-07-08 18-24-23](https://user-images.githubusercontent.com/26821140/86921133-46ed8a00-c148-11ea-811b-78bd32f2a84a.png)

**Comment by LabhanshAgrawal** [comment]
you can set the `showWindowControls` property to `'left'`

**Comment by kshitij86** [comment]
@LabhanshAgrawal  That worked. Thanks!
