### ISSUE TITLE
Plugin to dim inactive panes possible?

### ISSUE THREAD

**Issue by tberghuis** [vercel/hyper#4729]
There is an extension for vscode https://marketplace.visualstudio.com/items?itemName=ojkwon.vscode-activedocumentindicator that highlights the active pane by making inactive panes dimmer. Would it be possible to create a similar plugin for hyper?

**Comment by LabhanshAgrawal** [comment]
I use [hyper-pane](https://www.npmjs.com/package/hyper-pane)
you can explore more in https://github.com/bnb/awesome-hyper list
