### ISSUE TITLE
Text is beeing automatically selected after I paste it on Hyper (using Oh My Zsh)

### ISSUE THREAD

**Issue by matheusranzani** [vercel/hyper#4745]
Whenever I paste some text on Hyper it is selected automatically. I'm using Hyper with Oh My Zsh on Linux right now. I also use them on Windows and the same problem doesn't happen.

Steps to reproduce the problem:
1. Copy a browser URL, for example: https://github.com/matheusranzani/reactive-native-rocketseat (this is a private repo of mine, just to example the problem)
2. Paste it on Hyper
3. See that the URL text is selected

I don't want the text I paste be selected automatically, because I'm using the plugin 'fast-syntax-highlighting' and it doesn't work correctly after the text is auto selected.

Screenshot of the error:
![hyper-issue-1](https://user-images.githubusercontent.com/59764547/87679641-cf74b780-c752-11ea-8445-310bdabdc2d0.png)

Screenshot of the normal plugin behavior (writting manually the URL):
![hyper-issue-2](https://user-images.githubusercontent.com/59764547/87679653-d26fa800-c752-11ea-831d-2c98563de00c.png)

OS / Distro: Zorin OS
Latest ohmyzsh update?: Yes
ZSH Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Comment by LabhanshAgrawal** [comment]
This behaviour is from zsh with oh-my-zsh
It also occurs with the default terminal
I've also observed this, as I'm using the same setup
you can just type a space after pasting, it triggers the syntax highlighting
