### ISSUE TITLE
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by SuperMaZingCoder** [vercel/hyper#4750]
```
> hyper install hyper-dracula
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///usr/lib/hyper/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeBody.call.then.buffer (/usr/lib/hyper/resources/app.asar/node_modules/electron-fetch/lib/index.js:240:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
OS: Manjaro Linux
Installation: `pamac build hyper`
I have seen other [issues](https://github.com/vercel/hyper/issues/3423#issuecomment-647011001), but these seem to be because of Windows WSL limitations where I'm using Konsole on Manjaro KDE.

**Comment by allywilson** [comment]
Same issue here.
CentOS 8
AppImage 3.0.2 (stable).

```

$ hyper install hyper-dracula
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyper-ayjE5l/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeBody.call.then.buffer (/tmp/.mount_hyper-ayjE5l/resources/app.asar/node_modules/electron-fetch/lib/index.js:240:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It also opens a new hyper window, which doesn't do anything, but if I close it then the original window finally goes back to prompt, so must be expecting something from it...

**Comment by storenth** [comment]
The same issue caught when `hyper -v` called:
<img width="1552" alt="Снимок экрана 2020-07-24 в 17 36 58" src="https://user-images.githubusercontent.com/18244131/88383353-8c5eb800-cdd4-11ea-9b77-9c45a5e79acc.png">

**Comment by perzanko** [comment]
Same issue here :hand:
OS: Ubuntu 20.04.1,
Ver: 3.0.2

**Comment by cesar-cb** [comment]
I can install plugins without problems using **version 3.1.0-canary.4 (pre-release)**. But I keep struggling with **version 3.0.2**

OS: Arch Linux (5.8.1-arch1-1)

**Comment by mat-ale** [comment]
Same here.
- `KDE Neon 5.19` (based on `Ubuntu 20.04`)
- `Hyper v3.0.2` version `.AppImage`

**Comment by martonlederer** [comment]
Same. Arch Linux manjaro

**Comment by datadu-de** [comment]
ditto on artix

**Comment by be-krishna** [comment]
Same. Pop OS 20.10.

**Comment by gponty** [comment]
Same here, manjaro.

**Comment by rastydnb** [comment]
Same here, manjar

**Comment by kangxiaoju** [comment]
Same here, arch
Hyper version 3.0.2

**Comment by allywilson** [comment]
Just checked v3.1.0-canary.4 still the same on that (CentOS 8 Stream).

**Comment by LabhanshAgrawal** [comment]
This isn't something which will cause anyone issues. It's just failing to fetch the notifications as the server is down since some time, it doesn't impact anything else.

**Comment by allywilson** [comment]
It stops any themes from being installed and used. I'd say that's an issue.

**Comment by LabhanshAgrawal** [comment]
I'm talking about the error `Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0`
If you're facing trouble in installing plugins then that's because the cli is not setup properly
open hyper first and then add cli to path from the plugins (tools if you're on latest ci build) menu option.
try with latest build from https://github.com/vercel/hyper/actions/runs/527838058#artifacts
Confirm that you've it setup properly by running `hyper version`

Or you can also add the plugin to the config file and hyper will install it automatically.

**Comment by LabhanshAgrawal** [comment]
Also as someone has mentioned earlier that they are facing issues with AppImage, try with maybe rpm if you face the same.
If it's working on other builds and not on appimage then that can be tracked in a separate issue.

**Comment by allywilson** [comment]
Thanks, the RPM works for me. I'd have expected a known issues section or similar for the AppImage though. This has been an issue for ~6 months at least.

**Comment by LabhanshAgrawal** [comment]
@allywilson did you try using the `add hyper cli to path` option from the tools menu when you had the appimage install?
if not can you please try that once

**Comment by LabhanshAgrawal** [comment]
Also please install from the ci link from my earlier comment, the release is too old at this point, maybe it's fixed since then.

**Comment by docbobo** [comment]
Just installed Hyper AppImage and encountered the same problem. Using `add hyper cli to path`, I get a notification that says "Command is added in PATH only at package installation. Please reinstall."

**Comment by LabhanshAgrawal** [comment]
@docbobo can you run this once and check
```
mkdir -p /usr/local/bin
ln -sf '/opt/Hyper/resources/bin/hyper' '/usr/local/bin/hyper'
```
