### ISSUE TITLE
Zero-width-join emoji outputs don’t clear properly

### ISSUE THREAD

**Issue by gfscott** [vercel/hyper#4751]
I use a CLI tool that periodically outputs a [Zero-Width Join](https://emojipedia.org/emoji-zwj-sequence/) emoji at the beginning of the line — in this case [`woman-technologist`](https://emojipedia.org/woman-technologist/): 👩‍💻

In Hyper, that emoji doesn't disappear fully when clearing the buffer. I wind up with half a face overlaid on the terminal output (screenshots below).

Resizing the window does successfully clear the artifact — presumably there's a more thorough redraw at that point?

This is obviously a very minor bug, but it would save me _seconds per day_ not to have to resize my terminal to fully clear the output 😅 

#### Screenshot of the output in action

As you can see, the output is also not rendering the emoji combination as expected, but that's much less of an issue than the failure to clear it 
![20-07-5h3n3-i4boe](https://user-images.githubusercontent.com/547470/88308630-47a32600-ccdb-11ea-8c3d-2ca1991d84d1.png)

#### Screenshot just after clearing the terminal
<img width="96" alt="Screen Shot 2020-07-22 at 18 17 04" src="https://user-images.githubusercontent.com/547470/88306321-969b8c00-ccd8-11ea-9bb2-13eab221226a.png">

#### Screenshot of subsequent output

You can see the half-face obscures the output underneath it:
<img width="216" alt="20-07-7n8ox-7exxd" src="https://user-images.githubusercontent.com/547470/88307347-d747d500-ccd9-11ea-8bcd-133ca38e6575.png">

### System information

OS: macOS 10.15.5 (Build: 19F101)
Hyper: 3.0.2

Thanks for making Hyper! I'm a big fan 🙏🏻

**Comment by LabhanshAgrawal** [comment]
it should be working in the canary build
try it from [here](https://github.com/vercel/hyper/actions/runs/174098472)

**Comment by gfscott** [comment]
I downloaded the canary build and can verify it works! Looking forward to the stable release. Thanks! 👍🏻
