### ISSUE TITLE
Freezing while `node` is running in 2nd tab.

### ISSUE THREAD

**Issue by bvandenbon** [vercel/hyper#4753]
Steps to reproduce:

- start hyper.
- open a 2nd tab, leave the first one open as well.
- execute `node` from the commandline in that 2nd tab, it will ask for additional input, just leave it open.
- while `node` is still on, close the terminal window, clicking the cross of the window.

--> the terminal window stays open, but becomes unresponsive.

environment: windows.

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/pull/3781
