### ISSUE TITLE
I added a verminal theme on hyper windows and nothing changed

### ISSUE THREAD

**Issue by judicaelandria** [vercel/hyper#4755]
Hey,
first, this project is really great, but I have an issue when I add a new theme on hyper windows
nothing changed even after I reload the terminal, maybe I am missing something
![hyper](https://user-images.githubusercontent.com/46365844/88453526-638c0080-ce70-11ea-81ce-b6b3e810216b.PNG)
?

**Comment by LabhanshAgrawal** [comment]
your config?
