### ISSUE TITLE
How to setup that beautiful Vercel triangle on the prompt?

### ISSUE THREAD

**Issue by weeebdev** [vercel/hyper#4756]
As in all the examples. Do I have to install specific prompt like ohmyzsh or ohmyfish? Maybe starship?

**Comment by corscheid** [comment]
If you're using Bash, try
```bash
export PS1="▲ \w "
```
and add that line to your `~/.bashrc` or `~/.bash_profile` or `~/.profile`, whichever one is in use.

if you're on zsh, try
```zsh
export PS1="▲ %~ "
```
and add that to your `~/.zshrc`

I'm not sure about other shells.
