### ISSUE TITLE
Default terminal & Default shell

### ISSUE THREAD

**Issue by KnowsCount** [vercel/hyper#4757]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.6 
- **Hyper.app version**: Hyper 3.0.2 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist](https://gist.github.com/KnowsCount/c40b3e20520c2a6ac4bac68395efcbb1) (which looks like) ![Screenshot](https://raw.githubusercontent.com/KnowsCount/MarkdownPhotos/master/Res/Screenshot%202020-07-28%20at%2009.40.30.png) (the ip is proxied therefore attacking me is not useful lol)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I don't actually reckon this a bug report but... It is somewhat a suggestion whilst this suggestion is quite basic a need that it is enough to be a bug: to be able to set it as the **default terminal & shell**. What I am doing now is basically using 'command + I' to a script/executable & tell the system all these needs to be opened with Hyper.app, and it is a waste of time doing so. 

If I can actually do that, sorry to interrupt yet do tell me how to. 

Cheers!

**Comment by jackHedaya** [comment]
I believe you can do this by exporting `TERM_PROGRAM=Hyper` and `TERM_PROGRAM_VERSION=3.0.2` as variables. Using this option, Chrome (and I'm assuming other applications) will recognize Hyper as the default terminal.

![Screen Shot 2020-07-30 at 1 13 44 PM](https://user-images.githubusercontent.com/20172754/88953171-8189a480-d266-11ea-8643-00ae5e5b10c0.png)

**Comment by jackHedaya** [comment]
@KnowsCount Hope this solved your problem! if so, please be sure to close this issue.
