### ISSUE TITLE
Question: Can the new line on terminal startup be removed?

### ISSUE THREAD

**Issue by james-prado** [vercel/hyper#4788]
How do I prevent new terminal windows from starting with a new line?

- terminal starts with new line
![new_line](https://user-images.githubusercontent.com/13836920/89744048-fa62da80-da76-11ea-87e4-0ade7ad94df5.png)
- and it goes away after clearing (ctrl+l)
![no_new_line](https://user-images.githubusercontent.com/13836920/89744049-fb940780-da76-11ea-9c12-bad1a94eb43c.png)

This isn't a hyper specific issue, it happens in terminal too, but I'm not sure where else to ask this question.

**Comment by watsoncj** [comment]
Tested with 3.1.0-canary.4, using both zsh and bash. Did not see this behavior.

I suspect the issue has to do with your local shell config. 

Have you seen this with an empty/missing rc file? (.zshrc, .bashrc, etc)

**Comment by james-prado** [comment]
@watsoncj Yea you're right, it was a [theme](https://github.com/sindresorhus/pure) I load in my config that's causing it. Thanks for the suggestion, I didn't think to check if it was something in my `.zshrc` causing it.
