### ISSUE TITLE
After opening the terminal,% will appear

### ISSUE THREAD

**Issue by Yakumo-Yukari** [vercel/hyper#4803]
![2020-08-11 17 15 49](https://user-images.githubusercontent.com/12076232/89880165-83ece680-dbf6-11ea-98cc-02f79805ed88.png)

After opening the terminal,% will appear

How to set it not to appear%

**Comment by codehia** [comment]
same here. any solutions will be much appreciated.

**Comment by TheRafaelFarias** [comment]
With me this happens when i use zsh, try to use bash, if don't appear is problem with zsh

**Comment by warcayac** [comment]
same here
