### ISSUE TITLE
Windows CMD completion not working properly

### ISSUE THREAD

**Issue by diorcula** [vercel/hyper#4804]
When on Windows, using [TAB] to auto-complete your file/folder it only works half, it does complete but doesn't add the [/] and [SPACE] after the completion.

Not sure if this can be set in the Preferences, so i thought i should open this issue.

**Comment by diorcula** [comment]
Not sure if this ever will come but also seems to be an 'feature' with CMD in general

**Comment by LabhanshAgrawal** [comment]
this is not affected by hyper, it's a cmd thing
