### ISSUE TITLE
Add macos style option

### ISSUE THREAD

**Issue by TheRafaelFarias** [vercel/hyper#4808]
I use linux and the interface is like macos, and all apps is like macos. But in hyper is the windows style, then i tried to customize and set the mac buttons (in code) and worked but now don't work anymore (i will try to resolve later).

Add an option to set the buttons to mac os will be much better to who have a macos like interface and match with the system

(I'm not a native speaker, so may have misspellings)

**Comment by Hblanqueto** [comment]
How curious, just now I just installed it and I thought it would have the design of the macOS buttons.

The truth is that it would be a very good idea to implement it since there are many users who like that practical style.

I'm still looking for a way to pass the buttons to the left but I can't

**Comment by TheRafaelFarias** [comment]
I found a solution, if use the  plugin "hyper-custom-controls" already set to macos buttons

https://www.npmjs.com/package/hyper-custom-controls
