### ISSUE TITLE
hyper won't open when setting shell with visual studio developer prompt

### ISSUE THREAD

**Issue by MeirAtWork** [vercel/hyper#4820]
hi

when I set this line in the config:

shell: 'c:\windows\system32\cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat\"'

then hyper won't load.
I also tried to escape sequence the above - same result.
any help?

thanks
M

**Comment by LabhanshAgrawal** [comment]
you should put the arguments in `shellArgs` config option
