### ISSUE TITLE
does not Hyper support true color?

### ISSUE THREAD

**Issue by ryu1kup** [vercel/hyper#4824]
Hi developers, I'm a very beginner of Hyper.

I would like to use True Color for Neovim.
The environment variable TERM is xterm-256color, so I guess it supports true color.
However, it's said that hyper does not support true color in [this](https://gist.github.com/XVilka/8346728), 

Does this mean Hyper does not support true color actually?
Then here TERM no longer mean anything?

Sorry for my elemental question.

**Comment by bpeake-illuscio** [comment]
Was just scanning through the docs / issues with the same question, and if there is a setting somewhere I need to use to enable it.

**Comment by ryu1kup** [comment]
Of course I scanned the docs/issues quickly, but I didn't get clear answer.
I just want to know what TERM variable means in Hyper.

**Comment by creepinson** [comment]
Yeah I don't see a way to enable it :/ I really need this feature for bpytop to work!

**Comment by ryu1kup** [comment]
This has been solved for the moment in https://github.com/vercel/hyper/issues/4826
