### ISSUE TITLE
Color degradation in Neovim

### ISSUE THREAD

**Issue by iToXiQ** [vercel/hyper#4826]
Hello,

I would like to know if there is a fix for the color degradation which occurs when i open neovim in the Hyper.js Terminal.
I've tested the same in iTerm2 and there it worked. I found this Issue from 3 years ago(https://github.com/vercel/hyper/issues/2294), but i am unsure if was solved or if there exists any trick to get it working. I recently switched from iTerm2 to Hyper.js and this is the only thing bothering me so far.

OS version and name: macOS 10.15.6 
Hyper.app version: 3.0.2

Thanks in advance

<img width="1790" alt="Bildschirmfoto 2020-08-21 um 04 01 42" src="https://user-images.githubusercontent.com/35408274/90843978-2299e580-e363-11ea-813f-e79dc54e980a.png">

**Comment by shans10** [comment]
> 
> 
> Hello,
> 
> I would like to know if there is a fix for the color degradation which occurs when i open neovim in the Hyper.js Terminal.
> I've tested the same in iTerm2 and there it worked. I found this Issue from 3 years ago(#2294), but i am unsure if was solved or if there exists any trick to get it working. I recently switched from iTerm2 to Hyper.js and this is the only thing bothering me so far.
> 
> OS version and name: macOS 10.15.6
> Hyper.app version: 3.0.2
> 
> Thanks in advance
> 
> <img alt="Bildschirmfoto 2020-08-21 um 04 01 42" width="1790" src="https://user-images.githubusercontent.com/35408274/90843978-2299e580-e363-11ea-813f-e79dc54e980a.png">


I am facing the same issue on Windows 10 with Neovim and Hyper. However, the issue seems to have been fixed in the canary release. I tried the version **3.1.0-canary.4** and it displayed the colors correctly.

**OS -** Windows 10 v2004
**Hyper version -** 3.0.2 (issue present)
**Hyper version -** 3.1.0-canary.4 (issue fixed)

**Comment by ryu1kup** [comment]
@shans10 How did you install the canary release in Windows10? I could not find the released binary for Windows.

**Comment by shans10** [comment]
@ryu1kup Yes there is no canary release for Windows 10 in the official release pages so the first time when I had to install it I googled for it and I found a comment on github where I think one of the collaborators said that for Windows version we will have to get the ci build. [Here's](https://github.com/vercel/hyper/issues/4511#issuecomment-619431190) the link to that comment and if you want to directly go the download page then [this](https://github.com/vercel/hyper/actions/runs/378801823) is the link, download the "Hyper Setup 3.1.0-canary.4.exe" from there!

**Comment by ryu1kup** [comment]
@shans10 thanks a lot! It works for me too ;)
