### ISSUE TITLE
Incomplete matching on url

### ISSUE THREAD

**Issue by akhilpratap1991** [vercel/hyper#4833]
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

While hovering over a url to click, the whole url is not selected. This is the sample Url that I am trying that matches till before plus(+) symbol. I think Url matching is breaking because of "+" character in url. This is the standard pattern for gerrit reviews and important part of my daily dev routine.
http://gerrit.mmt.com/c/Service/+/37292

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** darwin x64 18.7.0
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** /bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 16,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true,
  "hypercwd": {
    "initialWorkingDirectory": "/Users/mmt8168/projects"
  }
}

          {
  "plugins": [
    "hypercwd",
    "hyperlinks"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by akhilpratap1991** [comment]
<img width="592" alt="Screenshot 2020-08-26 at 12 20 17 PM" src="https://user-images.githubusercontent.com/64142250/91310527-9c9cf500-e7cf-11ea-9159-1445062343cd.png">
I am also ok if I can modify the regex that matches the URL.

**Comment by kwickramasekara** [comment]
Having the same issue with "&" characters in url

**Comment by LabhanshAgrawal** [comment]
Working in canary, try with latest build from ci https://github.com/vercel/hyper/actions/runs/513403548#artifacts
