### ISSUE TITLE
[Hyper 3.0.2] "man" does not work

### ISSUE THREAD

**Issue by aroooo** [vercel/hyper#4839]
Hi.
_I'm using Hyper v3.0.2 on Void Linux (Kernel 5.8.1_1)._

I've recently came into an issue:
When I use the `man` command followed with another command (example `ls`) Hyper throws an error at me:
`hyper.AppImage: ERROR: ls: No such file or directory`
I can't figure out where it's coming, I've installed Hyper using the AppImage and it's located inside the /opt/Hyper folder.

Thank you.

**Comment by aroooo** [comment]
Bump, still occuring.

**Comment by LabhanshAgrawal** [comment]
can you please try with v3.1.3?
