### ISSUE TITLE
editor undo not working in hyper 3.0.2

### ISSUE THREAD

**Issue by mgowtham** [vercel/hyper#4850]
editor undo not working in hyper 3.0.2
os: mac OS Catalina

**Comment by LabhanshAgrawal** [comment]
can you please elaborate a bit

**Comment by catamphetamine** [comment]
Just installed Hyper on Windows and Undo isn't doing anything too.

**Comment by LabhanshAgrawal** [comment]
what do you expect undo to do in a terminal? we can't meddle with text.

**Comment by LabhanshAgrawal** [comment]
cmder provides the shell also and does the handling of undo. Since we just have the terminal we can't confidently edit things.
You should be able to use cmder shell inside hyper if you want.
That will probably be able to handle undo (pressing ctrl+z not from edit menu).

**Comment by LabhanshAgrawal** [comment]
they have a nice guide for using cmder with hyper
https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration

**Comment by LabhanshAgrawal** [comment]
closing this as it's out of scope for us
we can explore undo and redo for opening/closing tabs and splits once we've session restore figured out (long way to go currently)
