### ISSUE TITLE
Can't use poetry package manager

### ISSUE THREAD

**Issue by lvar** [vercel/hyper#4879]
I try to use poetry for make some python projects.
When I run **_poetry install_** get this error:

`
$ poetry install
  /c/Users/el_sh/.poetry/bin/poetry: line 2: import: command not found
/c/Users/el_sh/.poetry/bin/poetry: line 3: import: command not found
/c/Users/el_sh/.poetry/bin/poetry: line 4: import: command not found
/c/Users/el_sh/.poetry/bin/poetry: line 6: syntax error near unexpected token 
`('/c/Users/el_sh/.poetry/bin/poetry: line 6: `lib = os.path.normpath(os.path.join(os.path.realpath(__file__), "../..", "lib"))'`

Any idea ? Thanks for your help.

**Comment by LabhanshAgrawal** [comment]
Doesn't seem related to hyper
