### ISSUE TITLE
Hyper Terminal 'A javascript error occurred in the main process' 

### ISSUE THREAD

**Issue by Jack8400** [vercel/hyper#4887]
I'm using macOS Catalina and I wanted to download hyper terminal but it's showing an error 'a javascript error occurred in the main process' 

note: I've unstalled hyper previously, I'm reinstalling it now. | I'm using macOS Catalina and I wanted to download hyper terminal but it's showing an error 'a javascript error occurred in the main process' 
![Screenshot 2020-09-14 at 6 45 07 PM](https://user-images.githubusercontent.com/61938283/93090482-71187680-f6ba-11ea-9bfb-ae6c29bf0234.png)

**Comment by LabhanshAgrawal** [comment]
Looks like an issue in your config, the plugin names should be strings, i.e. `"hyper-material-theme"`
open `~/.hyper.js` and add `"` around the plugin names
