### ISSUE TITLE
Constant "Configuration Update" notification

### ISSUE THREAD

**Issue by nomad3k** [vercel/hyper#4892]
This has only started happening recently, so I guess it's a new bug.

I have a hyper terminal open, with multiple tabs even just typing "ls" causes the following error message to appear, along with multiple notification pings.  The tabs have processes running, which include .Net Core and a Vue application.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/149791/93311036-63b7d500-f7fd-11ea-8d93-b33fa2bc6d05.png">

<img width="345" alt="image" src="https://user-images.githubusercontent.com/149791/93311238-a8437080-f7fd-11ea-8c95-b9eb54de48e1.png">

Version: 3.0.2
MacOS: 10.15.6 (19G2021) installed.

**Comment by nomad3k** [comment]
Oh, I forgot to say.. I love Hyper.  Excellent tool.  Good work! :D

**Comment by LabhanshAgrawal** [comment]
Seems to be same as #4318
can you try the [latest build](https://github.com/vercel/hyper/actions/runs/254382407) and confirm if it's working for you.

**Comment by nomad3k** [comment]
I've installed the canary build and I'll let you know. :)

**Comment by parichaypari1986** [comment]
where do I find the Hyper config file for linux(my os is Ubuntu 20.04 LTS). However I found one config file which upon applying I am getting this:
**execvp(3) failed.: No such file or directory**.

**Comment by ktmq** [comment]
I've had this exact notification issue ever since I started using Hyper. I installed the latest build as suggested by @LabhanshAgrawal and it seems to have solved the issue so far! I haven't had the notification pop up (except when editing `~/.hyper.js`) in about an hour.
