### ISSUE TITLE
SCREEN command problem

### ISSUE THREAD

**Issue by harpreetsb** [vercel/hyper#4897]
Hi,
I was using terminator as my primary app, but had to look for other alternatives for better UI and themes.
I really love hyper but there seems to be a very irritating bug.
Here are steps to reproduce  is a bug.

1. Create a new screen with command `srceen -S test`
2. When you enter the screen, simply run `sudo apt update`, wait for it to complete.
3. Detach from screen by pressing `CTRL+A+D`
4. You will be back to your original terminal session. But now the problem is that the output from screen screen command is overlapped with current session.

I use screen command quite often while working with remote servers.

Please solve this.

**Comment by LabhanshAgrawal** [comment]
Fixed in canary #3391 
you can test using new build from ci https://github.com/vercel/hyper/actions/runs/499993353#artifacts
