### ISSUE TITLE
URL highlighting stops at '+' character

### ISSUE THREAD

**Issue by SpencerC** [vercel/hyper#4912]
A clicking on URL printed in the terminal pointing to https://something.com/path/thing1+thing2 navigates to https://something.com/path/thing1 in the browser (dropping the '+thing'). Using macOS 10.15.6.

To reproduce:
```shell
echo https://something.com/path/thing1+thing2
```
Then click on the link.

**Comment by LabhanshAgrawal** [comment]
Fixed in canary
you can test using new build from ci https://github.com/vercel/hyper/actions/runs/499993353#artifacts
