### ISSUE TITLE
webLinksActivationKey not working

### ISSUE THREAD

**Issue by mjuarez** [vercel/hyper#4924]
### Summary
I'm trying the new [`webLinksActivationKey`](https://github.com/vercel/hyper/pull/4543) feature in canary. I have tried setting my modifier to ctrl, alt, meta, shift. I'm restarting Hyper after saving the config file as per the caveats listed in #4543, however none of the attempts seem to be working. I double-checked the change-log for hyper 3.1.0-canary.4 release, and #4543 should have been included.

### Environment
```
hyper 3.1.0-canary.4-4805
Ubuntu 20.04.1 LTS
Linux osiris 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
GNOME Shell 3.36.4
```

### Configuration
https://gist.github.com/mjuarez/e0e5ae85ff25da972b9883f9b94989ef

### Expected Behavior
**Not** holding `ctrl` while clicking will **not** open a link.
Holding `ctrl` while clicking a link will open the link.

### Actual Behavior
Links will open regardless of `ctrl` being held down or not.

**Comment by danimas** [comment]
Same Problem here.
❯ echo $TERM_PROGRAM_VERSION                
3.1.0-canary.4
❯

**Comment by LabhanshAgrawal** [comment]
The 3.1.0-canary.4 release was done before #4543 was merged, please try with latest ci build
I've confirmed with new build that it's working.
