### ISSUE TITLE
Use the alt+[number] to switch between tabs instead of ctrl

### ISSUE THREAD

**Issue by davidcostadev** [vercel/hyper#4965]
I'm using the terminal before from popos 20.04, and I was so used to it to use `alt+[number]`, It's was not possible to found the alternative way to use it.

**Comment by tukusejssirs** [comment]
I second this. This should be the default behaviour on Linux. So it is in Gnome Terminal, `xfce4-terminal`, Firefox and other apps.

Note that the default shortcut for switching tabs on MS Windows is Ctrl+[0-9], but on Linux it is Alt+[0-9].

Anyway, how can I change this on `keymaps`? Where can I find a list of commands?

**Comment by LabhanshAgrawal** [comment]
Thanks @tukusejssirs 
Closing as answered

**Comment by tukusejssirs** [comment]
You’re welcome. However, could you update the defaults for Linux please?
