### ISSUE TITLE
Hyper doesn't start on Win 10

### ISSUE THREAD

**Issue by baermathias** [vercel/hyper#4969]
I restarted my computer and Hyper doesn't start. Supposedly it runs in the background? 

<img width="426" alt="Unbenannt" src="https://user-images.githubusercontent.com/45003352/96225339-39d70700-0f91-11eb-9f4c-081af743e66e.PNG">

**Comment by KarenEfereyan** [comment]
I have this same exact issue.

**Comment by fransiscusrolandamalau** [comment]
same problem bro

**Comment by JustinStark87** [comment]
has anyone found the solution

**Comment by LabhanshAgrawal** [comment]
can you run `hyper -v` from cmd and report the output?

**Comment by LabhanshAgrawal** [comment]
duplicate #4035
