### ISSUE TITLE
nodemon installing issue via bash command line

### ISSUE THREAD

**Issue by Meerkhani** [vercel/hyper#4985]
Facing this Issue While Installing nodemon

$ npm install -g nodemon
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\nodemon\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...--END PGP SIGNATURE--'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Usama Khan\AppData\Roaming\npm-cache\_logs\2020-10-22T19_17_28_664Z-debug.log

**Comment by LabhanshAgrawal** [comment]
Not related to hyper
