### ISSUE TITLE
Alt triggers menu dropdown in plasma

### ISSUE THREAD

**Issue by nyc-tinker** [vercel/hyper#4986]
Hitting the alt key in Hyper in KDE plasma triggers the menu dropdown in the top left corner.  I can't get rid of this action via .hyper.js config altIsMeta:

```
modifierKey{
altIsMeta: true
}
```

This behavior makes meta key unusable in terminal emacs (emacs -nw).  Any way to modify this / remove this behavior?  Seems this is also the default behavior in windows (win10).

**Comment by cherusker** [comment]
Just tried Hyper on Window as I'm trying to find a x-platform alternative for iterm2 and cmd but ran into the issue of not being able to use `Alt+F` in emacs; this would open the File menu on Window for me

**Comment by LabhanshAgrawal** [comment]
The default keymap for the menu has been changed to `alt+f`
You may set some other keymap for this using `window:hamburgerMenu`
