### ISSUE TITLE
Crashed when I want to close it and won't show installed themes

### ISSUE THREAD

**Issue by JuanLaparra** [vercel/hyper#4993]
When I close it, the window becomes unresponsive. With themes, I'm able to install them, but none will show no matter how many times I reload the page. I thought uninstalling the program would work, but the issue still continues.

**Comment by WickedWizard3588** [comment]
Same here with me, neither of the Plugins and Themes work.....

Windows 10 64Bit Home

Multiple restarts and reinstallations have been done....

**Comment by LabhanshAgrawal** [comment]
try with v3.1.3
the issue of crash on closing has been fixed https://github.com/vercel/hyper/pull/3781
you can open a new issue (or look for existing issues) if the plugin problem is still there in the latest release
