### ISSUE TITLE
Emoji breaks rendering

### ISSUE THREAD

**Issue by Renha** [vercel/hyper#4997]
I've typed an emoji, and next symbol is rendered on top of the right half of it. Looks like symbol width is ignored for some reason.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/3139759/97678449-dbd41480-1aa4-11eb-9c75-b4ffc64b9eaf.png">
btw: what does % symbol on launch mean? I've just launched the freshly installed app and it's already there. I didn't type it in.

**Comment by Renha** [comment]
Wow, the issue is even deeper: after the shown state I've pressed backspace until it stops to type actual command, and here's what I've got:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/3139759/97679153-f35fcd00-1aa5-11eb-9a14-a3e41810bbbd.png">

**Comment by Renha** [comment]
Oh, it looks like last year release according to copyright notice...
<img width="243" alt="image" src="https://user-images.githubusercontent.com/3139759/97679656-99133c00-1aa6-11eb-9add-e22f489daecd.png">

**Comment by LabhanshAgrawal** [comment]
Unicode support has greatly improved in canary branch, please the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts)
