### ISSUE TITLE
exit code 127 on yarn run

### ISSUE THREAD

**Issue by ChuckNorrison** [vercel/hyper#5001]
I want to build from source, after installing yarn i try to build this app.

> $ yarn run app
> yarn run v1.22.5
> $ electron target
> /bin/sh: 1: electron: not found
> error Command failed with exit code 127.

or this one

> $ yarn run dist
> yarn run v1.22.5
> $ yarn run build && cross-env BABEL_ENV=production babel target/renderer/bundle.js --out-file target/renderer/bundle.js --no-comments --minified && electron-builder
> $ cross-env NODE_ENV=production webpack && tsc -b -v
> /bin/sh: 1: cross-env: not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command f

**Comment by LabhanshAgrawal** [comment]
you need to first run `yarn` to install the dependencies

**Comment by ChuckNorrison** [comment]
Thanks i was not familar with yarn, works for me :+1:

**Comment by kirtirajsinh** [comment]
> you need to first run `yarn` to install the dependencies

It isn't working for me. I tried Everything. Deleted Node_modules and lock files, installed again then ran `yarn start` it is not working. showing "error Command failed with exit code 127" it will be really helpful if you can help with this. I'm not able to concentrate on learning React instead the Error is consuming my time.
