### ISSUE TITLE
Window Opacity?

### ISSUE THREAD

**Issue by angelhdz** [vercel/hyper#5023]
I tried some solutions I read in the Issues. None worked.

In the developers tools, in the console, I get this error: 
**bundle.js:1 WebGL Renderer has been disabled since it does not support transparent backgrounds yet. Falling back to canvas-based rendering.**

Is opacity possible on Windows 10 or not?

**Comment by angelhdz** [comment]
It's called "Hyper" but something expected, very basic as changing the window opacity, has been an odyssey.  I tried adding opacity: '0.5' as a property of the module exports literal object. Tried the css: "" property string. Tried the env: {} property. Tried the plugin hyper-opacity. Added it in the plugins array. Restarted Hyper. Nothing.

**Comment by angelhdz** [comment]
### Update

Now the plugin hyper-opacity is working. But I can't figure out where to change the opacity value... please help? Thank you.

**Comment by gaojr** [comment]
![image](https://user-images.githubusercontent.com/18600387/99233224-eb39b880-282d-11eb-83b8-8a79cf11fec6.png)

> ### Update
> Now the plugin hyper-opacity is working. But I can't figure out where to change the opacity value... please help? Thank you.
> 
> ![image](https://user-images.githubusercontent.com/10191085/98417770-efa8e900-2057-11eb-8c53-e09adbd8c0c8.png)

**Comment by angelhdz** [comment]
> ![image](https://user-images.githubusercontent.com/18600387/99233224-eb39b880-282d-11eb-83b8-8a79cf11fec6.png)
> 
> > ### Update
> > Now the plugin hyper-opacity is working. But I can't figure out where to change the opacity value... please help? Thank you.
> > ![image](https://user-images.githubusercontent.com/10191085/98417770-efa8e900-2057-11eb-8c53-e09adbd8c0c8.png)

Wow. I appreciate your time and help a lot. Stay safe!
