### ISSUE TITLE
Zoom-in shortcut didn't work

### ISSUE THREAD

**Issue by sekti92** [vercel/hyper#5024]
Hello, I was trying to Zoom in using (Ctrl+=) but seems didn't work. 
So, I have to go to `Menu > Edit > Zoom-in` to zoom in.
Anyone have the same issue? How to fix this?

**Comment by LabhanshAgrawal** [comment]
doesn't seem to be an issue in canary
please try the latest build from [ci](https://github.com/vercel/hyper/actions/runs/527838058#artifacts) and reopen the issue if you face this problem with the new build
