### ISSUE TITLE
Great lag on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by Lekesoldat** [vercel/hyper#5052]
Apple released its new macOS yesterday, Big Sur. Everything runs smoothly; however, Hyper seems to cause major lag on my system. I've performed a clean install of both the OS and Hyper.

The lag is most apparent while swapping between windows and showing all active windows. 

> plugins: ["hypercwd", "hyperline", "verminal"]
> Running powerlevel10k
> Hyper version 3.0.2

Any ideas?

**Comment by Stanzilla** [comment]
Try without the plugins

**Comment by Lekesoldat** [comment]
> Try without the plugins

Did some more debugging now. Seems like Verminal causes the issue. Will write an issue there.

**Comment by Lyrillind** [comment]
I didn't use verminal, and still have great lag.

**Comment by Kelhen** [comment]
I also have lag when hyper is open.
After removing my theme the lag is gone

**Comment by designedbyclu** [comment]
Have the same issue as well, but i found after disable the plugin. it's work well.
