### ISSUE TITLE
Kicked out - JS error

### ISSUE THREAD

**Issue by knettwerk** [vercel/hyper#5111]
Using Hyper v3.0.2 as my main windows terminal for myself and I class I teach. Do not want to use main Windows terminal but every time I need to add new tab or split window horizontally, I get a JS error message. My students are getting same error. 

Any way to fix this or no?

Thanks
![2020-11-30_13-46-04](https://user-images.githubusercontent.com/4305746/100690654-9c6f4100-334c-11eb-880c-e6a543621e5b.png)

**Comment by phillipkregg** [comment]
Same error here as well
