### ISSUE TITLE
[Question] M1 Mac & Rosetta

### ISSUE THREAD

**Issue by segersniels** [vercel/hyper#5115]
Has there been any progress made on creating an ARM compatible build for the new M1 Macs so everything isn't executed through Rosetta? 

Sorry if this has been discussed elsewhere before.

**Comment by Stanzilla** [comment]
https://github.com/vercel/hyper/runs/1561963547 has an arm64 artifact, can you try it?

**Comment by segersniels** [comment]
> https://github.com/vercel/hyper/runs/1561963547 has an arm64 artifact, can you try it?

I'm getting:
> “Hyper” is damaged and can’t be opened. You should move it to the Bin.

**Comment by andrewnorell** [comment]
@Stanzilla I got the same issue as @segersniels when attempting to run the arm64 artifact

**Comment by Stanzilla** [comment]
Yeah I think I know what it is, will be fixed soonish

**Comment by shinriyo** [comment]
I am looking for M1 native support

**Comment by mindesik** [comment]
Any news?

**Comment by Stanzilla** [comment]
Still have to fix the CI to properly upload the artifact

**Comment by Stanzilla** [comment]
Try https://github.com/vercel/hyper/suites/1759175736/artifacts/33489701

**Comment by xcity** [comment]
I tried this new build, it shows file is damaged, cannot open.

**Comment by Qetesh** [comment]
> Try https://github.com/vercel/hyper/suites/1759175736/artifacts/33489701

I tried "sudo xattr -rd com.apple.quarantine /Applications/Hyper.app",and it shows
```
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
at createNodePtyError (/Applications/Hyper.app/Contents/Resources/app.asar/session.js:31:34)
at Object.<anonymous> (/Applications/Hyper.app/Contents/Resources/app.asar/session.js:38:11)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Function._load (/Applications/Hyper.app/Contents/Resources/app.asar/plugins.js:94:37)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by mindesik** [comment]
Still broken

**Comment by segersniels** [comment]
@Stanzilla Anything we can do to assist?

**Comment by Stanzilla** [comment]
@segersniels I mean you can try building it locally and see if that works, I don't have a M1 mac to do that.

**Comment by mindesik** [comment]
Building canary is working on M1, I'm using it right now

**Comment by segersniels** [comment]
> Building canary is working on M1, I'm using it right now

Hmm I'm receiving the same error as reported above building from `canary`. Are you sure you are running the arm64 version?

**Comment by mindesik** [comment]
Yes. I'm also have node and yarn for arm64.

**Comment by mindesik** [comment]
![CleanShot 2021-01-05 at 03 27 20@2x](https://user-images.githubusercontent.com/4484092/103556462-ed52f600-4f05-11eb-9274-2cc3ec42a7d7.png)

**Comment by segersniels** [comment]
Aha, so apparently building using node 14 (which doesn't run natively on m1) causes the above error @Stanzilla. Building using 15 does seem to work now and hyper is running natively.

**Comment by segersniels** [comment]
@mindesik Thanks for clarifying that you were using node 15 👍

**Comment by Stanzilla** [comment]
Updated the CI to node 15, seems like there is still more to do though: https://github.com/vercel/hyper/runs/1645081308

**Comment by mindesik** [comment]
`Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`

I think it must use `MacOSX11.1.sdk`

**Comment by segersniels** [comment]
Exactly. It seems that the `runs-on: macos-latest` is starting the CI under version 10.15.7:

```
Operating System
  Mac OS X
  10.15.7
  19H15
```

Can you see if manually defining `macos-11.0` enforces anything?

**Comment by Stanzilla** [comment]
I just did that, yeah

**Comment by Stanzilla** [comment]
How about this then https://github.com/vercel/hyper/suites/1764441117/artifacts/33639826

**Comment by Qetesh** [comment]
Can run normally👍, very fast

> How about this then https://github.com/vercel/hyper/suites/1764441117/artifacts/33639826

**Comment by segersniels** [comment]
I get even though I was able to build and run it locally:
> “Hyper” is damaged and can’t be opened. You should move it to the Bin.

**Comment by AmyangXYZ** [comment]
It can be built and run natively, but the font is too bold.

**Comment by RocketLL** [comment]
> How about this then https://github.com/vercel/hyper/suites/1764441117/artifacts/33639826

Opening app fails with "damaged and can't be opened", but it opens and runs correctly after `sudo xattr -rd com.apple.quarantine`. What could be causing the warning?

**Comment by mbokman** [comment]
Except for having to do the `sudo xattr -rd com.apple.quarantine` trick on the https://github.com/vercel/hyper/suites/1764441117/artifacts/33639826 artifact, it seems to work very good for me. Any chance on this becoming available as part of the brew hyper-canary cask?

**Comment by sbinlondon** [comment]
Hello fellow M1 Hyper users! 👋 

Chiming in to say, `xattr -rd com.apple.quarantine` also worked for me. I have never used that command before so I didn't know what it was doing or how to use it, so if you're like me here is some more info:

Run the full command `xattr -rd com.apple.quarantine ~/Downloads/Hyper-3.1.0-canary.4-mac-arm64.dmg` (except wherever the dmg path actually is) in your normal M1 Terminal and then double click the dmg afterwards to install.

What the command is doing is removing the ["extended attribute"](https://ss64.com/osx/xattr.html) of `com.apple.quarantine` which you may have run into before when trying to open apps downloaded off the internet, and it says it's from an unrecognised developer and you have to go into system preferences to tick a box and allow it to open, etc etc etc. This is just a way of doing that on the command line. `-d` says to delete the quarantine extended attribute; `-r` is for recursive.

If you get an error like `zsh: command not found: xattr -rd` try typing out the full command above from scratch - I copy pasted the first time and for some reason it didn't work.

**Comment by psyrendust** [comment]
Is there a download link for the latest canary m1 build?

**Comment by LabhanshAgrawal** [comment]
> Is there a download link for the latest canary m1 build?

https://github.com/vercel/hyper/actions/runs/766491280#artifacts

**Comment by psyrendust** [comment]
Thank you! Using `xattr -rd com.apple.quarantine Hyper-3.1.0-canary.4-mac-arm64.dmg` worked with no issues. FYI I've been using this free menubar app [Silicon Info](https://apps.apple.com/us/app/silicon-info/id1542271266?mt=12) to see what architecture an app is using.

**Comment by tonymihut** [comment]
Building from source on node 16 worked for me, tyvm 🚀🚀

**Comment by Ganeshswaminathan1912** [comment]
https://github.com/vercel/hyper/releases/tag/v3.1.2

This has native M1 Hyper. I got this from the notes link in update notification in hyper

<img width="370" alt="Screenshot 2021-08-03 at 8 24 51 PM" src="https://user-images.githubusercontent.com/64898189/128037434-ed23975a-0e14-41c5-a805-6ab059087905.png">
