### ISSUE TITLE
[QUESTION] Move with path

### ISSUE THREAD

**Issue by SmashScharrer** [vercel/hyper#5137]
Hy ^^

I would like to move in my second storage platform (D:\).

With common cmd, i just put this path "D:\xxx".
With Hyper, it's seem not functionnal. 

I put a screen here.

Thanks for your response.

![image](https://user-images.githubusercontent.com/35690812/101777411-bc43f900-3af2-11eb-9888-49ab568a87a9.png)

**Comment by Kayoshi-dev** [comment]
Hello, you just have to type the letter corresponding to the hard drive you want to go to and then add a colon.

In your case :
```
C:\Users>D:

D:\>
```

Hope it helps

**Comment by SmashScharrer** [comment]
Okay thanks
