### ISSUE TITLE
Application freezes when try 'pane close' in WSL session

### ISSUE THREAD

**Issue by hwooo** [vercel/hyper#5174]
1. Open a new tab
2. Type 'bash' to enter WSL session
3. Close the tab (Ctrl+Shift+W)

Then the application freezes and it should be shut down by force.

**Comment by maclermo** [comment]
Same issue here. Can reproduce on Windows 10 build 19042.685, WSL2 and Hyper 3.0.2 with hyper-material-theme plugin installed.

**Comment by LabhanshAgrawal** [comment]
Try once with new build from ci https://github.com/vercel/hyper/actions/runs/499993353#artifacts

**Comment by JoanComasFdz** [comment]
I had the same issue.
Uninstalled Hyper and removed all configuration.
Installed Hyper Setup 3.1.0-canary.4.exe.
Opened 2 panes with CONTROL+D and CONTROL+E.
Closed first with CONTROL+W. No crash
Closed second with CONTROL+W. No crash.
Closed Hyper. No crash.
Opened Hyper.
CONTROL+,
Pasted my config and saved.
CONTRL+SHIFT+F5.
Repeated tests.
No crashes when closing panes.

**Comment by LabhanshAgrawal** [comment]
From @JoanComasFdz 's comment it seems this is fixed in canary.
Closing this for now, reopen if you face this with canary also.
