### ISSUE TITLE
cannot open file when dragged onto dock icon

### ISSUE THREAD

**Issue by KnowsCount** [vercel/hyper#5182]
as stated in the title. 

When one drags a folder onto the default macOS terminal, a terminal would be opened, working in the dragged directory, however, this does not work on hyper and is kinda annoying. 

Does not change the fact that this is a great app tho! Thanks!

**Comment by nils-kt** [comment]
I have the same "problem". Would be great if the function could be added.

**Comment by LabhanshAgrawal** [comment]
Try with new build from ci (https://github.com/vercel/hyper/actions/runs/477722328#artifacts)
Fixed in #4661
