### ISSUE TITLE
Weird  % char on launch

### ISSUE THREAD

**Issue by sebszocinski** [vercel/hyper#5198]
Not a huge issue but just annoying, but i've just setup my new MacBook running Big Sur and Hyper with OhMyZSH and notice this every time I launch a new terminal:

![image](https://user-images.githubusercontent.com/5466694/103326918-64b9fd00-4aa2-11eb-9799-cd1dd1ce0bb3.png)

Any ideas on how to fix / remove this?

**Comment by nickcabral** [comment]
I don't know if this is an ideal fix, but it works for me. A while back I added this to my `.zshrc`:
```
# fix Hyper first line precent sign
unsetopt PROMPT_SP
```

**Comment by sebszocinski** [comment]
Thanks mate, just got back to the machine and opened Hyper and it seems to have fixed itself... weird! but thanks i'll close this and hopefully it helps someone else.
