### ISSUE TITLE
Strange input line in terminal

### ISSUE THREAD

**Issue by Vladikasik** [vercel/hyper#5228]
Probably its simply do not print ~
(I already fixed '%' by adding unsetopt PROMPT_SP in .zshrc)
![image](https://user-images.githubusercontent.com/40665208/104465083-babf9200-55c4-11eb-8682-11366c4170da.png)

**Comment by LabhanshAgrawal** [comment]
You need to use a font with powerline glyphs

**Comment by Vladikasik** [comment]
> You need to use a font with powerline glyphs

Can you send what to enter in the font field in the config? I tried a few times to change the font but it was a failed attempt.

**Comment by LabhanshAgrawal** [comment]
You can get a font from https://www.nerdfonts.com/font-downloads
and add it's name at the beginning in the `fontFamily` field in the config.
Post your config if you're facing any issue

**Comment by Vladikasik** [comment]
Thanx, it helps
