### ISSUE TITLE
Weird % shows at the top of hyperjs but not iterm

### ISSUE THREAD

**Issue by imoby** [vercel/hyper#5230]
For some reason I am getting a weird "%" showing up at the top of my terminal the first time I open it. It doesnt happen on iterm and I've double/triple checked my hyperjs and reinstalled and uninstalled all plugins and I still get this issue:

![image](https://user-images.githubusercontent.com/6380855/104831843-f4f19380-5851-11eb-88eb-7874c2ebbe5c.png)

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/issues/2144#issuecomment-326741620
