### ISSUE TITLE
[Linux] mouse doesn't work in ncurses apps (MC)

### ISSUE THREAD

**Issue by reflog** [vercel/hyper#530]
Mouse clicks work half the time, the other half - random characters are dumped into the console

**Comment by Lupul** [comment]
I have seen the same behavior on [libapps/hterm](https://chromium.googlesource.com/apps/libapps/+/master/hterm)
I did some digging which I posted to the google groups but did not receive any replies.
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-hterm/IZTprebuJ_U
