### ISSUE TITLE
CLI is not usable with AppImage

### ISSUE THREAD

**Issue by LabhanshAgrawal** [vercel/hyper#5307]
As AppImage is mounted in a temp directory on run, we can't create a symlink to the cli
Need to look for alternative way

**Comment by luischoma** [comment]
Hi @LabhanshAgrawal ! Sorry for joining a closed thread but, I didn't want to create a duplicate. Just came here to tell I've experienced this issue today (May 19th). 

I'm running on Ubuntu 20.04 with the AppImage. :(
