### ISSUE TITLE
The hyper app disappeared

### ISSUE THREAD

**Issue by juniobiel** [vercel/hyper#5350]
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
N/A

  - **Is the issue reproducible in vanilla Hyper.app?**
No, it's in Red Hat 8.

## Issue

I installed Hyper in RHEL 8, this was working great, but I erased from my download folder. When I tried install again, the app not appears in anywhere.

What I need to do to recover this app?
Has any way to make Hyper to my default terminal?

In RHEL, I need use .AppImage and to do the installation I type:

`sudo chmod +x hyperfile.AppImage`

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** linux x64 4.18.0-240.15.1.el8_3.x86_64
 - **Electron:** 3.1.3  **LANG:** pt_BR.UTF-8
 - **SHELL:** /usr/bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by juniobiel** [comment]
This occur because I am moving the HyperFile.AppImage to hidden folder.

**Comment by juniobiel** [comment]
I downloaded again and the Hyper icon on Apps Menu appears when the file is on Downloads folder, but if I move it out, disappear.

**Comment by juniobiel** [comment]
I downloaded again and the Hyper icon on Apps Menu appears when the file is on Downloads folder, but if I move it out, disappear.

**Comment by juniobiel** [comment]
I found the problem.
Has a file that make an icon to Hyper in Linux, it was in `~/.local/share/applications/appimagekit-hyper.desktop` this contains a path variable that appoints to `HyperFile.AppImage`. When I've installed the Hyper in my computer, it wrote this path to Downloads folder, I updated this file and now it's working.

**Comment by LabhanshAgrawal** [comment]
That behaviour was caused by appimagekit, not related to hyper.
