### ISSUE TITLE
Hyper appears blurry after disconnecting mac from external display

### ISSUE THREAD

**Issue by warpling** [vercel/hyper#5359]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 11.2.1
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: n/a
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: n/a

## Issue
When switching monitors (ie. unplugging my closed mac from my monitor and then opening my laptop) Hyper appears blurry (like it's rendering at the wrong screen scale) until I resize it. Once resized by any amount the view appears to be redrawn correctly again.

**Comment by LabhanshAgrawal** [comment]
Can you try a build from https://github.com/vercel/hyper/actions/runs/597367682#artifacts and check if it happens with that also.

**Comment by warpling** [comment]
I tested this side by side with the stable build and the canary build you linked to doesn't have this issue!

**Comment by LabhanshAgrawal** [comment]
It's not an issue in canary then.
We can close this.
