### ISSUE TITLE
Hyper window resizing truncates text rather than wrap

### ISSUE THREAD

**Issue by Terrydaktal** [vercel/hyper#5360]
![image](https://user-images.githubusercontent.com/24293492/109334277-6f9dcd80-7858-11eb-9af0-4f448348839a.png)
![image](https://user-images.githubusercontent.com/24293492/109334336-804e4380-7858-11eb-9aa3-4a30cb16f97c.png)
![image](https://user-images.githubusercontent.com/24293492/109334372-893f1500-7858-11eb-8512-2777c1baf0af.png)
Windows 7 SP1

**Comment by LabhanshAgrawal** [comment]
You can try a build from the canary branch (https://github.com/vercel/hyper/actions/runs/597367682#artifacts) if you want
that might work for you (it's got lots of updates since the stable release)
closing this as it's for windows 7
