### ISSUE TITLE
Update to use the M1 chip on MacOS

### ISSUE THREAD

**Issue by Harry-Harrison** [vercel/hyper#5378]
**Describe the solution you'd like**
I believe updating the version of Electron in use will bring support for this, though I've done very little research on the matter so may be entirely wrong.

**Additional context**
I noticed that [VS Code has an Insiders build](https://code.visualstudio.com/updates/v1_53#_apple-silicon-insiders) that uses Electron 11 which brings support for Apple Silicon natively. It would be great if Hyper were also able to tap into that just to aid battery life and performance a little more.

The attached screenshot is of a single Hyper window with no plugins enabled with the initial theme and settings.

![image](https://user-images.githubusercontent.com/140605/109518022-cc3ff900-7aa1-11eb-8523-1583ad8dc566.png)

**Comment by LabhanshAgrawal** [comment]
There's no release yet but there's an arm build you can get from https://github.com/vercel/hyper/actions/runs/611073116#artifacts
refer to #5115 for how to get it running
