### ISSUE TITLE
visual bug, on El Cap 10.11.6

### ISSUE THREAD

**Issue by AIexo** [vercel/hyper#5396]
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** darwin x64 15.6.0
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment]
Any details?
no way to help from just the title

**Comment by AIexo** [comment]
sorry, thought I included a photo. I'll try again.
![Skjermbilde 2021-03-07 kl  17 31 09](https://user-images.githubusercontent.com/7308721/110247326-ff83fb80-7f6b-11eb-8b61-ba1ca2e06f24.png)

**Comment by AIexo** [comment]
![Skjermbilde 2021-03-07 kl  17 39 24](https://user-images.githubusercontent.com/7308721/110247344-14f92580-7f6c-11eb-910d-efbeeb576e1b.png)
I got no clue what's going on. First time user and fairly new to coding in general.

**Comment by LabhanshAgrawal** [comment]
try a build from https://github.com/vercel/hyper/actions/runs/629480636#artifacts

**Comment by LabhanshAgrawal** [comment]
did it work?

**Comment by AIexo** [comment]
is there any step guide on how to make this work? 

I don't have much experience with terminals. If it's too much bother I can look for something else.

**Comment by LabhanshAgrawal** [comment]
You can download the latest build for mac from https://github.com/vercel/hyper/suites/2197698201/artifacts/45355316
open the zip>dmg>drag app to applications and replace the previous one
and then open it and check if it's working

**Comment by AIexo** [comment]
Thanks, that worked =). Seems it can't get past verifying stage on my OS. Any workaround that? have filvault, firewall deactivated and allowed apps from anywhere. Can't open it. Did a reboot too.

**Comment by LabhanshAgrawal** [comment]
usually if you right click and click `open` then it asks you to allow
you're facing this because the build is not signed

**Comment by AIexo** [comment]
Did a reinstall and reboot again. Then got it running. Same result unfortunately
![Skjermbilde 2021-03-07 kl  18 07 09](https://user-images.githubusercontent.com/7308721/110248154-f6952900-7f6f-11eb-8766-73f1a3e1b4ad.png)

**Comment by LabhanshAgrawal** [comment]
Can you check from `Hyper` menu> `About Hyper` and confirm that the version is 3.1.0-canary-4

**Comment by AIexo** [comment]
Silly me opened the 3.0.2 ver again. The older build works! Wouldn
