### ISSUE TITLE
Resizing terminal window smaller is causing errors / crash

### ISSUE THREAD

**Issue by rtreagus** [vercel/hyper#5409]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.15.7 Catalina
- **Hyper.app version**: 3.0.2

## Issue
Resizing my hyper terminal smaller is causing multiple errors and the terminal to crash unless I open a new tab. No plugins installed or styling changes.
Is anyone experiencing the same problem on macs?

<img width="790" alt="Screenshot 2021-03-10 at 19 43 25" src="https://user-images.githubusercontent.com/33158428/110688494-8a1d6280-81d9-11eb-941d-94673759e10c.png">

**Comment by LabhanshAgrawal** [comment]
Try with a build from https://github.com/vercel/hyper/actions/runs/638831261#artifacts

**Comment by rtreagus** [comment]
Perfect thanks very much, all working 👍
