### ISSUE TITLE
How to remove context menu entry from Windows

### ISSUE THREAD

**Issue by brSkinz** [vercel/hyper#5410]
I don't want to have a context menu entry for Hyper. How do I remove it? Already looked at HKEY_CLASSES_ROOT\*\shell and HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers, nothing there. I installed as normal user, without running as admin.

**Comment by LabhanshAgrawal** [comment]
The keys are in
`Software\\Classes\\Directory\\Background\\shell\\Hyper`,
  `Software\\Classes\\Directory\\shell\\Hyper`,
  `Software\\Classes\\Drive\\shell\\Hyper`
in HKCU
An option to remove the context menu entry was added in #5256
there's no release yet, but you can get a new ci build from https://github.com/vercel/hyper/actions/runs/643776183#artifacts
