### ISSUE TITLE
Default zoom in Hyper 

### ISSUE THREAD

**Issue by Mohamab29** [vercel/hyper#5411]
The default zoom in Hyper terminal is at 12px , and I would like to change that to 16px or something else , but can't find any solution for this issue .
What can I do to change the default zoom setting ? 
<br>
![image](https://user-images.githubusercontent.com/45313255/110999532-2df94080-8389-11eb-8b5b-b328b0dace5b.png)

**Comment by LabhanshAgrawal** [comment]
You can change the font size from the config.

**Comment by Mohamab29** [comment]
yeah I changed that and it doesn't seem to work ...

![image](https://user-images.githubusercontent.com/45313255/111023387-76dce380-83e1-11eb-970e-f3840b9d8e75.png)

**Comment by Mohamab29** [comment]
Deleted verminal plugin then it worked fine , also this can help :

https://github.com/vercel/hyper/issues/2831

**Comment by Mohamab29** [comment]
Duplicate of #2831
