### ISSUE TITLE
Installer crash under windows

### ISSUE THREAD

**Issue by chen3feng** [vercel/hyper#5419]
![image](https://user-images.githubusercontent.com/1998410/111855246-b5811980-895e-11eb-9e12-2d3684265c71.png)

System: Windows 7 Ultimate Edition
CPU i7-3770k

**Comment by LabhanshAgrawal** [comment]
Windows 7 is out of support.

**Comment by chen3feng** [comment]
It will be better to add a prerequisite section on the download page?
