### ISSUE TITLE
Select All issue

### ISSUE THREAD

**Issue by amorimcode** [vercel/hyper#5420]
Just added `"editor:selectAll": "ctrl+a"` to my keymaps object. When i tap ctrl+a hyper selects all content including shell text instead line text.

There're a screenshot example.

![image](https://user-images.githubusercontent.com/71152836/111933030-67befb00-8a9d-11eb-855b-e5863c5448e9.png)

Hope you can help me. Thanks!

**Comment by LabhanshAgrawal** [comment]
this is the expected behaviour
