### ISSUE TITLE
The Future of Hyper! 🚀

### ISSUE THREAD

**Issue by leerob** [vercel/hyper#5435]
Hey everyone! I want to give an update here as there hasn't been a Hyper release in awhile. 

First off, _thank you_ to everyone who continues to use, support, and love Hyper. This project wouldn't exist without you! We know you've been asking for new releases (including things like support for M1 Macs, new themes, security fixes, and more) and we have been listening.

We're in the process of removing a blocker for releasing new versions and also setting up a sustainable way to fund this project moving forward. We are working with a potential new maintainer and will share more updates on this issue as things develop.

Stay tuned! 🥳

**Comment by ppassmannpriv** [comment]
Can we donate somewhere to help fund? I am a big fan and wouldn't mind contributing a bit that way!

**Comment by nerdalot** [comment]
> Can we donate somewhere to help fund? I am a big fan and wouldn't mind contributing a bit that way!

Same here. Please let us know.

**Comment by Divlo** [comment]
Hyper is a really cool terminal, so thank for that!
It could be cool if we could move terminal tabs like Google Chrome tabs for example.
I see that there is this issue opened since 2016. :confused: 
See: https://github.com/vercel/hyper/issues/911

**Comment by fernandopasik** [comment]
> We're in the process of removing a blocker for releasing new versions

Is there a link to a particular issue for the blocker that we can subscribe?

**Comment by skm7463** [comment]
I agree with above comments. Anything we can do to help? 

I've been working on a new plugin for hyper for some time now to implement command line options and lot of automation options which I think hyper could really benefit from. 

Testing with 3.0.2 and Canary.4 and while Canary.4 fixes some issues it still has a few (new ones too).

Would love to get a new Canary version to test!?

**Comment by effolkronium** [comment]
Any good alternatives to Hyper that are not dead?

**Comment by ivanreese** [comment]
Looks like things are just now trending in a positive direction: https://github.com/vercel/hyper/issues/4229#issuecomment-853558234

**Comment by leerob** [comment]
**Update:** we have finally got a new canary release cut after getting new certificates issued!

https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.5

Please try it out and provide feedback 😄

**Comment by leerob** [comment]
Closing this as the canary release is cut, discussions have been opened, and we're on the right path!

Feel free to leave any further feedback in discussions 😄 

https://github.com/vercel/hyper/discussions/5646
