### ISSUE TITLE
Path writing encoding issues

### ISSUE THREAD

**Issue by NoahELE** [vercel/hyper#5436]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  win10 20H2
- **Hyper.app version**:  stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hyper seems to have a problem with writing path containg non ascii characters. 
My path contains Chinese chracters, when I start hyper, it tries to add its path. But there seems to be a problem with encoding, as it messes up with my other paths. Like this:
Before:
![Snipaste_2021-03-26_11-17-12](https://user-images.githubusercontent.com/49080986/112575924-38f1ad80-8e2c-11eb-8dd2-8be1331d944a.png)
After:
![Snipaste_2021-03-26_11-17-53](https://user-images.githubusercontent.com/49080986/112575927-3abb7100-8e2c-11eb-8ae4-347e908c9ff9.png)

**Comment by LabhanshAgrawal** [comment]
Fixed in #4261 
ref #4190
you can try using a new ci build from [here](https://github.com/vercel/hyper/actions/runs/675890687#artifacts)
