### ISSUE TITLE
Is it possible to disable opening URL in browser?

### ISSUE THREAD

**Issue by sunnz** [vercel/hyper#5440]
Just started using hyper on macOS and found that when I click on a URL it opens up a browser.

How can I configure hyper not to do that and just do nothing?

**Comment by LabhanshAgrawal** [comment]
Use a new build from https://github.com/vercel/hyper/actions/runs/675890687#artifacts
and set `webLinksActivationKey: 'meta'` in the config (you can open it using `cmd+,`)
After this the links won't open unless you `cmd+click` on them.

**Comment by chriskim06** [comment]
is this setting going to be added to the stable channel?
