### ISSUE TITLE
how to disable hyperlinks ??

### ISSUE THREAD

**Issue by dirtbag** [vercel/hyper#5471]
Not sure if this is a feature or not, but I cant seem to find it.. I want to be able to disable the automatic hyperlinking of URLs
in hyper.. 

for example, if I cat a text file that contains the following text:

https://netboot.xyz/   

If I hover over that text, it will set up a hyperlink and open up my browser if I click it.. I want to disable this behavior somehow.

-db

**Comment by dirtbag** [comment]
so I found this https://github.com/vercel/hyper/pull/4543 which supposedly fixes it, but when I add 
    webLinksActivationKey: 'ctrl',
in my ~/.hyper.js

it doesnt seem to work.

-db

**Comment by LabhanshAgrawal** [comment]
You need to use a new build which has this pr included
you can try it from https://github.com/vercel/hyper/actions/runs/711727346#artifacts

**Comment by graylog23** [comment]
I have no clue what to do. I just my stuff to work properly. I swear I’m being watched. Crazy stuff has been happening. It’s like google appeRed out of nowhere and things got strange. Then last night YouTube took control of everything. I couldn’t exit it. But I did something. I got lucky is all I did


Sent from Yahoo Mail for iPhone


On Monday, April 5, 2021, 10:31 PM, Labhansh Agrawal ***@***.***> wrote:




You need to use a new build which has this pr included
you can try it from https://github.com/vercel/hyper/actions/runs/711727346#artifacts

**Comment by dirtbag** [comment]
> You need to use a new build which has this pr included
> you can try it from https://github.com/vercel/hyper/actions/runs/711727346#artifacts

THANKS!! that actually worked... but now whenever I open up a terminal I get a message after about 10 seconds saying 
"version 3.0.2 ready. Improve migration experience to Hyper 3(nodes). Download."

How can I disable that? ;)

-db

**Comment by LabhanshAgrawal** [comment]
You can set `updateChannel: 'canary'`

**Comment by dirtbag** [comment]
awesome! thanks!
