### ISSUE TITLE
App icon is larger than it should be according to specifications in macOS

### ISSUE THREAD

**Issue by rakleed** [vercel/hyper#5517]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 11.2.3
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/rakleed/78d63364363301f4da8b107984813d84
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
The app icon in the Dock is larger than it should be according to the specifications in macOS - https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

<details>
<summary>Screenshot</summary>

<img width="301" alt="Снимок экрана 2021-04-22 в 13 18 14" src="https://user-images.githubusercontent.com/19418601/115700053-f8277e80-a36e-11eb-806b-edaaa07df37c.png">
</details>

**Comment by LabhanshAgrawal** [comment]
Fixed in #5412 
You can get a new build from https://github.com/vercel/hyper/actions/runs/766491280#artifacts
