### ISSUE TITLE
hyper won't start when installed via nixos

### ISSUE THREAD

**Issue by schlichtanders** [vercel/hyper#5519]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version (not relevant here)
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- nixos 20.09.3786.a7ff7a57c96 (Nightingale) with kde plasma
- no way to check, I get `[1]    5950 segmentation fault (core dumped)  hyper --version`
- no .hyper.js
- no info from devtools, as hyper segfaults
- **The issue is reproducible in vanilla Hyper.app**. You need to setup nixos and configure hyper by adding to your /etc/nixos/configuration.nix file `environment.systemPackages = with pkgs; [ hyper ]`

## Issue
When executing hyper via commandline, I get the following error print:
```
[1]    5968 segmentation fault (core dumped)  hyper
```

when starting hyper as an application, it reports
```
Could not find the program '/opt/Hyper/hyper'
```
![Screenshot_20210423_075947](https://user-images.githubusercontent.com/4255480/115827051-0ecfe300-a40c-11eb-8aad-b5388a52847e.png)

**Comment by LabhanshAgrawal** [comment]
Can you try and install using deb file from https://github.com/vercel/hyper/actions/runs/766491280#artifacts 
The nix package is not actually maintained by us directly so can't say much on that.

**Comment by LabhanshAgrawal** [comment]
Or the AppImage if possible

**Comment by RyzeNGrind** [comment]
I just tried to run the nixpkgs hyper pkg and im receiving lots of errors when inspecting the logs upon opening with terminal. 

Is there any plans to support hyper via nixpkgs officially?
