### ISSUE TITLE
Window Controls don't use native system window controls

### ISSUE THREAD

**Issue by alkaris2** [vercel/hyper#5536]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro Linux - 5.10.30-1-MANJARO
- **Hyper.app version**: 3.0.2
- **Link of  .hyper.js config**: [hyper.js config GIST](https://gist.github.com/alkaris2/03a9817392bf3826d2415fe59291b93b)
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Hyper doesn't appear to use native system window controls when set in the config of hyper.js, instead it insists on using big blocky Windows 10 theme window controls which looks really out of place.

![image](https://user-images.githubusercontent.com/73155407/116381169-cec98f80-a853-11eb-90f1-324606a4c217.png)

On left Hyper's window controls, and on right my systems native window controls with Gnome Terminal.

and I can't seem to find any option for resizing the window controls, because they're too big and blocky, unless I'm supposed to create and customize a theme. Also Hyper seems to auto-select a font from the Fallback list, instead of what I had chosen in the config for `uiFontFamily` which is the Fira Code font, but Hyper insists on using Menlo, and as you can see can't render certain unicode characters properly like Gnome Terminal. I really do like this terminal emulator, but there are things are off-putting for me, and these are just some of the few things.

How do you even resize the title bar, or is that also part of the theme creation to be done in CSS?

**Comment by LabhanshAgrawal** [comment]
put `"Fira Code"` at the beginning of `fontFamily`
`uiFontFamily` is for title bar etc.

You will have to use some plugin/theme/css for title bar e.g. `hyper-mac-controls` etc.
