### ISSUE TITLE
Virtual Env name not showing up in the same line as desktop name/path.

### ISSUE THREAD

**Issue by darshannx** [vercel/hyper#5537]
I can't seem the get the virtual env name to show up in the same line as the desktop name. Could someone suggest the setting I need to be looking at?

Appreciate the help!

![image](https://user-images.githubusercontent.com/52811550/116812422-a6c08180-ab1c-11eb-81b2-1121d02a7078.png)

**Comment by LabhanshAgrawal** [comment]
what's the behavior in other terminals? for eg. vscode's terminal

**Comment by LabhanshAgrawal** [comment]
Nothing to do with hyper. This is the default behaviour of git bash.
