### ISSUE TITLE
Hyper is not responding

### ISSUE THREAD

**Issue by SulthanNK** [vercel/hyper#5546]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Version: 20H2 Name: Windows 10 Home
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Hyper config file](https://gist.github.com/SulthanNK/e14f4c3cd5c3ceb2348a3e4ca0cd9b22)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Haven't tested

## Issue

I'm using hyper past one year no issues occurred and run smoothly while working. 

But, for the past week, the hyper terminal suddenly crashed in the middle of my work and even its idle suddenly is loading and shows "Hyper is not responding" and it became unclickable.

It also occurs when I try to close the hyper terminal using the close button in the hyper window, it became unclickable and not responding. So every time, I need to end the program and start again everything where I left.

For now, It crashing frequently after opened in a few minutes when it is in an idle state.

I also added the picture of it for better understanding below
 
![Reference](https://user-images.githubusercontent.com/32130871/117107808-d29f6980-ad9f-11eb-81ab-df3a8bb3cab9.png)

**Comment by SulthanNK** [comment]
Can I get any response to this issue? Because while working on projects, it's a huge headache for those people like me when the terminal app goes unresponsive. 🤧🥺

**Comment by LabhanshAgrawal** [comment]
Have you tried installing the newer version?

**Comment by SulthanNK** [comment]
I currently have version 3.0.2

**Comment by LabhanshAgrawal** [comment]
The latest version is 3.1.3

**Comment by LabhanshAgrawal** [comment]
Anyways this has been fixed in #3781 and already in release
