### ISSUE TITLE
My plugin requires dynamic theme at run-time

### ISSUE THREAD

**Issue by ng-hai** [vercel/hyper#5551]
**Is your feature request related to a problem? Please describe.**
I'm writing a plugin that could change Hyper theme dynamically and automatically based on some criteria.
But those themes are not belong to my dependencies, so they need to be preinstalled when Hyper is reloaded or trigged updating plugins.

**Describe the solution you'd like**
I have tried to add a `preinstall` npm scripts to read the config and inject those dependencies name & version into my own plugin `package.json`. Similar to [this method](https://github.com/jamo/hyperambient/blob/master/preinstall.js), but it seems that Hyper ignored that scripts.

**Describe alternatives you've considered**
Maybe allow some ways for `localPlugins` using npm scripts.

**Additional context**
I'm using latest `canary` branch to developing & testing my plugin.

**Comment by ng-hai** [comment]
Sorry for disturbing you @jamo, I used some of your code from `hyperambient` and got stuck at `preinstall` scripts. Hope you can give an advice.

**Comment by jamo** [comment]
@ng-hai no worries, the underlying libraries to access the light sensor may not work properly in more recent macOS versions. 

I'm not sure but I believe it uses `npm` to install plugins, so you can try `npm install PLUGIN` to mimic the process.

**Comment by ng-hai** [comment]
Definitely `yarn-standalone.js` issue. I have successfully injected dependency on `preinstall`, but Hyper did not install that package to cache folder :(
<img width="624" alt="image" src="https://user-images.githubusercontent.com/19520278/117570099-250bbd80-b0f3-11eb-9ca5-51d9155f4207.png">

**Comment by LabhanshAgrawal** [comment]
What happens if you install them as your dependencies?
you can re-export the fields and decorators based on your requirement.

**Comment by ng-hai** [comment]
Here is the demo of my plugin at development stage. I have installed dependencies manually. But on production, the plugin crashed at `decorateConfig`, which never happened when developing.

https://user-images.githubusercontent.com/19520278/117576036-78d7d000-b10e-11eb-8eba-9e10aad843d4.mov

To use the plugin on production mode, you can edit the `.hyper.js` config

```
plugins: [
  "hyper-prefers-color-scheme@git+https://github.com/ng-hai/hyper-prefers-color-scheme"
]
```

**Comment by LabhanshAgrawal** [comment]
when you say production 
do you mean using release version of hyper? or building from canary branch?

**Comment by ng-hai** [comment]
Yes, the release version.

**Comment by LabhanshAgrawal** [comment]
that's quite old at this point
try from https://github.com/vercel/hyper/actions/runs/824537347#artifacts

**Comment by LabhanshAgrawal** [comment]
I know ideally it should work on the release as people are using that
but it's so old at this point that I don't really want to dig and debug it
hopefully we'll have a newer release soon.

**Comment by ng-hai** [comment]
I have another question, how can I access to Electron module like `nativeTheme` in my plugin? Don't know why it only works at development stage :(

<img width="394" alt="image" src="https://user-images.githubusercontent.com/19520278/118393734-c69e8c00-b66a-11eb-9ae8-a056b5271ecf.png">

**Comment by bet4it** [comment]
I also need it 😅 #3741

**Comment by LabhanshAgrawal** [comment]
> What happens if you install them as your dependencies?
> you can re-export the fields and decorators based on your requirement.

@bet4it

**Comment by bet4it** [comment]
>  you can re-export the fields and decorators based on your requirement.

How to do that?

**Comment by LabhanshAgrawal** [comment]
> > you can re-export the fields and decorators based on your requirement.
> 
> How to do that?

@bet4it 

Eg. you have `decorateTerm` and the plugin you depend on also has it. Then you can pass `Term` first to the dependency decorateTerm function and then modify it based on your need.
Any other exports could be handled similarly or just re-exported as it is if you're not modifying them.

But this might cause an issue if the dependency is already installed.

Ideally we should be able to install the dependencies automatically.
Maybe we could have a `hyper` key in `package.json` and some schema/manifest to handle such scenarios (e.g. extension packs).

**Comment by ng-hai** [comment]
I think this issue won't be possible to deal with for now. Close it since I have successful implemented my dynamic theme plugin.

For detail: https://github.com/ng-hai/hyper-rose-pine-next
