### ISSUE TITLE
Win10 with Git Bash doesn't load Hyper plugins

### ISSUE THREAD

**Issue by ghost** [vercel/hyper#5605]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro x64 version 1903 (OS Build 18362.295)
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/agreeff/648e5b712b9d4b09d7ad8c28c85bd89d
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: **see description below**
- **The issue is reproducible in vanilla Hyper.app**: **N/A, see secription below**

## Issue

I used Hyper through most of the 2.x release days, moved onto a few other terminals over the past 2-odd years, but now I'm coming back to Hyper again.. I am battling to get it to play nicely on my Windows 10 Pro machine (works perfectly on MacOS 10.15.7 and Pop!_OS 20.10.

Everything *appears* to work perfectly, from installation to launch, using Git Bash terminal, I can run and build all my projects as expected, I can even install plugins and themes through the `hyper` CLI command... but it never *loads* said plugins or themes.

**Note:** Not sure how relevant this is, but my Windows config file is actually located in `C:\Users\agreeff\AppData\Roaming\Hyper\.hyper.js`, whereas my MacOS config file sits at `/Users/agreeff/.hyper.js`, with Linux at `/home/agreeff/.hyper.js`. These were all located by using Hyper's `CMD/CTRL + ,` shortcut.

As per my `.hyper.js` file Gist above, I have the following three plugins *installed*:

* `hyper-tabs-enhanced`
* `hyper-cwd`
* `hyper-one-dark`

But when I check DevTools Console, all I see is the following:

```
bundle.js:1 (re)loading renderer plugins
index.html:36 total init time 173.60000000917353
```

> For comparison, the same configuration on my iMac (plus `hyper-quit` for cross-platform consistency) shows the following:
> 
> ```
> 
> bundle.js:1 (re)loading renderer plugins
> bundle.js:1 Plugin hypercwd (1.4.0) loaded.
> bundle.js:1 Plugin hyper-quit (1.0.3) loaded.
> bundle.js:1 Plugin hyper-tabs-enhanced (0.4.2) loaded.
> bundle.js:1 Plugin hyper-one-dark (1.0.0) loaded.
> bundle.js:1 Warning: "hyper-one-dark" plugin uses some deprecated CSS classes (cursor-node).
> /Users/agreeff/.hype…wd/configParse.js:5 hypercwd: no 'config.hypercwd' object found in ~/.hyper.js - see https://github.com/hharnisc/hypercwd#configuration for configuration details
> index.html:36 total init time 215.00000000014552
> ```

Any suggestions on what might be going wrong here? Don't remember seeing behaviour like this previously..

**Comment by LabhanshAgrawal** [comment]
Can you try once with the latest build from https://github.com/vercel/hyper/actions/runs/873475926#artifacts
Delete your current config and let hyper create a new one and then set the changes you need.

**Comment by agreeff** [comment]
Thanks @LabhanshAgrawal, `3.1.0` installs and loads plugins correctly on my Windows box.. 😁 

It seems some plugins will be needing changes soon though.. 🤔  With `hypercwd` installed, trying to create a new tab while my `shell` is anything other than the default fails with "Error: Cannot create process, error code: 267 at new WindowsPtyAgent". Either way, that's not a Hyper core issue, so not terribly relevant here.

---

Do you need any further information from me on this one, or can we close this issue?

**Comment by agreeff** [comment]
note: I'm in the process of ditching this @agreeff account (to be deleted shortly) and moving things over to my personal account.

any follow-up responses from me will come from theh @ZaLiTHkA account instead.
