### ISSUE TITLE
config.json Busy or locked, rename.

### ISSUE THREAD

**Issue by alesanmed** [vercel/hyper#5620]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/alesanmed/6087950398a596f848ca720e391a9ec2
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After opening and closing Hyper several times, it prompts the following error:
![image](https://user-images.githubusercontent.com/9042789/120342330-fd75d280-c2f7-11eb-8193-96e6d1efbbb7.png)

I noticed that in the hyper folder there are several config.json.NUMBER files. Only if I manually delete them and restart the computer, Hyper works again. I checked the task manager and when hyper is closed, there are 4 or 5 hyper processes still running, even killing them manually, deleting the files and opening hyper doesn't work. Only delete and restart.

**Comment by LabhanshAgrawal** [comment]
Can you try once with a new build from ci https://github.com/vercel/hyper/actions/runs/895613525#artifacts
uninstall the current one first and delete the hyper folder in appdata.

**Comment by alesanmed** [comment]
@LabhanshAgrawal Apparently, it worked with the canary. I'll close the issue for now and reopen if the problem comes back, ok?

Thank you very much.
