### ISSUE TITLE
Downgrade warning when installing 3.1.0-canary.5 with dpkg on Ubuntu 21.04

### ISSUE THREAD

**Issue by stu177** [vercel/hyper#5624]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 21.04
- **Hyper.app version**: 3.1.0-canary.5

## Issue

Something I noticed while upgrading to the latest canary version is when installation, dpkg throws a warning thinking it's a downgrade from the last canary version.

![2021-06-03_14-37](https://user-images.githubusercontent.com/7928209/120654217-60db3e00-c479-11eb-83a0-633571880d61.png)

Doesn't seem to affect anything, update installed fine, just thought it was worth noting.

**Comment by LabhanshAgrawal** [comment]
it might be due to some parsing error
it is comparing `5` with `4-4805` (I'm guessing it's a ci build)
closing for now, can reopen if it's causing any issues
