### ISSUE TITLE
Focus is lost when dragging and not restored when command-tabbing

### ISSUE THREAD

**Issue by rauchg** [vercel/hyper#5626]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4 (20F71)
- **Hyper.app version**: Hyper 3.1.0-canary.5 (stable)
- **The issue is reproducible in vanilla Hyper.app**:  Vanilla

## Issue

You can see it in these two gifs:

![CleanShot 2021-06-04 at 12 08 46](https://user-images.githubusercontent.com/13041/120851902-56c74700-c52e-11eb-8a99-0b7fab1667df.gif)
![CleanShot 2021-06-04 at 12 10 21](https://user-images.githubusercontent.com/13041/120851911-5929a100-c52e-11eb-994d-1b0e842a5676.gif)

Related:
- https://github.com/vercel/hyper/issues/3226
- https://github.com/vercel/hyper/issues/3154

**Comment by LabhanshAgrawal** [comment]
@rauchg Can you try out #5678
