### ISSUE TITLE
Being on canary suggests that I upgrade backwards

### ISSUE THREAD

**Issue by rauchg** [vercel/hyper#5627]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4 (20F71)
- **Hyper.app version**: Hyper 3.1.0-canary.5 (stable)

## Issue

![image](https://user-images.githubusercontent.com/13041/120852041-8aa26c80-c52e-11eb-8e2e-d0dcb066f4ef.png)

**Comment by robmorgan** [comment]
@rauchg I'm wondering if we need to set `config.updateChannel` to `canary`. Will test tonight.

**Comment by robmorgan** [comment]
@rauchg okay, from what it seems changing `config.updateChannel` to `canary`, seems to prevent Hyper from downloading 3.0.2 and staying on 3.1.0-canary.5 instead.

**Comment by LabhanshAgrawal** [comment]
Closing this as it's due to the updateChannel config being set to stable.
