### ISSUE TITLE
Hyper 3.1.0-canary.5 says "(stable)" in the "About" menu

### ISSUE THREAD

**Issue by matheuss** [vercel/hyper#5629]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4
- **Hyper.app version**: Hyper 3.1.0-canary.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  N/A, I don't have the file
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

I downloaded `Hyper-3.1.0-canary.5-mac-arm64.dmg` from the [Canary Release](https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.5) page. In the about page, it says `Hyper 3.1.0-canary.5 (stable)`:

![image](https://user-images.githubusercontent.com/4721750/120852713-f39adc00-c550-11eb-8005-b190ba5f7e7b.png)

Should be `(canary)`!

**Comment by giraffesyo** [comment]
Interesting, doesn't show it for me 
![image](https://user-images.githubusercontent.com/10459772/120863481-42944180-c550-11eb-9df8-ab4ce648c32c.png)

**Comment by LabhanshAgrawal** [comment]
Yeah that's the update channel you are on.
