### ISSUE TITLE
Terminal Lagging Way Too Much on 3.1.0-canary.5

### ISSUE THREAD

**Issue by Orimia** [vercel/hyper#5631]
- [x ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur Version 11.4, Intel
- **Hyper.app version**: 3.1.0-canary.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: <https://gist.github.com/Orimia/51e909a00caba06baaedde1534feaa3b>
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: don't know

## Issue
When I enter commands on my hyper terminal, it's lagging **a lot** and then text comes 2 seconds after I type them.
I don't know if it's because of my plugins:

- "hypercwd"
- "hyper-search"
- "hyper-tabs-enhanced"
- "hyper-snazzy"
- "hyperline"

But I believe it's a new bug since 3.1.0-canary.5 came out very recently.

**I appreciate your help!**

**Comment by LabhanshAgrawal** [comment]
Can you try once disabling the plugins, will help rule out if it's due to any plugin.
BTW you don't need hyper-search as search is inbuilt now.

**Comment by Orimia** [comment]
> Can you try once disabling the plugins, will help rule out if it's due to any plugin.
> BTW you don't need hyper-search as search is inbuilt now.

I disabled it and then it worked fine. So I assume it's a problem of the plugins.

**Comment by LabhanshAgrawal** [comment]
you can re-enable plugins one by one and find the culprit.
maybe you can open an issue in it's repo.

**Comment by Orimia** [comment]
It was hyperline
