### ISSUE TITLE
Hyper crashes when trying to close PowerShell session

### ISSUE THREAD

**Issue by loilo** [vercel/hyper#5644]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro Build 19041.985
- **Hyper.app version**: 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/loilo/256ae289e037a7baa94229327f7ef3e8
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: No according output in console
- **The issue is reproducible in vanilla Hyper.app**: yes, apart from the custom `shell`

## Issue
Hyper crashes when I try to close a session with PowerShell open and something has been typed into the prompt.

**Steps for reproduction:**

1. Configure PowerShell as the `shell` for Hyper (see linked configuration Gist).
2. Open the Hyper terminal app.
3. Type something into the PowerShell prompt (almost anything should do, I tried a path like `C:\Users`, a command like `ls` or even a gibberish string like `foobar`).
4. Try to close the session.

On my machine, Hyper immediately becomes unresponsive and the session won't close.

**Further observations:**

- Leaving the PowerShell prompt empty will allow the session to shut down without error. The same applies if text was entered and deleted afterwards.
- The bug occurs independent of the kind of closed chrome (tab, pane, window).
- It does not make a difference whether the closing was attempted through mouse interaction or keyboard shortcut.
- The issue applies equally for using [PowerShell Core](https://github.com/PowerShell/PowerShell).
- I currently have no access to other operating systems, so I could not cross-test this bug for PowerShell Core on macOS/Linux.

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/pull/3781
