### ISSUE TITLE
bash: hyper: command not found

### ISSUE THREAD

**Issue by fyrfli** [vercel/hyper#5679]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows10
- **Hyper.app version**:  3.1.0.Canary.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  [My hyper.js](https://gist.github.com/fyrfli/38ff515f95903c60e585f44720430e82)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I've searched around here and found a few different versions of this problem. I've tried:

* "Install Hyper CLI in command path" and restarted my machine
* Uninstalling hyper and removing all the directories I can find and reinstalling from [here](https://github.com/vercel/hyper/actions/runs/873475926)
* Removing the bash shell and trying to "hyper i" from powershell

I'm not sure what else to do now. I still cannot install plugins of themes from the command line. I get the error `bash: hyper: command not found`

What other information can I provide to help diagnose my issue?

**Comment by LabhanshAgrawal** [comment]
from your error it shows that you ran it in bash not powershell

**Comment by LabhanshAgrawal** [comment]
we currently don't support invoking the cli from wsl

**Comment by fyrfli** [comment]
I see. It has worked in previous versions just fine. Also, as I mentioned, it doesn't work in command shell either.

**Comment by LabhanshAgrawal** [comment]
what error comes when you run it powershell?

**Comment by divincode** [comment]
Hi, @LabhanshAgrawal  sorry to disturb you I want some guidance on how can I start on this project contributing I tried to run this project but it's not building locally and where does the community communicate of this repository, I have a fair bit of idea of the tech stack used.. when I build it locally here is the error can u help, please this is the error -

Error #1 --------------------------------------------------------------------------------
TypeError: fs.rm is not a function
    at createStageDirPath (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/targetUtil.ts:32:12)
    at Object.createStageDir (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/targetUtil.ts:27:29)
    at AppImageTarget.build (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:48:7)
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at /home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/platformPackager.ts:150:7

**Comment by fyrfli** [comment]
> what error comes when you run it powershell?

I tried it again with Powershell and it looks like that last reinstall fixed the issue. Thanks. Closing this now.

**Comment by LabhanshAgrawal** [comment]
> Hi, @LabhanshAgrawal sorry to disturb you I want some guidance on how can I start on this project contributing I tried to run this project but it's not building locally and where does the community communicate of this repository, I have a fair bit of idea of the tech stack used.. when I build it locally here is the error can u help, please this is the error -
> 
> Error #1 --------------------------------------------------------------------------------
> TypeError: fs.rm is not a function
> at createStageDirPath (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/targetUtil.ts:32:12)
> at Object.createStageDir (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/targetUtil.ts:27:29)
> at AppImageTarget.build (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/targets/AppImageTarget.ts:48:7)
> at async Promise.all (index 0)
> at AsyncTaskManager.awaitTasks (/home/vinay/Desktop/Open_source_exploration/hyper/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
> at /home/vinay/Desktop/Open_source_exploration/hyper/node_modules/app-builder-lib/src/platformPackager.ts:150:7

You can ask any questions on https://github.com/vercel/hyper/discussions/categories/q-a
You need to use Node version greater than or equal to 14.14 for this
