### ISSUE TITLE
arm64 builds getting auto updated to x64

### ISSUE THREAD

**Issue by LabhanshAgrawal** [vercel/hyper#5686]
Here's a weird one — I'm on an M1, and the arm64 canary.5 build was auto-updated to the x64 canary.6 build.

Just downloaded the arm64 build of 5 again, let it re-run the update, and confirmed that I was upgraded to the x64 build.

Before:
<img width="358" alt="canary 5" src="https://user-images.githubusercontent.com/2061924/122972492-72fc1e00-d34d-11eb-9fb0-414e228c23d6.png">

After:
<img width="337" alt="canary 6" src="https://user-images.githubusercontent.com/2061924/122972539-7d1e1c80-d34d-11eb-8068-db7bdbeee9d7.png">

Want me to file an issue?

_Originally posted by @ivanreese in https://github.com/vercel/hyper/discussions/5685#discussioncomment-906410_

**Comment by robmorgan** [comment]
I also tested this behaviour this morning and can confirm. We will likely have to take the architecture into account in: https://github.com/vercel/hyper/blob/canary/app/updater.ts.

### Before updating (canary.5)

<img width="1190" alt="Screen Shot 2021-06-23 at 9 44 01 am" src="https://user-images.githubusercontent.com/178939/123040912-1cfba900-d427-11eb-80ce-b5ddd8684a83.png">

### After Updating to canary.6

<img width="910" alt="Screen Shot 2021-06-23 at 9 45 27 am" src="https://user-images.githubusercontent.com/178939/123040915-2127c680-d427-11eb-8489-0902dcc12e4a.png">

**Comment by LabhanshAgrawal** [comment]
Fixed in #5787
