### ISSUE TITLE
Can't open official website hyper.is

### ISSUE THREAD

**Issue by smallnine9** [vercel/hyper#5687]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by LabhanshAgrawal** [comment]
https://downforeveryoneorjustme.com/hyper.is

**Comment by smallnine9** [comment]
> https://downforeveryoneorjustme.com/hyper.is

thanks，this problem is just for me, i will find the reason
