### ISSUE TITLE
Unicode character widths not working

### ISSUE THREAD

**Issue by zakcutner** [vercel/hyper#5691]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Using default settings
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue

Emoji characters are not displayed with the correct width, they are too narrow. This seems to be similar to #1857 which was fixed in a previous version of Hyper, although I am seeing it in the latest version so perhaps it was accidentally reintroduced.

I've uploaded a screenshot from the output of the tool used in https://github.com/vercel/hyper/issues/1857#issuecomment-648802356 which shows that the emojis are not being printed correctly. Sorry if this issue has already been identified, all the previous issues I've found on this are for much older versions of Hyper and have been closed for a while.

<img width="1460" alt="screenshot" src="https://user-images.githubusercontent.com/7256716/123494448-c86b5000-d617-11eb-928e-ec666fab00a3.png">

**Comment by LabhanshAgrawal** [comment]
That was not a previous version
We were not been able to do a stable channel release for a while. The fix is in the canary channel. You can set `updateChannel` to `canary` in your config and get it.

**Comment by zakcutner** [comment]
Ah, thanks for the response!
