### ISSUE TITLE
Can't install hyper plugins 

### ISSUE THREAD

**Issue by guptaushma** [vercel/hyper#5702]
- **OS version and name**: MacOS 11.4 Big Sur
- **Hyper.app version**: 3.0.2
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla 

## Issue
I haven't been able to install any hyper plugins (not even Hyper CLI command). I don't know what the error is, since it never shows any.

**Comment by LabhanshAgrawal** [comment]
you can add the plugins to install in the `plugins` array in the config file.

**Comment by steveblue** [comment]
Same for me. 

Big Sur / 3.0.2 , just installed the app for the first time and added plugins to the plugins Array in .hyper.js, tried installing with `hyper i`. Plugins do not appear to be working.

**Comment by steveblue** [comment]
@LabhanshAgrawal ^^^
