### ISSUE TITLE
Light theme dock icon for Hyper

### ISSUE THREAD

**Issue by saminiemi** [vercel/hyper#5703]
I have used terminal with light theme (hyper-one-light) few months and really started to like it. It was quite a change after 25+ years of light text on dark background :)

Now I wonder would it be possible to have a dock icon for Hyper to adapt light theme feeling? 

<img width="82" alt="Screenshot 2021-06-29 at 14 32 21" src="https://user-images.githubusercontent.com/4686187/123790303-d3a7cf80-d8e6-11eb-94ea-0605f4c40c36.png">

<img width="708" alt="Screenshot 2021-06-29 at 14 36 46" src="https://user-images.githubusercontent.com/4686187/123790865-7a8c6b80-d8e7-11eb-93be-0b13fcb4d8c0.png">

**Comment by LabhanshAgrawal** [comment]
Don't know if it's possible to change it dynamically, however you can change it on your end using 'get info' menu in mac os.
We don't have a light icon.
I'm not familiar with design, but the figma file for the icon is in the repo, you are free to edit and use it.

**Comment by saminiemi** [comment]
Thanks @LabhanshAgrawal for your help!

With figma.com I managed to create light versions of both stable and (upcoming?) canary icons.
<img src="https://user-images.githubusercontent.com/4686187/124090667-b9443200-da5d-11eb-86fd-a36a467360e9.png" width="100">

<img src="https://user-images.githubusercontent.com/4686187/124090674-bba68c00-da5d-11eb-9369-a0b8dad8ea54.png" width="100">

### How to change app icon on Mac OS
Finder --> Applications, select Hyper, "right click" and choose Get Info. Having new icon on clipboard (ie. Ctrl-C on Preview), select small icon upper left corner, and paste with Ctrl-V. Enjoy!

**Comment by steveblue** [comment]
Nova app changes the icon based on user preference in System Preferences, so it seems possible.
