### ISSUE TITLE
how to change title in tab bar to show only active folder

### ISSUE THREAD

**Issue by romadryud** [vercel/hyper#5705]
Hi. For example for the first tab, it be open-source and for the second one it will be home.

![image](https://user-images.githubusercontent.com/19193036/124111024-21e4dc00-da69-11eb-81a1-23b877f31b8a.png)

My shell and args:

```
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
```

**Comment by swarup4741** [comment]
@romadryud if you are using git-bash then you can edit the `git-prompt.sh` file where you can change the `PWD` as per your requirement which will also change the title for hyper

**Comment by romadryud** [comment]
@swarup4741 Hi, I think you misunderstand me,  what you send doesn't affect on tab bar title. Look at the screenshot.

![image](https://user-images.githubusercontent.com/19193036/126901776-948c86b4-e4f0-4f01-881c-48f2092ff21d.png)

**Comment by loctran016** [comment]
I guess @swarup4741 mean [editing C:\Program Files\Git\etc\profile.d\git-prompt.sh](https://alanbarber.com/post/how-to-customize-the-git-for-windows-bash-shell-prompt/)

**Comment by romadryud** [comment]
@loctran016 I editing `C:\Program Files\Git\etc\profile.d\git-prompt.sh` for have ~$ in terminal instead of c/Users/raak. So `C:\Program Files\Git\etc\profile.d\git-prompt.sh` not effect on tab bar title.

**Comment by SkandaSrinivasan** [comment]
@romadryud Not sure if you have figured this out yet, but @swarup4741 is right. 

instead of $PWD , sub in \W and you will get only the folder name which reflects in hyper tab titles.

See below 
`PS1='\[\033]0;$TITLEPREFIX:\W\007\]' # set window title
`
![image](https://user-images.githubusercontent.com/63913769/135330223-609ff590-ed7d-4c2a-84f0-5c0ed347e4c3.png)

@romadryud let me know if this is what you need.

**Comment by romadryud** [comment]
@SkandaSrinivasan Thank you but I already switch to a windows terminal. Unfortunately with Hyper, I have an issue with some js errors which irritate me and I don't have a lot of time to do PR to Hyper.
