### ISSUE TITLE
git bash/powershell doesn't opening via hyper

### ISSUE THREAD

**Issue by and-bulk** [vercel/hyper#5726]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/and-bulk/18d497a59c4690a0232548d2242a9acc
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

![image](https://user-images.githubusercontent.com/79831859/124987052-7251d000-e04d-11eb-9047-c52e6539dc9a.png)

- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`
## Issue

My git bash path - `E:\apps\Git\git-bash.exe`
I trying to open Hyper, but get this.
`upd.` get some error with `shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',`

![image](https://user-images.githubusercontent.com/79831859/124987554-0de34080-e04e-11eb-95f8-899748a2b2f2.png)

when setting `shellArgs: [],` instead `shellArgs: ['--login'],` I get two terminals.

![image](https://user-images.githubusercontent.com/79831859/124987800-4daa2800-e04e-11eb-8205-49d6ec8576c4.png)

I also want to use commands like `rm, ls` etc, but getting error.

![image](https://user-images.githubusercontent.com/79831859/124988233-cc9f6080-e04e-11eb-971b-f88396fba012.png)

**Comment by swarup4741** [comment]
`shell: 'C:\\Program Files\\Git\\bin\\bash.exe'`
`shellArgs: [],`

This is what I have configured in `.hyper.js` and it works perfectly for me.. 
you can give it a try

**Comment by and-bulk** [comment]
thanks :)
