### ISSUE TITLE
Serious performance issues in v3

### ISSUE THREAD

**Issue by Somebi** [vercel/hyper#5747]
While using `htop` i'm experiencing very high CPU usage.
You can try it youself.
Maybe i can provide some telemetry for you?

**Comment by Somebi** [comment]
On Ubuntu 21.04

**Comment by Somebi** [comment]
Using `3.0.2` atm

**Comment by Somebi** [comment]
Doing `tail` is lagging as hell as well...

**Comment by Somebi** [comment]
Very strange... After closing all tabs, that issue disappeared. This seems to be one time bug. If i'll catch it again, i'll try to identify the source of problem.
But it is related to the data piped through pipes.

**Comment by LabhanshAgrawal** [comment]
thanks for reporting.
closing for now as you said it seems like one time bug, can reopen if it's reproducing.
