### ISSUE TITLE
Hyper not opening and closing properly in Windows

### ISSUE THREAD

**Issue by prabormukherjee** [vercel/hyper#5750]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, 20H2
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [here](https://gist.github.com/prabormukherjee/d0991a9e064e4bdc3347118e70391707)

## Issue

+ Whenever I am trying to open hyper it is opening properly at `/c/Users/myname`, but if I try to open it at specific location using the `open hyper here`, it's still opening in the same directory. i.e. `/c/Users/myname` and not where I wanted it to open.
+ Also whenever I am trying to close the hyper using the `X` button it stops responding. But if I use `exit`, it's working properly. Here is the ss. Also reported here https://github.com/vercel/hyper/issues/5546

![image](https://user-images.githubusercontent.com/57007091/125770359-e43725b5-394f-4630-b448-30f1ace11bf7.png)

**Comment by prabormukherjee** [comment]
@LabhanshAgrawal please check. Thanks

**Comment by LabhanshAgrawal** [comment]
Have you tried installing the newer version?

**Comment by prabormukherjee** [comment]
Yes, it didn't work. I stopped using it :(

**Comment by LabhanshAgrawal** [comment]
which version did you test with?
also, does it happen when you use cmd.exe instead of git bash?

**Comment by prabormukherjee** [comment]
> which version did you test with?  

I think it is 3.0.2 (can't exactly remember, but this is what I wrote while creating the issue.)

> does it happen when you use cmd.exe instead of git bash?  

I don't think so. cmd and git bash both are working fine. I'm currently using git bash as an alternative. Also I don't use cmd much

**Comment by LabhanshAgrawal** [comment]
The newer version is 3.1.3
I meant using cmd in hyper instead of git bash, as your config and screenshot suggests.

**Comment by prabormukherjee** [comment]
Yes, may be that's the new version. But I reported it long time ago. May be that was the version when I reported it.  
Not sure. But I was not using cmd in hyper.

**Comment by LabhanshAgrawal** [comment]
I'd asked

> Have you tried installing the newer version?

You responded

> Yes, it didn't work. I stopped using it as `open hyper here` was also not working. :(

I know you reported it with version 3.0.2, but can you try the new version?
Similar issues have been fixed since that version was released.

**Comment by LabhanshAgrawal** [comment]
Anyways this is a duplicate issue and has already been fixed in #3781 and in release.
Please try the latest version and open a new issue if you face any problems with that.
