### ISSUE TITLE
Hyper reports wrong architecture on Apple Silicone

### ISSUE THREAD

**Issue by Basster** [vercel/hyper#5751]
- [x] I am on the Hyper.app version Hyper 3.1.0-canary.6 (canary)
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4 on Apple M1
- **Hyper.app version**: Hyper 3.1.0-canary.6 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Basster/96568f84342c8d8bec4cfe56fd13f251
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**:  Issue appears as well, when restarting hyper with a fresh .hyper.js

## Issue

Using Hyper on Apple Silicone (`arm64`) `echo $(arch)` reports the wrong architecture!

```shell

# hyper
$ echo $(arch)
i386

# iterm2 || terminal
$ echo $(arch)
arm64
```

Tested with:

* zsh
* bash
* sh

**Comment by LabhanshAgrawal** [comment]
Can you confirm once that you are running the arm build using system monitor.

**Comment by Basster** [comment]
Good catch. I've reinstalled Hyper 3.1.0-canary.6 (canary) from GitHub Releases page and now it reports the correct architecture! Thanks for the hint.
