### ISSUE TITLE
Can't remove "update" reminder

### ISSUE THREAD

**Issue by pkail** [vercel/hyper#5756]
- **OS version and name**: 
- Mint 19.2 64-bit
- **Hyper.app version**: 
- 3.02

I constantly get a "reminder" to install a new version.  I have tried setting
updateChannel: 'canary'

When this is set I get annoying pop-ups for the "canary" version.

When it's set to "stable" I get annoying pop-ups for the "stable" version.

When it's commented out I still get annoying pop-ups for the "stable" version.

I can't update because neither the AppImage nor the deb package for the latest version works.

**Comment by pkail** [comment]
I have also tried to make the pop-up invisible using CSS, but this also has no effect:
css: '.notification_indicator{display:none;}',

**Comment by pkail** [comment]
I have also tried

updateChannel: false,

This also has no effect.

**Comment by LabhanshAgrawal** [comment]
You can restrict access to https://releases.hyper.is/ and https://canary.hyper.is/ using hosts etc. if you want

**Comment by LabhanshAgrawal** [comment]
BTW what happens when you try to install Appimage or deb, I tried on ubuntu 20 and it was good.

**Comment by pkail** [comment]
With the AppImage I get a JavaScript error message saying that the package wasn't properly compiled.  
When I try to install the deb I get a message saying that it's for the wrong platform (even though it's not).

**Comment by LabhanshAgrawal** [comment]
Did you download through the site? or the releases page?

**Comment by pkail** [comment]
https://hyper.is/

**Comment by jnm2377** [comment]
@pkail fwiw, I did:

```
      .notification_indicator { 
        display: none !important;
      }
```

and it worked for me. Not sure if it's bc of the `!important` or the formatting. I wasn't sure how to restrict access to the urls linked in the comment, so just went with this solution.
