### ISSUE TITLE
Weird characters showing since upgrade to 3.1.0

### ISSUE THREAD

**Issue by corneliusroemer** [vercel/hyper#5757]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 20.04
- **Hyper.app version**: 3.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Vanilla
- **The issue is reproducible in vanilla Hyper.app**: Yes 

## Issue

I updated and have some very weird characters appearing.

I use fish shell and fira code nf.

I downgraded to 3.0.2 again and it's fine now.

![image](https://user-images.githubusercontent.com/25161793/125995723-3620f4af-9da6-4304-9eb6-0e21f9edc889.png)

**Comment by corneliusroemer** [comment]
Other people seem to have the same problem: https://github.com/vercel/hyper/discussions/5753#discussioncomment-1014529

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/discussions/5753#discussioncomment-1016775 mentions that removing ligatures plugin solved it.
You've written that you are using vanilla config, can you confirm again?

**Comment by corneliusroemer** [comment]
This is my config, the only change is that I now use "Fira Code NF" as font (which has ligatures). No plugin enabled.

https://gist.github.com/corneliusroemer/9783395f7793aa8b79ea6c08a7dd6380

**Comment by pregnor** [comment]
I experience the same on macOS 11.4 (Big Sur, amd), Hyper 3.1.0, bash shell with Fira Code font (contains ligatures), [.hyper.js](https://gist.github.com/pregnor/72e110dbbf1d0142b1cb4a2b51a99448).

I don't have the font-ligatures plugin, but I do have other plugins installed, although IMO none of those should interfere with the shell display area.

**Comment by LabhanshAgrawal** [comment]
Looks like xterm ligatures plugin is not playing well with webgl renderer.
Can you all try setting 
```js
disableLigatures: true
```
and check if it's fixed.

P.S. If you want to use ligatures, you will have to use canvas renderer by setting `webGLRenderer: false`

**Comment by pregnor** [comment]
For me using either `disableLigatures: true` or `webGLRenderer: false` successfully fixes the issue. 👍 

(Also not sure if it helps with anything, but the messed up text seems to be deterministic. I can reliably issue an `ls -al` command in my home directory and always the same characters are messed up when both ligatures and webGLRenderer are turned on.)

**Comment by LabhanshAgrawal** [comment]
I'll disable webgl and ligatures combination until it's fixed in xterm then.

**Comment by corneliusroemer** [comment]
Great, where/when can I test?

**Comment by LabhanshAgrawal** [comment]
Doing a patch release soon.

**Comment by corneliusroemer** [comment]
Just tested 3.1.1, looks good so far. Will close for now.

**Comment by gerdm** [comment]
Hi, I just downloaded version 3.1.1 and I still seem to have the same problem. Any suggestions?
<img width="252" alt="Screenshot 2021-07-19 at 13 30 59" src="https://user-images.githubusercontent.com/4108759/126160179-d9e6c2e5-4915-4b47-b7b6-b56ff67f1ab1.png">

<img width="440" alt="Screenshot 2021-07-19 at 13 30 47" src="https://user-images.githubusercontent.com/4108759/126160350-04fe093a-5eab-4f98-835d-851ca2624608.png">


I've also tried to set `webGLRenderer: false`, and `disableLigatures: true`

**Comment by corneliusroemer** [comment]
Ok, I reopen because of @gerdm's report. For me, it is fixed though (at least haven't seen any problems yet).

**Comment by LabhanshAgrawal** [comment]
@gerdm The about dialog is showing webgl as the renderer
you need to open a new window after disabling webgl
also you are using a plugin for ligatures which would enable the ligatures addon despite disabling it in the config.

**Comment by gerdm** [comment]
Hi @LabhanshAgrawal,

You're correct, I had a plugin for ligatures that was using ligatures. Removing that plugin made everything work fine.
Thank you!
