### ISSUE TITLE
Cannot remove 'upgrade' pop-up.  Cannot upgrade.

### ISSUE THREAD

**Issue by pkail** [vercel/hyper#5759]
This is being re-opened.  It was incorrectly closed by Labhansh Agrawal from India.
    OS version and name:
    Mint 19.2 64-bit
    Hyper.app version:
    3.02

I constantly get a "reminder" to install a new version. I have tried setting
updateChannel: 'canary'

When this is set I get annoying pop-ups for the "canary" version.

When it's set to "stable" I get annoying pop-ups for the "stable" version.

When it's commented out I still get annoying pop-ups for the "stable" version.

I can't update because neither the AppImage nor the deb package for the latest version works.

I have also tried to make the pop-up invisible using CSS, but this also has no effect:
css: '.notification_indicator{display:none;}',

I have also tried

updateChannel: false,

This also has no effect.

**Comment by LabhanshAgrawal** [comment]
I'd listed the URLs you need to block, if you don't want hyper checking for updates.
There's no preset option/config in 3.0.2 to stop updates. You can try using CSS, or a small local plugin. Even if I were to add such an option, it'd be in a new release, and sadly you'd have to update to that.
You can check #5758 for updates on the deb being built for arm64
You can download deb for x64 directly from https://github.com/vercel/hyper/releases/download/v3.1.0/hyper_3.1.0_amd64.deb

**Comment by pkail** [comment]
It would be good if you could fix this bug: users shouldn't have to modify their host file because popups can't be blocked.
Thanks for posting the correct URL for the deb package. 
I have moved to Kitty, so I won't be installing the new version.  However, thanks for your help.

**Comment by LabhanshAgrawal** [comment]
PRs are always welcome

**Comment by ShikherVerma** [comment]
Oh no, how will Hyper ever recover from pkail leaving... this is a disaster
