### ISSUE TITLE
Theme display issue after 3.1.0 update

### ISSUE THREAD

**Issue by pingshunhuangalex** [vercel/hyper#5762]
- [x ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Catalina 10.15.7
- **Hyper.app version**: 3.1.0
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 
```
  plugins: [
    "hyper-material-theme",
    "hyper-pane",
    "hypercwd",
    "hyper-search",
    "hyper-dnd-tabs",
  ],
```

## Issue

All colours seem to be darker (maybe due to opacity?), power10k chars no longer fit perfectly with each other, also the cursor stops blinking

Before:
![Screen Shot 2021-07-19 at 11 19 14 am](https://user-images.githubusercontent.com/17170199/126089274-9d9e13c5-8646-427c-8937-1849dc548480.png)

After:
![Screen Shot 2021-07-19 at 11 15 40 am](https://user-images.githubusercontent.com/17170199/126089280-87017d25-6a31-43a3-955a-f389577ccc14.png)

**Comment by LabhanshAgrawal** [comment]
These are known issues for webgl renderer currently.
You can disable it using `webGLRenderer: false`
Also you don't need hyper-search plugin anymore as search is built-in now.

**Comment by pingshunhuangalex** [comment]
All other issues are fixed after turning WebGL off, but the colour is still off somehow? Anything else that might cause the issue? Thanks @LabhanshAgrawal

**Comment by LabhanshAgrawal** [comment]
As you'd guessed, it might be because of opacity, which you can play with and check. I think it might be mainly due to rendering differences in new xterm versions.

**Comment by pingshunhuangalex** [comment]
I've made sure everything has an opacity of 1 tho, at least for items I can see in the settings file. Is there anywhere I should look specifically?
