### ISSUE TITLE
Add a setting to disable auto updates

### ISSUE THREAD

**Issue by bevanjkay** [vercel/hyper#5776]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to turn auto-updating off in Hyper's preferences.

**Additional context**
Would allow the user to stay on a particular version of the app if they desire.

**Comment by informeai** [comment]
> **Sua solicitação de recurso está relacionada a um problema? Por favor descreva. **
> Não
> 
> **Descreva a solução que você gostaria**
> A capacidade de desligar a atualização automática nas preferências do Hyper.
> 
> **Contexto adicional**
> Permitiria que o usuário permanecesse em uma versão específica do aplicativo, se desejasse.


I wanted that too, but the way I found it was to fork the repository and comment out the events in the app/update.ts file...
Then I packaged it and uploaded it to my /bin. When I wanted to update I would uncomment and repackage.
Of course an option to not update would help a lot... 😌

**Comment by marcofugaro** [comment]
Yes please.

@informeai do you have a build with autoupdates disabled from your fork? Something [like this](https://github.com/vercel/hyper/releases/tag/3.0.2) so other users can download it as well

**Comment by informeai** [comment]
> Yes please.
> 
> @informeai do you have a build with autoupdates disabled from your fork? Something [like this](https://github.com/vercel/hyper/releases/tag/3.0.2) so other users can download it as well

Yes friend yes i can ☺️
Link: https://github.com/informeai/hyper
it will even help the hyper team to add the option to disable auto update. 👍🏼

**Comment by LabhanshAgrawal** [comment]
Added in #5805 
will be in next release
