### ISSUE TITLE
“Hyper” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by MiKr13** [vercel/hyper#5779]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Big Sur 11.4
- **Hyper.app version**: 3.1.1
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hyper needs to be signed by developers for use in macOS by using Apple ID. Can you please put this into To-Do?

**Comment by LabhanshAgrawal** [comment]
The build is signed.
This is most probably about notarization. We have to look into that. 
You can open it by `right click > open ` for now.

**Comment by ganeshrvel** [comment]
Maybe follow these links to notorize the app for macOS?

https://github.com/ganeshrvel/openmtp#package
https://github.com/ganeshrvel/openmtp/blob/master/internals/scripts/Notarize.js
https://github.com/ganeshrvel/openmtp/blob/master/package.json#L17

**Comment by parthmishra** [comment]
For those of us who can't override in settings (e.g. work computer) Is this something that is intended for fix in a future release or is the expectation to rely on user-override method going forward?

**Comment by parthmishra** [comment]
I was able to get around this by downloading the [3.0.0 release](https://github.com/vercel/hyper/releases/tag/3.0.0), installing, and then updating it to the latest version after the initial launch.

**Comment by oluwabukolatina** [comment]
> For some reason, I can't do the right-click > open override workaround (probably due to this being work computer), but I was able to get around this by downloading the [3.0.0 release](https://github.com/vercel/hyper/releases/tag/3.0.0), installing, and then updating it to the latest version after the initial launch.

downloading this version fixed the issue for me too.

**Comment by Ccode-lang** [comment]
Open the general tab after launching and tell it to open anyway.    This worked for me.

**Comment by trm217** [comment]
I would appreciate it if this could be resolved. I just thought about giving Hyper a try and was greeted with this warning right after installation. Most certainly not how a new user likes to be welcomed to a newly installed application.
