### ISSUE TITLE
Emoji on macOS are broken on 3.1.1

### ISSUE THREAD

**Issue by marcofugaro** [vercel/hyper#5782]
Dude, you just released an unstable version. You should release 3.0.2 again or implement a way to disable autoupdates.

Emojis don't work at all.

https://user-images.githubusercontent.com/7217420/126455519-aded1e3f-70c2-4259-94a9-17441cb09576.mov

**Comment by LabhanshAgrawal** [comment]
Can you test the build from #5785 
https://github.com/vercel/hyper/actions/runs/1059088142

**Comment by marcofugaro** [comment]
The emojis work but the picker is not at the right position:

https://user-images.githubusercontent.com/7217420/126762117-42871ce4-6b6f-4fc0-94d9-4cc882360bb0.mov

How it was before:


https://user-images.githubusercontent.com/7217420/126762372-37b36d45-dfaf-4b8a-b02c-4a3e8073de5e.mov

**Comment by vannaka** [comment]
I'm seeing the same behavior as in the video in the OP. I'm on windows 10 using hyper 3.1.1. The issue appears to only affect any characters with a Unicode value larger than 0xFFFF. Using [this](https://unicode-table.com/en/#FFFF) site, copy the 0xFFFF character and past it into hyper, you'll see it pastes just fine. Then copy 0x10000 and past it into hyper and the cursor will not move at all and no new character shows up. This is true for all values over 0x10000 that I have tested.

**Comment by marcofugaro** [comment]
@LabhanshAgrawal is there a release I can download to test this issue is now fixed?

**Comment by LabhanshAgrawal** [comment]
You can get a canary build from https://nightly.link/vercel/hyper/workflows/nodejs/canary
will release in bit, once I'm done with release notes.

**Comment by LabhanshAgrawal** [comment]
released
