### ISSUE TITLE
Need to disable Auto Upgrade

### ISSUE THREAD

**Issue by Li-Yan** [vercel/hyper#5783]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when Hyper auto updates. The new version 3.1.1 does not support all the plugins. Hyper 3.1.1 is super slow with my plugins (by disable all the plugins, it works well). I tried to install older version, but it auto grade to 3.1.1 after restart. I am tired of it. My am using Macbook. I have to switch to other terminal until the issue is fixed... 

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. I think Hyper shell should not auto upgrade in the background but let the use to choose to upgrade or not.

**Additional context**

**Comment by LabhanshAgrawal** [comment]
Duplicate #5776
