### ISSUE TITLE
A error occurred in the JavaScript process? 

### ISSUE THREAD

**Issue by chatbox9321** [vercel/hyper#5784]
- [ ] Your Hyper.app version is **3.1.1**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

---

- **Hyper version**: undefined "3.1.1"
- **OS ARCH VERSION:** win32 x64 10.0.19043
- **Electron:** 13.1.6  **LANG:** undefined
- **SHELL:** undefined   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff",
    "limeGreen": "#32CD32",
    "lightCoral": "#F08080"
  },
  "shell": "C:\\Program Files\\Git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "cygwin"
  },
  "bell": "SOUND",
  "copyOnSelect": false
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment]
Any details?
The error message or screenshot etc.
