### ISSUE TITLE
Alt-Tab opens unwanted menu on GNOME

### ISSUE THREAD

**Issue by johhnry** [vercel/hyper#5801]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Pop!_OS 21.04 (GNOME 3.38)
- **Hyper.app version**: 3.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/johhnry/03984022f6b53db5417f34a9b4decf1b
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-material-theme (3.0.1) loaded.
bundle.js:1 Plugin hyper-pane (2.1.5) loaded.
index.html:36 total init time 204.90000000037253t
```
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

When pressing Alt-Tab to switch between windows, it opens the Alt menu when pressing Alt but it's unwanted since I can accidentally press on menu items.

![ezgif-4-5fc167415204](https://user-images.githubusercontent.com/35373357/127068496-38be790b-c763-4574-bf7d-2ee2a6e644d7.gif)

Before the update, this behavior was not present, is it normal?

Thanks!

**Comment by Kjeldgaard** [comment]
I'm experiencing the same problem. Was not an issue prior to 3.1.1.

**Comment by ja2142** [comment]
Seems like it's DE independant, also happens to me on KDE.

It's a unfortunate, because I use alt+number to switch between tabs (which is a universal tab switching shortcut across many terminals, web browsers, and probably tons of other stuff).

**Comment by fcFn** [comment]
After updating to 3.1.3 `Alt + .` stopped working. Fixed by putting `"window:hamburgerMenu": ""` into the keymap config.
