### ISSUE TITLE
Can't Copy and Paste Folder Pathname from Finder since Update

### ISSUE THREAD

**Issue by blockmonkey** [vercel/hyper#5802]
-  [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
-  [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- Mac OS Catalina 10.15.7
- Hyper 3.1.1
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A

--

Previously if I wanted to copy a file or folder's pathname to Hyper: 

Click on Folder in Finder > Command + C > In Hyper Command + V 

or

Drag Folder from Finder into Hyper

Since the 3.1.1 Update this is no longer working. If you drag the Folder it opens a blank window of Hyper. 

Appreciate any help with this.

**Comment by LabhanshAgrawal** [comment]
Fixed in #5780 and #5781 
will be included in next patch release.
