### ISSUE TITLE
Drag and Drop Shows Blank terminal over the original terminal. 

### ISSUE THREAD

**Issue by AHES03** [vercel/hyper#5804]
https://user-images.githubusercontent.com/76785777/127739081-ab339497-c1f3-44fc-8f47-c1ea11de2d09.mov

I'm a new user. Hyper(3.1.1 Stable) on MacOS(Big Sur 11.4). When I wanted to drag and drop files to change Directory the pathname is copied but a blank terminal in Hyper opens over the one I was using. Is there a way to disable this

Thanks in Advance

**Comment by LabhanshAgrawal** [comment]
Fixed in #5781 
should be in a release soon.
