### ISSUE TITLE
On Linux versions (deb/rpm), the exported version is still 3.0.2 in cli.js

### ISSUE THREAD

**Issue by FabianGD** [vercel/hyper#5810]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux, OpenSUSE Leap 15.3
- **Hyper.app version**: 3.1.1 (from the release section)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/FabianGD/3bb3bee881c527036cead8a6b765500b
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I am currently updating Hyper in the NixOS/nixpkgs repo, where I noticed that the version reported by Hyper is still 3.0.2 in the cli.js file after extracting the .deb archive. This leads to the problem that upon opening Hyper, I am asked to update to 3.1.1, on which I am already (I think). Could you have a look into the issue? Thanks a lot for the great work, I enjoy working with Hyper for over two years now and still am!

**Comment by LabhanshAgrawal** [comment]
cli.js checks the package json for the version, and that has 3.1.1 

https://github.com/vercel/hyper/blob/2f712e6eb3ab72fc38d74f030fd955214249256b/app/package.json#L5

What does it say when you check the version from `About Hyper` menu.
I don't know about how Nix packages are installed or how they differ from deb/rpm but if you're extracting the contents and not overwriting the package.json maybe, then you'd get wrong version reported.

**Comment by FabianGD** [comment]
I'm super sorry, the mistake was on my side because of caching of an old version of the installer. 🙈 

Thanks for your assistance!

**Comment by LabhanshAgrawal** [comment]
no worries
