### ISSUE TITLE
v3.1.2 downloads v3.1.1 as an update (Apple M1)

### ISSUE THREAD

**Issue by yhuard** [vercel/hyper#5827]
- **OS version and name**: macOS 11.5.1
- **Hyper.app version**:3.1.2

## Issue

Hi!
I've just downloaded and installed v3.1.2, and when I start it, it downloads v3.1.1 and as shown on the screenshot below:

![image](https://user-images.githubusercontent.com/3524389/128031034-8d53bc88-6594-4e10-b0d1-e1bb14438d86.png)

When I restart Hyper, v3.1.1 is running...

Thanks!

**Comment by LabhanshAgrawal** [comment]
That was because 3.1.1 was still cached in the release server.
This was there for 8-9 minutes only, I'm surprised someone downloaded it this quickly.

**Comment by LabhanshAgrawal** [comment]
Restart Hyper, it should update to 3.1.2

**Comment by yhuard** [comment]
It seems that you are right, I've reinstalled 3.1.2 and now it doesn't update to 3.1.1 anymore 👍 Thanks!
