### ISSUE TITLE
Not able to install hyper on Windows due to Windows Defender SmartScreen warning

### ISSUE THREAD

**Issue by Michelvl92** [vercel/hyper#5830]
- **OS version and name**: Windows 10 Enterprise 1909
- **Hyper.app version**: 3.1.2

## Issue
I am not able to install the application v3.1.2 and 3.1.1 due to the Windows Defender SmartScreen warning, and there is no option to "still run the app".

For my current version v3.0.2 I was able to install the terminal, and that works perfectly, but I want to update due to some bugs.

**Comment by LabhanshAgrawal** [comment]
It should update automatically.
If you want to install 3.1.2 directly, you can click `more info` in smart screen and run.

**Comment by Michelvl92** [comment]
@LabhanshAgrawal thank you for your comment. Hyper is not automatically updating since I installed 3.0.2 (I know that there are newer stable versions such as 3.1.0 etc. but it has never updated.

 Installing 3.1.2 directly, by clicking on `more info` in smart screen, does not provide me an option to `run` (maybe my company restrictions in Windows?, but I am power user).

**Comment by decidedlygray** [comment]
I am seeing the same thing as @Michelvl92 when trying to install the latest (`3.1.2`). Screenshot after clicking `More Info`:

![image](https://user-images.githubusercontent.com/11695977/131696029-8009433d-05b7-4071-a1f5-06be1afecb5d.png)

**Comment by decidedlygray** [comment]
Figured it out. This assumes you have local admin access (which you must to install anyway).

To whitelist the app, right-click the installer and go to Properties. At the bottom of the General tab, click Unblock, then OK:

![image](https://user-images.githubusercontent.com/11695977/131696768-b2058bc6-a968-4ad6-9947-2f8d5facb76f.png)

You should be able to run it without a warning now

**Comment by Michelvl92** [comment]
It looks that this is not happening with the latest version (3.1.4).
