### ISSUE TITLE
Window not showing up when `bell` is set to true in .hyper.js file. 'Uncaught TypeError: t.bell.toUpperCase is not a function' in Developer Tools console

### ISSUE THREAD

**Issue by 9tin9tin9** [vercel/hyper#5856]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Big Sur 11.5
- **Hyper.app version**: 3.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/9tin9tin9/45ca8952ea3fc6916fba808dd8a2f54e
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: Error shown in Developer Tools console : Uncaught TypeError: t.bell.toUpperCase is not a function
    at x (bundle.js:formatted:52982)
    at EventEmitter.<anonymous> (bundle.js:formatted:52999)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)
Code around the error:
```
const x = e=>{
            const t = w(w({}, e), {}, {
                bellSound: null
            });
            t.bell && "SOUND" === t.bell.toUpperCase() && t.bellSoundURL ? (0,
            f.getBase64FileData)(t.bellSoundURL).then(e=>{
                const r = e ? "base64," + e : null;
                t.bellSound = r,
                E.dispatch((0,
                m.reloadConfig)(t))
            }
            ) : E.dispatch((0,
            m.reloadConfig)(t))
        }
```
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue

When `bell` is set to true in .hyper.js file and the app is restarted, window does not show up. Non of the shortcut keys are ### working.

**Comment by LabhanshAgrawal** [comment]
The supported values are `'SOUND'` and `false` 

https://github.com/vercel/hyper/blob/e30969a9e6cd35b7fa9961c893eeb9f860fb8070/app/config/config-default.js#L126-L129
