### ISSUE TITLE
Installing Hyper Plugins without CLI

### ISSUE THREAD

**Issue by 5R33CH4** [vercel/hyper#5891]
Is it possible to install hyper plugins without ```NPM```-ing or using Hyper cli ?
like as if they were preinstalled with hyper

**Comment by LabhanshAgrawal** [comment]
Nope
Not possible to bundle plugins with hyper currently.
You may fork and add dependencies to the plugins in the main package.json and the one inside `app/`
then importing them in the `plugins.ts` files in `app/` and `lib/`
And then build.
Might be lot of work though.
