### ISSUE TITLE
Can't be opened on Mac Mini M1 in Parallel Desktop 16.5.1 on Kali 9

### ISSUE THREAD

**Issue by ghost** [vercel/hyper#5892]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 11.5.2, Parallel Desktop 16.5.1, Kali Rolling "2021.2"
- **Hyper.app version**: 3.1.2 arm64
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

After I manually download libappindicator3-1 and libindicator3-7 and install, I finally fix the dependencies and install Hyper.
It did export an application to my panel. However, it just keep bumping on my cursor like indicating me that it is running when I click on it.
After a few seconds, there is no icon bumping and it seems like I did nothing.
Did I miss anything needed? Like Javascript or something else?
This is a whole new os and Hyper is the first application I try to install.

If you need any log or else, please tell me where to get them and I'll report it immediately.

**Comment by LabhanshAgrawal** [comment]
I've opened https://github.com/vercel/hyper/pull/7227 for this
Please try the build from that PR and check if it works for you. (you can find it from the checks section or from the latest comment by github actions bot.)
