### ISSUE TITLE
is it possible to disable  word wrap

### ISSUE THREAD

**Issue by dickens88** [vercel/hyper#5893]
**Is your feature request related to a problem? Please describe.**
some of the scripts will print a table with command line, and if the terminal can't diable word wrap, it will feel very hard to read the message

![image](https://user-images.githubusercontent.com/8390209/131224408-41bef772-6dab-4d90-a2e0-675ac02f72e8.png)

**Describe the solution you'd like**

so is there any configrations that can diable word wrap, if the word too lone it can show horizontal scroll bar instead？

**Describe alternatives you've considered**

**Additional context**

**Comment by LabhanshAgrawal** [comment]
We use xterm.js for the rendering, and there's no inbuilt method to disable word wrap in it (https://github.com/xtermjs/xterm.js/issues/2544).
It's not something which I'm inclined to add to hyper directly. It should be doable inside a plugin. It'd need to put the terminal in a scrollable container and resize the terminal based on the length of text.
