### ISSUE TITLE
Wrong method `console.log()` called on error block in cli/index.ts

### ISSUE THREAD

**Issue by sider-bughunter** [vercel/hyper#5911]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

I have noticed that the `console.log()` method is called on error block in [this line](https://github.com/vercel/hyper/blob/7f01b06456b08e52590a50249f57ac88e6bdc27d/cli/index.ts#L76). To be consistent with other usages such as [this line](https://github.com/vercel/hyper/blob/7f01b06456b08e52590a50249f57ac88e6bdc27d/cli/index.ts#L61), it should be replaced with `console.error()`. (correct me if I am wrong)

```diff
diff --git a/cli/index.ts b/cli/index.ts
index 9e4091e..fe6c463 100644
--- a/cli/index.ts
+++ b/cli/index.ts
@@ -73,7 +73,7 @@ args.command(
     commandPromise = api
       .uninstall(pluginName)
       .then(() => console.log(chalk.green(`${pluginName} uninstalled successfully!`)))
-      .catch((err) => console.log(chalk.red(err)));
+      .catch((err) => console.error(chalk.red(err)));
   },
   ['u', 'rm', 'remove']
 );
```

**Comment by LabhanshAgrawal** [comment]
Fixed
Thanks
