### ISSUE TITLE
Error reading configuration "config" key is missing

### ISSUE THREAD

**Issue by abelbarraza3** [vercel/hyper#5924]
- [X ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.15.7 + macOS Catalina
- **Hyper.app version**: 3.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/abelbarraza3/1416743b5dae266f93cbb11f2a51df3c
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Hello,

I initially installed a theme. I was configuring the theme using the .hyper.js. and I believe that's where I caused the issue. I attempted to un-install hyper and do a new install. That did not work. I attempted to look up a generic .hyper.js file and copy and paste it into my existing file and that did not work. I believe it is a syntax issue or I have grabbed a hyper.js that was not generic. If anyone can point me to a "stock" hyper.js that would be greatly appreciated.

**Comment by paulkoeckdev** [comment]
Not sure if I'm wrong, but isn't there a colon missing at the end of line 142?

**Comment by abelbarraza3** [comment]
@paulkoeckdev I added the comma at the end of line 142. As shown below. That did not work.
`  plugins: ['hyper-star-wars'],`


 I do have a secondary error message:
**_Error loading config: SyntaxError
SyntaxError: Unexpected token ','_**

**Comment by paulkoeckdev** [comment]
Tried to copy your config and saw there are multiple syntax errors. Just fixed the ones my editor showed, but haven't tried to load it.


Here's the updated version:
https://gist.github.com/paulkoeckdev/65e06ebf12cf198a5e7f924073504775

**Comment by abelbarraza3** [comment]
@paulkoeckdev it works for me as well! Thank you very much!
