### ISSUE TITLE
Right click to paste words on windows version

### ISSUE THREAD

**Issue by dickens88** [vercel/hyper#5929]
Dear Team, 
I'm using the latest Hyper windows version, is there any functions can implement that right click the paste the word into Hyper cmd from clipboard? instead of showing a menu.

I also found there is a option `copyOnSelect` that can made selected text will automatically be copied to the clipboard, that's very usful, but i didn't found if there is a option to paste the content when right click the mouse. 

thank you for your work.

**Comment by SkandaSrinivasan** [comment]
![image](https://user-images.githubusercontent.com/63913769/135326310-c04fcc0c-3c7f-4f11-b605-8a9a856b23b8.png)
@dickens88 
This was false by default on a fresh install. Setting this to true will copy selected text to clipboard, and paste from clipboard on right-click.

**Comment by dickens88** [comment]
@SkandaSrinivasan Thank you so much for the answer, it's realy useful for me.
