### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by mbehnasr** [vercel/hyper#5967]
- [x] I am on the [3.0.2](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  20H2 Windows 10 Pro 
- **Hyper.app version**:  3.0.2

## Issue

in Contribute section of `README.md` in 
`1. Install necessary packages:  ` we don't need `yarn global add windows-build-tools` as the [felixrieseberg/windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) said .

**Comment by LabhanshAgrawal** [comment]
Have you tested building without installing `windows-build-tools` package?

**Comment by mbehnasr** [comment]
no I have some error when `yarn run dist`
![errros](https://user-images.githubusercontent.com/45386071/134597073-95f32121-23ac-4191-83b5-4303693dee1f.PNG)
with `windows-build-tools` and without that .

**Comment by mbehnasr** [comment]
I going step of contributing for windows os but for all run scripts e.g `yarn run app` , `yarn run app ' , etc ..  give me above errors
somebody help me :)

**Comment by mbehnasr** [comment]
yes :))))

**Comment by LabhanshAgrawal** [comment]
it's there in app/package.json
if you can, delete all the changes using `git clean -xdf` and then try `yarn && yarn run dist`

**Comment by LabhanshAgrawal** [comment]
not being able to build is different thing, open a new issue if you're still facing it.
can remove windows-build-tools from readme if someone confirms it's not needed for building hyper, closing for now
