### ISSUE TITLE
Hyper Mac (m1) - Open Using Rosetta

### ISSUE THREAD

**Issue by sswales** [vercel/hyper#5968]
**Describe the solution you'd like**
With the new Macbook m1 an option you can select for applications is `Open Using Rosetta` but when I look to enable this on the Hyper app it's not an option (when you right click > get info). The reason this is needed for backwards compatibility is because native extensions/code that aren't optimised for the M1 basically show as unavailable.

(I have tried installed the Intel version of Hyper on my M1 and still no luck)

**Describe alternatives you've considered**
Either this is enabled or I will have to look to swap back to using Iterm2 as it offers this feature.

**Additional context**

Popups side by side: 
<img width="546" alt="Screenshot 2021-09-24 at 09 26 40" src="https://user-images.githubusercontent.com/17008391/134643111-8265ef77-da13-4eff-80d1-4a201da0d0e2.png">

**Comment by LabhanshAgrawal** [comment]
The flag is only relevant for universal binaries, we ship separate ones for m1 and intel
refer [here](https://support.alfasoft.com/hc/en-us/articles/360017160858-How-to-use-Rosetta-and-what-is-it-M1-chip-#:~:text=Intel-only%20binaries%20automatically%20open%20with%20Rosetta%202%2C%20there%20is%20no%20other%20way%20to%20run%20them.%20The%20%22Open%20using%20Rosetta%22%20flag%20is%20only%20relevant%20for%20universal%20binaries%20(which%20contain%20both%20Intel%20and%20ARM%20code)%20to%20force%20them%20to%20open%20with%20Rosetta%20(e.g.%20if%20they%20require%20plugins%20only%20available%20as%20Intel%20binaries).)
