### ISSUE TITLE
File menu flashes on and off when you hold alt key on Windows

### ISSUE THREAD

**Issue by churichard** [vercel/hyper#5969]
- **OS version and name**: Windows 10
- **Hyper.app version**: 3.1.3

## Issue
If you hold down the alt key, the file menu flashes on and off. It's particularly annoying if you use alt+tab a lot because you'll constantly see the file menu popping up when you switch windows.

One solution could be to only open the file menu when the alt key has been released (i.e. onkeyup).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4218237/134727047-ae971f56-bad1-430d-977f-7449da926903.gif)

**Comment by SkandaSrinivasan** [comment]
I am on windows 10 Home 10.0.19043, Hyper version 3.1.3 , pressing and holding the alt key doesn't cause it to flicker like that.
It just brings it up once and it stays there even if the key is pressed down.
Does this happen on a fresh install?
