### ISSUE TITLE
Using OpenSSH client makes a popping noise

### ISSUE THREAD

**Issue by xMdb** [vercel/hyper#5982]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 11 Build 22000.194 (beta channel)
- **Hyper.app version**: 3.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/xMdb/60b63b6fdd2b61a7d0429e890dc174b4
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
While using the OpenSSH client and SSHed into a Linux machine, pressing backspace without anything typed makes a really weird popping sound. I believe it is supposed to be a Windows error sound.

**Comment by bmccord2** [comment]
Same exact situation here

**Comment by LabhanshAgrawal** [comment]
set https://gist.github.com/xMdb/60b63b6fdd2b61a7d0429e890dc174b4#file-hyper-js-L116 to `false`

**Comment by LabhanshAgrawal** [comment]
it's just the terminal bell sound, you can turn it off (see last comment for instructions) easily.
