### ISSUE TITLE
Output text is different to the one displayed in theme image.

### ISSUE THREAD

**Issue by ZeedzDev** [vercel/hyper#5983]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  [Click Here](https://gist.github.com/ZeedzDev/c48dd96946349c9c5de7e470ef50e249)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
 ```
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-material-theme (3.0.1) loaded.
​ total init time 169.80000000001746```
- **The issue is reproducible in vanilla Hyper.app**: <!-- Replace with info if applicable, or `Is Vanilla`. (Vanilla means Hyper.app without any add-ons or extras. Straight out of the box.) --> I just have the material theme added.
```
## Issue

In the [image](https://hyper.is/store/hyper-material-theme) of the material theme it shows that the output is green, but mine is only white--same with all other text. Is there any way to edit the output text?

**Comment by LabhanshAgrawal** [comment]
That green output is just for the installation successful message and on the right side is just some color test
You can check all the colors using this script https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011
You can also try opening an issue in the theme's repo if you think there's still any problem.
