### ISSUE TITLE
Hyper Terminal shows random character while reading file on terminal

### ISSUE THREAD

**Issue by ciscohack** [vercel/hyper#6030]
- **OS version and name**: macoS BigSur 11.6
- **Hyper.app version**:  Hyper 3.1.0 canary 6 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hi Team,

I am seeing random characters on my hyperterm while reading or doing doing anything with log files. you can see the screenshot.these character appear randomly on top of my log files word annoying reading logs.

![image](https://user-images.githubusercontent.com/11479557/137616530-9d24c312-3593-41b2-ba85-f31d6f363820.png)

- **Relevant information from devtools** 
![image](https://user-images.githubusercontent.com/11479557/137616599-caf64f8d-bbab-4168-aef1-b9f4e2393f17.png)

My Hyper Setting
[hyper.js.zip](https://github.com/vercel/hyper/files/7359020/hyper.js.zip)

**Comment by ciscohack** [comment]
As per my understanding of this issue. it's seem hyperterm is not compatible with FiraCode Nerd Font. That is strange most terminal App are very much compatible with FiraCode NF then why Hyperterm  is having issue also ligature is not working or failing

**Comment by BitInByte** [comment]
I think that we might need to wait for a solution for this, I have the same problem with Caskadya Nerd Font.

**Comment by LabhanshAgrawal** [comment]
@ciscohack webgl renderer has known issues with ligatures #5757 
If you want to continue using ligatures then you should use canvas renderer by setting `webGLRenderer` to `false`
webgl has better performance though, so if you don't need ligatures, you should remove the plugin `hyper-font-ligatures`
