### ISSUE TITLE
Auto-update doesn't work despite being enabled in settings

### ISSUE THREAD

**Issue by t-kowalewski** [vercel/hyper#6031]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
Windows 8.1 64bit
- **Hyper.app version**: 
3.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
https://gist.github.com/t-kowalewski/92b7a38a48645e220e81e20e79b1d9ee
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 
yes

## Issue

Hi,
My Hyper doesn't auto-update. All I can see - notification in the right bottom corner saying that version 3.1.4 is available.
Is there any way to fix that without reinstalling? (I don't have any plugins. Also I don't use any third-party firewalls/security suites)

**Comment by LabhanshAgrawal** [comment]
It's still checking for Squirrel, but we've moved from squirrel to nsis in v3.1.0 a122bcdf1b03ff8ddce87ff4c093269f2473820e
Are you on 3.1.2 or 3.0.2?
If you're on 3.0.2 then you'll have to install it manually (just run the new installer) as auto update might not be able to update from squirrel to nsis version (haven't received any reports earlier when we changed the installer though)

**Comment by LabhanshAgrawal** [comment]
Also check for `%LOCALAPPDATA%\hyper-updater` and `installer.exe`
