### ISSUE TITLE
How do I change the brown color in a string?

### ISSUE THREAD

**Issue by mofankk** [vercel/hyper#6084]
Like the brown in this picture

<img width="340" alt="截屏2021-11-04 14 32 47" src="https://user-images.githubusercontent.com/48255243/140268384-30ccd190-3c9f-462d-b475-f6a9e49de0b4.png">

**Comment by LabhanshAgrawal** [comment]
you may change it from the `colors` config option if this is using one of those colors. Or you'll need to configure it in the editor you've shown.
Do note that plugins can overwrite the config option you've set, so check them too.
