### ISSUE TITLE
Intermittently getting font artifacts in tmux

### ISSUE THREAD

**Issue by bradleyfrank** [vercel/hyper#6100]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ProductName: macOS ProductVersion: 12.0.1 BuildVersion: 21A559
- **Hyper.app version**: 3.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/647cbebd27e8a93a6a7faf9c3908300e
)
- **Relevant information from devtools**: n/a?
- **The issue is reproducible in vanilla Hyper.app**: So far, no (issue is intermittent)

## Issue

Sometimes when I clear multi-page output in tmux, it leaves behind font artifacts. It's happened with a couple different fonts, but it's difficult to reliably reproduce. Reloading Hyper or detaching/re-attaching my tmux session resolves the problem. I only use one plugin: https://github.com/Ghosh/hyper-solarized-light

Screenshot: https://nextcloud.francopuccini.casa/s/XXDZMRYsWAPPbSG

**Comment by LabhanshAgrawal** [comment]
Might be happening from ligatures, webgl renderer has some known issues with ligatures.
We've ligatures disabled when using webgl, but I'm guessing it might have something to do with this line
https://github.com/ghosh/hyper-solarized-light/blob/master/index.js#L42

You can use the values for the config from the plugin directly (excluding the line I mentioned) and try
Also set `disableLigatures` to `true` just in case.

**Comment by bradleyfrank** [comment]
Just to close this loop, I switched from SourceCode Pro font to SauceCode Pro font (via Nerd Fonts) and haven't encountered this issue since. I'm satisfied it was a font issue in the end.
