### ISSUE TITLE
Create command to quickly install Themes given Name

### ISSUE THREAD

**Issue by AllanOricil** [vercel/hyper#6102]
**Is your feature request related to a problem? Please describe.**
When I run `hyper -h` I can see there is a command to install plugins, but not one for installing themes. I think it would be good to make this command accepts themes as well or create a new one.

**Describe the solution you'd like**
I think it would be good to make the install command to accept themes, or create a new one just for installing and removing themes.

**Describe alternatives you've considered**
Manual installation

**Additional context**
Type hyper -h and check that the install command description is only for plugins

**Comment by AllanOricil** [comment]
The command exists, but its description is wrong.
![Screenshot 2021-11-13 at 17 12 31](https://user-images.githubusercontent.com/55927613/141657931-2b25edf7-59d8-4216-945a-5f771c990549.png)

**Comment by LabhanshAgrawal** [comment]
Themes are also just plugins, there's no identifier to differentiate them currently.

**Comment by AllanOricil** [comment]
@LabhanshAgrawal what made it confusing is the website. In the website they have two tabs Plugins and Thenes. This made me thing that a theme was something different than a plugin.
