### ISSUE TITLE
Remove right margin

### ISSUE THREAD

**Issue by BitInByte** [vercel/hyper#6111]
Is there any way to remove the right margin that you see on the image?

![Screenshot 2021-11-17 at 19 47 08](https://user-images.githubusercontent.com/64453275/142271981-1fb1c685-6025-499b-a355-4f35a715335e.png)

This space on the right is really annoying me :(

Thanks in advance :)

**Comment by LabhanshAgrawal** [comment]
Please fill the issue template

**Comment by LabhanshAgrawal** [comment]
you can use the `padding` option in the config
