### ISSUE TITLE
GET A COMMAND LIST WOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!WASTEOFTIME

### ISSUE THREAD

**Issue by Ericboston1** [vercel/hyper#6113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ericboston1** [comment]
is it that hard to type some quick commands I'll do it for you my goodness, wasting 15mins of my day!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Ccode-lang** [comment]
Hyper uses the terminal installed on your computer so there should not have to be a list of commands you can use.

**Comment by Ccode-lang** [comment]
[ X ] I can not fill in issue template
[ X ] I can complain about things not controlled by the software
[ X ] I must yell everything I say
