### ISSUE TITLE
Hyper is blank when opened, cursor dissapears... no clue why

### ISSUE THREAD

**Issue by thejoshuabowers** [vercel/hyper#6114]
- [ ] Your Hyper.app version is **3.1.4**. Please verify your using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

---

- **Hyper version**: undefined "3.1.4"
- **OS ARCH VERSION:** darwin x64 21.1.0
- **Electron:** 13.2.3  **LANG:** undefined
- **SHELL:** /bin/zsh   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [
    "verminal"
  ],
  "localPlugins": []
}
```
</details>

**Comment by LuckDIY** [comment]
Uncaught Error: No valid cmap sub-tables found.
    at q (bundle.js:1)
    at Hr (bundle.js:1)
    at bundle.js:1
    at XMLHttpRequest.Nr.r.onload (bundle.js:1)
same question

**Comment by LuckDIY** [comment]
![image](https://user-images.githubusercontent.com/49643408/142827175-7b07a0a4-c790-4535-b1b7-74f090842c53.png)

**Comment by LabhanshAgrawal** [comment]
@LuckDIY can you try once after setting `disableLigatures: true` in the config.

**Comment by Cobaramin** [comment]
> @LuckDIY can you try once after setting `disableLigatures: true` in the config.

Thanks for your solution.  It's working for me by adding these to the `.hyper.js` file.


```js
module.exports = {
  config: {

    disableLigatures: true,
```

**Comment by LuckDIY** [comment]
@LabhanshAgrawal  and @Cobaramin  effective
