### ISSUE TITLE
Constant ghosting

### ISSUE THREAD

**Issue by Immedicale** [vercel/hyper#6131]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Pop!_OS 21.04
- **Hyper.app version**: 3.1.4.
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/Immedicale/b02244cb24bd2d602af8667d2e6f7d5f
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Replace with info if applicable, or `Is Vanilla`. (Vanilla means Hyper.app without any add-ons or extras. Straight out of the box.)

## Issue
I get constant ghosting- after I move the cursor, after I scroll, after the resolution changes. This includes minimise-maximise-close buttons, rendered by Hyper.
![Screenshot from 2021-11-22 23-46-56](https://user-images.githubusercontent.com/37558395/142946646-f021930b-2fbc-4ad8-9706-860e41a1fdd3.png)

**Comment by LabhanshAgrawal** [comment]
Can you try once without the plugins? Once with `webGLRenderer` set to `true` and once with `false`.

**Comment by Immedicale** [comment]
Hey, I tried that and it works fine. I turned the plugins one by one, and it seems that it's verminal that's causing the issue.

**Comment by LabhanshAgrawal** [comment]
You may report this with verminal in that case
