### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by mayurankv** [vercel/hyper#6134]
Hi, there's not much documentation on how the css part of the config works. I want to inject some of my own css but don't know whether I should be linking a file, or if not, the format of the css. Enclosing the css in curly brackets across multiple lines didn't seem to work. Would love any examples or help!

**Comment by LabhanshAgrawal** [comment]
You can do something like what this plugin is doing https://github.com/wesbos/hyperterm-cobalt2-theme/blob/master/index.js#L32-L47
basically it's a css string which you can put in backticks ` (multiline js string) in the config

**Comment by mayurankv** [comment]
Thanks!
