### ISSUE TITLE
Hyper focused split pane

### ISSUE THREAD

**Issue by caprinux** [vercel/hyper#6149]
Hyper seems to dim out inactive split panes by default, is there any way I can turn this off?

**Comment by LabhanshAgrawal** [comment]
Please fill the issue template or paste the content from help>report issue menu.

**Comment by letsandeepio** [comment]
I think an option for disabling this behaviour can be added.

**Comment by LabhanshAgrawal** [comment]
It's not done by hyper actually.
Most likely from some plugin.
