### ISSUE TITLE
Stop nagging about updates

### ISSUE THREAD

**Issue by Warwolt** [vercel/hyper#6152]
**Is your feature request related to a problem? Please describe.**
As a user of hyper, I'm quite content with using an out of date version of the terminal. Having the little "new version" popup in the corner is very annoying, since it shows up every time the terminal is started. 

**Describe the solution you'd like**
It would be nice to have an option to turn this behavior off! 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jhaury** [comment]
I would love this, specially when the auto updates break my Hyper.

**Comment by LabhanshAgrawal** [comment]
You can set `disableAutoUpdates: true` (added in 3.1.2)
