### ISSUE TITLE
Which is later? 3.1.4 or 3.1.0-canary.6?

### ISSUE THREAD

**Issue by jaraco** [vercel/hyper#6154]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12
- **Hyper.app version**: 3.1.4

## Issue
I have this is my .hyper.js:

```
    updateChannel: 'canary',
```

I was running 3.1.0-canary.6, but it hadn't updated and I noticed that 3.1.4 was the latest on the website. So I manually installed 3.1.4 and after restarting, the terminal informed me that Version 3.1.0-canary.6 is ready:

![image](https://user-images.githubusercontent.com/308610/144060872-bd0cc522-be55-4529-9ea8-57ff31d2cd02.png)

I'm guessing that 3.1.4 is later than 3.1.0-canary.6 and includes everything in 3.1.0-canary.6. Is that true?

If that's the case, then there must be something wrong with the update workflow if it's trying to update to an older version.

**Comment by jaraco** [comment]
For now, I've set `updateChannel: 'stable'` to work around the issue.

**Comment by LabhanshAgrawal** [comment]
It is as intended
you're updated to the latest version in whatever update channel you choose.
For canary that's 3.1.0-canary.6 and for stable that's 3.1.4

**Comment by LabhanshAgrawal** [comment]
we'll have new canary releases in some time, once we've got the smaller things which were pending for a while done. Then we can have canary releases for bigger changes, that need to be tested thoroughly before going to stable.

**Comment by jaraco** [comment]
As an end user, I'd like if there was a setting which always updated to the latest version, so if stable includes the latest canary, it would use stable.
