### ISSUE TITLE
Using Fira Code 6 causes 100% CPU and hangs Hyper

### ISSUE THREAD

**Issue by tonsky** [vercel/hyper#6163]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.0.1
- **Hyper.app version**: 3.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/tonsky/8a7e3fb6f1f3dd4b2c0dcb107e5632a6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
```
[/Applications] ELECTRON_ENABLE_LOGGING=1 NODE_ENV=development ./Hyper.app/Contents/MacOS/Hyper
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html
Linking HyperCLI
Hyper CLI installation failed Symlink creation failed: EACCES undefined
[34536:1210/150725.352612:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)
[34536:1210/150725.358954:INFO:CONSOLE(1)] "(re)loading renderer plugins", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js (1)
[34536:1210/150725.415581:INFO:CONSOLE(36)] "total init time 88.19999998807907", source: file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html (36)
Checking for notification messages
[34536:1210/150725.845621:VERBOSE1:CONSOLE(1)] "Main._createAppUI: 15.31787109375 ms", source: devtools://devtools/bundled/main/main.js (1)
[34536:1210/150725.869334:VERBOSE1:CONSOLE(1)] "Main._showAppUI: 6.259033203125 ms", source: devtools://devtools/bundled/main/main.js (1)
[34536:1210/150725.870311:VERBOSE1:CONSOLE(1)] "Main._initializeTarget: 3.015869140625 ms", source: devtools://devtools/bundled/main/main.js (1)
[34536:1210/150725.974127:VERBOSE1:CONSOLE(1)] "Main._lateInitialization: 0.05712890625 ms", source: devtools://devtools/bundled/main/main.js (1)
No matching notification messages
```
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue

1. Install Fira Code v6 from https://github.com/tonsky/FiraCode/releases/tag/6.2
2. Set `fontFamily` to `"Fira Code"`
3. Set `disableLigatures` to `false`
4. Restart Hyper

Now I am able to type a few characters in ~0.5 seconds after Hyper starts, after that it goes into 100% CPU spin and no typing is processed anymore.

Issue presents itself only on Fira Code 6.* (earlier versions are fine), and only if you enable ligatures. Other fonts with ligatures, e.g. Fira Code 5 or Iosevka, seems to work fine.

Screenshot of a place where it hangs (could be useful, but sources are minified):

<img width="1472" alt="Screenshot 2021-12-10 at 15 17 42" src="https://user-images.githubusercontent.com/285292/145587999-84cbbade-0eb6-4eb8-a39e-282e1d2ef441.png">

Thanks!

**Comment by tonsky** [comment]
Seems to be `font-ligatures` issue https://github.com/princjef/font-ligatures/issues/23

**Comment by tcherokee** [comment]
Also ran into this issue.

**Comment by vivekimsit** [comment]
I am facing same issue, is there any update yet?

**Comment by LabhanshAgrawal** [comment]
I've opened https://github.com/princjef/font-ligatures/pull/24 for this

Here is the subtable from Fira Code which is hitting the problematic code in font-ligatures (substFormat = 2 and coverage.format = 2), it's not there in v5.2 of Fira Code
It's from `font.tables.gsub.lookups[*].subtables` where font is the parsed font file using opentype.js
```json
{
  "substFormat": 2,
  "coverage": {
    "format": 2,
    "ranges": [
      {
        "start": 688,
        "end": 694,
        "index": 0
      },
      {
        "start": 716,
        "end": 811,
        "index": 7
      }
    ]
  },
  "backtrackClassDef": {
    "format": 2,
    "ranges": [
      {
        "start": 664,
        "end": 696,
        "classId": 1
      },
      {
        "start": 716,
        "end": 811,
        "classId": 1
      },
      {
        "start": 1103,
        "end": 1103,
        "classId": 2
      }
    ]
  },
  "inputClassDef": {
    "format": 2,
    "ranges": [
      {
        "start": 688,
        "end": 694,
        "classId": 1
      },
      {
        "start": 716,
        "end": 811,
        "classId": 1
      }
    ]
  },
  "lookaheadClassDef": {
    "format": 2,
    "ranges": [
      {
        "start": 664,
        "end": 696,
        "classId": 1
      },
      {
        "start": 716,
        "end": 811,
        "classId": 1
      },
      {
        "start": 1103,
        "end": 1103,
        "classId": 2
      }
    ]
  },
  "chainClassSet": [
    [],
    [
      {
        "backtrack": [],
        "input": [],
        "lookahead": [
          1
        ],
        "lookupRecords": [
          {
            "sequenceIndex": 0,
            "lookupListIndex": 277
          }
        ]
      },
      {
        "backtrack": [
          1
        ],
        "input": [],
        "lookahead": [],
        "lookupRecords": [
          {
            "sequenceIndex": 0,
            "lookupListIndex": 278
          }
        ]
      },
      {
        "backtrack": [],
        "input": [],
        "lookahead": [
          2,
          1
        ],
        "lookupRecords": [
          {
            "sequenceIndex": 0,
            "lookupListIndex": 279
          }
        ]
      },
      {
        "backtrack": [
          2,
          1
        ],
        "input": [],
        "lookahead": [],
        "lookupRecords": [
          {
            "sequenceIndex": 0,
            "lookupListIndex": 280
          }
        ]
      }
    ]
  ]
}
```

**Comment by kumardeepakxyz** [comment]
Facing exactly the same issue 😢

**Comment by LabhanshAgrawal** [comment]
> I've opened [princjef/font-ligatures#24](https://github.com/princjef/font-ligatures/pull/24) for this
> 
> Here is the subtable from Fira Code which is hitting the problematic code in font-ligatures (substFormat = 2 and coverage.format = 2), it's not there in v5.2 of Fira Code It's from `font.tables.gsub.lookups[*].subtables` where font is the parsed font file using opentype.js
> 
> ```json
> {
>   "substFormat": 2,
>   "coverage": {
>     "format": 2,
>     "ranges": [
>       {
>         "start": 688,
>         "end": 694,
>         "index": 0
>       },
>       {
>         "start": 716,
>         "end": 811,
>         "index": 7
>       }
>     ]
>   },
>   "backtrackClassDef": {
>     "format": 2,
>     "ranges": [
>       {
>         "start": 664,
>         "end": 696,
>         "classId": 1
>       },
>       {
>         "start": 716,
>         "end": 811,
>         "classId": 1
>       },
>       {
>         "start": 1103,
>         "end": 1103,
>         "classId": 2
>       }
>     ]
>   },
>   "inputClassDef": {
>     "format": 2,
>     "ranges": [
>       {
>         "start": 688,
>         "end": 694,
>         "classId": 1
>       },
>       {
>         "start": 716,
>         "end": 811,
>         "classId": 1
>       }
>     ]
>   },
>   "lookaheadClassDef": {
>     "format": 2,
>     "ranges": [
>       {
>         "start": 664,
>         "end": 696,
>         "classId": 1
>       },
>       {
>         "start": 716,
>         "end": 811,
>         "classId": 1
>       },
>       {
>         "start": 1103,
>         "end": 1103,
>         "classId": 2
>       }
>     ]
>   },
>   "chainClassSet": [
>     [],
>     [
>       {
>         "backtrack": [],
>         "input": [],
>         "lookahead": [
>           1
>         ],
>         "lookupRecords": [
>           {
>             "sequenceIndex": 0,
>             "lookupListIndex": 277
>           }
>         ]
>       },
>       {
>         "backtrack": [
>           1
>         ],
>         "input": [],
>         "lookahead": [],
>         "lookupRecords": [
>           {
>             "sequenceIndex": 0,
>             "lookupListIndex": 278
>           }
>         ]
>       },
>       {
>         "backtrack": [],
>         "input": [],
>         "lookahead": [
>           2,
>           1
>         ],
>         "lookupRecords": [
>           {
>             "sequenceIndex": 0,
>             "lookupListIndex": 279
>           }
>         ]
>       },
>       {
>         "backtrack": [
>           2,
>           1
>         ],
>         "input": [],
>         "lookahead": [],
>         "lookupRecords": [
>           {
>             "sequenceIndex": 0,
>             "lookupListIndex": 280
>           }
>         ]
>       }
>     ]
>   ]
> }
> ```

@tonsky any possibility of using the above info to avoid this from Fira Code side?

**Comment by tonsky** [comment]
Nah, I have no idea what those mean
