### ISSUE TITLE
When I open hyper it shows me an error message and doesn't show anything

### ISSUE THREAD

**Issue by TurtleMeds** [vercel/hyper#6177]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 11
- **Hyper.app version**: three
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/TurtleMeds/3863138ac1946bdbf3a22717a2ab08a4
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: I edited the config, so not vanilla

## Issue
When I open the app it shows an error message and a blank/empty screen
![js hyper error](https://user-images.githubusercontent.com/76972146/146610781-44813ea0-7ce6-4472-9f33-09ff87220115.png)
![image](https://user-images.githubusercontent.com/76972146/146610976-d0ce42cc-d947-4335-a8c5-315774e01ad6.png)

**Comment by hippiiee** [comment]
I'm having the same issue on MacOS

**Comment by ShouryaHacker** [comment]
yeah bro

**Comment by LabhanshAgrawal** [comment]
in your config
https://gist.github.com/TurtleMeds/3863138ac1946bdbf3a22717a2ab08a4#file-gistfile1-txt-L95
check if the file is present

alternatively you can use the path to `wsl.exe` and set shell args to `['-d', 'Ubuntu']`

**Comment by TurtleMeds** [comment]
Thank you so much
