### ISSUE TITLE
Whitespace characters aren't empty?

### ISSUE THREAD

**Issue by bennettp123** [vercel/hyper#6239]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.2 Beta (21D5025f)
- **Hyper.app version**: Hyper 3.1.5 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/bennettp123/d6d483d9b8411f32c51b1a1895de73a9
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: no idea. N/A?
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Apologies, but I'm going to have trouble describing this one.

Whitespace characters don't always print whitespace. Intermittently, the previous characters are printed instead, seems like it prints characters from the scroll back buffer instead of whitespace?

Reproducible with the following file:
```
no leading whitespace (<-- note that I didn't type "nomleading" -- i typed "no leading")
   leading whitespace (spacebar x4)
				leading whitespace (tab x4)
no leading whitespace

```

Opening the file in vim, the first space shows a `m` character:
![image](https://user-images.githubusercontent.com/1610227/148874175-725a5e27-e700-4903-b529-a75692f506d7.png)

it also happens with `cat` (`num: 9930` is from the scroll back buffer):
![image](https://user-images.githubusercontent.com/1610227/148874209-cd039b84-9c40-47d7-8a6f-b225dea8a6af.png)

Not reproduced here, but I often see `-rw-r--r--` in vim where it should be whitespace.

**Comment by bennettp123** [comment]
This is what my .hyper.js looks like in vim:

![image](https://user-images.githubusercontent.com/1610227/148875153-d2bda21e-e66e-46d1-865b-cd1ba66ceb43.png)

**Comment by bennettp123** [comment]
Also, I'm able to reproduce the issue with `webGLRenderer: false,`

**Comment by bennettp123** [comment]
Not reproducible on 3.2.0-canary.1

**Comment by LabhanshAgrawal** [comment]
not able to reproduce
can you paste the output from `hyper -v` and from dev console (option+cmd+i)
You can also try the steps from https://github.com/vercel/hyper#contribute to see if it makes any difference if built on your system
