### ISSUE TITLE
black sharp corner problem hyperborder

### ISSUE THREAD

**Issue by masud-rana-2** [vercel/hyper#6241]
I'm using
Hyper 3.1.5 (stable)
![image](https://user-images.githubusercontent.com/96349874/149078780-242d56f1-a74a-454c-b272-0bee9ea3b1d1.png)

**Comment by LabhanshAgrawal** [comment]
You should report it in the hyperborder plugin's repository

**Comment by LabhanshAgrawal** [comment]
Anyways there's also options on that plugin https://github.com/webmatze/hyperborder#configuration
You can configure the radius
