### ISSUE TITLE
rustup error in Hyper (Appimage)

### ISSUE THREAD

**Issue by ross-ops** [vercel/hyper#6243]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 20.04
- **Hyper.app version**: 3.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ross-ops/284201bc7dd252d82f498365eae1e8f3
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Haven't attempted in fresh environment, but will do so if suggested

## Issue
Hi there, 

Trying to use `rustup` in hyper to try and install `rustlings` and teach myself rust. When running `rustup`, I get the error 
```Shell
error: unknown proxy name: 'Hyper-3.1.5_fdb7221642180a3fa737127e17da0df2'; valid proxy names are 'rustc', 'rustdoc', 'cargo', 'rust-lldb', 'rust-gdb', 'rls', 'cargo-clippy', 'clippy-driver', 'cargo-miri', 'rustfmt', 'cargo-fmt'
```
Upon researching the error, I came across this [link](https://github.com/GitSquared/edex-ui/issues/1124) for a different terminal emulator which seems to address the same issue I'm currently facing.  I don't know enough js/hyper internals to help solve the issue I'm afraid, but I wonder if something similar is happening here, and the env is being overwritten on creating the Hyper thread?

Many thanks
R

**Comment by Schr3da** [comment]
@ross-ops I cant reproduce your issue - on my end rustup works as expected.
Can you please ensure that your shell is loading all settings properly e.g. if you are using bash ensure that .bashrc is properly set and the PATH env variable gets properly extended...

**Comment by LabhanshAgrawal** [comment]
Hey @ross-ops
Can you try the build from #6268 (comment by github bot)
Please use AppImage if you were using that earlier too
