### ISSUE TITLE
Is it possible to use Hyper on Windows to open an Ubnuntu for Windows shell?

### ISSUE THREAD

**Issue by int-a** [vercel/hyper#6253]
Curious as I'm used to developing on Mac/unix and I only have access to a Windows computer currently. I use Hyper at work on my Mac and would like to continue to use it for some development I'm doing on my PC, where I have Ubuntu for Windows installed.

Is it possible to use Hyper for the Ubuntu VM that is running on my Windows machine?

**Comment by LabhanshAgrawal** [comment]
Check the exact distro name using `wsl --list -v`
and then you can set `shell` as path to `wsl.exe` and `shellArgs` to `['-d', '<distro name>']`
