### ISSUE TITLE
Please provide more Extension Samples

### ISSUE THREAD

**Issue by nidefawl** [vercel/hyper#6257]
I want to write some of my own extensions, but the the decorate/reduce concept along with the use of React classes isn't very obvious to me.

It would be helpful if you could provide more sample plugins. 

Also, is it possible to write extensions in typescript?

**Comment by bet4it** [comment]
There are many plugins in [awesome-hyper](https://github.com/bnb/awesome-hyper) and many of them are written by typescript.
