### ISSUE TITLE
Menu-item "Plugins" missing on Hyper.app 3.1.5 (Manjaro KDE) - Can't see plugin-options

### ISSUE THREAD

**Issue by exetico** [vercel/hyper#6270]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 5.10.84-1-MANJARO x86_64
- **Hyper.app version**: 3.1.5 (stable)
![image](https://user-images.githubusercontent.com/3549445/151577043-1241a469-cb47-4be3-a7a5-e3e16429c282.png)

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [](https://gist.github.com/exetico/84b46ac57c81e6a8b3b40989fa023704)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
![image](https://user-images.githubusercontent.com/3549445/151577308-96575686-8b1e-43f5-92ea-5516eb0a10bb.png)

- **The issue is reproducible in vanilla Hyper.app**: Well, it's the same issue without plugins - but... If so, there shouldn't be any plugins anyway, right?

## Issue
It seems like there should be a "Plugins" option in the nav-menu, but that's not present on my system. I've spotted it in [this repo](https://github.com/dfrankland/hyper-sync-settings), where the guide tell's the user to use the "Plugins" option.

It's also shown here: ![Gif from repo](https://camo.githubusercontent.com/3a420cdfc70ebf8c7150cb921cdc46d695605766dd3baf6a5515de74b1f32377/687474703a2f2f692e67697068792e636f6d2f39434e41306365753569756f552e676966)

But sadly that's not visible on my system with latest stable version of Manjaro with KDE:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.10.84-1-MANJARO (64-bit)
```

![image](https://user-images.githubusercontent.com/3549445/151576959-f99e191c-b3f9-4a12-965d-3c49e124de9e.png)
_Here's my options within the menu._

**Comment by exetico** [comment]
I noticed the issue in the search for the `Plugins > Sync Settings > Backup Settings` option from [hyper-sync-settings](https://github.com/dfrankland/hyper-sync-settings).

**Comment by exetico** [comment]
I just found a few words about `decorateMenu`, where the [Plugin development > Menu](https://github.com/vercel/hyper/blob/canary/PLUGINS.md#menu) information are shared... So there must be some kind of "Plugins" option, which are not shown on my machine.

**Comment by LabhanshAgrawal** [comment]
Plugins menu was renamed to Tools

**Comment by LabhanshAgrawal** [comment]
hyper-sync-settings is using the menu name `Plugins` to add it's options. They'd need to update it to `Tools`
As a workaround you can edit `~/.hyper_plugins/node_modules/hyper-sync-settings/dist/index.js` line 370 to `Tools` for the time being.

**Comment by exetico** [comment]
Oh... I was actually trying to spot the bug, but couldn't really find other plugins changing the "Plugins" menu, so that explained why. 

I was already in the source, and tried to play around.

![image](https://user-images.githubusercontent.com/3549445/151586878-852a1351-7e7d-4c81-9531-0460de2476cf.png)

But you helped me out, and saved me for even more time with the source code. 

Thanks!

![image](https://user-images.githubusercontent.com/3549445/151587351-5590d93b-57f8-4751-8184-a6b13334e37e.png)

I've submitted [#239](https://github.com/dfrankland/hyper-sync-settings/pull/239) in the repo for `hyper-sync-settings`.
