### ISSUE TITLE
Hyper does not seem to work.

### ISSUE THREAD

**Issue by Shigetorum635** [vercel/hyper#6273]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Win 10 21H1
- **Hyper.app version**: Cant' check. Latest as of 1/31/2022
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default one of installation
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
![image](https://user-images.githubusercontent.com/48862659/151773998-d0e99ba3-62be-462c-93da-5a16d128c4b4.png)

- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Hyper does not exist within my terminal.

![image](https://user-images.githubusercontent.com/48862659/151774072-90598808-da54-44a3-89f8-e4c806fd1ca0.png)

I'd also like to use it with bash commands rather than windows. I can do it on GIt Bash but on hyper?

**Comment by LabhanshAgrawal** [comment]
You need to do a restart to add the hyper command
