### ISSUE TITLE
new tab does not start at ~

### ISSUE THREAD

**Issue by ldeveber** [vercel/hyper#6287]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Mac OS Big Sur
- **Hyper.app version**:  3.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

New tabs are keeping the directory of the previous tab, and are not resetting to ~. This new feature is awful and I don't see any way to opt out

**Comment by LabhanshAgrawal** [comment]
https://github.com/vercel/hyper/discussions/6286#discussioncomment-2111601
