### ISSUE TITLE
Can't open vscode through terminal with hyper but regular can

### ISSUE THREAD

**Issue by LoyalPotato** [vercel/hyper#6288]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro 21.2.2
- **Hyper.app version**: 3.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default with just some font changes
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hello,
I installed visual studio code through snap, by following [these](https://snapcraft.io/install/code/manjaro) instructions.
In my normal terminal, the `code` command works fine and I can do `code .` to open the current directory.
In my $PATH I have the snap bin (`/var/lib/snapd/snap/bin`) which is where `code` is located.
When I run the `code` command in the hyper terminal it behaves as if I was running the `snap` command and printing the following error when I try to use the command like so `code .`:
```sh
error: unknown command ".", see 'snap help'.
```
Am I missing something? Shouldn't they perform the same?

**Comment by LabhanshAgrawal** [comment]
How did you install Hyper? Through AppImage?
Can you try a build from https://nightly.link/vercel/hyper/actions/runs/1794351456 and check

**Comment by LoyalPotato** [comment]
@LabhanshAgrawal Yeah it was through an AppImage.
I downloaded the [Hyper-3.3.0-canary.1.AppImage](https://nightly.link/vercel/hyper/actions/runs/1794351456/Hyper-3.3.0-canary.1.AppImage) and this time it doesn't do anything when I run the command `code .`

I also have zsh installed, but in the regular terminal the command works like mentioned above.

**Comment by LabhanshAgrawal** [comment]
The build I'd linked doesn't have shell environment vars inherited from hyper
I'm guessing it didn't do anything as `PATH` would also be stub
try to run `/var/lib/snapd/snap/bin/code .` and check

**Comment by LabhanshAgrawal** [comment]
may also try https://nightly.link/vercel/hyper/actions/runs/1800193266

**Comment by LoyalPotato** [comment]
Ok, running the command through the full pass, on the previous run (1794351456) and it still didn't work.
But :eyes: the run you posted after that (1800193266) worked :D
What made it so that one works?

**Comment by LabhanshAgrawal** [comment]
#6268

**Comment by LabhanshAgrawal** [comment]
> Ok, running the command through the full pass, on the previous run (1794351456) and it still didn't work.
> But :eyes: the run you posted after that (1800193266) worked :D
> What made it so that one works?

Just to confirm, you used appimage for all the tests, right?

**Comment by LoyalPotato** [comment]
Yep
