### ISSUE TITLE
ZSH Spaceship symbols not showing up as emoji's.

### ISSUE THREAD

**Issue by mrpbennett** [vercel/hyper#6310]
For example this is my VSC terminal

<img width="465" alt="Screenshot 2022-02-09 at 15 14 31" src="https://user-images.githubusercontent.com/1844080/153231979-7b9e3c56-c191-4b07-a4ff-8d0671ff28b7.png">

This is Hyper.js

<img width="531" alt="Screenshot 2022-02-09 at 15 14 07" src="https://user-images.githubusercontent.com/1844080/153232028-9babcc50-243f-4d49-b27f-97a5aa850c31.png">

https://spaceship-prompt.sh/options/#google-cloud-platform-gcloud

Is there a way to get these showing as emojis? I know iTerm can handle this but I do love Hyper

**Comment by LabhanshAgrawal** [comment]
What happens if you paste the emoji in hyper
Also make sure you're using the same font
Plugins can change the font also, so check once without them

**Comment by mrpbennett** [comment]
I get the same icon. Just a really sad looking cloud, not the actual emoji.

 I am using Fire Coda in VSC, iTerm and Hyper.

**Comment by LabhanshAgrawal** [comment]
![Screenshot 2022-02-09 at 23 47 25](https://user-images.githubusercontent.com/16598275/153264398-8538fdd8-51fd-4a5c-8174-be55c9a4077f.png)

Didn't work for me too in Fira Code, checked VS Code and I had "Source Code Pro for Powerline" font there
Working with that, so seems to be just a font thing

**Comment by LabhanshAgrawal** [comment]
On further inspection `Menlo` seems to be the culprit here
Since fonts are checked one by one to get the character and Menlo seems to have that punctured cloud, it's getting picked up instead of the apple [cloud](https://emojipedia.org/cloud/) emoji
