### ISSUE TITLE
Ghosting display problem when resize the terminal

### ISSUE THREAD

**Issue by LittleDC** [vercel/hyper#6311]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS Monterey 12.2 (21D49)
- **Hyper.app version**:  3.2.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  [.hyper.js](https://gist.github.com/LittleDC/b034358faeca9510460ede5abf5eb7bb)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue

as the picture shows: there are some lighter color fonts on the terminal
<img width="1552" alt="截屏2022-02-11 14 12 02" src="https://user-images.githubusercontent.com/48859961/153548357-7028d513-e0b3-4fbd-aa94-7e5383b4eebd.png">
<img width="922" alt="截屏2022-02-11 14 16 54" src="https://user-images.githubusercontent.com/48859961/153548399-f99c886f-3cb3-4a97-923f-59238adac48b.png">

Steps to get this result:
1. Enter some commands and let the terminal display some results (like 'll')
2. Resize the terminal when the terminal has a display (like maximize terminal)
3. clear the terminal ( enter 'clear' command) 
4. you would get the result in the picture above.

I don't know if I set a transparent background which is causing this problem,,🤯
I will be very glad if anyone solves this problem 🙌 ❤️

**Comment by Arro** [comment]
add `webGLRenderer: false` to your `~/.hyper.js` under `config`

**Comment by LittleDC** [comment]
!!! It works,thank you so much🙌

> add `webGLRenderer: false` to your `~/.hyper.js` under `config`
