### ISSUE TITLE
Vim/Neovim showing totally yellow

### ISSUE THREAD

**Issue by hrqmonteiro** [vercel/hyper#6318]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 20.04
- **Hyper.app version**: Latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
![Screenshot from 2022-02-16 14-29-44](https://user-images.githubusercontent.com/17055027/154322625-bf864c86-e7b9-4003-b353-942d1a896f78.png)

**Comment by LabhanshAgrawal** [comment]
Looks to be a theme set in your vim config. #2038

**Comment by hrqmonteiro** [comment]
> Looks to be a theme set in your vim config. #2038

No. Every theme i set is behaving like this in Hyper.

And my theme is Nord, never nord would be a yellowed theme lol.

**Comment by LabhanshAgrawal** [comment]
when you say theme, do you mean vim theme or Hyper theme?

**Comment by hrqmonteiro** [comment]
> when you say theme, do you mean vim theme or Hyper theme?

I was saying the vim theme.

But i am also using nord on Hyper, the `hyper-nord` plugin. But this yellow thing happens in the default theme as well.

**Comment by LabhanshAgrawal** [comment]
What happens when you do `nvim -u NONE`
