### ISSUE TITLE
Plugins decorating Hyper has been disabled due to a plugin crash.

### ISSUE THREAD

**Issue by albas99** [vercel/hyper#6335]
- [x] Your Hyper.app version is **3.2.0**. Please verify you're using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:
![Screen Shot 2022-02-22 at 18 50 28](https://user-images.githubusercontent.com/53338885/155157322-0d712e4d-496a-47aa-843f-bbe3026408c5.png)

- **Is the issue reproducible in vanilla Hyper.app?**
No.

## Issue

I've been facing this error since yesterday. Every time I open the Hyper terminal even if it's just a new window I get the error notification "Plugins decorating Hyper has been disabled due to a plugin crash. Check Developer Tools for Details".
I searched the issues and even reinstalled hyper which stopped the notification for a while, but then today I'm getting the same error again. I also uninstalled Fig, thinking it was the cause of the problem but kept getting the issue even after the uninstallation. I only have 2 extensions installed now, hyper-aura-theme and hyperline.

---

- **Hyper version**: undefined "3.2.0"
- **OS ARCH VERSION:** darwin x64 21.3.0
- **Electron:** 16.0.8  **LANG:** undefined
- **SHELL:** /bin/zsh   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "updateChannel": "stable",
  "fontSize": 14,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": true,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "workingDirectory": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF",
    "limeGreen": "#32CD32",
    "lightCoral": "#F08080"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": false,
  "webLinksActivationKey": "",
  "disableLigatures": true,
  "disableAutoUpdates": false
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [
    "hyper-aura-theme",
    "hyperline"
  ],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment]
hyperline seems to be the issue here
it calls child process module from the renderer process which has been disabled (except few methods) due to serious performance issues with electron and macos when doing this.
IIRC differently hyperline tickers call different methods, so you should be able to figure out the bad one by progressively enabling them. https://www.npmjs.com/package/hyperline#configuring-plugins
For a complete fix they would need to update the code to use the allowed methods or use the main process.
