### ISSUE TITLE
[Security] Preferences menu opens another application.

### ISSUE THREAD

**Issue by cristianchaparroa** [vercel/hyper#6353]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOs Monterey Version 12.1 M1 processor 
- **Hyper.app version**:  Hyper 3.2.0 (stable)
- **Link of a [Gist](https://gist.github.com/cristianchaparroa/060b70a833a93443d9648f2a873aedd3) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I recently downloaded the last version of Hyper on this page https://releases.hyper.is/download/mac_arm64. Unfortunately, when I'm trying to open the preferences, it opens RStudio, Tadam! 

 
![hyper-issue](https://user-images.githubusercontent.com/1727543/156408249-268308c2-9f39-4fc1-bad7-e7991fc8d927.gif)

**Comment by LabhanshAgrawal** [comment]
It opens the config file (js) with your default application for js files.
In your case the file is opening in rstudio.
You can change your default app or open ~/.hyper.js worth your desired app.
