### ISSUE TITLE
Can't start Hyper from terminal (/opt/homebrew/bin/hyper: line 4: /usr/bin/python: No such file or directory)

### ISSUE THREAD

**Issue by GBrachetta** [vercel/hyper#6386]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS Monterey 12.3
- **Hyper.app version**: 3.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/GBrachetta/0bb163e8429f9e72f73ea0faf68a4152)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

## Issue

Attempting to invoke Hyper from the terminal (terminal.app or iTerm2) fails:

```bash
$ hyper

$ /opt/homebrew/bin/hyper: line 4: /usr/bin/python: No such file or directory
$ /opt/homebrew/bin/hyper: line 8: ./MacOS/Hyper: No such file or directory
```

Please note my Python installation was done via Homebrew and as I am on an M1 machine all Homebrew installs go under `/opt/homebrew/bin`.

Also, there's no such `./MacOS/Hyper` anywhere. Was it supposed to get created by Hyper? It's not there.

Hyper was also installed with Homebrew.

Maybe Related: 

I cannot run either `Tools/Install Hyper CLI command in PATH`, I get the following error:

![Screenshot 2022-03-15 at 14 24 35](https://user-images.githubusercontent.com/57924268/158388966-9c878b04-34e5-400e-afcd-04dde5662146.png)

**Comment by GBrachetta** [comment]
I'm sorry but I don't understand.
I do have `python3` in `/usr/bin`

![Screenshot 2022-03-17 at 17 43 29](https://user-images.githubusercontent.com/57924268/158851215-945ba0ae-00d0-4763-b588-682677b90a75.png)

but my python3 in PATH lives in `/opt/homebrew`.

![Screenshot 2022-03-17 at 17 44 50](https://user-images.githubusercontent.com/57924268/158851250-7c4b72e3-f08e-47f7-92c7-482be97f6363.png)

I'm not sure what you're suggesting me to do to fix the cli.

**Comment by zcutlip** [comment]
> I do have python3 in /usr/bin

Yes, but it's not *really* python. It's actually a shim that, the first time you run it on vanilla macOS, will pop a UI to download and install Xcode Tools. Try it in a fresh macOS VM and you'll see what I mean.

What I'm suggesting is to not rely on python on macOS *at all* and instead use a shell-only solution. What I pasted above should work for you, but you may want to look to VSCode's fix for a more robust solution:
https://github.com/Microsoft/vscode/blob/1.65.2/resources/darwin/bin/code.sh

**Comment by zcutlip** [comment]
For more info on removal of default python on macOS and migration strategies:
https://scriptingosx.com/2020/02/wrangling-pythons/

**Comment by zcutlip** [comment]
For what it's worth, I patched my own `Hyper.app/Contents/Resources/bin/hyper` locally and it works fine:

```sh
#!/usr/bin/env bash
# Deeply inspired by https://github.com/Microsoft/vscode/blob/1.17.0/resources/darwin/bin/code.sh

_realpath() { cd "$(dirname $0)" && echo "$(pwd)/$(basename $0)"; }
CONTENTS="$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")"
ELECTRON="$CONTENTS/MacOS/Hyper"
CLI="$CONTENTS/Resources/bin/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by GBrachetta** [comment]
I'm afraid that doesn't work for me:

![Screenshot 2022-03-17 at 18 14 44](https://user-images.githubusercontent.com/57924268/158856864-460e44c7-3277-4643-9e35-9851394e503a.png)

Please excuse me with these basic questions, I'm not at all strong at scripting.

**Comment by zcutlip** [comment]
One additional change you may want to make is invoking either `dash` or plain `sh` in anticipation of the eventual removal of `bash` on macOS.

For more info:
https://scriptingosx.com/2019/09/get-current-user-in-shell-scripts-on-macos/

**Comment by GBrachetta** [comment]
Another issue now is that [fig](https://fig.io/) stopped working on `Hyper` after the patch...

**Comment by zcutlip** [comment]
Good catch with the linter warnings. I didn't realize I hadn't set mine up in vscode. This should fix those:
```sh
#!/usr/bin/env bash
# Deeply inspired by https://github.com/Microsoft/vscode/blob/1.17.0/resources/darwin/bin/code.sh

_realpath() { cd "$(dirname "$0")" && readlink "$(pwd)"/"$(basename "$0")"; }

CONTENTS="$(dirname "$(dirname "$(dirname "$(_realpath "$0")")")")"
ELECTRON="$CONTENTS/MacOS/Hyper"
CLI="$CONTENTS/Resources/bin/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

I've never used `fig` but I'll download it and have a look to see if I can spot the problem.

**Comment by zcutlip** [comment]
Hmm, I can't reproduce the issue with `fig` (thanks for the intro btw, neat tool). I did have to completely quite hyper and restart (not just open a new shell).

<img width="412" alt="Screen Shot 2022-03-17 at 10 50 42 AM" src="https://user-images.githubusercontent.com/2158303/158864858-a5228799-e847-4a94-8de1-ccdfbdb3f4e9.png">


does `fig doctor` tell you anything?

**Comment by brudnak** [comment]
> Good catch with the linter warnings. I didn't realize I hadn't set mine up in vscode. This should fix those:
> 
> ```shell
> #!/usr/bin/env bash
> # Deeply inspired by https://github.com/Microsoft/vscode/blob/1.17.0/resources/darwin/bin/code.sh
> 
> _realpath() { cd "$(dirname "$0")" && readlink "$(pwd)"/"$(basename "$0")"; }
> 
> CONTENTS="$(dirname "$(dirname "$(dirname "$(_realpath "$0")")")")"
> ELECTRON="$CONTENTS/MacOS/Hyper"
> CLI="$CONTENTS/Resources/bin/cli.js"
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> I've never used `fig` but I'll download it and have a look to see if I can spot the problem.

Having the same problem. But when I try and run this shell script I'm getting `file.sh: line 9: ./MacOS/Hyper: No such file or directory` Any ideas?

**Comment by zcutlip** [comment]
> Having the same problem. But when I try and run this shell script I'm getting `file.sh: line 9: ./MacOS/Hyper: No such file or directory` Any ideas?

can you add `set -x` right after your shebang, run it again and paste the output?

So, like:
```sh
#!/usr/bin/env bash
set -x
...
```

**Comment by zcutlip** [comment]
Ah I think I spotted the problem. If you invoke `hyper` directly from the application bundle (i.e., not from a symlink) `readlink` fails. You can provide `-f` which actually does everything we need. From the readlink(1) manpage:

> When invoked as readlink, only the target of the symbolic link is printed.
     If the given argument is not a symbolic link and the -f option is not
     specified, readlink will print nothing and exit with an error.  If the -f
     option is specified, the output is canonicalized by following every symlink
     in every component of the given path recursively.  readlink will resolve
     both absolute and relative paths, and return the absolute pathname
     corresponding to file.  In this case, the argument does not need to be a
     symbolic link.

This should get you going:

```sh
#!/usr/bin/env bash
# Deeply inspired by https://github.com/Microsoft/vscode/blob/1.17.0/resources/darwin/bin/code.sh

_realpath() { readlink -f "$0"; }

CONTENTS="$(dirname "$(dirname "$(dirname "$(_realpath "$0")")")")"
ELECTRON="$CONTENTS/MacOS/Hyper"
CLI="$CONTENTS/Resources/bin/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

Note that `-f` wasn't always available on macOS's `readlink`. I'm not sure when it was added so this may introduce backward compatibility issues. Stackexchange comment from 2013:
https://unix.stackexchange.com/questions/24293/converting-relative-path-to-absolute-path-without-symbolic-link#comment139876_24297

**Comment by zcutlip** [comment]
Okay, hopefully one last attempt. Since `-f` wasn't available on macOS until recently, here's a workaround:

https://unix.stackexchange.com/a/534101

```sh
#!/usr/bin/env bash

# On modern macOS there's readlink -f, but that's fairly recent so we can't rely on it.
# instead, check for failure (i.e., not a symlink) and just echo the actual path
# https://unix.stackexchange.com/a/534101
_readlink(){ readlink "$1" || echo "$1"; }

_realpath() { cd "$(dirname "$0")" && _readlink "$(pwd)"/"$(basename "$0")"; }

CONTENTS="$(dirname "$(dirname "$(dirname "$(_realpath "$0")")")")"
ELECTRON="$CONTENTS/MacOS/Hyper"
CLI="$CONTENTS/Resources/bin/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by zcutlip** [comment]
> Hmm getting this / or similar error when running the above with or without the `set -x` part as well
> 
> ```shell
> ❯ bash ./script.sh
> +++++ _realpath ./script.sh
> +++++ readlink -f ./script.sh
> ++++ dirname /Users/<USERNAME_REDACTED>/script.sh
> +++ dirname /Users/<USERNAME_REDACTED>
> ++ dirname /Users
> + CONTENTS=/
> + ELECTRON=//MacOS/Hyper
> + CLI=//Resources/bin/cli.js
> + ELECTRON_RUN_AS_NODE=1
> + //MacOS/Hyper //Resources/bin/cli.js
> ./script.sh: line 10: //MacOS/Hyper: No such file or directory
> + exit 127
> ```
> 
> `//MacOS/Hyper: No such file or directory` seems like a reoccurring error.

This shell script expects to be in its proper home inside the Hyper.app application bundle. That's what all the `CONTENTS=`, `ELECTRON=`, etc are doing...trying to find the path to `Hyper.app` relative to the `hyper` script. So you need to patch the script in place: `Hyper.app/Contents/Resources/bin/hyper`

> `hyper version` was working for me the other day before the latest mac update to macOS Monterey 12.3

That's because the system's default python was removed in macOS 12.3. This has been anticipated for a couple years, but the Hyper project must not have known. More info here: https://scriptingosx.com/2020/02/wrangling-pythons/

**Comment by brudnak** [comment]
Thanks so much @zcutlip! That did the trick! 🚀  🎉

**Comment by GBrachetta** [comment]
This latest version of the patch works perfectly fine, the cli is back and fig works as well (yes, indeed `fig` is very neat @zcutlip, did you check how nice is to create your own shortcuts or add mixins to expand the current clis?).

Thank you so much. Would this get overwritten on an upcoming version of Hyper?

**Comment by zcutlip** [comment]
> This latest version of the patch works perfectly fine, the cli is back and fig works as well (yes, indeed `fig` is very neat @zcutlip, did you check how nice is to create your own shortcuts or add mixins to expand the current clis?).

No, haven't played with it yet. Looking forward to it!

> 
> Thank you so much. Would this get overwritten on an upcoming version of Hyper?

Yes it'll get overwritten. I'll try to submit a PR soon so hopefully they'll take the fix.

**Comment by GBrachetta** [comment]
One very last little issue regarding fig (and potentially some others):

Fig doesn't work when opening Hyper from the terminal: i.e. if invoking "hyper" from iTerm2, fig doesn't work.
Fig does work though if Hyper is opened normally.

**Comment by TransformersWsz** [comment]
> I'm sorry but I don't understand. I do have `python3` in `/usr/bin`
> 
> ![Screenshot 2022-03-17 at 17 43 29](https://user-images.githubusercontent.com/57924268/158851215-945ba0ae-00d0-4763-b588-682677b90a75.png)
> 
> but my python3 in PATH lives in `/opt/homebrew`.
> 
> ![Screenshot 2022-03-17 at 17 44 50](https://user-images.githubusercontent.com/57924268/158851250-7c4b72e3-f08e-47f7-92c7-482be97f6363.png)
> 
> I'm not sure what you're suggesting me to do to fix the cli.

Hi, I love the theme of your Hyper, especially the apple logo on the left of the command line. Could you share the theme? Thanks.

**Comment by GBrachetta** [comment]
Hi @TransformersWsz! That's [Ohmyzsh](https://github.com/ohmyzsh/ohmyzsh) running the [powerlevel10k](https://github.com/romkatv/powerlevel10k) theme. It will look similar across all terminals if you source the `.zshrc` file: iTerm2, Terminal.app, Hyper, etc.

It's highly customizable. You can find how to place the OS logo in this section of the `.p10k.zsh` file:

```bash
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # os identifier
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )
```

Colors are also fully customizable. Let me know if you need help. It's a pretty big file with tons of variables.

With Hyper I use the `hyper-one-dark` theme, which changes some colors, but it doesn't alter the look of powerlevel10k.
You'll need a powerfont as well. I use `SauceCodePro Nerd Font`.

Hope this helps!

**Comment by GBrachetta** [comment]
I still don't understand why tools like [Fig](https://fig.io/) don't work anymore when Hyper is opened from the command line after this patch.

To reproduce:

```
Launch `Hyper` from iTerm2 or Terminal.app
(Fig doesn't work)
Launch `Hyper` just by double-clicking Hyper.app
(Fig works)
```

I wonder if there are some other side effects or other tools affected by this patch.
