### ISSUE TITLE
How does hide top border

### ISSUE THREAD

**Issue by Zhang-DJ** [vercel/hyper#6392]
### Discussed in https://github.com/vercel/hyper/discussions/6391

<div type='discussions-op-text'>

<sup>Originally posted by **Zhang-DJ** March 18, 2022</sup>
## i want to hide top border but not successed
<img src="https://github.com/Zhang-DJ/Test_1/blob/main/photo.png"></div>

**Comment by LabhanshAgrawal** [comment]
There's no config option but you may use any plugin to get it. I think there are plugins to make the title bar and tab bar look like mac, even on windows and linux.
