### ISSUE TITLE
Windows - I Just Installed and - "'hyper' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by Welding-Torch** [vercel/hyper#6394]
## Issue

I just installed Hyper 10 minutes ago, and this is the **first thing I see** when I try to install anything.

![image](https://user-images.githubusercontent.com/46340124/159218085-3b1d7ba8-6e21-4ab3-b262-51f4e7f30986.png)

**This should not be the case.** It's quite discouraging when the first thing suggested on the website doesn't work outside the box. Maybe automatically add 'hyper' to the Windows Environment Variable when it first installs? Other apps do it, so it's not impossible. 

[ The closest issue I found relating to this is:#2823 ]

---

- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

---

- **OS version and name**: Windows 10
- **Hyper.app version**: Latest
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

**Comment by Aryan-Srivastava** [comment]
have the same issue, did you figured it out ? @Welding-Torch

**Comment by kyds3k** [comment]
I am also having the same problem . . . time to go back to Powershell?

**Comment by Aryan-Srivastava** [comment]
Nah got it fixed, just do a reboot 😶

**Comment by neverlous** [comment]
I solve it by install these two and restart computer
![image](https://github.com/vercel/hyper/assets/8750037/aacff933-b487-4f6d-8925-c5e77dd98a0b)

**Comment by Welding-Torch** [comment]
I just had to reboot man.
