### ISSUE TITLE
preferences opens adobe dreamweaver???

### ISSUE THREAD

**Issue by artcore-c** [vercel/hyper#6431]
adobe wants to but in at every chance it seems... sure I pay for CC and apps are great but when I choose not otherwise.
open Hyper and then click preferences (so I can change font to MesloLGS NF) and Dreamweaver opens instead of Hyper prefs, had this issue with Maya and sometimes Blender something would open Dimension or some other 3D app from adobe. Not sure how to fix?

**Comment by LabhanshAgrawal** [comment]
We open the config file with the default editor.
It's a js file so you should check if they are set to open using Adobe cc by default.
Alternatively you can directly open `~/.hyper.js` using any editor of your choice.
