### ISSUE TITLE
Main process error on launch

### ISSUE THREAD

**Issue by mzamayias** [vercel/hyper#6447]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.3.1 21E258 arm64
- **Hyper.app version**: 3.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/mzamayias/c3fc8263c006e3d83b5dd374b4629896)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

I'm getting this error when I'm launching the app. I tried installing the app both from the official .pkg and homebrew and the error persists. Hyper remains open when I click OK in the error window, and to quit it I either have to _Right Click, Quit_ from the Dock or _Force Quit_ it through Activity Monitor. No other GUI except from the error window ever appears. Here are some screen captures of the error, hope they're helpful:

<img width="372" alt="Screen Shot 2022-04-08 at 18 08 22" src="https://user-images.githubusercontent.com/29067825/162475118-252ea5b9-7d59-470c-87e0-57c91c1304ca.png">

https://user-images.githubusercontent.com/29067825/162475140-d9919281-9175-44f7-80e7-d8c581fb1173.mov

**Comment by LabhanshAgrawal** [comment]
The config file you've added here just contains null.
If that's the same on your device then you should delete the file and hyper will recreate it properly.

**Comment by mzamayias** [comment]
Yes, the file contained just a null. I deleted it and launched hyper successfully. Thank you very much!
