### ISSUE TITLE
[Win] Support multiple shells

### ISSUE THREAD

**Issue by pakoito** [vercel/hyper#6448]
**Is your feature request related to a problem? Please describe.**
I use windows and would like to use hyper for both PowerShell and WSL terminals.

**Describe the solution you'd like**
I would like to have a picker when I summon a new terminal with a key, or a dropdown to pick from in the UI.

**Describe alternatives you've considered**
Always start with the windows terminal and run `wsl.exe` manually.

**Additional context**
![](https://www.privacy.com.sg/wp-content/uploads/2021/04/windows-terminal-menu-1536x768.jpg)

**Comment by NotesOfReality** [comment]
You could very well install hyper-manager and make a `cli` connection with `wsl` as custom argument, I think it could satisfy your request to at least a partial extent.

**Comment by pakoito** [comment]
i c u
