### ISSUE TITLE
Cannot open file with emacs -nw filename

### ISSUE THREAD

**Issue by junkoda** [vercel/hyper#6459]
I updated Hyper to the latest 3.2.1 after a long interval and realized I cannot open files with emacs

```
$ emacs -nw filename
```

I see "Quit" at the bottom left. This is related Hyper because

- It is fine with hyper_3.1.4_amd64.deb but occurs with hyper_3.2.1_amd64.deb
- No problem with Ubuntu default "Terminal"
- No problem without -nw, opening a separate window outside Hyper
- I can open files within emacs with ctrl x-f, emacs only fails to open file in the argument <filename>
- Emacs configuration .emacs, .emacs.d are irrelevant; reproducible with plain emacs

Environment

- OS: Ubuntu 18.04.6 LTS
- Version: Hyper 3.2.1 (stable)
- The issue is reproducible in vanilla Hyper.app: I removed ~/.hyper.js and .hyper_plugins
- GNU Emacs 25.2.2 and 28.1 (latest with apt and snap, respectively)

I am currently fine with version 3.1.4, maybe a rare case, but I leave this issue in case this also happens to many other users. Thanks!

**Comment by LabhanshAgrawal** [comment]
Thanks for reporting
Seems like it's coming from xterm https://github.com/xtermjs/xterm.js/issues/3700
I'll see if we can use the beta build or we should wait for their next release.
