### ISSUE TITLE
Black background on transparent terminal with newest update

### ISSUE THREAD

**Issue by yspreen** [vercel/hyper#6468]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS monterey
- **Hyper.app version**: 3.2.2 stable (same on canary too)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/yspreen/fbe533bfbba0904e2c13914bb08253e7
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: no

## Issue

<img width="541" alt="image" src="https://user-images.githubusercontent.com/12631527/163540666-30642ecc-0314-40ef-b2ef-9ee437b8534e.png">

happens with a reverse search (ctrl + r)

**Comment by yspreen** [comment]
also if I paste it's white on white again. these issues haven't happened for years, what's going on :/

**Comment by yspreen** [comment]
if I hit ctrl+r multiple times there's also text rendering above previous text. the terminal is really broken all of a sudden. all I did was install a new canary update and then I tried to revert to stable to fix it but it didn't help

**Comment by LabhanshAgrawal** [comment]
check https://github.com/vercel/hyper/issues/6446#issuecomment-1088593647

in your case the vibrancy is coming from the hyper-transparent-vibrancy plugin

**Comment by LabhanshAgrawal** [comment]
you may also try setting a transparent background color

**Comment by yspreen** [comment]
that didn't really change anything @LabhanshAgrawal 

I have some more weird issues:

https://user-images.githubusercontent.com/12631527/163557044-82cd56fc-eba2-4f3b-aa78-6054c327a0e4.mov

**Comment by yspreen** [comment]
disabling webgl works. seems like a bad solution though?

**Comment by LabhanshAgrawal** [comment]
You'd have been using the the canvas renderer earlier as well.
As we were using that when a transparent background was set.

In the recent release I'd enabled webgl for the same as comments on xterm issues suggested that it's working, which was also confirmed in my brief testing (I have quite simple shell setup though)
But looks like it still has some issues. Let's see if they can get resolved upstream soon.
