### ISSUE TITLE
Transparent background removes prompt on agnoster theme in recent update

### ISSUE THREAD

**Issue by presto2116** [vercel/hyper#6469]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOd Monterey 12.3
- **Hyper.app version**: 3.2.2
- **Link of a [Gist](https://gist.github.com/presto2116/a72a2ac4400d47680df676f98853a6d6)**
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I am using zsh with agnoster theme

in .hyper.js when i have `backgroundColor: 'rgba(0, 0, 0, 0.3)',`

<img width="584" alt="Screen Shot 2022-04-15 at 16 18 54" src="https://user-images.githubusercontent.com/9746108/163628298-382590dc-14d1-4e48-94ff-0160549c51b1.png">

in .hyper.js when i have `backgroundColor: '#000',`

<img width="625" alt="Screen Shot 2022-04-15 at 16 18 12" src="https://user-images.githubusercontent.com/9746108/163628367-146b01ca-58ba-4138-bc56-030d5ec1f8cd.png">

**Comment by alanyoungCN** [comment]
Maybe you can close this window and create a new one, and the prompt comes back.
![prompt](https://user-images.githubusercontent.com/32586930/176943628-f4b6a67e-ae72-4091-877c-732ef4538134.png)

**Comment by presto2116** [comment]
[alanyoungCN](https://github.com/alanyoungCN) 

Thanks for the update. I just switched back to transparent background and its working again. I think one of the updates must have fixed it. Thanks!
