### ISSUE TITLE
Nerd Fonts don't work

### ISSUE THREAD

**Issue by radstevee** [vercel/hyper#6505]
- [ ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: endeavourOS Atlantis
- **Hyper.app version**: hyper-git-3.1.2.r54.g7f01b064-1 from the AUR
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/radstevee/103bd621b8a177bd9737bc419b60fa9f
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Vanilla (with hypurr theme)

## Issue

Icons from nerd fonts don't load correctly (image)
![image](https://user-images.githubusercontent.com/96977790/166095561-c80fadf5-9fe6-409d-b2f1-4366ad9afe43.png)

**Comment by LabhanshAgrawal** [comment]
Use `'"Jetbrains mono"'`
