### ISSUE TITLE
a JavaScript error  ocurret

### ISSUE THREAD

**Issue by lizrivera18** [vercel/hyper#6528]
- [ ] Your Hyper.app version is **3.2.3**. Please verify you're using the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate
---
- **Any relevant information from devtools?** _(CMD+OPTION+I on macOS, CTRL+SHIFT+I elsewhere)_:

- **Is the issue reproducible in vanilla Hyper.app?**

## Issue

---

- **Hyper version**: undefined "3.2.3"
- **OS ARCH VERSION:** win32 x64 10.0.19044
- **Electron:** 17.2.0  **LANG:** undefined
- **SHELL:** undefined   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>

```json
{
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff",
    "limeGreen": "#32CD32",
    "lightCoral": "#F08080"
  },
  "shell": "C:\\Program Files\\Git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "cygwin"
  },
  "bell": "SOUND",
  "copyOnSelect": false
}
```
</details>
<details><summary><strong>plugins</strong></summary>

```json
{
  "plugins": [],
  "localPlugins": []
}
```
</details>

**Comment by LabhanshAgrawal** [comment]
can you provide a screenshot of the error as well?

**Comment by LabhanshAgrawal** [comment]
from your comment here https://github.com/vercel/hyper/issues/1594#issuecomment-1117097617

it's a file not found error
can you check if `C:\Program Files\Git\git-cmd.exe` is correct and does exist on your system (maybe it's lowercase git, or program files x64)

**Comment by lizrivera18** [comment]
Thank you so much for replay . Yes it is in program file x64 how I can fix it?
