### ISSUE TITLE
running hyper on root account

### ISSUE THREAD

**Issue by JoonyoungWie** [vercel/hyper#6530]
the guide from the program is telling me that i should run the hyper binary with "--user-data-dir".
but when i run the hyper with the "--user-data-dir"", it didn't work...

[root@haribo ~]# hyper
It is recommended to start hyper as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.

[root@haribo ~]# **hyper --user-data-dir=\~**
The option "user-data-dir" is unknown. Did you mean the following one?
-v, --verbose  Verbose mode (disabled by default)

hyper seem to have a conflict on this

**Comment by 1663049254** [comment]
I encounter the same problem,how did you solve it?
