### ISSUE TITLE
Instalation in Manjaro/Arch Linux using Yay or Makepkg

### ISSUE THREAD

**Issue by rodrigoschaer** [vercel/hyper#6545]
- [X] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Manjaro GNOME Linux 21.2.6
- **Hyper.app version**:  3.1.2-1

## Issue

I've been trying to install hyper on my  Manjaro GNOME Arch distribution but the system cannot proceed with the installation. I've tryied both ways:
- Pacman
- Yay
- Makepkg from github repo

But in all cases I get the following error message: 

```bash
  ...
  -> Downloading Hyper-Mark-120@3x.png...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Fail to download https://raw.githubusercontent.com/zeit/art/master/hyper/mark/Hyper-Mark-120@3x.png
    Aborting...
 -> fail to build hyper

```

I've searched in the forums but could not find a case similar to mine.

**Comment by xiaoxigua-1** [comment]
me too

**Comment by LabhanshAgrawal** [comment]
pacman build added in #7272
