### ISSUE TITLE
Unable to compile on bionic ARM64

### ISSUE THREAD

**Issue by theofficialgman** [vercel/hyper#6587]
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu Bionic ARM64
- **Hyper.app version**: canary

## Issue
Unable to build due to playwright not supporting firefox on arm64. this is an issue with hyper's dependency tree. it should not be using `playwright` instead it should use `playwright-core` and implement an `install.js` file to download only electron (since firefox is not used here)

```
rror /github/workspace/hyper/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /github/workspace/hyper/node_modules/playwright
Output:
Playwright build of chromium v978106 downloaded to /github/home/.cache/ms-playwright/chromium-978106
Playwright build of ffmpeg v1007 downloaded to /github/home/.cache/ms-playwright/ffmpeg-1007
/github/workspace/hyper/node_modules/playwright-core/lib/utils/registry.js:554
    if (!downloadPathTemplate || !executablePath) throw new Error(`ERROR: Playwright does not support ${descriptor.name} on ${_utils.hostPlatform}`);
                                                        ^
Error: ERROR: Playwright does not support firefox on ubuntu18.04-arm64
    at Registry._downloadExecutable (/github/workspace/hyper/node_modules/playwright-core/lib/utils/registry.js:554:57)
    at Object._install (/github/workspace/hyper/node_modules/playwright-core/lib/utils/registry.js:363:28)
    at Registry.install (/github/workspace/hyper/node_modules/playwright-core/lib/utils/registry.js:539:51)
    at async installBrowsersForNpmInstall (/github/workspace/hyper/node_modules/playwright-core/lib/utils/registry.js:728:3)
```

see: https://github.com/microsoft/playwright/pull/834

edit: actually this is even simpler, since you are using electron only, you can skip browser download entirely https://playwright.dev/docs/api/class-electron

**Comment by LabhanshAgrawal** [comment]
Even if you skip playwright browser download, mksnapshot doesn't run arm64, and electron-rebuild also has many issues running on arm64, so it's not really straightforward to build Hyper on arm64 right now.
If you just want to get arm64 builds to install Hyper, I suggest you take a look at https://github.com/vercel/hyper/pull/7227
Please try the build from that PR and check if it works for you. (you can find it from the checks section or from the latest comment by github actions bot.)
