### ISSUE TITLE
Web terminals have more font saturation

### ISSUE THREAD

**Issue by FormalSnake** [vercel/hyper#6599]
Hi, i love Hyper terminal and when i run neofetch, the colors look different than in iTerm2 (more saturated). It is the case in any other non-web terminal as well.
When i am on my iPad, i want to get the same saturation, but without a web terminal. Is there some special software i can install?

Hyper is on the right, and iTerm2 is on the left:
<img width="1440" alt="Screenshot 2022-06-16 at 07 37 17" src="https://user-images.githubusercontent.com/90651091/174007338-d2dde8f9-4574-4e51-ac6d-36f72ca91c2a.png">
there is clearly a big difference in saturation

**Comment by Buzzraider** [comment]
At the first glance it looks like You have a different theme (Color preset) applied in iterm2 hence the different color scheme, 

this is also iterm2 with default color preset:
![image](https://user-images.githubusercontent.com/69143224/178438438-fc9f07bd-7404-461a-9ac2-2473e8b36e13.png)

and this is hyper term with hyper-flat theme.
![image](https://user-images.githubusercontent.com/69143224/178439001-abadb975-045f-40c0-8293-0e52d89453c7.png)

**Comment by FormalSnake** [comment]
> At the first glance it looks like you have a theme applied to hyper.app that changed the colors a bit, but Your iterm2 runs with default color preset, hence why you see difference. It has nothing to do with web-terminal :)
> 
> For example this is iterm2 with Color Preset "Solarized Dark"
> 
> ![image](https://user-images.githubusercontent.com/69143224/178441126-c73183eb-2bb9-4de9-8ed2-83fc8a151382.png)
> 
> So as you can see its all about (Color Preset) in iterm2 and themes in hyper.app. Different themes in hyper.app will sometimes use different color palette and produce different visual experience.

This fixed my problem, I saw your answer before but forgot to reply, thanks a lot!
