### ISSUE TITLE
.hyper config location for macOS is incorrect in website

### ISSUE THREAD

**Issue by dheerajkysetti** [vercel/hyper#6616]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app 3.2.3 macOS arm64
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS 12.4 and macOS monterey M1**: 
- **Hyper.app 3.2.3**: 
- **default .hyper.js config**: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
In the hyper.is website, when opened on a macOS m1(monterey), the configuration section shows 
<img width="810" alt="image" src="https://user-images.githubusercontent.com/7882386/175830297-6a679a23-bb31-4166-afff-b8e1058db33c.png">

But the .hyper.js file in the ~/Library/Application Support/Hyper/.hyper.js is never read.
Only the ~/.hyper.js file works.

Taking a look at the code at tag 3.2.3
https://github.com/vercel/hyper/blob/ef5419b5200a04b244e9d507baf6f4e5cf5bad9c/app/config/paths.ts#L12-L19
The user directory does point to mac.

**Does the website need to update the documentation or the code require a change to match the documentation?**

**Comment by maxdevjs** [comment]
(This also happens for Linux when  `XDG_CONFIG_HOME` is not explicitly set) @dheerajkysetti check if your `XDG_CONFIG_HOME` is set

```yaml
$ echo $XDG_CONFIG_HOME
```

Also, please check https://github.com/vercel/hyper/issues/6789 to verify if that behavior currently happen also on Mac. Thank you.

**Comment by 17hao** [comment]
@maxdevjs 
It is not necessary to set XDG_CONFIG_HOME explicitly, the default value is `$HOME/.config`.

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
