### ISSUE TITLE
Getting JavaScript Error when opening new Tab in Hyper

### ISSUE THREAD

**Issue by JBarker90** [vercel/hyper#6648]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10  x64  Version	10.0.19044 Build 19044
- **Hyper.app version**: 3.2.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/JBarker90/1ac22bdd5d99d2213d292c1e242474f4
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I recently updated Hyper terminal to Version 3.2.3 and now am noticing that I get a JavaScript Error when trying to open a new tab. I did come across some older GitHub issues where others ran into the same error. But the resolution was to remove the hypercwd plugin. This doesn't apply in my case because I don't have any plugins installed. If anyone can help troubleshoot this issue, it would be much appreciated! Thanks!
![JavaScript Error](https://user-images.githubusercontent.com/54541586/177825336-88098c48-4f71-4149-99fc-1ba0827ca88d.png)

**Comment by LabhanshAgrawal** [comment]
Can you check the shell path once, that error code is generally there when path doesn't exist

**Comment by LabhanshAgrawal** [comment]
try once with `env: {}` and `shellArgs: []`

**Comment by JBarker90** [comment]
So removing the values for env and shellArgs fixed the error.

```
         // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
        // by default `['--login']` will be used
        shellArgs: [],
        // for environment variables
        env: {},
```
But now bash commands can't be found. Are there recommended configurations I can use in .hyper.js to configure Cygwin Bash in Hyper?

```
jonat@Beastmaster /cygdrive/c/Users/jonat
$ ls
bash: ls: command not found
jonat@Beastmaster /cygdrive/c/Users/jonat
$ clear
bash: clear: command not found
```

**Comment by itshikanov** [comment]
> So removing the values for env and shellArgs fixed the error.
> 
> ```
>          // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
>         // by default `['--login']` will be used
>         shellArgs: [],
>         // for environment variables
>         env: {},
> ```
> 
> But now bash commands can't be found. Are there recommended configurations I can use in .hyper.js to configure Cygwin Bash in Hyper?
> 
> ```
> jonat@Beastmaster /cygdrive/c/Users/jonat
> $ ls
> bash: ls: command not found
> jonat@Beastmaster /cygdrive/c/Users/jonat
> $ clear
> bash: clear: command not found
> ```

New tab work, but need testing more.
```
        shell: 'C:\\cygwin\\Cygwin.bat',
	shellArgs: [],
        env: {
		TERM: 'cygwin',
	  },
```

**Comment by LabhanshAgrawal** [comment]
This is fixed in canary release, you can set `updateChannel: "canary"` to use canary builds, or set `preserveCWD: false` for the time being.
