### ISSUE TITLE
ssh://host does not get handled correctly

### ISSUE THREAD

**Issue by mazedlx** [vercel/hyper#6767]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 12.6
- **Hyper.app version**: 3.3.0 (arm64)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mazedlx/fc6f844c798f622429a64ef2665711aa
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
First of all, thanks for the great app! Here's the issue I'm dealing with:

Type `ssh://host` into the address bar of your browser, and press enter. Hyper should open `ssh host` but only runs `ssh`. This worked before but now seems to be broken. Works fine in iTerm (if it is set as the designated protocol handler for ssh).

**Comment by LabhanshAgrawal** [comment]
thanks for reporting, will check

**Comment by tendallas** [comment]
Same for me

**Comment by tendallas** [comment]
Any updates here?

**Comment by alessandro-newzoo** [comment]
was about to report the same issue :( @LabhanshAgrawal have you got any news by any chance please?
