### ISSUE TITLE
Not available in my area => This site can’t be reached

### ISSUE THREAD

**Issue by sumyat-aung** [vercel/hyper#6849]
### It's not available in my area (Myanmar). The website only load with VPN but even with VPN, I'm not able to download for Window 10. 

<br>
<br>

![image](https://user-images.githubusercontent.com/108873224/199234556-8b68e965-efa8-4421-a6a7-7499d2f6c50c.png)

**Comment by LabhanshAgrawal** [comment]
You can try from the releases page https://github.com/vercel/hyper/releases
