### ISSUE TITLE
error creating third tab

### ISSUE THREAD

**Issue by Clownsw** [vercel/hyper#6852]
- **OS Windows 21H2**
- **Hyper.app 3.3.0 version**

## Issue
error creating third tab
![hyperjs create table error](https://user-images.githubusercontent.com/28394742/199408468-a691a547-047b-4caa-a741-8bce99506518.png)

**Comment by LabhanshAgrawal** [comment]
fill the issue template
add your config as well

**Comment by Clownsw** [comment]
> fill the issue template add your config as well

i use default config

**Comment by LabhanshAgrawal** [comment]
Can you please paste the contents here
also screenshot from dev tools (ctrl+shift+i) when this happens
This error comes when the path for the shell is incorrect generally

**Comment by Clownsw** [comment]
> Can you please paste the contents here also screenshot from dev tools (ctrl+shift+i) when this happens This error comes when the path for the shell is incorrect generally

![微信截图_20221108123045](https://user-images.githubusercontent.com/28394742/200475491-83a17a2b-414f-4f2b-8615-afd2afbcc443.png)

**Comment by LabhanshAgrawal** [comment]
you can try with preserveCWD set to false in the config. And please paste your config here, I can't really help you out properly without knowing what's there exactly.

**Comment by Clownsw** [comment]
set preserveCWD to false, it solved my problem
