### ISSUE TITLE
Multiple Hyper.exe processes in Windows 11

### ISSUE THREAD

**Issue by aniketgm** [vercel/hyper#6854]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 11 Home (Build: 10.0.22621)
- **Hyper.app version**: 3.3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/aniketgm/655ffa75978f14406a2314951f49db15
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes, it is reproducible. I checked by removing all the installed plugins and still I see the behavior/issue I have described below.

## Issue
I see that when I launch a Single instance (meaning only once and not multiple times), I see multiple "Hyper.exe" processes as shown in the image below.

![hyper-terminal-processes](https://user-images.githubusercontent.com/14215698/199806688-b2f865d5-16a9-4853-9cca-aac1787bcff7.png)

And as I keep adding new tabs and opening processes and services, these processes keep taking up more memory. 

![hyper-terminal-processes-01](https://user-images.githubusercontent.com/14215698/199808359-88ac505f-f336-4de4-a374-7a8f20328ba7.png)

Due to this sometimes I feel lag and sometimes the terminal feels like it's frozen but after a while gives response. Can this be improved a little bit ? Also why does it launch multiple processes ?
The Windows terminal and even Alacritty spawns only one process taking at most like 100 mb

**Comment by LabhanshAgrawal** [comment]
Hyper is an Electron app, so we have separate renderer and main processes and also for multiple windows. You might've observed similar behaviour with other electron apps, eg. vscode with code.exe processes.
Windows terminal and Alacritty might be native apps and thus behave differently.
