### ISSUE TITLE
Arm64 Build of Hyper doesn't run on Linux.

### ISSUE THREAD

**Issue by mokshsinghji** [vercel/hyper#6937]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 22.04.1 LTS
- **Hyper.app version**: 3.3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mokshsinghji/dcaece8ef060a5e224be1dc01f2ab24e
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue

Hi, ,when I download the arm64 version of Hyper from both hyper.is and GitHub releases for Linux, and install it using `dpkg`, it installs successfully, but when I try to run it from both the command line and the activities menu on Ubuntu, it doesn't open any windows.

When I did `hyper -v`, when I received the output of 
```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/Hyper/resources/app.asar/session.js
- /opt/Hyper/resources/app.asar/ui/window.js
- /opt/Hyper/resources/app.asar/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/Hyper/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/Hyper/resources/app.asar/session.js',
    '/opt/Hyper/resources/app.asar/ui/window.js',
    '/opt/Hyper/resources/app.asar/index.js',
    undefined
  ]
}

A JavaScript error occurred in the main process
Uncaught Exception:
Error: `node-pty` failed to load. Typically this means that it was built incorrectly. Please check the `readme.md` to more info.
    at createNodePtyError (/opt/Hyper/resources/app.asar/session.js:39:34)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/session.js:46:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function._load (/opt/Hyper/resources/app.asar/plugins.js:103:37)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

I would really like to use Hyper, but due to this I am unable to use it at all.

**Comment by 1mansh0w** [comment]
I have the exact same issue. Installed Ubuntu 22.04 (ARM64) with parallels. Tried also the latest Version 4 Canary - same error message.

**Comment by LabhanshAgrawal** [comment]
Yeah, there's issues with arm64 builds on github actions, I've recently got an arm64 device to use as host for our github actions, it might take some time, but should be fixed soon. You can try to build on your device if you want something immediate.

**Comment by mokshsinghji** [comment]
Hey Labhansh,

I tried to build it myself at the time when I created this issue, and I believe I was getting a similar error about Pty. Maybe not available for arm? 🤷‍♀️

**Comment by LabhanshAgrawal** [comment]
Yeah, I remember something similar from when I was trying this last time on qemu, but I think there was some workaround. Will know for sure once I get my hands on the arm device I've ordered.

**Comment by mokshsinghji** [comment]
👍

**Comment by randyg3000** [comment]
same error on NVIDIA Orin

Linux maitai1 5.10.104-tegra #2 SMP PREEMPT Thu Apr 27 14:23:04 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by LabhanshAgrawal** [comment]
can you guys please try this appimage build https://github.com/LabhanshAgrawal/hyper/actions/runs/5176383886
and comment if it works for you

**Comment by randyg3000** [comment]
I installed via deb at the link you provided, and it does seem to be up and working. Have not tested anything extensively, or used any plugins but this looks good- thanks!

**Comment by randyg3000** [comment]
Was not able to get hyper to honor fontSize or fontFamily, seems to be working otherwise

**Comment by mokshsinghji** [comment]
Hi,

I was just testing it out. Like mentioned before, the deb file is working on my Ubuntu 20.04, however the AppImage build does not seem to work. It fails at some point with this error message: `[1]    52105 bus error (core dumped)  ./Hyper-4.0.0-canary.3-arm64.AppImage`. If I run it many times, it will get as far as to actually open up a window, but causes many errors in the terminal, with the window being just plain black.

I will be happy to answer any further questions 😄

Thanks for the progress and the efforts that are being made so far.

**Comment by LabhanshAgrawal** [comment]
@mokshsinghji Can you launch the AppImage from the default terminal and then paste the logs here?
I'm testing the build on UTM Ubuntu vm, running the AppImage using AppImage Launcher and everything looks fine.
Sadly my rpi clone is not powerful enough to run a desktop environment, so couldn't test it on a real device.

**Comment by LabhanshAgrawal** [comment]
I've opened https://github.com/vercel/hyper/pull/7227 for this
Please try the build from that PR and check if it works for you. (you can find it from the checks section or from the latest comment by github actions bot.)
