### ISSUE TITLE
a JavaScript error

### ISSUE THREAD

**Issue by AAAAAAAAAAAASada** [vercel/hyper#6961]
win11, Hyper3.4.0, when I closed a tab
Uncaught Exception:
Error: read EPIPE
 at Pipe.onStreamread (node:internal/stream_base_commons:217:20)

**Comment by LabhanshAgrawal** [comment]
can you add a screenshot?

**Comment by AAAAAAAAAAAASada** [comment]
![AAAAAAAAA](https://user-images.githubusercontent.com/119103206/210745492-d70fb040-d9a7-4b80-b86a-db7822080525.png)
Well, I didn't type any commands. It's the only information that I got. I've tried Hyper4.0.0, but when I close a new tab, I'll get this.

**Comment by LabhanshAgrawal** [comment]
can you add your config as well?

**Comment by AAAAAAAAAAAASada** [comment]
> can you add your config as well?
{
  "$schema": "./schema.json",
  "config": {
    "updateChannel": "stable",
    "fontSize": 18,
    "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
    "fontWeight": "normal",
    "fontWeightBold": "bold",
    "lineHeight": 1,
    "letterSpacing": 0,
    "scrollback": 1000,
    "cursorColor": "rgba(255,255,255,0.8)",
    "cursorAccentColor": "#99f",
    "cursorShape": "BLOCK",
    "cursorBlink": true,
    "foregroundColor": "#99f",
    "backgroundColor": "#000",
    "selectionColor": "rgba(153,153,255,0.3)",
    "borderColor": "#99f",
    "css": "",
    "termCSS": "",
    "workingDirectory": "",
    "showHamburgerMenu": "",
    "showWindowControls": "",
    "padding": "12px 14px",
    "colors": {
      "black": "#000000",
      "red": "#C51E14",
      "green": "#1DC121",
      "yellow": "#C7C329",
      "blue": "#0A2FC4",
      "magenta": "#C839C5",
      "cyan": "#20C5C6",
      "white": "#C7C7C7",
      "lightBlack": "#686868",
      "lightRed": "#FD6F6B",
      "lightGreen": "#67F86F",
      "lightYellow": "#FFFA72",
      "lightBlue": "#6A76FB",
      "lightMagenta": "#FD7CFC",
      "lightCyan": "#68FDFE",
      "lightWhite": "#FFFFFF",
      "limeGreen": "#32CD32",
      "lightCoral": "#F08080"
    },
    "shell": "",
    "shellArgs": [
      "--login"
    ],
    "env": {},
    "bell": "SOUND",
    "bellSound": null,
    "bellSoundURL": null,
    "copyOnSelect": false,
    "defaultSSHApp": true,
    "quickEdit": false,
    "macOptionSelectionMode": "vertical",
    "webGLRenderer": false,
    "webLinksActivationKey": "",
    "disableLigatures": true,
    "disableAutoUpdates": false,
    "autoUpdatePlugins": true,
    "preserveCWD": true,
    "screenReaderMode": false
  },
  "plugins": [],
  "localPlugins": [],
  "keymaps": {}
}

You mean that right? I'm a rookie, thanks for your patience.

**Comment by LabhanshAgrawal** [comment]
Try with `"useConpty": false` once

**Comment by AAAAAAAAAAAASada** [comment]
> Try with `"useConpty": false` once

It worked out!

**Comment by ghifarizuhir** [comment]
same issue, where can i put this line ?

> Try with `"useConpty": false` once

**Comment by AAAAAAAAAAAASada** [comment]
> same issue, where can i put this line ?
> 
> > Try with `"useConpty": false` once

open your .hyper.js, in "config" :   {

**Comment by chriswinger** [comment]
> > same issue, where can i put this line ?
> > > Try with `"useConpty": false` once
> 
> open your .hyper.js, in "config" : {

Adding `useConpty: false,` to .hyper.js fixed it for me. Thanks.

**Comment by LabhanshAgrawal** [comment]
@AAAAAAAAAAAASada @ghifarizuhir @chriswinger 
Can you guys try a build from https://github.com/vercel/hyper/actions/runs/3854997522#artifacts with `useConpty: true`
This will help in understanding if the issue is from conpty or pty-node.

**Comment by AAAAAAAAAAAASada** [comment]
I still got a issue after adding `"useConpty": false`, when I used a command-line utility
normally:
![dfsfdsfds](https://user-images.githubusercontent.com/119103206/211140708-3bc00104-03c2-47d5-82be-92aa59598f47.png)
now:
![575887htfth](https://user-images.githubusercontent.com/119103206/211140714-1e70bc8e-1499-47bc-9223-250303ef2219.png)

**Comment by LabhanshAgrawal** [comment]
Download the installer from the link I posted for your platform and install. Make sure to have `useConpty` either removed or `true` in config. And then test it.

**Comment by AAAAAAAAAAAASada** [comment]
Hyper Setup 3.4.0.exe from the link [https://github.com/vercel/hyper/actions/runs/3854997522#artifacts](url) solved the problem on win11. Thanks a lot.

**Comment by chriswinger** [comment]
> @AAAAAAAAAAAASada @ghifarizuhir @chriswinger Can you guys try a build from https://github.com/vercel/hyper/actions/runs/3854997522#artifacts with `useConpty: true` This will help in understanding if the issue is from conpty or pty-node.

This build also fixed the issue for me, on Win10.
