### ISSUE TITLE
Internal Alias System

### ISSUE THREAD

**Issue by ARiyou2000** [vercel/hyper#6989]
### Alias as Internal command:
Every command-line interface needs to have its own internal commands.

as such I request to develop an alias system in which each `key` represents a complex or custom `single-line command`.

```
+-------------+------------------------------------------------------------------+
|  Alias Key  |                              Command                             |
+-------------+------------------------------------------------------------------+
|  dock_phpm  |  docker run --name db-view -p 80:8080 bitnami/phpmyadmin:latest  |
+-------------+------------------------------------------------------------------+
|     ...     |                                ...                               |
+-------------+------------------------------------------------------------------+
|     ...     |                                ...                               |
+-------------+------------------------------------------------------------------+
|     ...     |                                ...                               |
+-------------+------------------------------------------------------------------+
```

Now typing `dock_phpm` is equal to running the corresponding command in the hype.

> C:\Users\Administrator>dock_phpm

> C:\Users\Administrator>docker run --name db-view -p 80:8080 bitnami/phpmyadmin:latest

**Comment by LostInCompilation** [comment]
I don't get why that should be implemented natively into Hyper. You can just create you own aliases in your`~\.bashrc` (or `~\.zshrc` for zsh respectivelly).
Complex functions can simply be defined in your `~\.bashprofile` (or `~\.zprofile` for zsh) too, by writing something like this:
```sh
function MyCustomCommand()
{
    echo -e "Running my custom command"
    ./myCustomScript.sh
}
```
Also for Windows you can do the same. But implementing it into Hyper is the wrong way.

**Comment by ARiyou2000** [comment]
Fair enough. Thanks for your suggestion.

Actually I have no idea why I pushed this idea at the time😅.
