### ISSUE TITLE
why my application window is bare - missing the close & minimize buttons in macOS?

### ISSUE THREAD

**Issue by tal-rofe** [vercel/hyper#7008]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: M1 Ventura 13.0.1
- **Hyper.app version**: 3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: https://gist.github.com/tal-rofe/40950a53f3313bdf138ad682c12c5aa6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

After Downloading the application, I dont have buttons like "close" and minimze:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/100444463/216462461-b2cc5a73-9a54-41cf-aab0-e0a53e07afe4.png">

**Comment by LabhanshAgrawal** [comment]
Try once after renaming the `.hyper.js` file to something else and restart hyper so that it will regenerate config. If that works then the issue can be singled out by setting the values from your current config into the new config one by one

**Comment by tal-rofe** [comment]
@LabhanshAgrawal 

The issue occurs when using this plugins: ` plugins: ["hyper-tabs-enhanced", "hyper-github-dark"],`

**Comment by LabhanshAgrawal** [comment]
https://github.com/henrikruscon/hyper-tabs-enhanced#config

**Comment by tal-rofe** [comment]
@LabhanshAgrawal 
Thanks
