### ISSUE TITLE
Config key missing

### ISSUE THREAD

**Issue by ShrekRequiem** [vercel/hyper#7032]
- **OS version and name**: Fedora 37 (Workstation)
- **Hyper.app version**: 3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: https://gist.github.com/ShrekRequiem/d0662c4d04a5ac4a54513237e7aae403

## Issue
Not really an issue per se since everything seems to be working properly, but everytime I start Hyper, I get two notifications that I assume are caused by the same problem. I have looked everywhere in my Hyper.json file and I cant seem to find the error.
The first notification reads "SyntaxError : unexpected token ':' the second ""config key missing"
![image](https://user-images.githubusercontent.com/121633226/220191593-bbfdbc28-ba9c-472c-a9b2-47d2b7e55163.png)

**Comment by LabhanshAgrawal** [comment]
needs `]` at the end of https://gist.github.com/ShrekRequiem/d0662c4d04a5ac4a54513237e7aae403#file-hyper-js-L152

**Comment by ShrekRequiem** [comment]
thank you so much for the answer, unfortunately I still get the error :(
![image](https://user-images.githubusercontent.com/121633226/220441898-08e738be-2414-46c6-ac91-f7b5c2763d0c.png)

**Comment by LabhanshAgrawal** [comment]
oh, sorry it should be `],`

**Comment by ShrekRequiem** [comment]
thank you that fixed it !
