### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by Praisepa1** [vercel/hyper#7125]
![Screenshot 2023-04-14 063229](https://user-images.githubus
![Screenshot 2023-04-14 063229](https://user-images.githubusercontent.com/99658340/231952937-0fa11821-a2a9-4212-9637-ec4a0200b0bb.png)
ercontent.com/99658340/231952852-1f88070b-57d5-4a66-8d6b-c3111c6ab268.png)

**Comment by Amarjit0511** [comment]
@Praisepa1 
I am not sure if it will work, but can you once try configuring the DNS to see if it fixes this problem.

**Comment by iammrmehedi** [comment]
![hyper-install-error](https://user-images.githubusercontent.com/89072438/232994748-f8f1b625-e80d-433a-8b25-57bdfcbab7c9.png)
Can't Install **Hyper** Terminal on **Windows 11** Machine.

**Comment by iammrmehedi** [comment]
there was some problem with the properties option after opening properties option the compatibility was marked automatically.
![error-fix-1](https://user-images.githubusercontent.com/89072438/232998681-cc22a0f3-9b97-484d-9924-b8afff36aa57.png)

after unchecking them there is no error.
![error-fix-final](https://user-images.githubusercontent.com/89072438/233000246-1d811720-1780-4a22-9de0-d9b1a81b40c3.png)

**Comment by LabhanshAgrawal** [comment]
Please ensure that you are using the latest release, also set `useConpty: true` in your config. Also disable compatibility mode as @devbytemehedi mentioned.
