### ISSUE TITLE
Themes not loading

### ISSUE THREAD

**Issue by 7xa5h** [vercel/hyper#7295]
- [x ] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Tiny 11
- **Hyper.app version**: v3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json** https://gist.github.com/7xa5h/aa6b1ebc94e10f028216dae8db36529c.js
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Verminal, wont load, ive rebooted my pc, ive tried everything, it says that its downloaded, but it simply wont work
thanks

**Comment by LabhanshAgrawal** [comment]
vibrancy is only supported on macOS at the moment

**Comment by 7xa5h** [comment]
> vibrancy is only supported on macOS at the moment

how is that an answer im saying themes wont load for me?

**Comment by LabhanshAgrawal** [comment]
It is an answer, if you know what vibrancy is or spend a moment to look it up.

That plugin only works fully on macos, because vibrancy (transparent/blurred background) is only supported on macos at the moment.

Is the text color and other parts of the theme also not working or only the background transparency?

**Comment by LabhanshAgrawal** [comment]
On a side note, recent electron releases add support for vibrancy on windows as well. So verminal should work well on windows in the upcoming canary release of hyper.
