### ISSUE TITLE
Ligatures do not work

### ISSUE THREAD

**Issue by evonicgu** [vercel/hyper#7334]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Arch Linux (kernel 6.4.3)
- **Hyper.app version**: Hyper 3.4.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your hyper.json**: [gist](https://gist.github.com/evonicgu/4d97355dfa6ab26bdcee9e599698ac38)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: The issue is reproducible both in vanilla and slightly customized versions of the application.
## Issue

Jetbrains Mono font ligatures don't work, despite the fact that `disableLigatures` is set to false. I've tested most of the ligatures known to me: `<=`, `>=`, `==`, `===`, `!=`, `!==`, `#{`, `#[` and etc, none of them work in the terminal.

**Comment by LabhanshAgrawal** [comment]
we use xterm.js for rendering the terminal, the webgl renderer has known issues with ligatures, thus we don't enable ligatures if `webGLRenderer` is `true`. You can disable the webgl renderer if you want to use ligatures, though webgl renderer is more performant.
