### ISSUE TITLE
Hyper opens and crashes

### ISSUE THREAD

**Issue by aakashgupt** [vercel/hyper#7350]
- [x] I am on the Hyper.app version 3.4.1
- [x] I have searched in this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When I installed Hyper on my M2 Mac, Hyper didn't work. There was some symlink issue. After some research ii was able to fix it. I have installed bash via Homebrew and the location is /opt/homebrew/bin/bash. Later on, it started crashing everytime I opened it.

I tried opening Hyper from Mac's default terminal from the Hyper package contents. There I saw some logs which I think will you understand why it is crashing.
`Last login: Thu Jul 20 16:03:16 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Applications/Hyper.app/Contents/MacOS/Hyper ; exit;
MacBook-Air:~ aakashgupta$ /Applications/Hyper.app/Contents/MacOS/Hyper ; exit;
Plugin hyper-material-theme (3.0.1) loaded.
Plugin hyper-quit (1.0.3) loaded.
Plugin hyper-search (0.4.0) loaded.
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html
(node:18997) electron: NSVisualEffectMaterialDark has been deprecated and removed as of macOS 10.15.
(Use `Hyper --trace-warnings ...` to show where the warning was created)
Linking HyperCLI
Hyper CLI installation failed Symlink creation failed: EACCES undefined
objc[18999]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23b9f6cb0) and /Applications/Hyper.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10a0c5d08). One of the two will be used. Which one is undefined.
Checking for notification messages

shell exited in 69 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 126 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 183 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 237 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 291 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 345 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 402 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 455 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 508 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 561 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 616 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 673 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 725 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 782 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 838 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

No matching notification messages

shell exited in 895 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

shell exited in 952 ms with exit code 1
please check the shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}
fallback to default shell config: {
  "shell": "/usr/local/bin/bash",
  "shellArgs": [
    "--login"
  ]
}

logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

`

**Comment by LabhanshAgrawal** [comment]
You might have set `/usr/local/bin/bash` as default shell using `chsh` instead of `/opt/homebrew/bin/bash` that's why hyper is trying to run the former. You can do either `chsh -s /opt/homebrew/bin/bash` or set `shell: "/opt/homebrew/bin/bash"` in ~/.hyper.js

**Comment by aakashgupt** [comment]
> You might have set `/usr/local/bin/bash` as default shell using `chsh` instead of `/opt/homebrew/bin/bash` that's why hyper is trying to run the former. You can do either `chsh -s /opt/homebrew/bin/bash` or set `shell: "/opt/homebrew/bin/bash"` in ~/.hyper.js

@LabhanshAgrawal Thanks for the reply. the second solution worked for me. Thanks a lot
