### ISSUE TITLE
Menu bar and keyboard shortcut do not open config

### ISSUE THREAD

**Issue by OJFord** [vercel/hyper#901]
If I use the macOS (10.12) menu bar, or the `Cmd+,` keyboard shortcut, to open `.hyper.js` it fails every time:

``` sh
 echo Attempting to open ~/.hyper.js with your $EDITOR
 echo If it fails, open it manually with your favorite editor!
 bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
~> echo Attempting to open ~/.hyper.js with your $EDITOR
Attempting to open /Users/ojf/.hyper.js with your vim
~>
```

As you can see, it doesn't even attempt to run the second `echo`. Running `bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'` manually works fine.

This has been an issue for as long as I've been using Hyper(term); not related to latest update to v0.8.3 (0.8.3.873).

**Comment by OJFord** [comment]
Ah - this is perhaps an issue with the way the commands are sent, depending on the shell used - I'm using xonsh. Perhaps `;` or `&&` chaining (rather than newlines) would be more portable if that's the case.

**Comment by olivier-w** [comment]
Might be related to #822, but I'm still seeing the same issue on 0.8.3:

```
 echo Attempting to open ~/.hyper.js with your $EDITOR                                     
 echo If it fails, open it manually with your favorite editor!
 bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
 ~ echo Attempting to open ~/.hyper.js with your $EDITOR
Attempting to open /Users/olivier/.hyper.js with your vi
 ~ echo If it fails, open it manually with your favorite editor!
If it fails, open it manually with your favorite editor!
~ bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
```

Using `zsh` as my shell, I have `export EDITOR=vi` in my `~/.zshrc`.

**Comment by OJFord** [comment]
This is getting worse; not better!

Output is now:
```sh
 echo Attempting to open ~/.hyper.js with your \$EDITOR
 echo If it fails, open it manually with your favorite editor!
 bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
~> echo Attempting to open ~/.hyper.js with your \$EDITOR
Attempting to open /Users/ojf/.hyper.js with your \vim
~>
```

(Note the 'escape', and `\vim`.)

**Comment by giggio** [comment]
Same on Windows, if you use Powershell:

````
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 1009ms.
C:\Users\giggi>  echo Attempting to open .hyper.js with notepad
Attempting
to
open
.hyper.js
with
notepad
C:\Users\giggi>
>>  start notepad "%userprofile%\.hyper.js"
C:\Users\giggi>
>>
````

**Comment by LabhanshAgrawal** [comment]
Closing as this was for v1
Feel free to open a new issue if you face any problems with the latest [build](https://github.com/vercel/hyper/actions/runs/157826845)

**Comment by OJFord** [comment]
I don't use Hyper any more, but FYI in case it pops up again - shouldn't be tagged Windows. (I thought that seemed off since I didn't think I'd ever used Windows for development, and sure enough my OP did say macOS.)
